{resource constants}
const
  IDC_MSG_TITLE     = 2703;
  IDC_MSG_TEXT      = 2704;
  IDC_MSGB_ARI      = 2706;
  IDC_MSGB_OK       = 2707;
  IDC_MSGB_OC       = 2708;
  IDC_MSGB_RC       = 2709;
  IDC_MSGB_YN       = 2710;
  IDC_MSGB_YNC      = 2711;
  IDC_MSGI_NONE     = 2713;
  IDC_MSGI_WARN     = 2714;
  IDC_MSGI_INFO     = 2715;
  IDC_MSGI_QUEST    = 2716;
  IDC_MSGI_ERROR    = 2717;
  IDC_MSG_RTL       = 2718;
  IDC_MSG_RIGHT     = 2719;
