{resource constants}
const
  IDC_RW_READ       = 2601;
  IDC_RW_WRITE      = 2602;
  IDC_RW_DELETE     = 2603;
  IDC_RW_MODULE     = 2606;
  IDC_RW_SETTING    = 2608;
  IDC_RW_VALUE      = 2610;
  IDC_RW_DATATYPE   = 2611;
  IDC_RW_CURRENT    = 2614;
  IDC_RW_PARAM      = 2615;
  IDC_RW_MANUAL     = 2616;
  IDC_RW_RESULT     = 2619;
  IDC_RW_LAST       = 2620;
  IDC_RW_SAVE       = 2621;

  IDC_CONTACTLIST   = 2141;
  IDC_CNT_REFRESH   = 2142;
