// DB keys
#define WHATSAPP_KEY_ID                      "ID"
#define WHATSAPP_KEY_LOGIN                   "Login"
#define WHATSAPP_KEY_CC                      "CountryCode"
#define WHATSAPP_KEY_NICK                    "Nick"
#define WHATSAPP_KEY_PASS                    "Password"
#define WHATSAPP_KEY_IDX                     "DeviceID"
#define WHATSAPP_KEY_MAP_STATUSES			   "MapStatuses"
#define WHATSAPP_KEY_LOGGING_ENABLE			   "LoggingEnable"
#define WHATSAPP_KEY_NAME                    "RealName"
#define WHATSAPP_KEY_PUSH_NAME               "Nick"
#define WHATSAPP_KEY_LAST_SEEN               "LastSeen"
#define WHATSAPP_KEY_AVATAR_ID               "AvatarId"
#define WHATSAPP_KEY_SYSTRAY_NOTIFY			   "UseSystrayNotify"
#define WHATSAPP_KEY_DEF_GROUP               "DefaultGroup"
#define WHATSAPP_KEY_REG_CODE                "RegistrationCode"
#define WHATSAPP_KEY_SSL                     "UseSSL"

#define WHATSAPP_KEY_EVENT_CLIENT_ENABLE            "EventClientEnable"
#define WHATSAPP_KEY_EVENT_OTHER_ENABLE             "EventOtherEnable"

#define WHATSAPP_KEY_EVENT_CLIENT_COLBACK           "PopupClientColorBack"
#define WHATSAPP_KEY_EVENT_CLIENT_COLTEXT           "PopupClientColorText"
#define WHATSAPP_KEY_EVENT_CLIENT_TIMEOUT           "PopupClientTimeout"
#define WHATSAPP_KEY_EVENT_CLIENT_DEFAULT           "PopupClientColorDefault"

#define WHATSAPP_KEY_EVENT_OTHER_COLBACK            "PopupOtherColorBack"
#define WHATSAPP_KEY_EVENT_OTHER_COLTEXT            "PopupOtherColorText"
#define WHATSAPP_KEY_EVENT_OTHER_TIMEOUT            "PopupOtherTimeout"
#define WHATSAPP_KEY_EVENT_OTHER_DEFAULT            "PopupOtherColorDefault"

