{resource constants}
const
  // dialogs
  IDD_HOOKS         = 1029;

  // icons
  IDI_NEW           = 1025;
  IDI_DELETE        = 1028;

  // Hook editor
  IDC_HOOKLIST      = 1025;
  IDC_ACTIONLIST    = 1026;
  IDC_EVENTLIST     = 1027;
  IDC_EVENT_HELP    = 1028;
  IDC_HOOK_NEW      = 1029;
  IDC_HOOK_DELETE   = 1030;
  IDC_HOOK_APPLY    = 1031;
  IDC_EVENT_CHELP   = 1032;

  IDC_DESCR         = 1040;
