//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by YAMN.rc
//
#define IDI_CHECKMAIL                   104
#define IDI_LAUNCHAPP                   105
#define IDD_DLGVIEWMESSAGES             107
#define IDD_DLGSHOWMESSAGE              108
#define IDI_ICOYAMN2                    112
#define IDI_ICOYAMN1                    113
#define IDD_DLGBADCONNECT               115
#define IDD_POP3ACCOUNTOPT              121
#define IDD_YAMNOPT                     126
#define IDI_BADCONNECT                  131
#define IDI_ICOTTBUP                    138
#define IDD_PLUGINOPT                   141
#define IDI_NEWMAIL                     159
#define IDD_CHOOSESTATUSMODES           310
#define IDD_OPTIONS                     311
#define IDD_POP3ACCOUNTPOPUP            312
#define IDC_EDITSERVER                  1000
#define IDC_EDITPORT                    1001
#define IDC_EDITLOGIN                   1002
#define IDC_EDITPASS                    1003
#define IDC_COMBOACCOUNT                1005
#define IDC_BTNDEFAULT                  1006
#define IDC_EDITINTERVAL                1007
#define IDC_CHECKSND                    1008
#define IDC_CHECKMSG                    1009
#define IDC_CHECKAPP                    1010
#define IDC_BTNAPP                      1011
#define IDC_CHECKICO                    1012
#define IDC_CHECK                       1013
#define IDC_BTNDEL                      1014
#define IDC_STSERVER                    1015
#define IDC_CHECKFSND                   1016
#define IDC_CHECKFMSG                   1017
#define IDC_CHECKFICO                   1018
#define IDC_CHECKST0                    1019
#define IDC_CHECKST1                    1020
#define IDC_CHECKST2                    1021
#define IDC_CHECKST3                    1022
#define IDC_CHECKST4                    1023
#define IDC_CHECKST5                    1024
#define IDC_CHECKST6                    1025
#define IDC_CHECKST7                    1026
#define IDC_EDITAPP                     1027
#define IDC_CHECKST8                    1028
#define IDC_CHECKST9                    1029
#define IDC_CHECKCONTACT                1030
#define IDC_CHECKCONTACTNICK            1031
#define IDC_CHECKCONTACTNOEVENT         1032
#define IDC_STTIMELEFT                  1033
#define IDC_LISTMAILS                   1038
#define IDC_LISTHEADERS                 1039
#define IDC_EDITAPPPARAM                1044
#define IDC_BTNOK                       1047
#define IDC_COMBOCP                     1050
#define IDC_STCP                        1055
#define IDC_STATICMSG                   1055
#define IDC_STPORT                      1056
#define IDC_STLOGIN                     1057
#define IDC_STPASS                      1058
#define IDC_STINTERVAL                  1059
#define IDC_AUTOBODY                    1062
#define IDC_BTNRESET                    1063
#define IDC_CHECKSTART                  1064
#define IDC_STWCHECK                    1065
#define IDC_CHECKFORCE                  1066
#define IDC_RADIOPOP1                   1068
#define IDC_RADIOPOPN                   1069
#define IDC_CPB                         1070
#define IDC_CPNB                        1071
#define IDC_CHECKCOL                    1073
#define IDC_CPT                         1074
#define IDC_CPFB                        1075
#define IDC_CPFT                        1076
#define IDC_CHECKFCOL                   1077
#define IDC_CHECKNCOL                   1078
#define IDC_CPNT                        1079
#define IDC_CHECKPOP                    1087
#define IDC_CHECKNPOP                   1088
#define IDC_CHECKFPOP                   1089
#define IDC_EDITPOPS                    1090
#define IDC_EDITNPOPS                   1091
#define IDC_EDITFPOPS                   1092
#define IDC_GBNEWMAIL                   1094
#define IDC_GBNONEWMAIL                 1095
#define IDC_GBBADCONNECT                1096
#define IDC_STSTATUS                    1102
#define IDC_COMBOPLUGINS                1104
#define IDC_STWWW                       1111
#define IDC_STMAIL                      1113
#define IDC_STCOPY                      1114
#define IDC_STDESC                      1115
#define IDC_STVER                       1116
#define IDC_CHECKTTB                    1117
#define IDC_CHECKSSL                    1117
#define IDC_CHECKNMSGP                  1118
#define IDC_CHECKNOTLS                  1120
#define IDC_CHECKKBN                    1121
#define IDC_BTNSTATUS                   1123
#define IDC_OPTIONSTAB                  1124
#define IDC_BTNCHECKALL                 1125
#define IDC_MAINMENU                    1126
#define IDC_CLOSEONDELETE               1127
#define IDC_LONGDATE                    1128
#define IDC_SMARTDATE                   1129
#define IDC_NOSECONDS                   1130
#define IDC_YAMNASPROTO                 1131
#define IDC_CHECKAPOP                   1200
#define IDC_STATUSGROUP                 1338
#define IDC_SPLITTER                    1400
#define IDC_EDITBODY                    1401
#define IDC_PREVIEW                     1402
#define IDC_BTNADD                      1403
#define IDC_EDITNAME                    1404

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1407
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
