//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDC_AUTHICON                    1
#define IDC_NOTOALL                     3
#define IDC_APPLY                       3
#define IDI_MIRANDA                     102
#define IDD_OPT_TRAFFIC_POPUPS          103
#define IDD_ABOUT                       103
#define IDI_SMS                         103
#define IDI_ONLINE                      104
#define IDI_OFFLINE                     105
#define IDD_CUSTOM_FONT                 106
#define IDD_OPT_FONTS                   107
#define IDD_OPT_GENMENU                 108
#define IDD_OPT_PROTOCOLORDER           109
#define IDD_OPT_ICOLIB                  110
#define IDD_ICOLIB_IMPORT               111
#define IDD_ADDED                       115
#define IDD_URLSEND                     119
#define IDD_URLRECV                     120
#define IDD_AUTHREQ                     121
#define IDD_DETAILS                     125
#define IDD_HISTORY                     127
#define IDI_AWAY                        128
#define IDI_FREE4CHAT                   129
#define IDI_INVISIBLE                   130
#define IDI_NA                          131
#define IDI_LOAD                        132
#define IDD_OPT_SOUND                   134
#define IDI_RECVMSG                     136
#define IDI_URL                         138
#define IDI_DND                         158
#define IDI_OCCUPIED                    159
#define IDI_USERDETAILS                 160
#define IDI_FINDUSER                    161
#define IDI_HELP                        162
#define IDI_OPTIONS                     163
#define IDI_MIRANDAWEBSITE              172
#define IDI_RENAME                      173
#define IDI_HISTORY                     174
#define IDI_DELETE                      175
#define IDR_CONTEXT                     180
#define IDR_ICOLIB_CONTEXT              181
#define IDC_DROP                        183
#define IDD_HISTORY_FIND                192
#define IDI_SENDEMAIL                   193
#define IDD_FILERECV                    194
#define IDD_PROFILEMANAGER              197
#define IDR_CLISTMENU                   199
#define IDI_BLANK                       200
#define IDD_FINDADD                     201
#define IDI_USERONLINE                  201
#define IDI_GROUPSHUT                   202
#define IDD_OPTIONS                     203
#define IDI_GROUPOPEN                   203
#define IDD_FILESEND                    205
#define IDI_NOTICK                      205
#define IDD_OPT_PLUGINS                 206
#define IDI_TICK                        206
#define IDD_OPT_ICONS                   207
#define IDI_FILE                        207
#define IDI_ADDCONTACT                  210
#define IDI_SMALLDOT                    211
#define IDI_FILLEDBLOB                  212
#define IDD_READAWAYMSG                 213
#define IDI_EMPTYBLOB                   213
#define IDD_OPT_IGNORE                  214
#define IDC_HYPERLINKHAND               214
#define IDD_OPT_VISIBILITY              215
#define IDC_DROPUSER                    215
#define IDD_SETAWAYMSG                  216
#define IDI_DETAILSLOGO                 216
#define IDD_OPT_AWAYMSG                 217
#define IDI_UNICODE                     218
#define IDI_ANSI                        219
#define IDD_INFO_SUMMARY                220
#define IDI_LOADED                      220
#define IDD_INFO_CONTACT                221
#define IDR_CREDITS                     221
#define IDI_NOTLOADED                   221
#define IDD_INFO_BACKGROUND             222
#define IDD_INFO_NOTES                  223
#define IDD_ADDEMAIL                    226
#define IDD_ICONINDEX                   227
#define IDD_INFO_LOCATION               231
#define IDD_INFO_WORK                   232
#define IDD_ADDPHONE                    233
#define IDD_INSTALLINI                  235
#define IDD_WARNINICHANGE               236
#define IDD_INIIMPORTDONE               237
#define IDB_SORTCOLUP                   239
#define IDB_SORTCOLDOWN                 240
#define IDD_OPT_TRAFFIC                 248
#define IDD_FILETRANSFERINFO            249
#define IDD_OPT_FILETRANSFER            250
#define IDD_FILEEXISTS                  251
#define IDD_DELETECONTACT               254
#define IDD_DENYREASON                  256
#define IDD_ADDCONTACT                  257
#define IDD_OPT_CONTACT                 261
#define IDI_DOWNARROW                   264
#define IDD_OPT_IDLE                    268
#define IDD_PROFILE_SELECTION           269
#define IDD_PROFILE_NEW                 270
#define IDI_TYPING                      274
#define IDD_UPDATE_NOTIFY               275
#define IDD_OPT_UPDATENOTIFY            276
#define IDI_GROUP_ICON                  286
#define IDI_UNINSTALL_ICON              287
#define IDD_OPT_STATS                   295
#define IDI_ONTHEPHONE                  1002
#define IDC_MESSAGE                     1002
#define IDI_OUTTOLUNCH                  1003
#define IDC_AUTOCLOSE                   1004
#define IDC_FROM                        1005
#define IDC_AUTOMIN                     1005
#define IDC_DATE                        1006
#define IDC_MSG                         1008
#define IDC_NAME                        1009
#define IDC_NAMEVAL                     1010
#define IDC_ST_ENTERMSG                 1013
#define IDC_ST_ENTERURL                 1014
#define IDC_ENABLEUPNP                  1015
#define IDC_ABOUT                       1032
#define IDC_MYNOTES                     1033
#define IDC_URLS                        1037
#define IDC_REPLY                       1039
#define IDC_URL                         1041
#define IDC_FONTGROUP                   1042
#define IDC_COLOURLIST                  1043
#define IDC_STAT_RESTART                1044
#define IDC_BTN_RESET                   1045
#define IDC_REASON                      1046
#define IDC_BTN_UNDO                    1047
#define IDC_EMAIL                       1048
#define IDC_NAMENICK                    1049
#define IDC_NAMEFIRST                   1050
#define IDC_NAMELAST                    1051
#define IDC_NICK                        1053
#define IDC_BTN_EXPORT                  1054
#define IDC_FONTLIST                    1056
#define IDC_CHOOSEFONT                  1057
#define IDC_GENDER                      1060
#define IDC_CITY                        1061
#define IDC_STATE                       1062
#define IDC_COUNTRY                     1063
#define IDC_AGE                         1064
#define IDC_ZIP                         1064
#define IDC_PHONE                       1065
#define IDC_STREET                      1065
#define IDC_COMPANY                     1066
#define IDC_LANGUAGE1                   1066
#define IDC_TIMEZONE                    1067
#define IDC_DEPARTMENT                  1067
#define IDC_LOCALTIME                   1068
#define IDC_DETAILS                     1069
#define IDC_POSITION                    1069
#define IDC_LANGUAGE2                   1069
#define IDC_ADD                         1070
#define IDC_LANGUAGE3                   1070
#define IDC_MOREOPTIONS                 1071
#define IDC_USERMENU                    1071
#define IDC_EDIT                        1078
#define IDC_LIST                        1079
#define IDC_HISTORY                     1080
#define IDC_MENUOBJECTS                 1081
#define IDC_MENUITEMS                   1082
#define IDC_NOTSUPPORTWARNING           1083
#define IDC_INSERTSEPARATOR             1084
#define IDC_GENMENU_SERVICE             1085
#define IDC_GENMENU_CUSTOMNAME          1086
#define IDC_GENMENU_SET                 1087
#define IDC_GENMENU_SET2                1088
#define IDC_GENMENU_DEFAULT             1089
#define IDC_BUILDTIME                   1108
#define IDC_CREDITSFILE                 1109
#define IDC_NUMBER                      1113
#define IDC_UIN                         1123
#define IDC_FINDWHAT                    1131
#define IDC_FIND                        1132
#define IDC_FILE                        1133
#define IDC_PROFILELIST                 1134
#define IDC_TABS                        1141
#define IDC_RESULTS                     1142
#define IDC_STATUS                      1144
#define IDC_CHANGE                      1164
#define IDC_PREVIEW                     1165
#define IDC_CHOOSE                      1169
#define IDC_TO                          1170
#define IDC_VERSION                     1179
#define IDC_ICONSET                     1183
#define IDC_BROWSE                      1184
#define IDC_PAGETREE                    1186
#define IDC_RETRIEVING                  1193
#define IDC_GETMORE                     1200
#define IDC_VISIBLEICON                 1204
#define IDC_INVISIBLEICON               1205
#define IDC_FILEICON                    1206
#define IDC_ONLINEICON                  1207
#define IDC_FILENAMES                   1208
#define IDC_ALLICON                     1208
#define IDC_DONTREPLY                   1209
#define IDC_NONEICON                    1209
#define IDC_USEPREVIOUS                 1210
#define IDC_TYPINGICON                  1210
#define IDC_NODIALOG                    1211
#define IDC_USESPECIFIC                 1212
#define IDC_FILEDIR                     1213
#define IDC_ALLFILESPROGRESS            1217
#define IDC_CURRENTSPEED                1219
#define IDC_WHITERECT                   1221
#define IDC_ALLSPEED                    1221
#define IDC_CURRENTFILEPROGRESS         1222
#define IDC_CURRENTFILEGROUP            1223
#define IDC_FIRSTNAME                   1224
#define IDC_LASTNAME                    1225
#define IDC_CURRENTTRANSFERRED          1225
#define IDC_DOBDAY                      1226
#define IDC_DOBMONTH                    1227
#define IDC_WEBPAGE                     1228
#define IDC_DOBYEAR                     1228
#define IDC_UPDATING                    1231
#define IDC_NAMEORDER                   1234
#define IDC_IMPORT                      1241
#define IDC_TOMAIN                      1243
#define IDC_TOPROTO                     1244
#define IDC_PROTOLIST                   1245
#define IDC_TODEFICON                   1246
#define IDC_IMPORTMULTI                 1247
#define IDC_BKGCOLOUR                   1269
#define IDC_FONTCOLOUR                  1282
#define IDC_INTERESTS                   1305
#define IDC_EMAILS                      1306
#define IDC_PAST                        1307
#define IDC_PHONES                      1308
#define IDC_SMS                         1310
#define IDC_AREA                        1312
#define IDC_UPDATE                      1313
#define IDC_ININAME                     1333
#define IDC_VIEWINI                     1334
#define IDC_SECURITYINFO                1335
#define IDC_SETTINGNAME                 1336
#define IDC_NEWVALUE                    1337
#define IDC_WARNNOMORE                  1338
#define IDC_DELETE                      1339
#define IDC_RECYCLE                     1340
#define IDC_NEWNAME                     1341
#define IDC_MOVE                        1342
#define IDC_LEAVE                       1343
#define IDC_EXPERT                      1346
#define IDC_CATEGORYLIST                1366
#define IDC_LOADICONS                   1369
#define IDC_STICONSGROUP                1371
#define IDC_MSGICON                     1375
#define IDC_URLICON                     1376
#define IDC_STNOPAGE                    1377
#define IDC_STCHECKMARKS                1380
#define IDC_MIRANDA                     1388
#define IDC_STATUSBAR                   1389
#define IDC_PROTOIDGROUP                1392
#define IDC_BYPROTOID                   1393
#define IDC_PROTOID                     1394
#define IDC_EMAILGROUP                  1395
#define IDC_BYEMAIL                     1396
#define IDC_STNAMENICK                  1397
#define IDC_NAMEGROUP                   1398
#define IDC_BYNAME                      1399
#define IDC_STNAMEFIRST                 1400
#define IDC_STNAMELAST                  1401
#define IDC_ADVANCEDGROUP               1402
#define IDC_BYADVANCED                  1403
#define IDC_ADVANCED                    1404
#define IDC_PROTOCOLORDER               1405
#define IDC_TINYEXTENDEDGROUP           1406
#define IDC_RESETPROTOCOLDATA           1407
#define IDC_BYCUSTOM                    1408
#define IDC_PROTOCOLORDERWARNING        1409
#define IDC_STSIMPLERIGHT               1440
#define IDC_STATIC54                    1453
#define IDC_FILEDIRBROWSE               1475
#define IDC_ALLFILESGROUP               1476
#define IDC_SCANCMDLINEBROWSE           1476
#define IDC_ALLTRANSFERRED              1477
#define IDC_OPENFOLDER                  1478
#define IDC_OPENFILE                    1479
#define IDC_TOTALSIZE                   1480
#define IDC_AUTOACCEPT                  1484
#define IDC_SCANCMDLINE                 1485
#define IDC_WARNBEFOREOPENING           1488
#define IDC_SCANDURINGDL                1489
#define IDC_SCANAFTERDL                 1490
#define IDC_NOSCANNER                   1491
#define IDC_ST_CMDLINE                  1492
#define IDC_ST_CMDLINEHELP              1493
#define IDC_PROPERTIES                  1496
#define IDC_RESUME                      1497
#define IDC_EXISTINGICON                1499
#define IDC_RESUMEALL                   1500
#define IDC_OVERWRITE                   1501
#define IDC_OVERWRITEALL                1502
#define IDC_SKIP                        1503
#define IDC_EXISTINGSIZE                1506
#define IDC_EXISTINGDATE                1507
#define IDC_EXISTINGTYPE                1508
#define IDC_NEWICON                     1509
#define IDC_NEWSIZE                     1510
#define IDC_NEWDATE                     1511
#define IDC_NEWTYPE                     1512
#define IDC_SAVEAS                      1513
#define IDC_ASK                         1516
#define IDC_RENAME                      1519
#define IDC_VIRUSSCANNERGROUP           1520
#define IDC_HIDE                        1534
#define IDC_TOPLINE                     1535
#define IDC_MAIL                        1536
#define IDC_DESCRIPTION                 1538
#define IDC_MYHANDLE                    1540
#define IDC_GROUP                       1541
#define IDC_ADDED                       1542
#define IDC_AUTH                        1543
#define IDC_DELETEHISTORY               1560
#define IDC_AUTHREQ                     1577
#define IDC_AUTHGB                      1578
#define IDC_PROTOCOL                    1580
#define IDC_CONTRIBLINK                 1586
#define IDC_DEVS                        1589
#define IDC_LOGO                        1591
#define IDC_BUTTON_TSHOW                1597
#define IDC_BUTTON_TSHOWHIDE            1598
#define IDC_BUTTON_THIDE                1599
#define IDC_CHECK1                      1600
#define IDC_DRAWKB                      1601
#define IDC_CHECK2                      1604
#define IDC_LAST_CLEAR                  1609
#define IDC_SAVETIMER                   1612
#define IDC_ESAVETIMER                  1613
#define IDC_BSHOWHIDE                   1614
#define IDC_NEED_RESTART                1615
#define IDC_COLOR1                      1617
#define IDC_USESNAPPING                 1618
#define IDC_RESETCOLORS                 1619
#define IDC_COLOR2                      1620
#define IDC_DRAWCLEARDATE               1621
#define IDC_NOTIFYSIZE                  1622
#define IDC_ENOTIFYSIZE                 1623
#define IDC_NOTIFYTIME                  1624
#define IDC_ENOTIFYTIME                 1625
#define IDC_TTRANSPARENT                1627
#define IDC_TEST                        1628
#define IDC_TSTATIC                     1633
#define IDC_MAINTAB                     1636
#define IDC_IDLEONWINDOWS               1637
#define IDC_POPUP_TIMEOUT               1638
#define IDC_IDLEONMIRANDA               1638
#define IDC_RADIO_FROMPOPUP             1639
#define IDC_RADIO_CUSTOM                1640
#define IDC_SELECT_PROTOCOLS            1641
#define IDC_SCREENSAVER                 1642
#define IDC_LOCKED                      1643
#define IDC_IDLESHORT                   1644
#define IDC_COMBO_AUTO_CLEAR            1645
#define IDC_IDLE1STTIME                 1646
#define IDC_IDLEPRIVATE                 1649
#define IDC_AASTATUS                    1650
#define IDC_AUTO_HIDE                   1651
#define IDC_AASHORTIDLE                 1651
#define IDC_CHECK3                      1653
#define IDC_CHECK_FIXED_HEIGHT          1655
#define IDC_FORMAT                      1656
#define IDC_EDIT_DATEFORMAT             1657
#define IDC_LINE_HEIGHT                 1658
#define IDC_CHECK_DATELINE              1659
#define IDC_LOCATION                    1659
#define IDC_EDIT_                       1659
#define IDC_SGROUP                      1660
#define IDC_COMBO_DATE_ALLIGN           1661
#define IDC_SLOC                        1661
#define IDC_EDIT_COUNTER_FORMAT2        1661
#define IDC_EDIT_COUNTER_FORMAT         1661
#define IDC_EDIT_COUNTER_FORMAT3        1662
#define IDC_EDIT_OVERALL_COUNTER_FORMAT 1662
#define IDC_PROFILENAME                 1673
#define IDC_PROFILEDRIVERS              1674
#define IDC_PLUGLIST                    1676
#define IDC_PLUGINLONGINFO              1677
#define IDC_PLUGINAUTHOR                1679
#define IDC_PLUGININFOFRAME             1680
#define IDC_PLUGINCPYR                  1681
#define IDC_PLUGINURL                   1682
#define IDC_PLUGINPID                   1683
#define IDC_PLUGINEMAIL                 1684
#define IDC_IDLESPIN                    1687
#define IDC_NODBDRIVERS                 1690
#define IDC_IDLESTATUSLOCK              1691
#define IDC_RESTART                     1692
#define IDC_TAB                         1693
#define IDC_IDLETERMINAL                1694
#define IDC_ENABLESOUNDS                1695
#define IDC_NEWVERSIONLABEL             1696
#define IDC_CURRENTVERSION              1697
#define IDC_DOWNLOAD                    1699
#define IDC_ENABLEUPDATES               1700
#define IDC_ENABLEALPHA                 1701
#define IDC_RESETMENU                   1702
#define IDC_MODULES                     1704
#define IDC_STATIC_FILTERCAPTION        1705
#define IDC_APPEARANCEOPTIONS           1715
#define IDC_SPIN1                       1716
#define IDC_TOOLTIP_FORMAT              1718
#define IDC_EDIT_TOOLTIP_FORMAT         1718
#define IDC_TAB_STATS                   1721
#define IDC_COMBO1                      1722
#define IDC_COMBO_UNITS                 1722
#define IDC_LIST_DATA                   1725
#define IDC_STATIC_DNL                  1726
#define IDC_STATIC_UPL                  1727
#define IDC_STATIC_SUMM                 1728
#define IDC_BUTTON_CLEAR                1730
#define IDC_EDIT_SPACE                  21660
#define IDC_EDIT_SPACE2                 21661
#define IDI_SEARCHALL                   32548
#define ID_ICQ_EXIT                     40001
#define IDM_COPY                        40001
#define ID_RESET                        40002
#define POPUP_HIDEEMPTYGROUPS           40003
#define POPUP_NEWSUBGROUP               40004
#define POPUP_HIDEOFFLINE               40005
#define POPUP_GROUPHIDEOFFLINE          40006
#define POPUP_HIDEOFFLINEROOT           40007
#define POPUP_DISABLEGROUPS             40008
#define IDC_SENDMESSAGE                 40009
#define IDM_COPYALL                     40011
#define IDM_SELECTALL                   40012
#define IDM_CLEAR                       40013
#define IDM_OPENNEW                     40014
#define IDM_OPENEXISTING                40015
#define IDM_COPYLINK                    40016
#define POPUP_HIDEMIRANDA               40017
#define ID_CANCELCHANGE                 40018
#define ID_TRAY_HIDE                    40038
#define ID_TRAY_EXIT                    40040
#define POPUP_NEWGROUP                  40050
#define POPUP_RENAMEGROUP               40052
#define POPUP_DELETEGROUP               40053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        297
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1731
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
