/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: encrypted_app_ticket.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "encrypted_app_ticket.pb-c.h"
size_t encrypted_app_ticket__get_packed_size
                     (const EncryptedAppTicket *message)
{
  assert(message->descriptor == &encrypted_app_ticket__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t encrypted_app_ticket__pack
                     (const EncryptedAppTicket *message,
                      uint8_t       *out)
{
  assert(message->descriptor == &encrypted_app_ticket__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t encrypted_app_ticket__pack_to_buffer
                     (const EncryptedAppTicket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->descriptor == &encrypted_app_ticket__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EncryptedAppTicket *
       encrypted_app_ticket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EncryptedAppTicket *)
     protobuf_c_message_unpack (&encrypted_app_ticket__descriptor,
                                allocator, len, data);
}
void   encrypted_app_ticket__free_unpacked
                     (EncryptedAppTicket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->descriptor == &encrypted_app_ticket__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}

static const ProtobufCFieldDescriptor encrypted_app_ticket__field_descriptors[5] =
{
  {
    "ticket_version_no",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EncryptedAppTicket, has_ticket_version_no),
    offsetof(EncryptedAppTicket, ticket_version_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crc_encryptedticket",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EncryptedAppTicket, has_crc_encryptedticket),
    offsetof(EncryptedAppTicket, crc_encryptedticket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cb_encrypteduserdata",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EncryptedAppTicket, has_cb_encrypteduserdata),
    offsetof(EncryptedAppTicket, cb_encrypteduserdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cb_encrypted_appownershipticket",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EncryptedAppTicket, has_cb_encrypted_appownershipticket),
    offsetof(EncryptedAppTicket, cb_encrypted_appownershipticket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_ticket",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EncryptedAppTicket, has_encrypted_ticket),
    offsetof(EncryptedAppTicket, encrypted_ticket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned encrypted_app_ticket__field_indices_by_name[] = {
  3,   /* field[3] = cb_encrypted_appownershipticket */
  2,   /* field[2] = cb_encrypteduserdata */
  1,   /* field[1] = crc_encryptedticket */
  4,   /* field[4] = encrypted_ticket */
  0,   /* field[0] = ticket_version_no */
};
static const ProtobufCIntRange encrypted_app_ticket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor encrypted_app_ticket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EncryptedAppTicket",
  "EncryptedAppTicket",
  "EncryptedAppTicket",
  "",
  sizeof(EncryptedAppTicket),
  5,
  encrypted_app_ticket__field_descriptors,
  encrypted_app_ticket__field_indices_by_name,
  1,  encrypted_app_ticket__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[123] */
};
