/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: enums.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "enums.pb-c.h"
static const ProtobufCEnumValue epublished_file_query_type__enum_values_by_number[22] =
{
  { "k_PublishedFileQueryType_RankedByVote", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByVote", 0 },
  { "k_PublishedFileQueryType_RankedByPublicationDate", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByPublicationDate", 1 },
  { "k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate", 2 },
  { "k_PublishedFileQueryType_RankedByTrend", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByTrend", 3 },
  { "k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate", 4 },
  { "k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate", 5 },
  { "k_PublishedFileQueryType_RankedByNumTimesReported", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByNumTimesReported", 6 },
  { "k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate", 7 },
  { "k_PublishedFileQueryType_NotYetRated", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_NotYetRated", 8 },
  { "k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions", 9 },
  { "k_PublishedFileQueryType_RankedByTotalVotesAsc", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByTotalVotesAsc", 10 },
  { "k_PublishedFileQueryType_RankedByVotesUp", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByVotesUp", 11 },
  { "k_PublishedFileQueryType_RankedByTextSearch", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByTextSearch", 12 },
  { "k_PublishedFileQueryType_RankedByPlaytimeTrend", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByPlaytimeTrend", 13 },
  { "k_PublishedFileQueryType_RankedByTotalPlaytime", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByTotalPlaytime", 14 },
  { "k_PublishedFileQueryType_RankedByAveragePlaytimeTrend", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByAveragePlaytimeTrend", 15 },
  { "k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime", 16 },
  { "k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend", 17 },
  { "k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions", 18 },
  { "k_PublishedFileQueryType_RankedByInappropriateContentRating", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByInappropriateContentRating", 19 },
  { "k_PublishedFileQueryType_RankedByBanContentCheck", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByBanContentCheck", 20 },
  { "k_PublishedFileQueryType_RankedByLastUpdatedDate", "EPUBLISHED_FILE_QUERY_TYPE__k_PublishedFileQueryType_RankedByLastUpdatedDate", 21 },
};
static const ProtobufCIntRange epublished_file_query_type__value_ranges[] = {
{0, 0},{0, 22}
};
static const ProtobufCEnumValueIndex epublished_file_query_type__enum_values_by_name[22] =
{
  { "k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate", 2 },
  { "k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate", 7 },
  { "k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate", 5 },
  { "k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate", 4 },
  { "k_PublishedFileQueryType_NotYetRated", 8 },
  { "k_PublishedFileQueryType_RankedByAveragePlaytimeTrend", 15 },
  { "k_PublishedFileQueryType_RankedByBanContentCheck", 20 },
  { "k_PublishedFileQueryType_RankedByInappropriateContentRating", 19 },
  { "k_PublishedFileQueryType_RankedByLastUpdatedDate", 21 },
  { "k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime", 16 },
  { "k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions", 18 },
  { "k_PublishedFileQueryType_RankedByNumTimesReported", 6 },
  { "k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend", 17 },
  { "k_PublishedFileQueryType_RankedByPlaytimeTrend", 13 },
  { "k_PublishedFileQueryType_RankedByPublicationDate", 1 },
  { "k_PublishedFileQueryType_RankedByTextSearch", 12 },
  { "k_PublishedFileQueryType_RankedByTotalPlaytime", 14 },
  { "k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions", 9 },
  { "k_PublishedFileQueryType_RankedByTotalVotesAsc", 10 },
  { "k_PublishedFileQueryType_RankedByTrend", 3 },
  { "k_PublishedFileQueryType_RankedByVote", 0 },
  { "k_PublishedFileQueryType_RankedByVotesUp", 11 },
};
const ProtobufCEnumDescriptor epublished_file_query_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EPublishedFileQueryType",
  "EPublishedFileQueryType",
  "EPublishedFileQueryType",
  "",
  22,
  epublished_file_query_type__enum_values_by_number,
  22,
  epublished_file_query_type__enum_values_by_name,
  1,
  epublished_file_query_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue epublished_file_inappropriate_provider__enum_values_by_number[3] =
{
  { "k_EPublishedFileInappropriateProvider_Invalid", "EPUBLISHED_FILE_INAPPROPRIATE_PROVIDER__k_EPublishedFileInappropriateProvider_Invalid", 0 },
  { "k_EPublishedFileInappropriateProvider_Google", "EPUBLISHED_FILE_INAPPROPRIATE_PROVIDER__k_EPublishedFileInappropriateProvider_Google", 1 },
  { "k_EPublishedFileInappropriateProvider_Amazon", "EPUBLISHED_FILE_INAPPROPRIATE_PROVIDER__k_EPublishedFileInappropriateProvider_Amazon", 2 },
};
static const ProtobufCIntRange epublished_file_inappropriate_provider__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex epublished_file_inappropriate_provider__enum_values_by_name[3] =
{
  { "k_EPublishedFileInappropriateProvider_Amazon", 2 },
  { "k_EPublishedFileInappropriateProvider_Google", 1 },
  { "k_EPublishedFileInappropriateProvider_Invalid", 0 },
};
const ProtobufCEnumDescriptor epublished_file_inappropriate_provider__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EPublishedFileInappropriateProvider",
  "EPublishedFileInappropriateProvider",
  "EPublishedFileInappropriateProvider",
  "",
  3,
  epublished_file_inappropriate_provider__enum_values_by_number,
  3,
  epublished_file_inappropriate_provider__enum_values_by_name,
  1,
  epublished_file_inappropriate_provider__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue epublished_file_inappropriate_result__enum_values_by_number[6] =
{
  { "k_EPublishedFileInappropriateResult_NotScanned", "EPUBLISHED_FILE_INAPPROPRIATE_RESULT__k_EPublishedFileInappropriateResult_NotScanned", 0 },
  { "k_EPublishedFileInappropriateResult_VeryUnlikely", "EPUBLISHED_FILE_INAPPROPRIATE_RESULT__k_EPublishedFileInappropriateResult_VeryUnlikely", 1 },
  { "k_EPublishedFileInappropriateResult_Unlikely", "EPUBLISHED_FILE_INAPPROPRIATE_RESULT__k_EPublishedFileInappropriateResult_Unlikely", 30 },
  { "k_EPublishedFileInappropriateResult_Possible", "EPUBLISHED_FILE_INAPPROPRIATE_RESULT__k_EPublishedFileInappropriateResult_Possible", 50 },
  { "k_EPublishedFileInappropriateResult_Likely", "EPUBLISHED_FILE_INAPPROPRIATE_RESULT__k_EPublishedFileInappropriateResult_Likely", 75 },
  { "k_EPublishedFileInappropriateResult_VeryLikely", "EPUBLISHED_FILE_INAPPROPRIATE_RESULT__k_EPublishedFileInappropriateResult_VeryLikely", 100 },
};
static const ProtobufCIntRange epublished_file_inappropriate_result__value_ranges[] = {
{0, 0},{30, 2},{50, 3},{75, 4},{100, 5},{0, 6}
};
static const ProtobufCEnumValueIndex epublished_file_inappropriate_result__enum_values_by_name[6] =
{
  { "k_EPublishedFileInappropriateResult_Likely", 4 },
  { "k_EPublishedFileInappropriateResult_NotScanned", 0 },
  { "k_EPublishedFileInappropriateResult_Possible", 3 },
  { "k_EPublishedFileInappropriateResult_Unlikely", 2 },
  { "k_EPublishedFileInappropriateResult_VeryLikely", 5 },
  { "k_EPublishedFileInappropriateResult_VeryUnlikely", 1 },
};
const ProtobufCEnumDescriptor epublished_file_inappropriate_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EPublishedFileInappropriateResult",
  "EPublishedFileInappropriateResult",
  "EPublishedFileInappropriateResult",
  "",
  6,
  epublished_file_inappropriate_result__enum_values_by_number,
  6,
  epublished_file_inappropriate_result__enum_values_by_name,
  5,
  epublished_file_inappropriate_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue epersona_state_flag__enum_values_by_number[10] =
{
  { "k_EPersonaStateFlag_HasRichPresence", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_HasRichPresence", 1 },
  { "k_EPersonaStateFlag_InJoinableGame", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_InJoinableGame", 2 },
  { "k_EPersonaStateFlag_Golden", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_Golden", 4 },
  { "k_EPersonaStateFlag_RemotePlayTogether", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_RemotePlayTogether", 8 },
  { "k_EPersonaStateFlag_ClientTypeWeb", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_ClientTypeWeb", 256 },
  { "k_EPersonaStateFlag_ClientTypeMobile", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_ClientTypeMobile", 512 },
  { "k_EPersonaStateFlag_ClientTypeTenfoot", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_ClientTypeTenfoot", 1024 },
  { "k_EPersonaStateFlag_ClientTypeVR", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_ClientTypeVR", 2048 },
  { "k_EPersonaStateFlag_LaunchTypeGamepad", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_LaunchTypeGamepad", 4096 },
  { "k_EPersonaStateFlag_LaunchTypeCompatTool", "EPERSONA_STATE_FLAG__k_EPersonaStateFlag_LaunchTypeCompatTool", 8192 },
};
static const ProtobufCIntRange epersona_state_flag__value_ranges[] = {
{1, 0},{4, 2},{8, 3},{256, 4},{512, 5},{1024, 6},{2048, 7},{4096, 8},{8192, 9},{0, 10}
};
static const ProtobufCEnumValueIndex epersona_state_flag__enum_values_by_name[10] =
{
  { "k_EPersonaStateFlag_ClientTypeMobile", 5 },
  { "k_EPersonaStateFlag_ClientTypeTenfoot", 6 },
  { "k_EPersonaStateFlag_ClientTypeVR", 7 },
  { "k_EPersonaStateFlag_ClientTypeWeb", 4 },
  { "k_EPersonaStateFlag_Golden", 2 },
  { "k_EPersonaStateFlag_HasRichPresence", 0 },
  { "k_EPersonaStateFlag_InJoinableGame", 1 },
  { "k_EPersonaStateFlag_LaunchTypeCompatTool", 9 },
  { "k_EPersonaStateFlag_LaunchTypeGamepad", 8 },
  { "k_EPersonaStateFlag_RemotePlayTogether", 3 },
};
const ProtobufCEnumDescriptor epersona_state_flag__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EPersonaStateFlag",
  "EPersonaStateFlag",
  "EPersonaStateFlag",
  "",
  10,
  epersona_state_flag__enum_values_by_number,
  10,
  epersona_state_flag__enum_values_by_name,
  9,
  epersona_state_flag__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue econtent_check_provider__enum_values_by_number[4] =
{
  { "k_EContentCheckProvider_Invalid", "ECONTENT_CHECK_PROVIDER__k_EContentCheckProvider_Invalid", 0 },
  { "k_EContentCheckProvider_Google", "ECONTENT_CHECK_PROVIDER__k_EContentCheckProvider_Google", 1 },
  { "k_EContentCheckProvider_Amazon", "ECONTENT_CHECK_PROVIDER__k_EContentCheckProvider_Amazon", 2 },
  { "k_EContentCheckProvider_Local", "ECONTENT_CHECK_PROVIDER__k_EContentCheckProvider_Local", 3 },
};
static const ProtobufCIntRange econtent_check_provider__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex econtent_check_provider__enum_values_by_name[4] =
{
  { "k_EContentCheckProvider_Amazon", 2 },
  { "k_EContentCheckProvider_Google", 1 },
  { "k_EContentCheckProvider_Invalid", 0 },
  { "k_EContentCheckProvider_Local", 3 },
};
const ProtobufCEnumDescriptor econtent_check_provider__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EContentCheckProvider",
  "EContentCheckProvider",
  "EContentCheckProvider",
  "",
  4,
  econtent_check_provider__enum_values_by_number,
  4,
  econtent_check_provider__enum_values_by_name,
  1,
  econtent_check_provider__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eprofile_customization_type__enum_values_by_number[25] =
{
  { "k_EProfileCustomizationTypeInvalid", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeInvalid", 0 },
  { "k_EProfileCustomizationTypeRareAchievementShowcase", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeRareAchievementShowcase", 1 },
  { "k_EProfileCustomizationTypeGameCollector", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeGameCollector", 2 },
  { "k_EProfileCustomizationTypeItemShowcase", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeItemShowcase", 3 },
  { "k_EProfileCustomizationTypeTradeShowcase", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeTradeShowcase", 4 },
  { "k_EProfileCustomizationTypeBadges", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeBadges", 5 },
  { "k_EProfileCustomizationTypeFavoriteGame", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeFavoriteGame", 6 },
  { "k_EProfileCustomizationTypeScreenshotShowcase", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeScreenshotShowcase", 7 },
  { "k_EProfileCustomizationTypeCustomText", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeCustomText", 8 },
  { "k_EProfileCustomizationTypeFavoriteGroup", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeFavoriteGroup", 9 },
  { "k_EProfileCustomizationTypeRecommendation", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeRecommendation", 10 },
  { "k_EProfileCustomizationTypeWorkshopItem", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeWorkshopItem", 11 },
  { "k_EProfileCustomizationTypeMyWorkshop", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeMyWorkshop", 12 },
  { "k_EProfileCustomizationTypeArtworkShowcase", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeArtworkShowcase", 13 },
  { "k_EProfileCustomizationTypeVideoShowcase", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeVideoShowcase", 14 },
  { "k_EProfileCustomizationTypeGuides", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeGuides", 15 },
  { "k_EProfileCustomizationTypeMyGuides", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeMyGuides", 16 },
  { "k_EProfileCustomizationTypeAchievements", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeAchievements", 17 },
  { "k_EProfileCustomizationTypeGreenlight", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeGreenlight", 18 },
  { "k_EProfileCustomizationTypeMyGreenlight", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeMyGreenlight", 19 },
  { "k_EProfileCustomizationTypeSalien", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeSalien", 20 },
  { "k_EProfileCustomizationTypeLoyaltyRewardReactions", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeLoyaltyRewardReactions", 21 },
  { "k_EProfileCustomizationTypeSingleArtworkShowcase", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeSingleArtworkShowcase", 22 },
  { "k_EProfileCustomizationTypeAchievementsCompletionist", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeAchievementsCompletionist", 23 },
  { "k_EProfileCustomizationTypeReplay", "EPROFILE_CUSTOMIZATION_TYPE__k_EProfileCustomizationTypeReplay", 24 },
};
static const ProtobufCIntRange eprofile_customization_type__value_ranges[] = {
{0, 0},{0, 25}
};
static const ProtobufCEnumValueIndex eprofile_customization_type__enum_values_by_name[25] =
{
  { "k_EProfileCustomizationTypeAchievements", 17 },
  { "k_EProfileCustomizationTypeAchievementsCompletionist", 23 },
  { "k_EProfileCustomizationTypeArtworkShowcase", 13 },
  { "k_EProfileCustomizationTypeBadges", 5 },
  { "k_EProfileCustomizationTypeCustomText", 8 },
  { "k_EProfileCustomizationTypeFavoriteGame", 6 },
  { "k_EProfileCustomizationTypeFavoriteGroup", 9 },
  { "k_EProfileCustomizationTypeGameCollector", 2 },
  { "k_EProfileCustomizationTypeGreenlight", 18 },
  { "k_EProfileCustomizationTypeGuides", 15 },
  { "k_EProfileCustomizationTypeInvalid", 0 },
  { "k_EProfileCustomizationTypeItemShowcase", 3 },
  { "k_EProfileCustomizationTypeLoyaltyRewardReactions", 21 },
  { "k_EProfileCustomizationTypeMyGreenlight", 19 },
  { "k_EProfileCustomizationTypeMyGuides", 16 },
  { "k_EProfileCustomizationTypeMyWorkshop", 12 },
  { "k_EProfileCustomizationTypeRareAchievementShowcase", 1 },
  { "k_EProfileCustomizationTypeRecommendation", 10 },
  { "k_EProfileCustomizationTypeReplay", 24 },
  { "k_EProfileCustomizationTypeSalien", 20 },
  { "k_EProfileCustomizationTypeScreenshotShowcase", 7 },
  { "k_EProfileCustomizationTypeSingleArtworkShowcase", 22 },
  { "k_EProfileCustomizationTypeTradeShowcase", 4 },
  { "k_EProfileCustomizationTypeVideoShowcase", 14 },
  { "k_EProfileCustomizationTypeWorkshopItem", 11 },
};
const ProtobufCEnumDescriptor eprofile_customization_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EProfileCustomizationType",
  "EProfileCustomizationType",
  "EProfileCustomizationType",
  "",
  25,
  eprofile_customization_type__enum_values_by_number,
  25,
  eprofile_customization_type__enum_values_by_name,
  1,
  eprofile_customization_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue epublished_file_storage_system__enum_values_by_number[4] =
{
  { "k_EPublishedFileStorageSystemInvalid", "EPUBLISHED_FILE_STORAGE_SYSTEM__k_EPublishedFileStorageSystemInvalid", 0 },
  { "k_EPublishedFileStorageSystemLegacyCloud", "EPUBLISHED_FILE_STORAGE_SYSTEM__k_EPublishedFileStorageSystemLegacyCloud", 1 },
  { "k_EPublishedFileStorageSystemDepot", "EPUBLISHED_FILE_STORAGE_SYSTEM__k_EPublishedFileStorageSystemDepot", 2 },
  { "k_EPublishedFileStorageSystemUGCCloud", "EPUBLISHED_FILE_STORAGE_SYSTEM__k_EPublishedFileStorageSystemUGCCloud", 3 },
};
static const ProtobufCIntRange epublished_file_storage_system__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex epublished_file_storage_system__enum_values_by_name[4] =
{
  { "k_EPublishedFileStorageSystemDepot", 2 },
  { "k_EPublishedFileStorageSystemInvalid", 0 },
  { "k_EPublishedFileStorageSystemLegacyCloud", 1 },
  { "k_EPublishedFileStorageSystemUGCCloud", 3 },
};
const ProtobufCEnumDescriptor epublished_file_storage_system__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EPublishedFileStorageSystem",
  "EPublishedFileStorageSystem",
  "EPublishedFileStorageSystem",
  "",
  4,
  epublished_file_storage_system__enum_values_by_number,
  4,
  epublished_file_storage_system__enum_values_by_name,
  1,
  epublished_file_storage_system__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ecloud_storage_persist_state__enum_values_by_number[3] =
{
  { "k_ECloudStoragePersistStatePersisted", "ECLOUD_STORAGE_PERSIST_STATE__k_ECloudStoragePersistStatePersisted", 0 },
  { "k_ECloudStoragePersistStateForgotten", "ECLOUD_STORAGE_PERSIST_STATE__k_ECloudStoragePersistStateForgotten", 1 },
  { "k_ECloudStoragePersistStateDeleted", "ECLOUD_STORAGE_PERSIST_STATE__k_ECloudStoragePersistStateDeleted", 2 },
};
static const ProtobufCIntRange ecloud_storage_persist_state__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ecloud_storage_persist_state__enum_values_by_name[3] =
{
  { "k_ECloudStoragePersistStateDeleted", 2 },
  { "k_ECloudStoragePersistStateForgotten", 1 },
  { "k_ECloudStoragePersistStatePersisted", 0 },
};
const ProtobufCEnumDescriptor ecloud_storage_persist_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ECloudStoragePersistState",
  "ECloudStoragePersistState",
  "ECloudStoragePersistState",
  "",
  3,
  ecloud_storage_persist_state__enum_values_by_number,
  3,
  ecloud_storage_persist_state__enum_values_by_name,
  1,
  ecloud_storage_persist_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esdcard_format_stage__enum_values_by_number[6] =
{
  { "k_ESDCardFormatStage_Invalid", "ESDCARD_FORMAT_STAGE__k_ESDCardFormatStage_Invalid", 0 },
  { "k_ESDCardFormatStage_Starting", "ESDCARD_FORMAT_STAGE__k_ESDCardFormatStage_Starting", 1 },
  { "k_ESDCardFormatStage_Testing", "ESDCARD_FORMAT_STAGE__k_ESDCardFormatStage_Testing", 2 },
  { "k_ESDCardFormatStage_Rescuing", "ESDCARD_FORMAT_STAGE__k_ESDCardFormatStage_Rescuing", 3 },
  { "k_ESDCardFormatStage_Formatting", "ESDCARD_FORMAT_STAGE__k_ESDCardFormatStage_Formatting", 4 },
  { "k_ESDCardFormatStage_Finalizing", "ESDCARD_FORMAT_STAGE__k_ESDCardFormatStage_Finalizing", 5 },
};
static const ProtobufCIntRange esdcard_format_stage__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex esdcard_format_stage__enum_values_by_name[6] =
{
  { "k_ESDCardFormatStage_Finalizing", 5 },
  { "k_ESDCardFormatStage_Formatting", 4 },
  { "k_ESDCardFormatStage_Invalid", 0 },
  { "k_ESDCardFormatStage_Rescuing", 3 },
  { "k_ESDCardFormatStage_Starting", 1 },
  { "k_ESDCardFormatStage_Testing", 2 },
};
const ProtobufCEnumDescriptor esdcard_format_stage__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESDCardFormatStage",
  "ESDCardFormatStage",
  "ESDCardFormatStage",
  "",
  6,
  esdcard_format_stage__enum_values_by_number,
  6,
  esdcard_format_stage__enum_values_by_name,
  1,
  esdcard_format_stage__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esystem_fan_control_mode__enum_values_by_number[3] =
{
  { "k_SystemFanControlMode_Invalid", "ESYSTEM_FAN_CONTROL_MODE__k_SystemFanControlMode_Invalid", 0 },
  { "k_SystemFanControlMode_Disabled", "ESYSTEM_FAN_CONTROL_MODE__k_SystemFanControlMode_Disabled", 1 },
  { "k_SystemFanControlMode_Default", "ESYSTEM_FAN_CONTROL_MODE__k_SystemFanControlMode_Default", 2 },
};
static const ProtobufCIntRange esystem_fan_control_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex esystem_fan_control_mode__enum_values_by_name[3] =
{
  { "k_SystemFanControlMode_Default", 2 },
  { "k_SystemFanControlMode_Disabled", 1 },
  { "k_SystemFanControlMode_Invalid", 0 },
};
const ProtobufCEnumDescriptor esystem_fan_control_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESystemFanControlMode",
  "ESystemFanControlMode",
  "ESystemFanControlMode",
  "",
  3,
  esystem_fan_control_mode__enum_values_by_number,
  3,
  esystem_fan_control_mode__enum_values_by_name,
  1,
  esystem_fan_control_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ecolor_profile__enum_values_by_number[4] =
{
  { "k_EColorProfile_Invalid", "ECOLOR_PROFILE__k_EColorProfile_Invalid", 0 },
  { "k_EColorProfile_Native", "ECOLOR_PROFILE__k_EColorProfile_Native", 1 },
  { "k_EColorProfile_Standard", "ECOLOR_PROFILE__k_EColorProfile_Standard", 2 },
  { "k_EColorProfile_Vivid", "ECOLOR_PROFILE__k_EColorProfile_Vivid", 3 },
};
static const ProtobufCIntRange ecolor_profile__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ecolor_profile__enum_values_by_name[4] =
{
  { "k_EColorProfile_Invalid", 0 },
  { "k_EColorProfile_Native", 1 },
  { "k_EColorProfile_Standard", 2 },
  { "k_EColorProfile_Vivid", 3 },
};
const ProtobufCEnumDescriptor ecolor_profile__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EColorProfile",
  "EColorProfile",
  "EColorProfile",
  "",
  4,
  ecolor_profile__enum_values_by_number,
  4,
  ecolor_profile__enum_values_by_name,
  1,
  ecolor_profile__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ebluetooth_device_type__enum_values_by_number[12] =
{
  { "k_BluetoothDeviceType_Invalid", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Invalid", 0 },
  { "k_BluetoothDeviceType_Unknown", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Unknown", 1 },
  { "k_BluetoothDeviceType_Phone", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Phone", 2 },
  { "k_BluetoothDeviceType_Computer", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Computer", 3 },
  { "k_BluetoothDeviceType_Headset", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Headset", 4 },
  { "k_BluetoothDeviceType_Headphones", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Headphones", 5 },
  { "k_BluetoothDeviceType_Speakers", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Speakers", 6 },
  { "k_BluetoothDeviceType_OtherAudio", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_OtherAudio", 7 },
  { "k_BluetoothDeviceType_Mouse", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Mouse", 8 },
  { "k_BluetoothDeviceType_Joystick", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Joystick", 9 },
  { "k_BluetoothDeviceType_Gamepad", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Gamepad", 10 },
  { "k_BluetoothDeviceType_Keyboard", "EBLUETOOTH_DEVICE_TYPE__k_BluetoothDeviceType_Keyboard", 11 },
};
static const ProtobufCIntRange ebluetooth_device_type__value_ranges[] = {
{0, 0},{0, 12}
};
static const ProtobufCEnumValueIndex ebluetooth_device_type__enum_values_by_name[12] =
{
  { "k_BluetoothDeviceType_Computer", 3 },
  { "k_BluetoothDeviceType_Gamepad", 10 },
  { "k_BluetoothDeviceType_Headphones", 5 },
  { "k_BluetoothDeviceType_Headset", 4 },
  { "k_BluetoothDeviceType_Invalid", 0 },
  { "k_BluetoothDeviceType_Joystick", 9 },
  { "k_BluetoothDeviceType_Keyboard", 11 },
  { "k_BluetoothDeviceType_Mouse", 8 },
  { "k_BluetoothDeviceType_OtherAudio", 7 },
  { "k_BluetoothDeviceType_Phone", 2 },
  { "k_BluetoothDeviceType_Speakers", 6 },
  { "k_BluetoothDeviceType_Unknown", 1 },
};
const ProtobufCEnumDescriptor ebluetooth_device_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EBluetoothDeviceType",
  "EBluetoothDeviceType",
  "EBluetoothDeviceType",
  "",
  12,
  ebluetooth_device_type__enum_values_by_number,
  12,
  ebluetooth_device_type__enum_values_by_name,
  1,
  ebluetooth_device_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esystem_audio_direction__enum_values_by_number[3] =
{
  { "k_SystemAudioDirection_Invalid", "ESYSTEM_AUDIO_DIRECTION__k_SystemAudioDirection_Invalid", 0 },
  { "k_SystemAudioDirection_Input", "ESYSTEM_AUDIO_DIRECTION__k_SystemAudioDirection_Input", 1 },
  { "k_SystemAudioDirection_Output", "ESYSTEM_AUDIO_DIRECTION__k_SystemAudioDirection_Output", 2 },
};
static const ProtobufCIntRange esystem_audio_direction__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex esystem_audio_direction__enum_values_by_name[3] =
{
  { "k_SystemAudioDirection_Input", 1 },
  { "k_SystemAudioDirection_Invalid", 0 },
  { "k_SystemAudioDirection_Output", 2 },
};
const ProtobufCEnumDescriptor esystem_audio_direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESystemAudioDirection",
  "ESystemAudioDirection",
  "ESystemAudioDirection",
  "",
  3,
  esystem_audio_direction__enum_values_by_number,
  3,
  esystem_audio_direction__enum_values_by_name,
  1,
  esystem_audio_direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esystem_audio_channel__enum_values_by_number[10] =
{
  { "k_SystemAudioChannel_Invalid", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_Invalid", 0 },
  { "k_SystemAudioChannel_Aggregated", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_Aggregated", 1 },
  { "k_SystemAudioChannel_FrontLeft", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_FrontLeft", 2 },
  { "k_SystemAudioChannel_FrontRight", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_FrontRight", 3 },
  { "k_SystemAudioChannel_LFE", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_LFE", 4 },
  { "k_SystemAudioChannel_BackLeft", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_BackLeft", 5 },
  { "k_SystemAudioChannel_BackRight", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_BackRight", 6 },
  { "k_SystemAudioChannel_FrontCenter", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_FrontCenter", 7 },
  { "k_SystemAudioChannel_Unknown", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_Unknown", 8 },
  { "k_SystemAudioChannel_Mono", "ESYSTEM_AUDIO_CHANNEL__k_SystemAudioChannel_Mono", 9 },
};
static const ProtobufCIntRange esystem_audio_channel__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex esystem_audio_channel__enum_values_by_name[10] =
{
  { "k_SystemAudioChannel_Aggregated", 1 },
  { "k_SystemAudioChannel_BackLeft", 5 },
  { "k_SystemAudioChannel_BackRight", 6 },
  { "k_SystemAudioChannel_FrontCenter", 7 },
  { "k_SystemAudioChannel_FrontLeft", 2 },
  { "k_SystemAudioChannel_FrontRight", 3 },
  { "k_SystemAudioChannel_Invalid", 0 },
  { "k_SystemAudioChannel_LFE", 4 },
  { "k_SystemAudioChannel_Mono", 9 },
  { "k_SystemAudioChannel_Unknown", 8 },
};
const ProtobufCEnumDescriptor esystem_audio_channel__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESystemAudioChannel",
  "ESystemAudioChannel",
  "ESystemAudioChannel",
  "",
  10,
  esystem_audio_channel__enum_values_by_number,
  10,
  esystem_audio_channel__enum_values_by_name,
  1,
  esystem_audio_channel__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esystem_audio_port_type__enum_values_by_number[5] =
{
  { "k_SystemAudioPortType_Invalid", "ESYSTEM_AUDIO_PORT_TYPE__k_SystemAudioPortType_Invalid", 0 },
  { "k_SystemAudioPortType_Unknown", "ESYSTEM_AUDIO_PORT_TYPE__k_SystemAudioPortType_Unknown", 1 },
  { "k_SystemAudioPortType_Audio32f", "ESYSTEM_AUDIO_PORT_TYPE__k_SystemAudioPortType_Audio32f", 2 },
  { "k_SystemAudioPortType_Midi8b", "ESYSTEM_AUDIO_PORT_TYPE__k_SystemAudioPortType_Midi8b", 3 },
  { "k_SystemAudioPortType_Video32RGBA", "ESYSTEM_AUDIO_PORT_TYPE__k_SystemAudioPortType_Video32RGBA", 4 },
};
static const ProtobufCIntRange esystem_audio_port_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex esystem_audio_port_type__enum_values_by_name[5] =
{
  { "k_SystemAudioPortType_Audio32f", 2 },
  { "k_SystemAudioPortType_Invalid", 0 },
  { "k_SystemAudioPortType_Midi8b", 3 },
  { "k_SystemAudioPortType_Unknown", 1 },
  { "k_SystemAudioPortType_Video32RGBA", 4 },
};
const ProtobufCEnumDescriptor esystem_audio_port_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESystemAudioPortType",
  "ESystemAudioPortType",
  "ESystemAudioPortType",
  "",
  5,
  esystem_audio_port_type__enum_values_by_number,
  5,
  esystem_audio_port_type__enum_values_by_name,
  1,
  esystem_audio_port_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esystem_audio_port_direction__enum_values_by_number[3] =
{
  { "k_SystemAudioPortDirection_Invalid", "ESYSTEM_AUDIO_PORT_DIRECTION__k_SystemAudioPortDirection_Invalid", 0 },
  { "k_SystemAudioPortDirection_Input", "ESYSTEM_AUDIO_PORT_DIRECTION__k_SystemAudioPortDirection_Input", 1 },
  { "k_SystemAudioPortDirection_Output", "ESYSTEM_AUDIO_PORT_DIRECTION__k_SystemAudioPortDirection_Output", 2 },
};
static const ProtobufCIntRange esystem_audio_port_direction__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex esystem_audio_port_direction__enum_values_by_name[3] =
{
  { "k_SystemAudioPortDirection_Input", 1 },
  { "k_SystemAudioPortDirection_Invalid", 0 },
  { "k_SystemAudioPortDirection_Output", 2 },
};
const ProtobufCEnumDescriptor esystem_audio_port_direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESystemAudioPortDirection",
  "ESystemAudioPortDirection",
  "ESystemAudioPortDirection",
  "",
  3,
  esystem_audio_port_direction__enum_values_by_number,
  3,
  esystem_audio_port_direction__enum_values_by_name,
  1,
  esystem_audio_port_direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esystem_service_state__enum_values_by_number[3] =
{
  { "k_ESystemServiceState_Unavailable", "ESYSTEM_SERVICE_STATE__k_ESystemServiceState_Unavailable", 0 },
  { "k_ESystemServiceState_Disabled", "ESYSTEM_SERVICE_STATE__k_ESystemServiceState_Disabled", 1 },
  { "k_ESystemServiceState_Enabled", "ESYSTEM_SERVICE_STATE__k_ESystemServiceState_Enabled", 2 },
};
static const ProtobufCIntRange esystem_service_state__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex esystem_service_state__enum_values_by_name[3] =
{
  { "k_ESystemServiceState_Disabled", 1 },
  { "k_ESystemServiceState_Enabled", 2 },
  { "k_ESystemServiceState_Unavailable", 0 },
};
const ProtobufCEnumDescriptor esystem_service_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESystemServiceState",
  "ESystemServiceState",
  "ESystemServiceState",
  "",
  3,
  esystem_service_state__enum_values_by_number,
  3,
  esystem_service_state__enum_values_by_name,
  1,
  esystem_service_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue egraphics_perf_overlay_level__enum_values_by_number[5] =
{
  { "k_EGraphicsPerfOverlayLevel_Hidden", "EGRAPHICS_PERF_OVERLAY_LEVEL__k_EGraphicsPerfOverlayLevel_Hidden", 0 },
  { "k_EGraphicsPerfOverlayLevel_Basic", "EGRAPHICS_PERF_OVERLAY_LEVEL__k_EGraphicsPerfOverlayLevel_Basic", 1 },
  { "k_EGraphicsPerfOverlayLevel_Medium", "EGRAPHICS_PERF_OVERLAY_LEVEL__k_EGraphicsPerfOverlayLevel_Medium", 2 },
  { "k_EGraphicsPerfOverlayLevel_Full", "EGRAPHICS_PERF_OVERLAY_LEVEL__k_EGraphicsPerfOverlayLevel_Full", 3 },
  { "k_EGraphicsPerfOverlayLevel_Minimal", "EGRAPHICS_PERF_OVERLAY_LEVEL__k_EGraphicsPerfOverlayLevel_Minimal", 4 },
};
static const ProtobufCIntRange egraphics_perf_overlay_level__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex egraphics_perf_overlay_level__enum_values_by_name[5] =
{
  { "k_EGraphicsPerfOverlayLevel_Basic", 1 },
  { "k_EGraphicsPerfOverlayLevel_Full", 3 },
  { "k_EGraphicsPerfOverlayLevel_Hidden", 0 },
  { "k_EGraphicsPerfOverlayLevel_Medium", 2 },
  { "k_EGraphicsPerfOverlayLevel_Minimal", 4 },
};
const ProtobufCEnumDescriptor egraphics_perf_overlay_level__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EGraphicsPerfOverlayLevel",
  "EGraphicsPerfOverlayLevel",
  "EGraphicsPerfOverlayLevel",
  "",
  5,
  egraphics_perf_overlay_level__enum_values_by_number,
  5,
  egraphics_perf_overlay_level__enum_values_by_name,
  1,
  egraphics_perf_overlay_level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue egpuperformance_level__enum_values_by_number[6] =
{
  { "k_EGPUPerformanceLevel_Invalid", "EGPUPERFORMANCE_LEVEL__k_EGPUPerformanceLevel_Invalid", 0 },
  { "k_EGPUPerformanceLevel_Auto", "EGPUPERFORMANCE_LEVEL__k_EGPUPerformanceLevel_Auto", 1 },
  { "k_EGPUPerformanceLevel_Manual", "EGPUPERFORMANCE_LEVEL__k_EGPUPerformanceLevel_Manual", 2 },
  { "k_EGPUPerformanceLevel_Low", "EGPUPERFORMANCE_LEVEL__k_EGPUPerformanceLevel_Low", 3 },
  { "k_EGPUPerformanceLevel_High", "EGPUPERFORMANCE_LEVEL__k_EGPUPerformanceLevel_High", 4 },
  { "k_EGPUPerformanceLevel_Profiling", "EGPUPERFORMANCE_LEVEL__k_EGPUPerformanceLevel_Profiling", 5 },
};
static const ProtobufCIntRange egpuperformance_level__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex egpuperformance_level__enum_values_by_name[6] =
{
  { "k_EGPUPerformanceLevel_Auto", 1 },
  { "k_EGPUPerformanceLevel_High", 4 },
  { "k_EGPUPerformanceLevel_Invalid", 0 },
  { "k_EGPUPerformanceLevel_Low", 3 },
  { "k_EGPUPerformanceLevel_Manual", 2 },
  { "k_EGPUPerformanceLevel_Profiling", 5 },
};
const ProtobufCEnumDescriptor egpuperformance_level__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EGPUPerformanceLevel",
  "EGPUPerformanceLevel",
  "EGPUPerformanceLevel",
  "",
  6,
  egpuperformance_level__enum_values_by_number,
  6,
  egpuperformance_level__enum_values_by_name,
  1,
  egpuperformance_level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue escaling_filter__enum_values_by_number[6] =
{
  { "k_EScalingFilter_Invalid", "ESCALING_FILTER__k_EScalingFilter_Invalid", 0 },
  { "k_EScalingFilter_FSR", "ESCALING_FILTER__k_EScalingFilter_FSR", 1 },
  { "k_EScalingFilter_Nearest", "ESCALING_FILTER__k_EScalingFilter_Nearest", 2 },
  { "k_EScalingFilter_Integer", "ESCALING_FILTER__k_EScalingFilter_Integer", 3 },
  { "k_EScalingFilter_Linear", "ESCALING_FILTER__k_EScalingFilter_Linear", 4 },
  { "k_EScalingFilter_NIS", "ESCALING_FILTER__k_EScalingFilter_NIS", 5 },
};
static const ProtobufCIntRange escaling_filter__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex escaling_filter__enum_values_by_name[6] =
{
  { "k_EScalingFilter_FSR", 1 },
  { "k_EScalingFilter_Integer", 3 },
  { "k_EScalingFilter_Invalid", 0 },
  { "k_EScalingFilter_Linear", 4 },
  { "k_EScalingFilter_NIS", 5 },
  { "k_EScalingFilter_Nearest", 2 },
};
const ProtobufCEnumDescriptor escaling_filter__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EScalingFilter",
  "EScalingFilter",
  "EScalingFilter",
  "",
  6,
  escaling_filter__enum_values_by_number,
  6,
  escaling_filter__enum_values_by_name,
  1,
  escaling_filter__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esplit_scaling_filter__enum_values_by_number[5] =
{
  { "k_ESplitScalingFilter_Invalid", "ESPLIT_SCALING_FILTER__k_ESplitScalingFilter_Invalid", 0 },
  { "k_ESplitScalingFilter_Linear", "ESPLIT_SCALING_FILTER__k_ESplitScalingFilter_Linear", 1 },
  { "k_ESplitScalingFilter_Nearest", "ESPLIT_SCALING_FILTER__k_ESplitScalingFilter_Nearest", 2 },
  { "k_ESplitScalingFilter_FSR", "ESPLIT_SCALING_FILTER__k_ESplitScalingFilter_FSR", 3 },
  { "k_ESplitScalingFilter_NIS", "ESPLIT_SCALING_FILTER__k_ESplitScalingFilter_NIS", 4 },
};
static const ProtobufCIntRange esplit_scaling_filter__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex esplit_scaling_filter__enum_values_by_name[5] =
{
  { "k_ESplitScalingFilter_FSR", 3 },
  { "k_ESplitScalingFilter_Invalid", 0 },
  { "k_ESplitScalingFilter_Linear", 1 },
  { "k_ESplitScalingFilter_NIS", 4 },
  { "k_ESplitScalingFilter_Nearest", 2 },
};
const ProtobufCEnumDescriptor esplit_scaling_filter__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESplitScalingFilter",
  "ESplitScalingFilter",
  "ESplitScalingFilter",
  "",
  5,
  esplit_scaling_filter__enum_values_by_number,
  5,
  esplit_scaling_filter__enum_values_by_name,
  1,
  esplit_scaling_filter__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esplit_scaling_scaler__enum_values_by_number[6] =
{
  { "k_ESplitScalingScaler_Invalid", "ESPLIT_SCALING_SCALER__k_ESplitScalingScaler_Invalid", 0 },
  { "k_ESplitScalingScaler_Auto", "ESPLIT_SCALING_SCALER__k_ESplitScalingScaler_Auto", 1 },
  { "k_ESplitScalingScaler_Integer", "ESPLIT_SCALING_SCALER__k_ESplitScalingScaler_Integer", 2 },
  { "k_ESplitScalingScaler_Fit", "ESPLIT_SCALING_SCALER__k_ESplitScalingScaler_Fit", 3 },
  { "k_ESplitScalingScaler_Fill", "ESPLIT_SCALING_SCALER__k_ESplitScalingScaler_Fill", 4 },
  { "k_ESplitScalingScaler_Stretch", "ESPLIT_SCALING_SCALER__k_ESplitScalingScaler_Stretch", 5 },
};
static const ProtobufCIntRange esplit_scaling_scaler__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex esplit_scaling_scaler__enum_values_by_name[6] =
{
  { "k_ESplitScalingScaler_Auto", 1 },
  { "k_ESplitScalingScaler_Fill", 4 },
  { "k_ESplitScalingScaler_Fit", 3 },
  { "k_ESplitScalingScaler_Integer", 2 },
  { "k_ESplitScalingScaler_Invalid", 0 },
  { "k_ESplitScalingScaler_Stretch", 5 },
};
const ProtobufCEnumDescriptor esplit_scaling_scaler__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESplitScalingScaler",
  "ESplitScalingScaler",
  "ESplitScalingScaler",
  "",
  6,
  esplit_scaling_scaler__enum_values_by_number,
  6,
  esplit_scaling_scaler__enum_values_by_name,
  1,
  esplit_scaling_scaler__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ehdrtone_map_operator__enum_values_by_number[3] =
{
  { "k_EHDRToneMapOperator_Invalid", "EHDRTONE_MAP_OPERATOR__k_EHDRToneMapOperator_Invalid", 0 },
  { "k_EHDRToneMapOperator_Uncharted", "EHDRTONE_MAP_OPERATOR__k_EHDRToneMapOperator_Uncharted", 1 },
  { "k_EHDRToneMapOperator_Reinhard", "EHDRTONE_MAP_OPERATOR__k_EHDRToneMapOperator_Reinhard", 2 },
};
static const ProtobufCIntRange ehdrtone_map_operator__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ehdrtone_map_operator__enum_values_by_name[3] =
{
  { "k_EHDRToneMapOperator_Invalid", 0 },
  { "k_EHDRToneMapOperator_Reinhard", 2 },
  { "k_EHDRToneMapOperator_Uncharted", 1 },
};
const ProtobufCEnumDescriptor ehdrtone_map_operator__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EHDRToneMapOperator",
  "EHDRToneMapOperator",
  "EHDRToneMapOperator",
  "",
  3,
  ehdrtone_map_operator__enum_values_by_number,
  3,
  ehdrtone_map_operator__enum_values_by_name,
  1,
  ehdrtone_map_operator__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ecpugovernor__enum_values_by_number[4] =
{
  { "k_ECPUGovernor_Invalid", "ECPUGOVERNOR__k_ECPUGovernor_Invalid", 0 },
  { "k_ECPUGovernor_Perf", "ECPUGOVERNOR__k_ECPUGovernor_Perf", 1 },
  { "k_ECPUGovernor_Powersave", "ECPUGOVERNOR__k_ECPUGovernor_Powersave", 2 },
  { "k_ECPUGovernor_Manual", "ECPUGOVERNOR__k_ECPUGovernor_Manual", 3 },
};
static const ProtobufCIntRange ecpugovernor__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ecpugovernor__enum_values_by_name[4] =
{
  { "k_ECPUGovernor_Invalid", 0 },
  { "k_ECPUGovernor_Manual", 3 },
  { "k_ECPUGovernor_Perf", 1 },
  { "k_ECPUGovernor_Powersave", 2 },
};
const ProtobufCEnumDescriptor ecpugovernor__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ECPUGovernor",
  "ECPUGovernor",
  "ECPUGovernor",
  "",
  4,
  ecpugovernor__enum_values_by_number,
  4,
  ecpugovernor__enum_values_by_name,
  1,
  ecpugovernor__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eupdater_type__enum_values_by_number[8] =
{
  { "k_EUpdaterType_Invalid", "EUPDATER_TYPE__k_EUpdaterType_Invalid", 0 },
  { "k_EUpdaterType_Client", "EUPDATER_TYPE__k_EUpdaterType_Client", 1 },
  { "k_EUpdaterType_OS", "EUPDATER_TYPE__k_EUpdaterType_OS", 2 },
  { "k_EUpdaterType_BIOS", "EUPDATER_TYPE__k_EUpdaterType_BIOS", 3 },
  { "k_EUpdaterType_Aggregated", "EUPDATER_TYPE__k_EUpdaterType_Aggregated", 4 },
  { "k_EUpdaterType_Test1", "EUPDATER_TYPE__k_EUpdaterType_Test1", 5 },
  { "k_EUpdaterType_Test2", "EUPDATER_TYPE__k_EUpdaterType_Test2", 6 },
  { "k_EUpdaterType_Dummy", "EUPDATER_TYPE__k_EUpdaterType_Dummy", 7 },
};
static const ProtobufCIntRange eupdater_type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex eupdater_type__enum_values_by_name[8] =
{
  { "k_EUpdaterType_Aggregated", 4 },
  { "k_EUpdaterType_BIOS", 3 },
  { "k_EUpdaterType_Client", 1 },
  { "k_EUpdaterType_Dummy", 7 },
  { "k_EUpdaterType_Invalid", 0 },
  { "k_EUpdaterType_OS", 2 },
  { "k_EUpdaterType_Test1", 5 },
  { "k_EUpdaterType_Test2", 6 },
};
const ProtobufCEnumDescriptor eupdater_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EUpdaterType",
  "EUpdaterType",
  "EUpdaterType",
  "",
  8,
  eupdater_type__enum_values_by_number,
  8,
  eupdater_type__enum_values_by_name,
  1,
  eupdater_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eupdater_state__enum_values_by_number[7] =
{
  { "k_EUpdaterState_Invalid", "EUPDATER_STATE__k_EUpdaterState_Invalid", 0 },
  { "k_EUpdaterState_UpToDate", "EUPDATER_STATE__k_EUpdaterState_UpToDate", 2 },
  { "k_EUpdaterState_Checking", "EUPDATER_STATE__k_EUpdaterState_Checking", 3 },
  { "k_EUpdaterState_Available", "EUPDATER_STATE__k_EUpdaterState_Available", 4 },
  { "k_EUpdaterState_Applying", "EUPDATER_STATE__k_EUpdaterState_Applying", 5 },
  { "k_EUpdaterState_ClientRestartPending", "EUPDATER_STATE__k_EUpdaterState_ClientRestartPending", 6 },
  { "k_EUpdaterState_SystemRestartPending", "EUPDATER_STATE__k_EUpdaterState_SystemRestartPending", 7 },
};
static const ProtobufCIntRange eupdater_state__value_ranges[] = {
{0, 0},{2, 1},{0, 7}
};
static const ProtobufCEnumValueIndex eupdater_state__enum_values_by_name[7] =
{
  { "k_EUpdaterState_Applying", 4 },
  { "k_EUpdaterState_Available", 3 },
  { "k_EUpdaterState_Checking", 2 },
  { "k_EUpdaterState_ClientRestartPending", 5 },
  { "k_EUpdaterState_Invalid", 0 },
  { "k_EUpdaterState_SystemRestartPending", 6 },
  { "k_EUpdaterState_UpToDate", 1 },
};
const ProtobufCEnumDescriptor eupdater_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EUpdaterState",
  "EUpdaterState",
  "EUpdaterState",
  "",
  7,
  eupdater_state__enum_values_by_number,
  7,
  eupdater_state__enum_values_by_name,
  2,
  eupdater_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue estorage_block_content_type__enum_values_by_number[5] =
{
  { "k_EStorageBlockContentType_Invalid", "ESTORAGE_BLOCK_CONTENT_TYPE__k_EStorageBlockContentType_Invalid", 0 },
  { "k_EStorageBlockContentType_Unknown", "ESTORAGE_BLOCK_CONTENT_TYPE__k_EStorageBlockContentType_Unknown", 1 },
  { "k_EStorageBlockContentType_FileSystem", "ESTORAGE_BLOCK_CONTENT_TYPE__k_EStorageBlockContentType_FileSystem", 2 },
  { "k_EStorageBlockContentType_Crypto", "ESTORAGE_BLOCK_CONTENT_TYPE__k_EStorageBlockContentType_Crypto", 3 },
  { "k_EStorageBlockContentType_Raid", "ESTORAGE_BLOCK_CONTENT_TYPE__k_EStorageBlockContentType_Raid", 4 },
};
static const ProtobufCIntRange estorage_block_content_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex estorage_block_content_type__enum_values_by_name[5] =
{
  { "k_EStorageBlockContentType_Crypto", 3 },
  { "k_EStorageBlockContentType_FileSystem", 2 },
  { "k_EStorageBlockContentType_Invalid", 0 },
  { "k_EStorageBlockContentType_Raid", 4 },
  { "k_EStorageBlockContentType_Unknown", 1 },
};
const ProtobufCEnumDescriptor estorage_block_content_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EStorageBlockContentType",
  "EStorageBlockContentType",
  "EStorageBlockContentType",
  "",
  5,
  estorage_block_content_type__enum_values_by_number,
  5,
  estorage_block_content_type__enum_values_by_name,
  1,
  estorage_block_content_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue estorage_block_file_system_type__enum_values_by_number[4] =
{
  { "k_EStorageBlockFileSystemType_Invalid", "ESTORAGE_BLOCK_FILE_SYSTEM_TYPE__k_EStorageBlockFileSystemType_Invalid", 0 },
  { "k_EStorageBlockFileSystemType_Unknown", "ESTORAGE_BLOCK_FILE_SYSTEM_TYPE__k_EStorageBlockFileSystemType_Unknown", 1 },
  { "k_EStorageBlockFileSystemType_VFat", "ESTORAGE_BLOCK_FILE_SYSTEM_TYPE__k_EStorageBlockFileSystemType_VFat", 2 },
  { "k_EStorageBlockFileSystemType_Ext4", "ESTORAGE_BLOCK_FILE_SYSTEM_TYPE__k_EStorageBlockFileSystemType_Ext4", 3 },
};
static const ProtobufCIntRange estorage_block_file_system_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex estorage_block_file_system_type__enum_values_by_name[4] =
{
  { "k_EStorageBlockFileSystemType_Ext4", 3 },
  { "k_EStorageBlockFileSystemType_Invalid", 0 },
  { "k_EStorageBlockFileSystemType_Unknown", 1 },
  { "k_EStorageBlockFileSystemType_VFat", 2 },
};
const ProtobufCEnumDescriptor estorage_block_file_system_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EStorageBlockFileSystemType",
  "EStorageBlockFileSystemType",
  "EStorageBlockFileSystemType",
  "",
  4,
  estorage_block_file_system_type__enum_values_by_number,
  4,
  estorage_block_file_system_type__enum_values_by_name,
  1,
  estorage_block_file_system_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue estorage_drive_media_type__enum_values_by_number[5] =
{
  { "k_EStorageDriveMediaType_Invalid", "ESTORAGE_DRIVE_MEDIA_TYPE__k_EStorageDriveMediaType_Invalid", 0 },
  { "k_EStorageDriveMediaType_Unknown", "ESTORAGE_DRIVE_MEDIA_TYPE__k_EStorageDriveMediaType_Unknown", 1 },
  { "k_EStorageDriveMediaType_HDD", "ESTORAGE_DRIVE_MEDIA_TYPE__k_EStorageDriveMediaType_HDD", 2 },
  { "k_EStorageDriveMediaType_SSD", "ESTORAGE_DRIVE_MEDIA_TYPE__k_EStorageDriveMediaType_SSD", 3 },
  { "k_EStorageDriveMediaType_Removable", "ESTORAGE_DRIVE_MEDIA_TYPE__k_EStorageDriveMediaType_Removable", 4 },
};
static const ProtobufCIntRange estorage_drive_media_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex estorage_drive_media_type__enum_values_by_name[5] =
{
  { "k_EStorageDriveMediaType_HDD", 2 },
  { "k_EStorageDriveMediaType_Invalid", 0 },
  { "k_EStorageDriveMediaType_Removable", 4 },
  { "k_EStorageDriveMediaType_SSD", 3 },
  { "k_EStorageDriveMediaType_Unknown", 1 },
};
const ProtobufCEnumDescriptor estorage_drive_media_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EStorageDriveMediaType",
  "EStorageDriveMediaType",
  "EStorageDriveMediaType",
  "",
  5,
  estorage_drive_media_type__enum_values_by_number,
  5,
  estorage_drive_media_type__enum_values_by_name,
  1,
  estorage_drive_media_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esystem_display_compatibility_mode__enum_values_by_number[3] =
{
  { "k_ESystemDisplayCompatibilityMode_Invalid", "ESYSTEM_DISPLAY_COMPATIBILITY_MODE__k_ESystemDisplayCompatibilityMode_Invalid", 0 },
  { "k_ESystemDisplayCompatibilityMode_None", "ESYSTEM_DISPLAY_COMPATIBILITY_MODE__k_ESystemDisplayCompatibilityMode_None", 1 },
  { "k_ESystemDisplayCompatibilityMode_MinimalBandwith", "ESYSTEM_DISPLAY_COMPATIBILITY_MODE__k_ESystemDisplayCompatibilityMode_MinimalBandwith", 2 },
};
static const ProtobufCIntRange esystem_display_compatibility_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex esystem_display_compatibility_mode__enum_values_by_name[3] =
{
  { "k_ESystemDisplayCompatibilityMode_Invalid", 0 },
  { "k_ESystemDisplayCompatibilityMode_MinimalBandwith", 2 },
  { "k_ESystemDisplayCompatibilityMode_None", 1 },
};
const ProtobufCEnumDescriptor esystem_display_compatibility_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESystemDisplayCompatibilityMode",
  "ESystemDisplayCompatibilityMode",
  "ESystemDisplayCompatibilityMode",
  "",
  3,
  esystem_display_compatibility_mode__enum_values_by_number,
  3,
  esystem_display_compatibility_mode__enum_values_by_name,
  1,
  esystem_display_compatibility_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esteam_deck_compatibility_category__enum_values_by_number[4] =
{
  { "k_ESteamDeckCompatibilityCategory_Unknown", "ESTEAM_DECK_COMPATIBILITY_CATEGORY__k_ESteamDeckCompatibilityCategory_Unknown", 0 },
  { "k_ESteamDeckCompatibilityCategory_Unsupported", "ESTEAM_DECK_COMPATIBILITY_CATEGORY__k_ESteamDeckCompatibilityCategory_Unsupported", 1 },
  { "k_ESteamDeckCompatibilityCategory_Playable", "ESTEAM_DECK_COMPATIBILITY_CATEGORY__k_ESteamDeckCompatibilityCategory_Playable", 2 },
  { "k_ESteamDeckCompatibilityCategory_Verified", "ESTEAM_DECK_COMPATIBILITY_CATEGORY__k_ESteamDeckCompatibilityCategory_Verified", 3 },
};
static const ProtobufCIntRange esteam_deck_compatibility_category__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex esteam_deck_compatibility_category__enum_values_by_name[4] =
{
  { "k_ESteamDeckCompatibilityCategory_Playable", 2 },
  { "k_ESteamDeckCompatibilityCategory_Unknown", 0 },
  { "k_ESteamDeckCompatibilityCategory_Unsupported", 1 },
  { "k_ESteamDeckCompatibilityCategory_Verified", 3 },
};
const ProtobufCEnumDescriptor esteam_deck_compatibility_category__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESteamDeckCompatibilityCategory",
  "ESteamDeckCompatibilityCategory",
  "ESteamDeckCompatibilityCategory",
  "",
  4,
  esteam_deck_compatibility_category__enum_values_by_number,
  4,
  esteam_deck_compatibility_category__enum_values_by_name,
  1,
  esteam_deck_compatibility_category__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esteam_deck_compatibility_result_display_type__enum_values_by_number[5] =
{
  { "k_ESteamDeckCompatibilityResultDisplayType_Invisible", "ESTEAM_DECK_COMPATIBILITY_RESULT_DISPLAY_TYPE__k_ESteamDeckCompatibilityResultDisplayType_Invisible", 0 },
  { "k_ESteamDeckCompatibilityResultDisplayType_Informational", "ESTEAM_DECK_COMPATIBILITY_RESULT_DISPLAY_TYPE__k_ESteamDeckCompatibilityResultDisplayType_Informational", 1 },
  { "k_ESteamDeckCompatibilityResultDisplayType_Unsupported", "ESTEAM_DECK_COMPATIBILITY_RESULT_DISPLAY_TYPE__k_ESteamDeckCompatibilityResultDisplayType_Unsupported", 2 },
  { "k_ESteamDeckCompatibilityResultDisplayType_Playable", "ESTEAM_DECK_COMPATIBILITY_RESULT_DISPLAY_TYPE__k_ESteamDeckCompatibilityResultDisplayType_Playable", 3 },
  { "k_ESteamDeckCompatibilityResultDisplayType_Verified", "ESTEAM_DECK_COMPATIBILITY_RESULT_DISPLAY_TYPE__k_ESteamDeckCompatibilityResultDisplayType_Verified", 4 },
};
static const ProtobufCIntRange esteam_deck_compatibility_result_display_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex esteam_deck_compatibility_result_display_type__enum_values_by_name[5] =
{
  { "k_ESteamDeckCompatibilityResultDisplayType_Informational", 1 },
  { "k_ESteamDeckCompatibilityResultDisplayType_Invisible", 0 },
  { "k_ESteamDeckCompatibilityResultDisplayType_Playable", 3 },
  { "k_ESteamDeckCompatibilityResultDisplayType_Unsupported", 2 },
  { "k_ESteamDeckCompatibilityResultDisplayType_Verified", 4 },
};
const ProtobufCEnumDescriptor esteam_deck_compatibility_result_display_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESteamDeckCompatibilityResultDisplayType",
  "ESteamDeckCompatibilityResultDisplayType",
  "ESteamDeckCompatibilityResultDisplayType",
  "",
  5,
  esteam_deck_compatibility_result_display_type__enum_values_by_number,
  5,
  esteam_deck_compatibility_result_display_type__enum_values_by_name,
  1,
  esteam_deck_compatibility_result_display_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eacstate__enum_values_by_number[4] =
{
  { "k_EACState_Unknown", "EACSTATE__k_EACState_Unknown", 0 },
  { "k_EACState_Disconnected", "EACSTATE__k_EACState_Disconnected", 1 },
  { "k_EACState_Connected", "EACSTATE__k_EACState_Connected", 2 },
  { "k_EACState_ConnectedSlow", "EACSTATE__k_EACState_ConnectedSlow", 3 },
};
static const ProtobufCIntRange eacstate__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex eacstate__enum_values_by_name[4] =
{
  { "k_EACState_Connected", 2 },
  { "k_EACState_ConnectedSlow", 3 },
  { "k_EACState_Disconnected", 1 },
  { "k_EACState_Unknown", 0 },
};
const ProtobufCEnumDescriptor eacstate__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EACState",
  "EACState",
  "EACState",
  "",
  4,
  eacstate__enum_values_by_number,
  4,
  eacstate__enum_values_by_name,
  1,
  eacstate__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ebattery_state__enum_values_by_number[4] =
{
  { "k_EBatteryState_Unknown", "EBATTERY_STATE__k_EBatteryState_Unknown", 0 },
  { "k_EBatteryState_Discharging", "EBATTERY_STATE__k_EBatteryState_Discharging", 1 },
  { "k_EBatteryState_Charging", "EBATTERY_STATE__k_EBatteryState_Charging", 2 },
  { "k_EBatteryState_Full", "EBATTERY_STATE__k_EBatteryState_Full", 3 },
};
static const ProtobufCIntRange ebattery_state__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ebattery_state__enum_values_by_name[4] =
{
  { "k_EBatteryState_Charging", 2 },
  { "k_EBatteryState_Discharging", 1 },
  { "k_EBatteryState_Full", 3 },
  { "k_EBatteryState_Unknown", 0 },
};
const ProtobufCEnumDescriptor ebattery_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EBatteryState",
  "EBatteryState",
  "EBatteryState",
  "",
  4,
  ebattery_state__enum_values_by_number,
  4,
  ebattery_state__enum_values_by_name,
  1,
  ebattery_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eosbranch__enum_values_by_number[7] =
{
  { "k_EOSBranch_Unknown", "EOSBRANCH__k_EOSBranch_Unknown", 0 },
  { "k_EOSBranch_Release", "EOSBRANCH__k_EOSBranch_Release", 1 },
  { "k_EOSBranch_ReleaseCandidate", "EOSBRANCH__k_EOSBranch_ReleaseCandidate", 2 },
  { "k_EOSBranch_Beta", "EOSBRANCH__k_EOSBranch_Beta", 3 },
  { "k_EOSBranch_BetaCandidate", "EOSBRANCH__k_EOSBranch_BetaCandidate", 4 },
  { "k_EOSBranch_Main", "EOSBRANCH__k_EOSBranch_Main", 5 },
  { "k_EOSBranch_Staging", "EOSBRANCH__k_EOSBranch_Staging", 6 },
};
static const ProtobufCIntRange eosbranch__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex eosbranch__enum_values_by_name[7] =
{
  { "k_EOSBranch_Beta", 3 },
  { "k_EOSBranch_BetaCandidate", 4 },
  { "k_EOSBranch_Main", 5 },
  { "k_EOSBranch_Release", 1 },
  { "k_EOSBranch_ReleaseCandidate", 2 },
  { "k_EOSBranch_Staging", 6 },
  { "k_EOSBranch_Unknown", 0 },
};
const ProtobufCEnumDescriptor eosbranch__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EOSBranch",
  "EOSBranch",
  "EOSBranch",
  "",
  7,
  eosbranch__enum_values_by_number,
  7,
  eosbranch__enum_values_by_name,
  1,
  eosbranch__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ecommunity_item_class__enum_values_by_number[18] =
{
  { "k_ECommunityItemClass_Invalid", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_Invalid", 0 },
  { "k_ECommunityItemClass_Badge", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_Badge", 1 },
  { "k_ECommunityItemClass_GameCard", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_GameCard", 2 },
  { "k_ECommunityItemClass_ProfileBackground", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_ProfileBackground", 3 },
  { "k_ECommunityItemClass_Emoticon", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_Emoticon", 4 },
  { "k_ECommunityItemClass_BoosterPack", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_BoosterPack", 5 },
  { "k_ECommunityItemClass_Consumable", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_Consumable", 6 },
  { "k_ECommunityItemClass_GameGoo", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_GameGoo", 7 },
  { "k_ECommunityItemClass_ProfileModifier", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_ProfileModifier", 8 },
  { "k_ECommunityItemClass_Scene", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_Scene", 9 },
  { "k_ECommunityItemClass_SalienItem", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_SalienItem", 10 },
  { "k_ECommunityItemClass_Sticker", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_Sticker", 11 },
  { "k_ECommunityItemClass_ChatEffect", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_ChatEffect", 12 },
  { "k_ECommunityItemClass_MiniProfileBackground", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_MiniProfileBackground", 13 },
  { "k_ECommunityItemClass_AvatarFrame", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_AvatarFrame", 14 },
  { "k_ECommunityItemClass_AnimatedAvatar", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_AnimatedAvatar", 15 },
  { "k_ECommunityItemClass_SteamDeckKeyboardSkin", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_SteamDeckKeyboardSkin", 16 },
  { "k_ECommunityItemClass_SteamDeckStartupMovie", "ECOMMUNITY_ITEM_CLASS__k_ECommunityItemClass_SteamDeckStartupMovie", 17 },
};
static const ProtobufCIntRange ecommunity_item_class__value_ranges[] = {
{0, 0},{0, 18}
};
static const ProtobufCEnumValueIndex ecommunity_item_class__enum_values_by_name[18] =
{
  { "k_ECommunityItemClass_AnimatedAvatar", 15 },
  { "k_ECommunityItemClass_AvatarFrame", 14 },
  { "k_ECommunityItemClass_Badge", 1 },
  { "k_ECommunityItemClass_BoosterPack", 5 },
  { "k_ECommunityItemClass_ChatEffect", 12 },
  { "k_ECommunityItemClass_Consumable", 6 },
  { "k_ECommunityItemClass_Emoticon", 4 },
  { "k_ECommunityItemClass_GameCard", 2 },
  { "k_ECommunityItemClass_GameGoo", 7 },
  { "k_ECommunityItemClass_Invalid", 0 },
  { "k_ECommunityItemClass_MiniProfileBackground", 13 },
  { "k_ECommunityItemClass_ProfileBackground", 3 },
  { "k_ECommunityItemClass_ProfileModifier", 8 },
  { "k_ECommunityItemClass_SalienItem", 10 },
  { "k_ECommunityItemClass_Scene", 9 },
  { "k_ECommunityItemClass_SteamDeckKeyboardSkin", 16 },
  { "k_ECommunityItemClass_SteamDeckStartupMovie", 17 },
  { "k_ECommunityItemClass_Sticker", 11 },
};
const ProtobufCEnumDescriptor ecommunity_item_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ECommunityItemClass",
  "ECommunityItemClass",
  "ECommunityItemClass",
  "",
  18,
  ecommunity_item_class__enum_values_by_number,
  18,
  ecommunity_item_class__enum_values_by_name,
  1,
  ecommunity_item_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esteam_deck_compatibility_feedback__enum_values_by_number[4] =
{
  { "k_ESteamDeckCompatibilityFeedback_Unset", "ESTEAM_DECK_COMPATIBILITY_FEEDBACK__k_ESteamDeckCompatibilityFeedback_Unset", 0 },
  { "k_ESteamDeckCompatibilityFeedback_Agree", "ESTEAM_DECK_COMPATIBILITY_FEEDBACK__k_ESteamDeckCompatibilityFeedback_Agree", 1 },
  { "k_ESteamDeckCompatibilityFeedback_Disagree", "ESTEAM_DECK_COMPATIBILITY_FEEDBACK__k_ESteamDeckCompatibilityFeedback_Disagree", 2 },
  { "k_ESteamDeckCompatibilityFeedback_Ignore", "ESTEAM_DECK_COMPATIBILITY_FEEDBACK__k_ESteamDeckCompatibilityFeedback_Ignore", 3 },
};
static const ProtobufCIntRange esteam_deck_compatibility_feedback__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex esteam_deck_compatibility_feedback__enum_values_by_name[4] =
{
  { "k_ESteamDeckCompatibilityFeedback_Agree", 1 },
  { "k_ESteamDeckCompatibilityFeedback_Disagree", 2 },
  { "k_ESteamDeckCompatibilityFeedback_Ignore", 3 },
  { "k_ESteamDeckCompatibilityFeedback_Unset", 0 },
};
const ProtobufCEnumDescriptor esteam_deck_compatibility_feedback__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESteamDeckCompatibilityFeedback",
  "ESteamDeckCompatibilityFeedback",
  "ESteamDeckCompatibilityFeedback",
  "",
  4,
  esteam_deck_compatibility_feedback__enum_values_by_number,
  4,
  esteam_deck_compatibility_feedback__enum_values_by_name,
  1,
  esteam_deck_compatibility_feedback__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eprovide_deck_feedback_preference__enum_values_by_number[3] =
{
  { "k_EProvideDeckFeedbackPreference_Unset", "EPROVIDE_DECK_FEEDBACK_PREFERENCE__k_EProvideDeckFeedbackPreference_Unset", 0 },
  { "k_EProvideDeckFeedbackPreference_Yes", "EPROVIDE_DECK_FEEDBACK_PREFERENCE__k_EProvideDeckFeedbackPreference_Yes", 1 },
  { "k_EProvideDeckFeedbackPreference_No", "EPROVIDE_DECK_FEEDBACK_PREFERENCE__k_EProvideDeckFeedbackPreference_No", 2 },
};
static const ProtobufCIntRange eprovide_deck_feedback_preference__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex eprovide_deck_feedback_preference__enum_values_by_name[3] =
{
  { "k_EProvideDeckFeedbackPreference_No", 2 },
  { "k_EProvideDeckFeedbackPreference_Unset", 0 },
  { "k_EProvideDeckFeedbackPreference_Yes", 1 },
};
const ProtobufCEnumDescriptor eprovide_deck_feedback_preference__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EProvideDeckFeedbackPreference",
  "EProvideDeckFeedbackPreference",
  "EProvideDeckFeedbackPreference",
  "",
  3,
  eprovide_deck_feedback_preference__enum_values_by_number,
  3,
  eprovide_deck_feedback_preference__enum_values_by_name,
  1,
  eprovide_deck_feedback_preference__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue etouch_gesture__enum_values_by_number[14] =
{
  { "k_ETouchGestureNone", "ETOUCH_GESTURE__k_ETouchGestureNone", 0 },
  { "k_ETouchGestureTouch", "ETOUCH_GESTURE__k_ETouchGestureTouch", 1 },
  { "k_ETouchGestureTap", "ETOUCH_GESTURE__k_ETouchGestureTap", 2 },
  { "k_ETouchGestureDoubleTap", "ETOUCH_GESTURE__k_ETouchGestureDoubleTap", 3 },
  { "k_ETouchGestureShortPress", "ETOUCH_GESTURE__k_ETouchGestureShortPress", 4 },
  { "k_ETouchGestureLongPress", "ETOUCH_GESTURE__k_ETouchGestureLongPress", 5 },
  { "k_ETouchGestureLongTap", "ETOUCH_GESTURE__k_ETouchGestureLongTap", 6 },
  { "k_ETouchGestureTwoFingerTap", "ETOUCH_GESTURE__k_ETouchGestureTwoFingerTap", 7 },
  { "k_ETouchGestureTapCancelled", "ETOUCH_GESTURE__k_ETouchGestureTapCancelled", 8 },
  { "k_ETouchGesturePinchBegin", "ETOUCH_GESTURE__k_ETouchGesturePinchBegin", 9 },
  { "k_ETouchGesturePinchUpdate", "ETOUCH_GESTURE__k_ETouchGesturePinchUpdate", 10 },
  { "k_ETouchGesturePinchEnd", "ETOUCH_GESTURE__k_ETouchGesturePinchEnd", 11 },
  { "k_ETouchGestureFlingStart", "ETOUCH_GESTURE__k_ETouchGestureFlingStart", 12 },
  { "k_ETouchGestureFlingCancelled", "ETOUCH_GESTURE__k_ETouchGestureFlingCancelled", 13 },
};
static const ProtobufCIntRange etouch_gesture__value_ranges[] = {
{0, 0},{0, 14}
};
static const ProtobufCEnumValueIndex etouch_gesture__enum_values_by_name[14] =
{
  { "k_ETouchGestureDoubleTap", 3 },
  { "k_ETouchGestureFlingCancelled", 13 },
  { "k_ETouchGestureFlingStart", 12 },
  { "k_ETouchGestureLongPress", 5 },
  { "k_ETouchGestureLongTap", 6 },
  { "k_ETouchGestureNone", 0 },
  { "k_ETouchGesturePinchBegin", 9 },
  { "k_ETouchGesturePinchEnd", 11 },
  { "k_ETouchGesturePinchUpdate", 10 },
  { "k_ETouchGestureShortPress", 4 },
  { "k_ETouchGestureTap", 2 },
  { "k_ETouchGestureTapCancelled", 8 },
  { "k_ETouchGestureTouch", 1 },
  { "k_ETouchGestureTwoFingerTap", 7 },
};
const ProtobufCEnumDescriptor etouch_gesture__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ETouchGesture",
  "ETouchGesture",
  "ETouchGesture",
  "",
  14,
  etouch_gesture__enum_values_by_number,
  14,
  etouch_gesture__enum_values_by_name,
  1,
  etouch_gesture__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esession_persistence__enum_values_by_number[3] =
{
  { "k_ESessionPersistence_Invalid", "ESESSION_PERSISTENCE__k_ESessionPersistence_Invalid", -1 },
  { "k_ESessionPersistence_Ephemeral", "ESESSION_PERSISTENCE__k_ESessionPersistence_Ephemeral", 0 },
  { "k_ESessionPersistence_Persistent", "ESESSION_PERSISTENCE__k_ESessionPersistence_Persistent", 1 },
};
static const ProtobufCIntRange esession_persistence__value_ranges[] = {
{-1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex esession_persistence__enum_values_by_name[3] =
{
  { "k_ESessionPersistence_Ephemeral", 1 },
  { "k_ESessionPersistence_Invalid", 0 },
  { "k_ESessionPersistence_Persistent", 2 },
};
const ProtobufCEnumDescriptor esession_persistence__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ESessionPersistence",
  "ESessionPersistence",
  "ESessionPersistence",
  "",
  3,
  esession_persistence__enum_values_by_number,
  3,
  esession_persistence__enum_values_by_name,
  1,
  esession_persistence__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue enew_steam_announcement_state__enum_values_by_number[4] =
{
  { "k_ENewSteamAnnouncementState_Invalid", "ENEW_STEAM_ANNOUNCEMENT_STATE__k_ENewSteamAnnouncementState_Invalid", 0 },
  { "k_ENewSteamAnnouncementState_AllRead", "ENEW_STEAM_ANNOUNCEMENT_STATE__k_ENewSteamAnnouncementState_AllRead", 1 },
  { "k_ENewSteamAnnouncementState_NewAnnouncement", "ENEW_STEAM_ANNOUNCEMENT_STATE__k_ENewSteamAnnouncementState_NewAnnouncement", 2 },
  { "k_ENewSteamAnnouncementState_FeaturedAnnouncement", "ENEW_STEAM_ANNOUNCEMENT_STATE__k_ENewSteamAnnouncementState_FeaturedAnnouncement", 3 },
};
static const ProtobufCIntRange enew_steam_announcement_state__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex enew_steam_announcement_state__enum_values_by_name[4] =
{
  { "k_ENewSteamAnnouncementState_AllRead", 1 },
  { "k_ENewSteamAnnouncementState_FeaturedAnnouncement", 3 },
  { "k_ENewSteamAnnouncementState_Invalid", 0 },
  { "k_ENewSteamAnnouncementState_NewAnnouncement", 2 },
};
const ProtobufCEnumDescriptor enew_steam_announcement_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ENewSteamAnnouncementState",
  "ENewSteamAnnouncementState",
  "ENewSteamAnnouncementState",
  "",
  4,
  enew_steam_announcement_state__enum_values_by_number,
  4,
  enew_steam_announcement_state__enum_values_by_name,
  1,
  enew_steam_announcement_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
