/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_unified_base.steamclient.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "steammessages_unified_base.steamclient.pb-c.h"
size_t no_response__get_packed_size
                     (const NoResponse *message)
{
  assert(message->descriptor == &no_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t no_response__pack
                     (const NoResponse *message,
                      uint8_t       *out)
{
  assert(message->descriptor == &no_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t no_response__pack_to_buffer
                     (const NoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->descriptor == &no_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NoResponse *
       no_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NoResponse *)
     protobuf_c_message_unpack (&no_response__descriptor,
                                allocator, len, data);
}
void   no_response__free_unpacked
                     (NoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->descriptor == &no_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}

#define no_response__field_descriptors NULL
#define no_response__field_indices_by_name NULL
#define no_response__number_ranges NULL
const ProtobufCMessageDescriptor no_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NoResponse",
  "NoResponse",
  "NoResponse",
  "",
  sizeof(NoResponse),
  0,
  no_response__field_descriptors,
  no_response__field_indices_by_name,
  0,  no_response__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue eproto_execution_site__enum_values_by_number[2] =
{
  { "k_EProtoExecutionSiteUnknown", "EPROTO_EXECUTION_SITE__k_EProtoExecutionSiteUnknown", 0 },
  { "k_EProtoExecutionSiteSteamClient", "EPROTO_EXECUTION_SITE__k_EProtoExecutionSiteSteamClient", 2 },
};
static const ProtobufCIntRange eproto_execution_site__value_ranges[] = {
{0, 0},{2, 1},{0, 2}
};
static const ProtobufCEnumValueIndex eproto_execution_site__enum_values_by_name[2] =
{
  { "k_EProtoExecutionSiteSteamClient", 1 },
  { "k_EProtoExecutionSiteUnknown", 0 },
};
const ProtobufCEnumDescriptor eproto_execution_site__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EProtoExecutionSite",
  "EProtoExecutionSite",
  "EProtoExecutionSite",
  "",
  2,
  eproto_execution_site__enum_values_by_number,
  2,
  eproto_execution_site__enum_values_by_name,
  2,
  eproto_execution_site__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
