#define	MS_SHAKE_CLIST			"SHAKE/Service/ShakeClist"
#define	MS_SHAKE_CHAT			"SHAKE/Service/ShakeChat"
#define	MS_SHAKE_CLIST_TRIGGER	"SHAKE/Service/TriggerShakeClist"
#define	MS_SHAKE_CHAT_TRIGGER	"SHAKE/Service/TirggerShakeChat"
#define	MS_NUDGE_SEND			"NUDGE/Send"
