version: 0.3.2.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: v141
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      TOOLSET: v140
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      TOOLSET: v120

branches:
  except:
    - coverity_scan

configuration:
- Debug
- Release

platform:
- x86
- x64
#- ARM

build_script:
- ps: >
    msbuild "C:\projects\libmdbx\mdbx.sln" /verbosity:minimal
    /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    /property:PlatformToolset=$env:TOOLSET
    /property:Configuration=$env:CONFIGURATION
    /property:Platform=$env:PLATFORM

test_script:
- ps: |
    if (($env:PLATFORM -eq "x86") -and (Test-Path "C:\projects\libmdbx\Win32\$env:CONFIGURATION\mdbx_test.exe" -PathType Leaf)) {
      $mdbx_test = "C:\projects\libmdbx\Win32\$env:CONFIGURATION\mdbx_test.exe"
      $mdbx_chk = "C:\projects\libmdbx\Win32\$env:CONFIGURATION\mdbx_chk.exe"
    } elseif (($env:PLATFORM -ne "ARM") -and ($env:PLATFORM -ne "ARM64")) {
      $mdbx_test = "C:\projects\libmdbx\$env:PLATFORM\$env:CONFIGURATION\mdbx_test.exe"
      $mdbx_chk = "C:\projects\libmdbx\$env:PLATFORM\$env:CONFIGURATION\mdbx_chk.exe"
    } else {
      $mdbx_test = ""
      $mdbx_chk = ""
    }

    if ($mdbx_test -ne "") {
        & "$mdbx_test" --pathname=test.db --dont-cleanup-after basic | Tee-Object -file test.log | Select-Object -last 42
        & "$mdbx_chk" -nvv test.db | Tee-Object -file chk.log | Select-Object -last 42
    }

on_failure:
- ps: Push-AppveyorArtifact test.log
- ps: Push-AppveyorArtifact test.db
- ps: Push-AppveyorArtifact chk.log
