//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resources.rc
//
#define IDD_POPUPOPTDLG                 101
#define IDD_CCN_ERROR                   103
#define IDC_POPUPOPTDLG_POPUPNOTIFY     1002
#define IDC_POPUPOPTDLG_BGCOLOUR        1003
#define IDC_POPUPOPTDLG_TEXTCOLOUR      1004
#define IDC_POPUPOPTDLG_LCLICK_ACTION   1005
#define IDC_POPUPOPTDLG_RCLICK_ACTION   1006
#define IDC_POPUPOPTDLG_POPUPPREVIEW    1007
#define IDC_POPUPOPTDLG_DEFBGCOLOUR     1013
#define IDC_POPUPOPTDLG_DEFTEXTCOLOUR   1014
#define IDC_POPUPOPTDLG_STATIC_LCLICK   1016
#define IDC_POPUPOPTDLG_STATIC_RCLICK   1017
#define IDC_POPUPOPTDLG_STATIC_BGCOLOUR 1018
#define IDC_POPUPOPTDLG_STATIC_TEXTCOLOUR 1019
#define IDC_POPUPOPTDLG_POPUPDELAY      1020
#define IDC_POPUPOPTDLG_STATIC_SEC      1021
#define IDC_POPUPOPTDLG_STATIC_DEFAULT  1022
#define IDC_POPUPOPTDLG_STATIC_INFINITE 1023
#define IDC_POPUPOPTDLG_POPUPDELAY_SPIN 1024
#define IDC_POPUPOPTDLG_VERCHGNOTIFY    1025
#define IDC_POPUPOPTDLG_SHOWPREVCLIENT  1026
#define IDC_POPUPOPTDLG_USESTATUSNOTIFYFLAG 1032
#define IDC_POPUPOPTDLG_SHOWVER         1033
#define IDC_DONTREMIND                  1034
#define IDC_POPUPOPTDLG_IGNORESTRINGS   1035
#define IDC_POPUPOPTDLG_STATIC_IGNORESTRINGS 1036
#define IDC_POPUPOPTDLG_STATIC_REGEXP   1037

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
