//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ..\res\resources.rc
//
#define IDC_OTHERICON                   1
#define IDD_OPT_KN_ACTION               120
#define IDD_OPTIONS                     150
#define IDD_PROTO_OPTIONS               151
#define IDD_BASIC_OPTIONS               152
#define IDD_EFFECT_OPTIONS              153
#define IDD_THEME_OPTIONS               154
#define IDD_EVENTLEDS                   155
#define IDD_PROCESSES                   156
#define IDD_IGNORE_OPTIONS              157
#define IDD_XSTATUSES                   158
#define IDC_ONMESSAGE                   1000
#define IDC_ONFILE                      1001
#define IDC_ONURL                       1002
#define IDC_ONOTHER                     1003
#define IDC_IFOPEN                      1004
#define IDC_IFNOTTOP                    1005
#define IDC_IFOLDER                     1006
#define IDC_SOLDER                      1007
#define IDC_OLDERSPIN                   1008
#define IDC_UNTILBLK                    1009
#define IDC_SBLINK                      1010
#define IDC_BLINKSPIN                   1011
#define IDC_UNTILATTENDED               1012
#define IDC_MIRORWIN                    1013
#define IDC_UNTILOPEN                   1014
#define IDC_UNTILCOND                   1015
#define IDC_FSCREEN                     1016
#define IDC_SSAVER                      1017
#define IDC_LOCKED                      1018
#define IDC_PGMS                        1019
#define IDC_ASSIGNPGMS                  1020
#define IDC_ACTIVE                      1021
#define IDC_ONLINE                      1022
#define IDC_AWAY                        1023
#define IDC_NA                          1024
#define IDC_OCCUPIED                    1025
#define IDC_DND                         1026
#define IDC_FREECHAT                    1027
#define IDC_INVISIBLE                   1028
#define IDC_ONTHEPHONE                  1029
#define IDC_OUTTOLUNCH                  1030
#define IDC_OFFLINE                     1031
#define IDC_REMCHECK                    1032
#define IDC_SREMCHECK                   1033
#define IDC_NUM                         1034
#define IDC_CAPS                        1035
#define IDC_SCROLL                      1036
#define IDC_SAMETIME                    1037
#define IDC_INTURN                      1038
#define IDC_INSEQUENCE                  1039
#define IDC_SEQORDER                    1040
#define IDC_CUSTOM                      1041
#define IDC_SCUSTOM                     1042
#define IDC_TRILLIAN                    1043
#define IDC_ASSIGNLEDS                  1044
#define IDC_SDELAY                      1045
#define IDC_DELAYSPIN                   1046
#define IDC_PREVIEW                     1047
#define IDC_SPEED                       1048
#define IDC_THEME                       1049
#define IDC_CUSTOMSTRING                1050
#define IDC_TEST                        1051
#define IDC_ADD                         1052
#define IDC_UPDATE                      1053
#define IDC_DELETE                      1054
#define IDC_EXPORT                      1055
#define IDC_IMPORT                      1056
#define IDC_OVERRIDE                    1057
#define IDC_PROTOCOLLIST                1058
#define IDC_MSGLEDNUM                   1059
#define IDC_MSGLEDCAPS                  1060
#define IDC_MSGLEDSCROLL                1061
#define IDC_FILELEDNUM                  1062
#define IDC_FILELEDCAPS                 1063
#define IDC_FILELEDSCROLL               1064
#define IDC_URLLEDNUM                   1065
#define IDC_URLLEDCAPS                  1066
#define IDC_URLLEDSCROLL                1067
#define IDC_OTHERLEDNUM                 1068
#define IDC_OTHERLEDCAPS                1069
#define IDC_OTHERLEDSCROLL              1070
#define IDC_OK                          1071
#define IDC_CANCEL                      1072
#define IDC_PROGRAMS                    1073
#define IDC_ADDPGM                      1074
#define IDC_DELETEPGM                   1075
#define IDC_OKPGM                       1076
#define IDC_CANCELPGM                   1077
#define IDC_KEYPRESSES                  1078
#define IDC_CUSTOMTHEME                 1079
#define IDC_USECUSTOM                   1080
#define IDC_LIST                        1081
#define IDC_FORCEOPEN                   1082
#define IDC_SFORCEOPEN                  1083
#define IDC_SELECTXSTATUS               1084
#define IDC_TREE_XSTATUS                1085
#define IDC_OKXST                       1086
#define IDC_CANCELXST                   1087
#define IDC_FILEICON                    1206
#define IDC_ALLICON                     1208
#define IDC_NONEICON                    1209
#define IDC_MSGICON                     1375
#define IDC_URLICON                     1376
#define IDC_TABS                        2000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
