//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ..\res\Resource.rc
//
#define IDI_SKYPE                       102
#define IDI_ONLINE                      104
#define IDI_OFFLINE                     105
#define IDI_AWAY                        128
#define IDI_CHAT                        129
#define IDI_INVISIBLE                   130
#define IDI_NA                          131
#define IDI_DND                         158
#define IDI_OCCUPIED                    159
#define IDI_ADD                         160
#define IDI_IMPORT                      161
#define IDI_ERRORS                      162
#define IDI_MESSAGE                     163
#define IDI_CALL                        164
#define IDI_CALLSKYPEOUT                165
#define IDI_HOLD                        166
#define IDI_RESUME                      167
#define IDI_HANGUP                      168
#define IDI_AVATAR                      169
#define IDD_OPTIONS                     170
#define IDI_INVITE                      170
#define IDD_DIAL                        171
#define IDB_CALL                        172
#define IDD_INPUTBOX                    172
#define IDD_CALLSTAT                    173
#define IDD_SETAVATAR                   174
#define IDD_OPT_DEFAULT                 175
#define IDD_OPT_PROXY                   176
#define IDD_SETDETAILS                  177
#define IDD_OPT_ADVANCED                178
#define IDD_OPT_POPUP                   179
#define IDI_BLOCKCONTACT                182
#define IDI_PHONE                       1002
#define IDC_SHUTDOWN                    1004
#define IDC_ENABLEMENU                  1005
#define IDC_UNLOADOFFLINE               1006
#define IDC_USES2S                      1007
#define IDC_HOST                        1008
#define IDC_PORT                        1009
#define IDC_REQPASS                     1010
#define IDC_PASSWORD                    1011
#define IDC_USEPOPUP                    1012
#define IDC_GROUPCHAT                   1014
#define IDC_NOERRORS                    1015
#define IDC_CONNATTEMPTS                1016
#define IDC_GROUPCHATREAD               1016
#define IDC_SKYPEOUTSTAT                1018
#define IDC_NUMBER                      1019
#define IDDIAL                          1020
#define IDC_KEEPSTATE                   1021
#define IDC_CLEANUP                     1022
#define IDC_JOIN                        1023
#define IDC_TIMEZONE                    1023
#define IDC_HOLD                        1024
#define IDC_SHOWDEFAULTAVATAR           1024
#define IDC_HANGUP                      1025
#define IDC_IGNTZ                       1025
#define IDC_AVATAR                      1026
#define IDC_NOSKYPE3STATS               1026
#define IDC_SETAVATAR                   1027
#define IDC_SHOWFULLNAME                1027
#define IDC_DELETEAVATAR                1028
#define IDC_STARTSKYPE                  1029
#define IDC_NOTRAY                      1030
#define IDC_NOSPLASH                    1031
#define IDC_MINIMIZED                   1032
#define IDC_TEXT                        1033
#define IDC_CUSTOMCOMMAND               1033
#define IDC_OPTIONSTAB                  1034
#define IDC_REMOVEABLE                  1034
#define IDC_FULLNAME                    1035
#define IDC_DATAPATHO                   1035
#define IDC_BIRTHDAY                    1036
#define IDC_SECONDARY                   1036
#define IDC_SEX                         1037
#define IDC_CITY                        1038
#define IDC_COUNTRY                     1039
#define IDC_PROVINCE                    1040
#define IDC_HOMEPHONE                   1041
#define IDC_OFFICEPHONE                 1042
#define IDC_HOMEPAGE                    1043
#define IDC_SAVEDETAILS                 1044
#define IDC_COMMANDLINE                 1045
#define IDC_DATAPATH                    1046
#define IDC_POPUPINCOMING               1049
#define IDC_PREVIEW                     1050
#define IDC_POPUPTEXTCOLOR              1051
#define IDC_POPUPTIME                   1052
#define IDC_POPUPBACKCOLOR              1053
#define IDC_USEWINCOLORS                1054
#define IDC_POPUPERROR                  1055
#define IDC_USERNAME                    1055
#define IDC_PREVIEWERR                  1056
#define IDC_EDIT2                       1056
#define IDC_POPUPTIMEERR                1057
#define IDC_POPUPBACKCOLORERR           1058
#define IDC_POPUPTEXTCOLORERR           1059
#define IDC_USEWINCOLORSERR             1060
#define IDC_SUPPRESSCALLSUMMARYMESSAGE  1061
#define IDC_AUTODETECTION               1062
#define IDC_STATIC_HOST                 1063
#define IDC_STATIC_PORT                 1064
#define IDC_BROWSEDP                    1065
#define IDC_BROWSECMDL                  1066
#define IDC_STATIC_POPUPBACKCOLOR       1066
#define IDC_STATIC_POPUPTEXTCOLOR       1067
#define IDC_STATIC_POPUPTEXTCOLORERR    1068
#define IDC_STATIC_POPUPBACKCOLORERR    1069
#define IDC_STATIC_PATHINFO             1070
#define IDC_STATIC_RESTART              1071
#define IDC_NOACK                       1072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
