//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by chat.rc
//
#define IDR_MENU                        151
#define IDD_CHANNEL                     401
#define IDD_OPTIONS1                    402
#define IDD_OPTIONS2                    403
#define IDD_FILTER                      404
#define IDD_OPTIONSPOPUP                405
#define IDD_OPTIONS3                    407
#define IDD_OPTIONS4                    408
#define IDD_ADDHIGHLIGHT                409
#define IDC_CHAT_LOG                    1005
#define IDC_SPLITTERX                   1006
#define IDC_SMILEY                      1007
#define IDC_SPLITTERY                   1008
#define IDC_CHAT_MESSAGE                1009
#define IDC_FILTER                      1013
#define IDC_CHANMGR                     1014
#define IDC_SHOWNICKLIST                1015
#define IDC_BKGCOLOR                    1019
#define IDC_CHECKBOXES                  1021
#define IDC_NICKROW2                    1023
#define IDC_NICKROW                     1024
#define IDC_LOGLIMIT                    1024
#define IDC_CHAT_CLOSE                  1025
#define IDC_CHAT_SPIN1                  1028
#define IDC_CHAT_SPIN2                  1029
#define IDC_CHAT_SPIN3                  1030
#define IDC_CHAT_SPIN4                  1031
#define IDC_PANELNICK                   1032
#define IDC_PANELUIN                    1033
#define IDC_INSTAMP                     1041
#define IDC_OUTSTAMP                    1043
#define IDC_TIMESTAMP                   1046
#define IDC_FONTCHOOSE                  1047
#define IDC_LOGDIRECTORY                1048
#define IDC_LIMIT                       1050
#define IDC_LOGTIMESTAMP                1051
#define IDC_GROUP                       1057
#define IDC_CHAT_RADIO1                 1061
#define IDC_RADIO2                      1062
#define IDC_RADIO3                      1063
#define IDC_TEXT                        1064
#define IDC_BKG                         1065
#define IDC_TIMEOUT                     1067
#define IDC_TEXTO                       1069
#define IDC_LOGGING                     1069
#define IDC_TEXTO2                      1070
#define IDC_TEXTO3                      1071
#define IDC_LIST                        1072
#define IDC_TEXTO4                      1072
#define IDC_STATIC_ADD                  1077
#define IDC_STATIC_ULIST                1078
#define IDC_STATIC_OTHER                1079
#define IDC_STATIC_MESSAGE              1081
#define IDC_STATIC110                   1082
#define IDC_STATIC112                   1085
#define IDC_TRAYONLYFORINACTIVE         1086
#define IDC_NOPOPUPSFORCLOSEDWINDOWS    1087
#define IDC_LOGICONTYPE                 1088
#define IDC_HIGHLIGHTNICKENABLE         1089
#define IDC_HIGHLIGHTNICKUID            1090
#define IDC_HIGHLIGHTNICKPATTERN        1091
#define IDC_HIGHLIGHTTEXTENABLE         1092
#define IDC_COMBO1                      1092
#define IDC_ADDHIGHLIGHTNAME            1092
#define IDC_HIGHLIGHTTEXTPATTERN        1093
#define IDC_ADDHIGHLIGHTTITLE           1093
#define IDC_ADDHIGHLIGHTEXPLAIN         1094
#define IDC_HIGHLIGHTNICKUID2           1094
#define IDC_HIGHLIGHTME                 1094
#define IDC_ADDHIGHLIGHTEDITLIST        1095
#define IDC_MUC_OPENLOGBASEDIR          1096
#define IDC_CHAT_BOLD                   1106
#define IDC_ITALICS                     1107
#define IDC_CHAT_UNDERLINE              1108
#define IDC_COLOR                       1110
#define IDC_CHAT_HISTORY                1111
#define IDC_1                           1200
#define IDC_2                           1201
#define IDC_3                           1202
#define IDC_4                           1203
#define IDC_5                           1204
#define IDC_6                           1205
#define IDC_7                           1206
#define IDC_8                           1207
#define IDC_9                           1208
#define IDC_10                          1209
#define IDC_11                          1210
#define IDC_PANELSPLITTER               1216
#define IDC_CHAT_TOGGLESIDEBAR          1277
#define IDC_P1                          1300
#define IDC_P2                          1301
#define IDC_P3                          1302
#define IDC_P4                          1303
#define IDC_P5                          1304
#define IDC_P6                          1305
#define IDC_P7                          1306
#define IDC_P8                          1307
#define IDC_P9                          1308
#define IDC_P10                         1309
#define IDC_P11                         1310
#define IDC_P12                         1311
#define IDC_T1                          1400
#define IDC_T2                          1401
#define IDC_T3                          1402
#define IDC_T4                          1403
#define IDC_T5                          1404
#define IDC_T6                          1405
#define IDC_T7                          1406
#define IDC_T8                          1407
#define IDC_T9                          1408
#define IDC_T10                         1409
#define IDC_T11                         1410
#define IDC_T12                         1411
#define IDC_L1                          1500
#define IDC_L2                          1501
#define IDC_L3                          1502
#define IDC_L4                          1503
#define IDC_L5                          1504
#define IDC_L6                          1505
#define IDC_L7                          1506
#define IDC_L8                          1507
#define IDC_L9                          1508
#define IDC_L10                         1509
#define IDC_L11                         1510
#define IDC_WHITERECT                   1600
#define ID_MESS                         40001
#define ID_NEW                          40002
#define ID_CURR                         40003
#define ID_COPY                         40004
#define ID_COPYALL                      40006
#define ID_CLEARLOG                     40009
#define ID_MESSAGE_UNDO                 40013
#define ID_MESSAGE_COPY                 40014
#define ID_MESSAGE_CUT                  40015
#define ID_MESSAGE_CLEAR                40017
#define ID_MESSAGE_SELECTALL            40018
#define ID_MESSAGE_REDO                 40019
#define ID_MESSAGE_PASTE                40020
#define ID_CLOSE                        40022
#define ID_CLOSEOTHER                   40023
#define ID_LOCKPOSITION                 40024
#define ID_SEARCH_GOOGLE                40027
#define ID_SEARCH_WIKIPEDIA             40028
#define ID_WIKIPEDIA_                   40029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
