#ifndef _TLENCOMMONS_INC
#define _TLENCOMMONS_INC


#define TLENMUCC_MAJOR_VERSION		2
#define TLENMUCC_MINOR_VERSION		1
#define TLENMUCC_RELEASE_NUM		0
#define TLENMUCC_BUILD_NUM			0
#define TLENMUCC_VERSION_STRING		"2.1.0.0"



//consts for tlen.dll
#define TLEN_MAJOR_VERSION		TLENMUCC_MAJOR_VERSION
#define TLEN_MINOR_VERSION		TLENMUCC_MINOR_VERSION
#define TLEN_RELEASE_NUM		TLENMUCC_RELEASE_NUM
#define TLEN_BUILD_NUM			TLENMUCC_BUILD_NUM

#define TLEN_FILEVERSION_STRING		TLEN_MAJOR_VERSION,TLEN_MINOR_VERSION,TLEN_RELEASE_NUM,TLEN_BUILD_NUM
#define TLEN_VERSION_STRING			TLENMUCC_VERSION_STRING



#endif //ifndef _TLENCOMMONS_INC
