//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by spamotron.rc
//
#define IDD_SPAMOTRON_MAIN              101
#define IDD_SPAMOTRON_Q                 102
#define IDD_SPAMOTRON_BAYES             103
#define IDD_SPAMOTRON_POPUPS            104
#define IDD_SPAMOTRON_MAIN1             105
#define IDC_OPT_OUT_MSG_APPROVE         1002
#define IDC_OPT_MODE                    1003
#define IDC_OPT_CHALLENGE               1004
#define IDC_OPT_RESPONSE                1005
#define IDC_OPT_SUCCESS_RESPONSE        1006
#define IDC_OPT_AUTH_CHALLENGE          1007
#define IDC_OPT_MATH_RESPONSE           1008
#define IDC_STATIC_RESPONSE             1009
#define IDC_STATIC_MODEMSG              1010
#define IDC_DEFAULTS                    1011
#define IDC_OPT_PROTOCOLS               1012
#define IDC_OPT_REPLY_ON_SUCCESS        1013
#define IDC_OPT_DONT_REPLY_SAME_MSG     1014
#define IDC_OPT_REPLY_ON_AUTH           1015
#define IDC_OPT_BAYES_AUTOLEARN_APPROVED 1016
#define IDC_OPT_POPUPS_NOTIFY_APPROVED  1017
#define IDC_OPT_LOG_ACTIONS             1019
#define IDC_OPT_MAX_MSG_CONTACT         1023
#define IDC_OPT_DONT_REPLY_MSG_WORDLIST 1024
#define IDC_OPT_MAX_SAME_MSG            1025
#define IDC_OPT_IN_MSG_APPROVE          1027
#define IDC_OPT_IN_MSG_APPROVE_WORDLIST 1028
#define IDC_OPT_DONT_REPLY_MSG          1029
#define IDC_OPT_HIDE_UNTIL_VERIFIED     1033
#define IDC_OPT_ADD_PERMANENTLY         1034
#define IDC_OPT_BAYES_SPAM              1036
#define IDC_OPT_POPUPS_PREVIEW          1036
#define IDC_OPT_KEEP_BLOCKED_MSG        1037
#define IDC_OPT_BAYES_BLOCK_MSG         1039
#define IDC_OPT_BAYES_AUTOLEARN_OUTGOING 1041
#define IDC_OPT_BAYES_LEARNBOX          1042
#define IDC_OPT_BAYES_HAM               1043
#define IDC_OPT_BAYES_SPAM_SCORE        1044
#define IDC_OPT_BAYES_AUTO_APPROVE      1045
#define IDC_EDIT3                       1046
#define IDC_OPT_BAYES_HAM_SCORE         1046
#define IDC_STATIC_HAM_COUNT            1047
#define IDC_STATIC_SPAM_COUNT           1048
#define IDC_CHECK_MSG                   1049
#define IDC_OPT_BAYES_AUTOLEARN_NOT_APPROVED 1050
#define IDC_OPT_BAYES_WAIT_APPROVE      1051
#define IDC_OPT_BAYES_ENABLED           1052
#define IDC_OPT_FILTERING_GROUP         1053
#define IDC_OPT_LEARNING_GROUP          1054
#define IDC_OPT_BAYES_AUTOLEARN_NOT_APPROVED2 1055
#define IDC_OPT_CCRESPONSE              1056
#define IDC_OPT_BAYES_AUTOLEARN_AUTOAPPROVED 1058
#define IDC_STATIC_DAYSASSPAM           1059
#define IDC_STATIC_SPAMCOUNT_LABEL      1060
#define IDC_STATIC_HAMCOUNT_LABEL       1061
#define IDC_OPT_REPLY_ON_MSG            1062
#define IDC_OPT_POPUPS_ENABLE           1063
#define IDC_OPT_POPUPS_ENABLED          1063
#define IDC_OPT_POPUPS_NOTIFY_BLOCKED   1064
#define IDC_OPT_POPUPS_BLOCKED_FOREGROUND 1065
#define IDC_OPT_POPUPS_BLOCKED_BACKGROUND 1066
#define IDC_OPT_POPUPS_APPROVED_FOREGROUND 1067
#define IDC_OPT_POPUPS_APPROVED_BACKGROUND 1068
#define IDC_OPT_POPUPS_CHALLENGE_FOREGROUND 1069
#define IDC_OPT_POPUPS_CHALLENGE_BACKGROUND 1070
#define IDC_OPT_POPUPS_BLOCKED_TIMEOUT  1073
#define IDC_OPT_POPUPS_APPROVED_TIMEOUT 1074
#define IDC_OPT_POPUPS_CHALLENGE_TIMEOUT 1075
#define IDC_OPT_POPUPS_DEFAULT_COLORS   1076
#define IDC_OPT_POPUPS_DEFAULT_TIMEOUT  1077
#define IDC_OPT_POPUPS_WINDOWS_COLORS   1078
#define IDC_OPT_POPUPS_NOTIFY_CHALLENGE 1079
#define IDC_OPT_MARK_MSG_AS_NEW_ON_APPROVAL 1080
#define IDC_OPT_MARK_MSG_UNREAD_ON_APPROVAL 1080

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
