//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ..\iconpacks\fp_icons.rc
//
#define __MAJOR_VERSION                 0
#define __RELEASE_NUM                   0
#define __BUILD_NUM                     0
#define __MINOR_VERSION                 1
#define IDI_BLANK                       1
#define IDI_NOTFOUND                    2
#define IDI_UNDETECTED                  3
#define IDI_UNKNOWN                     4
#define IDI_MIRANDA_NG                  10
#define IDI_MIRANDA_NG_STABLE           11
#define IDI_MIRANDA_OLD                 12
#define IDI_MIRANDA_UNKNOWN             13
#define IDI_MIRANDA_04XX                21
#define IDI_MIRANDA_05XX                22
#define IDI_MIRANDA_06XX                23
#define IDI_MIRANDA_07XX                24
#define IDI_MIRANDA_08XX                25
#define IDI_MIRANDA_09XX                26
#define IDI_MIRANDA_010X                27
#define IDI_MIRANDA_IM_V4               31
#define IDI_MIRANDA_IM_V5               32
#define IDI_MIRANDA_IM_V6               33
#define IDI_MIRANDA_IM_V7               34
#define IDI_MIRANDA_IM_V8               35
#define IDI_MIRANDA_IM_V9               36
#define IDI_MIRANDA_IM_V10              37
#define IDI_MIRANDA_NG_V1               41
#define IDI_MIRANDA_NG_V2               42
#define IDI_MIRANDA_NG_V3               43
#define IDI_MIRANDA_NG_V4               44
#define IDI_MIRANDA_NG_V5               45
#define IDI_MIRANDA_NG_V6               46
#define IDI_MIRANDA_NG_V7               47
#define IDI_MIRANDA_NG_V8               48
#define IDI_MIRANDA_NG_V9               49
#define IDI_DEBUG_OVERLAY               51
#define IDI_HOME_OVERLAY                52
#define IDI_MOBILE_OVERLAY              53
#define IDI_NOTEBOOK_OVERLAY            54
#define IDI_OFFICE_OVERLAY              55
#define IDI_WORK_OVERLAY                56
#define IDI_PLATFORM_AMIGA              61
#define IDI_PLATFORM_ANDROID            62
#define IDI_PLATFORM_FLASH              63
#define IDI_PLATFORM_IOS                64
#define IDI_PLATFORM_JAVA               65
#define IDI_PLATFORM_LINUX              66
#define IDI_PLATFORM_MAC                67
#define IDI_PLATFORM_SYMBIAN            68
#define IDI_PLATFORM_WIN                69
#define IDI_PLATFORM_WEBSITE            70
#define IDI_PLATFORM_WINPHONE           71
#define IDI_PLATFORM_MOBILE             72
#define IDI_UNICODE_CLIENT              75
#define IDI_PLATFORM_X32                76
#define IDI_PLATFORM_X64                77
#define IDI_AIM_OVERLAY                 78
#define IDI_GMAIL_OVERLAY               79
#define IDI_ICQJ_OVERLAY                80
#define IDI_ICQJ_PLUS_OVERLAY           81
#define IDI_IRC_OVERLAY                 82
#define IDI_JABBER_OVERLAY              83
#define IDI_JGTALK_OVERLAY              84
#define IDI_MAILRU_OVERLAY              85
#define IDI_MSN_OVERLAY                 86
#define IDI_QQ_OVERLAY                  87
#define IDI_TLEN_OVERLAY                88
#define IDI_YAHOO_OVERLAY               89
#define IDI_VK_OVERLAY                  90
#define IDI_SECUREIM_OVERLAY            95
#define IDI_NEWGPG_OVERLAY              96
#define IDI_MIROTR_OVERLAY              97
#define IDI_MIRANDA_A0X                 101
#define IDI_MIRANDA_AF                  102
#define IDI_MIRANDA_ALFAMAR             103
#define IDI_MIRANDA_AMATORY             104
#define IDI_MIRANDA_BRI                 105
#define IDI_MIRANDA_CAPPUCCINO          106
#define IDI_MIRANDA_DAR                 107
#define IDI_MIRANDA_DEVIL               108
#define IDI_MIRANDA_DMIKOS              109
#define IDI_MIRANDA_E33                 110
#define IDI_MIRANDA_FAITH               111
#define IDI_MIRANDA_FINAL               112
#define IDI_MIRANDA_FR                  113
#define IDI_MIRANDA_FREIZE              114
#define IDI_MIRANDA_GHOST               115
#define IDI_MIRANDA_HIEROS              116
#define IDI_MIRANDA_INDUCTION           117
#define IDI_MIRANDA_KDL                 118
#define IDI_MIRANDA_KOLICH              119
#define IDI_MIRANDA_KUZZMAN             120
#define IDI_MIRANDA_LENINPACK           121
#define IDI_MIRANDA_LESTAT              122
#define IDI_MIRANDA_LEXSYS              123
#define IDI_MIRANDA_MATAES              124
#define IDI_MIRANDA_MD                  125
#define IDI_MIRANDA_ME                  126
#define IDI_MIRANDA_NATIVE              127
#define IDI_MIRANDA_NEW_STYLE           128
#define IDI_MIRANDA_PILOT               129
#define IDI_MIRANDA_RAZUNTER            130
#define IDI_MIRANDA_ROBYER              131
#define IDI_MIRANDA_SE7VEN              132
#define IDI_MIRANDA_SPELLHOWLER         133
#define IDI_MIRANDA_SSS_MOD             134
#define IDI_MIRANDA_STALKER             135
#define IDI_MIRANDA_TWEETY              136
#define IDI_MIRANDA_UMEDON              137
#define IDI_MIRANDA_VALERAVI            138
#define IDI_MIRANDA_WATCHER             139
#define IDI_MIRANDA_YAOL                140
#define IDI_MIRANDA_ZELEBOBA            141
#define IDI_ICQ                         190
#define IDI_ICQ3_OVERLAY                193
#define IDI_ICQ4_OVERLAY                194
#define IDI_ICQ5_OVERLAY                195
#define IDI_ICQ6_OVERLAY                196
#define IDI_ICQ7_OVERLAY                197
#define IDI_ICQ8_OVERLAY                198
#define IDI_ASIA                        202
#define IDI_DICHAT                      203
#define IDI_GNOMEICU                    214
#define IDI_ICY_JUICE                   215
#define IDI_LIBICQ2000                  216
#define IDI_LICQ                        217
#define IDI_LOCID                       218
#define IDI_QIP_2005                    219
#define IDI_RANDQ                       220
#define IDI_SMARTICQ                    221
#define IDI_SPAM                        222
#define IDI_STRICQ                      223
#define IDI_TICQ                        234
#define IDI_IRC                         300
#define IDI_AMIRC                       301
#define IDI_AMULE                       302
#define IDI_BABBEL                      303
#define IDI_BERSIRC                     304
#define IDI_CBIRC                       305
#define IDI_CHATZILLA                   306
#define IDI_CONVERSATION                307
#define IDI_DIRC                        308
#define IDI_EGGDROP                     309
#define IDI_EGGDROP_RACBOT              310
#define IDI_EMULE                       311
#define IDI_EMULE_MORPHXT               312
#define IDI_EMULE_NEO                   313
#define IDI_EMULE_PLUS                  314
#define IDI_EMULE_XTREME                315
#define IDI_FCHAT                       316
#define IDI_GDPCHAT                     317
#define IDI_GOPOWERTOOLS                318
#define IDI_HYDRA_IRC                   319
#define IDI_ICECHAT                     320
#define IDI_IRC_UNKNOWN                 321
#define IDI_IRCLE                       322
#define IDI_IRCXPRO                     323
#define IDI_JIRCII                      324
#define IDI_JMIRC                       325
#define IDI_KLIENT                      326
#define IDI_KONVERSATION                327
#define IDI_KSIRC                       328
#define IDI_KVIRC                       329
#define IDI_MIRC                        330
#define IDI_MP3_SCRIPT                  331
#define IDI_NEORATRION                  332
#define IDI_NETTALK                     333
#define IDI_NONAME_SCRIPT               334
#define IDI_OPERA                       335
#define IDI_PIORUN                      336
#define IDI_PIRC                        337
#define IDI_PIRCH                       338
#define IDI_PJIRC                       339
#define IDI_PROCHAT                     340
#define IDI_PSYBNC                      341
#define IDI_SAVIRC                      342
#define IDI_SMART_IRC                   343
#define IDI_SNAK                        344
#define IDI_SYSRESET                    345
#define IDI_VIRCAIRC                    346
#define IDI_VISIONIRC                   347
#define IDI_VISUALIRC                   348
#define IDI_VORTECIRC                   349
#define IDI_WEECHAT                     350
#define IDI_WLIRC                       351
#define IDI_WMIRC                       352
#define IDI_XCHATAQUA                   353
#define IDI_XBITCH                      354
#define IDI_XCHAT                       355
#define IDI_XIRC                        356
#define IDI_XIRCON                      357
#define IDI_ZSIRC                       359
#define IDI_POCKET_IRC                  360
#define IDI_IROFFER_DINOEX              361
#define IDI_IROFFER                     362
#define IDI_ZNC                         363
#define IDI_AKENI                       400
#define IDI_AMBROSIA                    401
#define IDI_ANDROID                     402
#define IDI_ANOTHRSSBOT                 403
#define IDI_AQQ                         404
#define IDI_BARNOWL                     405
#define IDI_BEEJIVE                     406
#define IDI_BEEM                        407
#define IDI_BELLSOUTH                   408
#define IDI_BITWISE                     409
#define IDI_BOMBUS                      410
#define IDI_BOMBUS_MOD                  411
#define IDI_BOMBUS_NG                   412
#define IDI_BOMBUS_QD                   413
#define IDI_BOWLINE                     414
#define IDI_BUDDYSPACE                  415
#define IDI_CANDY                       416
#define IDI_CARRIER                     417
#define IDI_CHATOPUS                    418
#define IDI_CHAT_BOT                    419
#define IDI_CHIKKA                      420
#define IDI_CHITCHAT                    421
#define IDI_CJC                         422
#define IDI_CLAROS_CHAT                 423
#define IDI_COCCINELLA                  424
#define IDI_COLIBRY                     425
#define IDI_COLLOQUY                    426
#define IDI_COMMUNIGATE                 427
#define IDI_CONFERENCE                  428
#define IDI_CROOM                       429
#define IDI_CROSSTALK                   430
#define IDI_CUDUMAR                     431
#define IDI_CYCLOPS_CHAT                432
#define IDI_DESYR                       433
#define IDI_DZIOBBER                    434
#define IDI_EJABBERD                    435
#define IDI_ELMER                       436
#define IDI_EMACS                       437
#define IDI_EMESS                       438
#define IDI_EMITE                       439
#define IDI_EMPATHY                     440
#define IDI_EXODUS                      441
#define IDI_FIRE                        443
#define IDI_GABBER                      444
#define IDI_GAJIM                       445
#define IDI_GCN                         446
#define IDI_GIBBERBOT                   447
#define IDI_GLU                         448
#define IDI_GMAIL                       449
#define IDI_GNOME                       450
#define IDI_GOIM                        452
#define IDI_GOSSIP                      453
#define IDI_GOTALKMOBILE                454
#define IDI_GREENTHUMB                  455
#define IDI_GTALK                       456
#define IDI_GTALK_GADGET                457
#define IDI_GUSH                        458
#define IDI_GYABER                      459
#define IDI_IGOOGLE                     460
#define IDI_IJAB                        461
#define IDI_IMCOM                       462
#define IDI_IMEEM                       463
#define IDI_IMIFIED                     464
#define IDI_IMOV                        465
#define IDI_IMPORTAL                    466
#define IDI_IM_FRIENDLY                 467
#define IDI_INSTANT                     468
#define IDI_INTERACTION                 469
#define IDI_IRUKA                       470
#define IDI_J2J_TRANSPORT               471
#define IDI_JABBA                       472
#define IDI_JABBER                      473
#define IDI_JABBER_DISK                 474
#define IDI_JABBERFOX                   475
#define IDI_JABBERNAUT                  476
#define IDI_JABBERWOCKY                 477
#define IDI_JABBERZILLA                 478
#define IDI_JABBER_APPLET               479
#define IDI_JABBER_BEOS                 480
#define IDI_JABBER_MESSENGER            481
#define IDI_JABBER_NET                  482
#define IDI_JABBIM                      483
#define IDI_JABBROID                    484
#define IDI_JABIRU                      485
#define IDI_JAJC                        486
#define IDI_JAMM                        487
#define IDI_JAPPIX                      488
#define IDI_JCLAIM                      489
#define IDI_JETI                        490
#define IDI_JITSI                       491
#define IDI_JMC                         492
#define IDI_JOOST                       493
#define IDI_JRUDEVELS                   494
#define IDI_JTALK                       495
#define IDI_JTALKMOD                    496
#define IDI_JUICK                       497
#define IDI_JWCHAT                      498
#define IDI_JWGC                        500
#define IDI_KADU                        501
#define IDI_KF                          502
#define IDI_KONNEKT                     503
#define IDI_LAFFER                      504
#define IDI_LAMPIRO                     505
#define IDI_LAMP_IM                     506
#define IDI_LANDELL                     507
#define IDI_LEAF                        508
#define IDI_LINQ                        509
#define IDI_LLUNA                       510
#define IDI_M8JABBER                    511
#define IDI_MANGO                       512
#define IDI_MCABBER                     513
#define IDI_MEINVZ                      514
#define IDI_MERCURY_MESSENGER           515
#define IDI_MGTALK                      516
#define IDI_MJABBER                     517
#define IDI_MOBBER                      518
#define IDI_MOJAB                       519
#define IDI_MOZILLACHAT                 520
#define IDI_MUCKL                       521
#define IDI_MYJABBER                    522
#define IDI_NEOS                        523
#define IDI_NITRO                       524
#define IDI_NOSTROMO                    525
#define IDI_OCTROTALK                   526
#define IDI_OM                          527
#define IDI_ONETEAM                     528
#define IDI_ORKUT                       529
#define IDI_PALTALK                     530
#define IDI_PANDION                     531
#define IDI_PAPLA                       532
#define IDI_PJC                         533
#define IDI_POEZIO                      534
#define IDI_PROSODY                     535
#define IDI_PSI                         536
#define IDI_PSIPLUS                     537
#define IDI_PSTO                        538
#define IDI_PSYC                        539
#define IDI_PYGEON                      540
#define IDI_QTJIM                       546
#define IDI_QUTECOM                     547
#define IDI_RENREN                      548
#define IDI_SAJE                        549
#define IDI_SAMEPLACE                   550
#define IDI_SAPO                        551
#define IDI_SBOT                        552
#define IDI_SCHULERVZ                   553
#define IDI_SIEJC                       554
#define IDI_SIP_COMM                    555
#define IDI_SKYMESSAGER                 556
#define IDI_SLICK                       557
#define IDI_SMACK                       558
#define IDI_SMTP_TRANSPORT              559
#define IDI_SOAPBOX                     560
#define IDI_SPARK                       561
#define IDI_SPEAKALL                    562
#define IDI_SPEEQE                      563
#define IDI_SPIK                        564
#define IDI_STUDIVZ                     565
#define IDI_SWIFT                       566
#define IDI_SWORIM                      567
#define IDI_SYNAPSE                     568
#define IDI_TALKDROID                   569
#define IDI_TALKONAUT                   570
#define IDI_TAPIOCA                     571
#define IDI_TEABOT                      572
#define IDI_TELEPATHY                   573
#define IDI_THEBEE                      574
#define IDI_THUNDERBIRD                 575
#define IDI_TIGASE                      576
#define IDI_TIPICIM                     577
#define IDI_TKABBER                     578
#define IDI_TKCHAT                      579
#define IDI_TRANSACTIM                  580
#define IDI_TRANSLATE                   581
#define IDI_TRIPLE_SOFTWARE             582
#define IDI_UKEEPER                     585
#define IDI_VACUUM                      586
#define IDI_VANDV                       587
#define IDI_VAYUSPHERE                  588
#define IDI_VBUZZER                     589
#define IDI_VIRTUS                      590
#define IDI_VYSPER                      591
#define IDI_WANNACHAT                   592
#define IDI_WEBEX                       593
#define IDI_WHISPERIM                   594
#define IDI_WHOISBOT                    595
#define IDI_WIJA                        596
#define IDI_WILDFIRE                    597
#define IDI_WINJAB                      598
#define IDI_WTW                         599
#define IDI_XABBER                      600
#define IDI_GABBLE                      601
#define IDI_XEUS                        602
#define IDI_XEUS2                       603
#define IDI_XIFFIAN                     604
#define IDI_XMPP                        605
#define IDI_YAMBI                       606
#define IDI_YAONLINE                    607
#define IDI_YAXIM                       608
#define IDI_OPENFIRE                    609
#define IDI_MAIL_RU_MOBILE              701
#define IDI_MAIL_RU_OFFICIAL            702
#define IDI_MAIL_RU_UNKNOWN             703
#define IDI_MAIL_RU_WEBAGENT            704
#define IDI_AIM_6                       714
#define IDI_AIM_7                       715
#define IDI_AIM_MAC                     716
#define IDI_AIM_MOBILE                  717
#define IDI_AIM_TRITON                  718
#define IDI_MINIAIM                     719
#define IDI_NAIM                        720
#define IDI_TERRAIM                     721
#define IDI_GG                          724
#define IDI_GG8_OVERLAY                 725
#define IDI_GG9_OVERLAY                 726
#define IDI_GG10_OVERLAY                727
#define IDI_GG11_OVERLAY                728
#define IDI_TLEN                        731
#define IDI_TLEN5_OVERLAY               732
#define IDI_TLEN6_OVERLAY               733
#define IDI_TLEN7_OVERLAY               734
#define IDI_TLEN8_OVERLAY               735
#define IDI_AMSN                        741
#define IDI_MSN_MAC                     742
#define IDI_MSN_45                      743
#define IDI_MSN_6                       744
#define IDI_MSN_7                       745
#define IDI_MSN_8                       746
#define IDI_MSN                         747
#define IDI_WEBMESSENGER                748
#define IDI_WLM_9                       749
#define IDI_WLM_10                      750
#define IDI_ATOM1                       761
#define IDI_ATOM3                       762
#define IDI_RSS09                       763
#define IDI_RSS1                        764
#define IDI_RSS2                        765
#define IDI_MOBILEQQ                    770
#define IDI_QQ                          771
#define IDI_QQCONCEPT                   772
#define IDI_QQCRM                       773
#define IDI_QQINT                       774
#define IDI_QQSILVER                    775
#define IDI_TM                          776
#define IDI_TM2008                      777
#define IDI_WEBQQ                       778
#define IDI_QQ_2000_OVERLAY             780
#define IDI_QQ_2001_OVERLAY             781
#define IDI_QQ_2002_OVERLAY             782
#define IDI_QQ_2003_OVERLAY             783
#define IDI_QQ_2004_OVERLAY             784
#define IDI_QQ_2005_OVERLAY             785
#define IDI_QQ_2006_OVERLAY             786
#define IDI_QQ_2007_OVERLAY             787
#define IDI_QQ_2008_OVERLAY             788
#define IDI_QQ_2009_OVERLAY             789
#define IDI_QQ_2010_OVERLAY             790
#define IDI_QQ_2011_OVERLAY             791
#define IDI_QQ_2012_OVERLAY             792
#define IDI_YAMQQ                       799
#define IDI_ACCU                        801
#define IDI_GISMETEO                    802
#define IDI_INTELLI                     803
#define IDI_REALMETEO                   804
#define IDI_WETTER                      805
#define IDI_UNDERGROUND                 806
#define IDI_WEATHER                     807
#define IDI_WEATHER_CN                  808
#define IDI_WEATHERXML                  809
#define IDI_METEOGID                    810
#define IDI_YWEATHER                    811
#define IDI_METEONOVOSTI                812
#define IDI_NOAA                        813
#define IDI_LIBYAHOO2                   821
#define IDI_YAHOO_PINGBOX               822
#define IDI_YAHOO                       823
#define IDI_YAHOO_WEB                   828
#define IDI_YAHOO_GO_MOBILE             829
#define IDI_YAHOO5_OVERLAY              831
#define IDI_YAHOO6_OVERLAY              832
#define IDI_YAHOO7_OVERLAY              833
#define IDI_YAHOO8_OVERLAY              834
#define IDI_YAHOO9_OVERLAY              835
#define IDI_YAHOO10_OVERLAY             836
#define IDI_YAHOO11_OVERLAY             837
#define IDI_ADIUM                       1000
#define IDI_AGILE                       1001
#define IDI_APPOLO                      1002
#define IDI_AYTTM                       1003
#define IDI_BAYANICQ                    1004
#define IDI_BIMOID                      1005
#define IDI_BITLBEE                     1006
#define IDI_BLACKBERRY                  1007
#define IDI_BUDDYCLOUD                  1008
#define IDI_CAUSERIE                    1009
#define IDI_1UND1                       1010
#define IDI_CENTERIM                    1011
#define IDI_CHATSECURE                  1012
#define IDI_CITRON                      1013
#define IDI_CLIMM                       1014
#define IDI_DIGSBY                      1015
#define IDI_EASYMESSAGE                 1016
#define IDI_EBUDDY                      1017
#define IDI_EKG2                        1018
#define IDI_EMESENE                     1019
#define IDI_EM_CLIENT                   1020
#define IDI_EQO                         1021
#define IDI_EYEBALL_CHAT                1022
#define IDI_FAMAIM                      1023
#define IDI_FRING                       1024
#define IDI_GAIM                        1025
#define IDI_GALAXIUM                    1026
#define IDI_GMX                         1027
#define IDI_ICALL                       1028
#define IDI_ICHAT                       1029
#define IDI_IM2                         1030
#define IDI_IMADERING                   1031
#define IDI_IMOIM                       1032
#define IDI_IMPLUS                      1033
#define IDI_IMVU                        1034
#define IDI_INLUX                       1035
#define IDI_INSTANTBIRD                 1036
#define IDI_IRSSI                       1037
#define IDI_JABBEAR                     1038
#define IDI_JABBIN                      1039
#define IDI_JASMINEIM                   1040
#define IDI_JBOTHER                     1041
#define IDI_JBUDDY                      1042
#define IDI_JIMM                        1043
#define IDI_JIMMY                       1044
#define IDI_JIMM_ASPRO                  1045
#define IDI_KMESS                       1046
#define IDI_KOOLIM                      1047
#define IDI_KOPETE                      1048
#define IDI_LEECHCRAFT                  1049
#define IDI_MCHAT                       1050
#define IDI_MDC                         1051
#define IDI_MEEBO                       1052
#define IDI_MEETRO                      1053
#define IDI_MONAL                       1054
#define IDI_NIMBUZZ                     1055
#define IDI_PALRINGO                    1056
#define IDI_PIDGIN                      1057
#define IDI_PIGEON                      1058
#define IDI_PLAYXPERT                   1059
#define IDI_PRELUDE                     1060
#define IDI_PROTEUS                     1061
#define IDI_PYTHON                      1062
#define IDI_QIP_2010                    1063
#define IDI_QIP_2012                    1064
#define IDI_QIP_ANDROID                 1065
#define IDI_QIP_INFIUM                  1066
#define IDI_QIP_JAVA                    1067
#define IDI_QIP_PDA                     1068
#define IDI_QIP_SYMBIAN                 1069
#define IDI_QIP_IOS                     1070
#define IDI_QNEXT                       1071
#define IDI_QUTIM                       1072
#define IDI_MQUTIM                      1073
#define IDI_SALUT_A_TOI                 1074
#define IDI_SHAIM                       1075
#define IDI_SIM                         1076
#define IDI_SIM_OLD                     1077
#define IDI_SREVIM                      1078
#define IDI_TRILLIAN                    1079
#define IDI_TRILLIAN_ANDROID            1080
#define IDI_TRILLIAN_ASTRA              1081
#define IDI_TRILLIAN_PRO                1082
#define IDI_TUUKLE_CHAT                 1083
#define IDI_UIM                         1084
#define IDI_UTALK                       1085
#define IDI_WINDOWS_PHONE               1086
#define IDI_WIPPIEN                     1087
#define IDI_YAMIGO                      1088
#define IDI_YEIGO                       1089
#define IDI_YOONO                       1090
#define IDI_GNUGADU                     1091
#define IDI_FACEBOOK                    2001
#define IDI_FACEBOOK_APP                2002
#define IDI_FACEBOOK_MESSENGER          2003
#define IDI_FACEBOOK_OTHER              2004
#define IDC_STATUSBAR                   7001
#define IDI_SKYPE                       9002
#define IDI_TWITTER                     9003
#define IDI_XFIRE                       9004
#define IDI_HANGOUTS                    9005
#define IDI_VK                          9006
#define IDI_WHATSAPP                    9007

#define IDD_DIALOG                      10000
#define IDC_GROUP_MIRANDA               10025
#define IDC_GROUP_MIRANDA_VERSION       10026
#define IDC_GROUP_MIRANDA_PACKS         10027
#define IDC_GROUP_MULTI                 10028
#define IDC_GROUP_AIM                   10029
#define IDC_GROUP_GG                    10030
#define IDC_GROUP_ICQ                   10032
#define IDC_GROUP_IRC                   10033
#define IDC_GROUP_JABBER                10034
#define IDC_GROUP_MSN                   10035
#define IDC_GROUP_MRA                   10036
#define IDC_GROUP_QQ                    10037
#define IDC_GROUP_RSS                   10038
#define IDC_GROUP_TLEN                  10039
#define IDC_GROUP_WEATHER               10040
#define IDC_GROUP_YAHOO                 10041
#define IDC_GROUP_FACEBOOK              10042
#define IDC_GROUP_VK                    10043
#define IDC_GROUP_OTHER_PROTOS          10044
#define IDC_GROUP_OTHERS                10045
#define IDC_GROUP_OVERLAYS_RESOURCE     10046
#define IDC_GROUP_OVERLAYS_PLATFORM     10047
#define IDC_GROUP_OVERLAYS_PROTO        10048
#define IDC_GROUP_OVERLAYS_SECURITY     10049
#define IDC_GROUP_OVERLAYS_UNICODE      10050

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2007
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         7002
#define _APS_NEXT_SYMED_VALUE           7000
#endif
#endif
