//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by W:\miranda-ng\src\core\stdmsg\res\resource.rc
//
#define IDD_MSGSENDERROR                102
#define IDD_OPTIONS2                    103
#define IDD_OPTIONS1                    104
#define IDD_FILTER                      105
#define IDD_OPTIONSPOPUP                106
#define IDD_CONTAINER                   107
#define IDD_OPT_TABS                    108
#define IDD_OPT_MSGHIST                 109
#define IDI_BUNDERLINE                  120
#define IDI_BBOLD                       121
#define IDI_BITALICS                    122
#define IDI_BSMILEY                     123
#define IDI_TOPICBUT                    124
#define IDI_BKGCOLOR                    125
#define IDI_CHANMGR                     126
#define IDI_COLOR                       127
#define IDI_FILTER                      128
#define IDI_HISTORY                     129
#define IDI_NICKLIST                    130
#define IDI_JOIN                        131
#define IDI_PART                        132
#define IDI_QUIT                        133
#define IDI_KICK                        134
#define IDI_NICK                        135
#define IDI_NOTICE                      136
#define IDI_MESSAGE                     137
#define IDI_MESSAGEOUT                  138
#define IDI_TOPIC                       139
#define IDI_INFO                        140
#define IDI_ADDSTATUS                   141
#define IDI_REMSTATUS                   142
#define IDI_ACTION                      143
#define IDI_HIGHLIGHT                   144
#define IDI_BLANK                       146
#define IDI_TAG1                        149
#define IDI_TAG2                        150
#define IDR_MENU                        151
#define IDI_CLOSE                       159
#define IDI_OVERLAY                     160
#define IDI_NICKLIST2                   161
#define IDI_FILTER2                     162
#define IDI_SECURE                      163
#define IDI_SECURE_STRONG               164
#define IDR_CONTEXT                     180
#define IDC_DROP                        183
#define IDC_HYPERLINKHAND               214
#define IDC_DROPUSER                    215
#define IDD_OPT_MSGDLG                  243
#define IDD_MSG                         244
#define IDD_OPT_MSGLOG                  245
#define IDD_OPT_MSGTYPE                 275
#define IDI_INCOMING                    276
#define IDI_OUTGOING                    277
#define IDI_EXCL                        282
#define IDC_AUTOCOPY                    1001
#define IDC_SPLITTERX                   1003
#define IDC_AUTOCLOSE                   1004
#define IDC_AUTOMIN                     1005
#define IDC_DONOTSTEALFOCUS             1006
#define IDC_SPLITTERY                   1008
#define IDC_CHECKBOXES                  1018
#define IDC_NICKLISTBKG                 1021
#define IDC_NICKROW                     1022
#define IDC_LOGLIMIT                    1024
#define IDC_NICKROW2                    1025
#define IDC_SHOWNAMES                   1026
#define IDC_SHOWSENDBTN                 1029
#define IDC_SHOWLOGICONS                1032
#define IDC_SHOWTIMES                   1033
#define IDC_SHOWDATES                   1034
#define IDC_CLIST                       1035
#define IDC_SHOWFORMATTING              1036
#define IDC_SAVEPERCONTACT              1037
#define IDC_LOADCOUNTN                  1039
#define IDC_LOADCOUNTSPIN               1040
#define IDC_SHOWBUTTONLINE              1042
#define IDC_LOADUNREAD                  1043
#define IDC_LOADCOUNT                   1044
#define IDC_LOADTIMEN                   1045
#define IDC_LOADTIMESPIN                1046
#define IDC_LOADTIME                    1047
#define IDC_STMINSOLD                   1048
#define IDC_SPIN1                       1049
#define IDC_SPIN2                       1050
#define IDC_SPIN3                       1051
#define IDC_SPIN4                       1052
#define IDC_FONTLIST                    1053
#define IDC_CHOOSEFONT                  1054
#define IDC_FONTCOLOR                   1055
#define IDC_MESSAGEBKG                  1056
#define IDC_LOGBKG                      1057
#define IDC_HIGHLIGHTWORDS              1058
#define IDC_INSTAMP                     1059
#define IDC_OUTSTAMP                    1060
#define IDC_TIMESTAMP                   1061
#define IDC_FONTCHOOSE                  1062
#define IDC_LOGDIRECTORY                1063
#define IDC_LIMIT                       1064
#define IDC_LOGTIMESTAMP                1065
#define IDC_GROUP                       1066
#define IDC_RADIO1                      1067
#define IDC_RADIO2                      1068
#define IDC_RADIO3                      1069
#define IDC_ADD                         1070
#define IDC_CHAT_USEGROUP               1071
#define IDC_TAB                         1074
#define IDC_1                           1075
#define IDC_2                           1076
#define IDC_3                           1077
#define IDC_4                           1078
#define IDC_5                           1079
#define IDC_6                           1080
#define IDC_7                           1081
#define IDC_8                           1082
#define IDC_9                           1083
#define IDC_10                          1084
#define IDC_11                          1085
#define IDC_TEXT                        1086
#define IDC_BKG                         1087
#define IDC_TIMEOUT                     1088
#define IDC_HIGHLIGHT                   1089
#define IDC_TEXTO                       1090
#define IDC_LOGGING                     1091
#define IDC_STMSGLOGGROUP               1442
#define IDC_DETAILS                     1469
#define IDC_USERMENU                    1471
#define IDC_ERRORTEXT                   1596
#define IDC_MSGTEXT                     1597
#define IDC_SHOWNOTIFY                  1600
#define IDC_STATUSWIN                   1601
#define IDC_TYPEWIN                     1602
#define IDC_CHARCOUNT                   1603
#define IDC_TYPETRAY                    1603
#define IDC_CASCADE                     1604
#define IDC_SECONDS                     1605
#define IDC_NOTIFYTRAY                  1606
#define IDC_NFLASHES                    1606
#define IDC_NOTIFYBALLOON               1607
#define IDC_CTRLSUPPORT                 1608
#define IDC_DELTEMP                     1609
#define IDC_AVATAR                      1610
#define IDC_AVATARSUPPORT               1611
#define IDC_LIMITAVATARH                1612
#define IDC_AVATARHEIGHT                1613
#define IDC_SHOWSECS                    1614
#define IDC_POPLIST                     1616
#define IDC_FRAME                       1617
#define IDC_USETABS                     1620
#define IDC_CLOSETABS                   1621
#define IDC_TABSBOTTOM                  1623
#define IDC_SRMM_COLOR                  3001
#define IDC_SRMM_BKGCOLOR               3002
#define IDC_SRMM_BOLD                   3003
#define IDC_SRMM_ITALICS                3004
#define IDC_SRMM_UNDERLINE              3005
#define IDC_SRMM_FILTER                 3006
#define IDC_SRMM_CHANMGR                3007
#define IDC_SRMM_SHOWNICKLIST           3008
#define IDC_SRMM_HISTORY                3009
#define IDC_SRMM_NICKLIST               3010
#define IDC_SRMM_LOG                    3011
#define IDC_SRMM_MESSAGE                3012
#define IDC_SRMM_QUOTE                  3013
#define IDC_SRMM_CLOSEQUOTE             3014
#define IDM_CUT                         40000
#define IDM_COPY                        40001
#define IDM_PASTE                       40002
#define IDM_UNDO                        40003
#define IDM_DELETE                      40004
#define IDM_REDO                        40005
#define IDM_PASTESEND                   40006
#define IDM_COPYALL                     40011
#define IDM_SELECTALL                   40012
#define IDM_CLEAR                       40013
#define ID_MESS                         40021
#define ID_COPYALL                      40026
#define ID_CLEARLOG                     40029
#define ID_MESSAGE_PASTE                40030
#define ID_MESSAGE_UNDO                 40033
#define ID_MESSAGE_COPY                 40034
#define ID_MESSAGE_CUT                  40035
#define ID_MESSAGE_CLEAR                40037
#define ID_MESSAGE_SELECTALL            40038
#define ID_MESSAGE_REDO                 40039
#define ID_CLOSE                        40042
#define ID_CLOSEOTHER                   40043
#define ID_LOCKPOSITION                 40044
#define ID_SEARCH_GOOGLE                40047
#define ID_SEARCH_WIKIPEDIA             40048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        291
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1620
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
