.PHONY: clean All

All:
	@echo "----------Building project:[ mir_app - Debug ]----------"
	@cd "/home/ghazan/miranda-ng/src/mir_app" && "$(MAKE)" -f  "mir_app.mk"
clean:
	@echo "----------Cleaning project:[ mir_app - Debug ]----------"
	@cd "/home/ghazan/miranda-ng/src/mir_app" && "$(MAKE)" -f  "mir_app.mk" clean
