.PHONY: clean All

All:
	@echo "----------Building project:[ mir_core - Release ]----------"
	@cd "/var/www/miranda-ng/src/mir_core" && "$(MAKE)" -f  "mir_core.mk"
clean:
	@echo "----------Cleaning project:[ mir_core - Release ]----------"
	@cd "/var/www/miranda-ng/src/mir_core" && "$(MAKE)" -f  "mir_core.mk" clean
