//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by E:\Projects\C++\MirandaNG\protocols\Skype\res\Resource.rc
//
#define IDD_ACCMGR                      9
#define IDD_OPT_MAIN                    10
#define IDD_INFO_SKYPE                  11
#define IDD_OWNINFO_PERSONAL            12
#define IDD_OWNINFO_HOME                13
#define IDD_OWNINFO_CONTACT             14
#define IDD_PASSWORD_CHANGE             15
#define IDD_CHATROOM_INVITE             16
#define IDD_PASSWORD_REQUEST            17
#define IDD_CHATROOM_CREATE             18
#define IDD_CHATROOM_CONFIG             19
#define IDD_OPT_BLOCKED                 20
#define IDD_IGNORE_LIST                 21
#define IDD_BLOCK                       22
#define IDD_OWNINFO_ACCOUNT             23
#define IDD_OPT_PRIVACY                 24
#define IDI_SKYPE                       101
#define IDR_RUNTIME                     102
#define IDR_KEY                         107
#define IDI_CALL                        108
#define IDI_ADD_CONTACTS                109
#define IDI_SEND_CONTACTS               110
#define IDI_DELETE                      112
#define IDI_BLOCK                       115
#define IDI_CONFERENCE                  116
#define IDI_CONTACT                     117
#define IDC_CCLIST                      173
#define IDC_EDITSCR                     174
#define IDC_ADDSCR                      175
#define IDC_SN                          1001
#define IDC_PW                          1002
#define IDC_SL                          1003
#define IDC_SAVEPASS                    1004
#define IDC_SAVEPASSWORD                1005
#define IDC_PASSWORD                    1006
#define IDC_INSTRUCTION                 1007
#define IDC_INSTRUCTION2                1008
#define IDC_INSTRUCTION3                1009
#define IDC_SID                         1010
#define IDC_STATUSTEXT                  1011
#define IDC_ONLINESINCE                 1012
#define IDC_LASTEVENTDATE               1013
#define IDC_PASSWORD3                   1014
#define IDC_LASTPROFILECHANGE           1015
#define IDC_PORT                        1016
#define IDC_USE_ALT_PORTS               1017
#define IDC_REGISTER                    1018
#define IDC_CHANGE_PWD                  1019
#define IDC_DEFAULT_GROUP               1020
#define IDC_GROUP                       1021
#define IDC_PASSWORD2                   1023
#define IDC_FULLNAME                    1025
#define IDC_EMAIL1                      1026
#define IDC_EMAIL2                      1027
#define IDC_EMAIL3                      1028
#define IDC_BIRTH_DAY                   1029
#define IDC_BIRTH_MONTH                 1030
#define IDC_BIRTH_YEAR                  1031
#define IDC_MOBPHONE                    1032
#define IDC_GENDER                      1033
#define IDC_HOMEPHONE                   1034
#define IDC_HOMEPAGE                    1035
#define IDC_OFFICEPHONE                 1036
#define IDC_LANGUAGE                    1037
#define IDC_ABOUT                       1038
#define IDC_MOOD                        1039
#define IDC_CITY                        1040
#define IDC_STATE                       1041
#define IDC_COUNTRY                     1042
#define IDC_TIMEZONE                    1043
#define IDC_CHAT_TOPIC                  1044
#define IDC_CHAT_GUIDLINE               1045
#define IDC_CHAT_JOINING                1046
#define IDC_CHAT_GUIDLINE2              1047
#define IDC_CHAT_ROLES                  1048
#define IDC_CHAT_GUIDLINE3              1049
#define IDC_CONTACTS                    1050
#define IDC_CHAT_SECURED                1051
#define IDC_CHAT_GUIDLINE4              1052
#define IDC_CHAT_PASSWORD               1053
#define IDC_CHAT_CONFIRMATION           1054
#define IDC_CHAT_HINT                   1055
#define IDC_CHECK1                      1056
#define IDC_COMBO2                      1057
#define IDC_CHECK2                      1058
#define IDC_BLOCK                       1059
#define IDC_REPORT_ABUSE                1060
#define IDC_REMOVE_FROM_CL              1061
#define IDC_MESSAGE                     1062
#define IDC_HEADERBAR                   1063
#define IDC_BM_LIST                     1064
#define IDC_LIST                        1065
#define IDC_PRIVACY_IM_ANYONE           1066
#define IDC_PRIVACY_IM_CONTACTLIST      1067
#define IDC_PRIVACY_CALL_ANYONE         1068
#define IDC_PRIVACY_CALL_CONTACTLIST    1069
#define IDC_PRIVACY_SHARE_ANYONE        1070
#define IDC_PRIVACY_SHARE_CONTACTLIST   1071
#define IDC_PRIVACY_SHARE_NOONE         1072
#define IDC_PRIVACY_WEB                 1073
#define IDC_CREDITVALUE                 1074
#define IDC_CREDITCURRENCY              1075
#define IDC_PRIVACY_AVATAR_ANYONE       1076
#define IDC_PRIVACY_AVATARS_CONTACTLIST 1077
#define IDC_PRIVACY_COUNT_ANYONE        1078
#define IDC_PRIVACY_COUNT_CONTACTLIST   1079
#define IDC_PRIVACY_TIME_ANYONE         1080
#define IDC_PRIVACY_TIME_CONTACTLIST    1081

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
