//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ..\res\resource.rc
//
#define VS_VERSION_INFO                 1
#define IDD_MSGWIN                      100
#define IDD_MSG                         101
#define IDD_MSGSENDERROR                102
#define IDD_CONFIRM_SENDALL             103
#define IDD_INFOBAR                     104
#define IDD_OPT_MSGDLG                  111
#define IDD_OPT_MSGLOG                  112
#define IDD_OPT_MSGTYPE                 114
#define IDD_OPT_MSGTABS                 115
#define IDD_OPT_LAYOUT                  116
#define IDI_ADDCONTACT                  120
#define IDI_USERDETAILS                 121
#define IDI_HISTORY                     122
#define IDI_SEND                        123
#define IDI_SMILEY                      125
#define IDI_TYPING                      126
#define IDI_UNICODEON                   127
#define IDI_UNICODEOFF                  128
#define IDI_TIMESTAMP                   129
#define IDI_QUOTE                       130
#define IDI_INCOMING                    132
#define IDI_OUTGOING                    133
#define IDI_NOTICE                      134
#define IDI_CLOSEX                      135
#define IDI_GOOGLE                      140
#define IDI_BING                        141
#define IDI_YANDEX                      142
#define IDI_WIKIPEDIA                   143
#define IDI_GOOGLE_MAPS                 144
#define IDI_GOOGLE_TRANSLATE            145
#define IDI_YAHOO                       146
#define IDI_FOODNETWORK                 147
#define IDR_CONTEXT                     180
#define IDD_CHANNEL                     401
#define IDD_OPTIONS1                    402
#define IDD_OPTIONS2                    403
#define IDD_FILTER                      405
#define IDD_OPTIONSPOPUP                406
#define IDI_BUNDERLINE                  420
#define IDI_BBOLD                       421
#define IDI_BITALICS                    422
#define IDI_TOPICBUT                    424
#define IDI_BKGCOLOR                    425
#define IDI_CHANMGR                     426
#define IDI_COLOR                       427
#define IDI_FILTER                      428
#define IDI_NICKLIST                    430
#define IDI_JOIN                        431
#define IDI_PART                        432
#define IDI_QUIT                        433
#define IDI_KICK                        434
#define IDI_NICK                        435
#define IDI_CHAT_NOTICE                 436
#define IDI_TOPIC                       439
#define IDI_INFO                        440
#define IDI_ADDSTATUS                   441
#define IDI_REMSTATUS                   442
#define IDI_ACTION                      443
#define IDR_MENU                        451
#define IDD_COLORCHOOSER                452
#define IDI_STATUS3                     453
#define IDI_STATUS2                     454
#define IDI_STATUS4                     455
#define IDI_STATUS1                     456
#define IDI_STATUS0                     457
#define IDI_STATUS5                     458
#define IDI_OVERLAY                     460
#define IDI_NICKLIST2                   461
#define IDI_FILTER2                     462
#define IDI_TYPINGOFF                   463
#define IDC_HYPERLINKHAND               600
#define IDC_DRAGCURSOR                  601
#define IDC_TABS                        1000
#define IDC_LOG                         1001
#define IDC_MESSAGE                     1002
#define IDC_AUTOPOPUP                   1003
#define IDC_AUTOMIN                     1005
#define IDC_STAYMINIMIZED               1006
#define IDC_SWITCHTOACTIVE              1007
#define IDC_SEPARATECHATSCONTAINERS     1008
#define IDC_TABCLOSEBUTTON              1009
#define IDC_LIMITTABS                   1010
#define IDC_LIMITTABSNUM                1011
#define IDC_LIMITTABSNUMSPIN            1012
#define IDC_LIMITCHATSTABS              1013
#define IDC_LIMITCHATSTABSNUM           1014
#define IDC_LIMITCHATSTABSNUMSPIN       1015
#define IDC_SPLITTER                    1017
#define IDC_SHOWNAMES                   1020
#define IDC_USETABS                     1022
#define IDC_SHOWSECONDS                 1023
#define IDC_USELONGDATE                 1024
#define IDC_USERELATIVEDATE             1025
#define IDC_USEIEVIEW                   1026
#define IDC_FONTSCOLORS                 1027
#define IDC_SHOWLOGICONS                1032
#define IDC_SHOWTIMES                   1033
#define IDC_SHOWDATES                   1034
#define IDC_CLIST                       1035
#define IDC_GROUPMESSAGES               1036
#define IDC_SAVEPERCONTACT              1037
#define IDC_LOADCOUNTN                  1039
#define IDC_LOADCOUNTSPIN               1040
#define IDC_SHOWSTATUSBAR               1041
#define IDC_SHOWTOOLBAR                 1042
#define IDC_LOADUNREAD                  1043
#define IDC_SENDONENTER                 1043
#define IDC_LOADCOUNT                   1044
#define IDC_SENDONDBLENTER              1044
#define IDC_LOADTIMEN                   1045
#define IDC_LOADTIMESPIN                1046
#define IDC_LOADTIME                    1047
#define IDC_SHOWTITLEBAR                1050
#define IDC_STMINSOLD                   1051
#define IDC_SHOWPROGRESS                1052
#define IDC_SHOWINFOBAR                 1053
#define IDC_DETAILS                     1069
#define IDC_ADD                         1070
#define IDC_USERMENU                    1071
#define IDC_QUOTE                       1072
#define IDC_HISTORY                     1080
#define IDC_SMILEYS                     1081
#define IDC_REMEMBER                    1082
#define IDC_INFOBAR_NAME                1090
#define IDC_INFOBAR_STATUS              1091
#define IDC_STMSGLOGGROUP               1442
#define IDC_ERRORTEXT                   1596
#define IDC_MSGTEXT                     1597
#define IDC_SHOWNOTIFY                  1600
#define IDC_STATUSWIN                   1601
#define IDC_TYPEWIN                     1602
#define IDC_TYPETRAY                    1603
#define IDC_TABSATBOTTOM                1603
#define IDC_CASCADE                     1604
#define IDC_SECONDS                     1605
#define IDC_SECONDSSPIN                 1606
#define IDC_NOTIFYTRAY                  1607
#define IDC_NOTIFYBALLOON               1608
#define IDC_DELTEMP                     1609
#define IDC_AVATARSUPPORT               1611
#define IDC_LIMITNAMES                  1615
#define IDC_TRANSPARENCY                1616
#define IDC_MARKFOLLOWUPS               1617
#define IDC_MESSAGEONNEWLINE            1618
#define IDC_ATRANSPARENCYVALUE          1619
#define IDC_ATRANSPARENCYPERC           1620
#define IDC_ITRANSPARENCYVALUE          1621
#define IDC_ITRANSPARENCYPERC           1622
#define IDC_ALWAYSSHOWTABS              1623
#define IDC_TRANSPARENCYTEXT1           1627
#define IDC_TRANSPARENCYTEXT2           1628
#define IDC_DRAWLINES                   1629
#define IDC_SAVEDRAFTS                  1631
#define IDC_POPLIST                     1632
#define IDC_LIMITNAMESLEN               1633
#define IDC_LIMITNAMESLENSPIN           1634
#define IDC_CHARS                       1635
#define IDC_INDENTTEXT                  1636
#define IDC_INDENTSIZE                  1637
#define IDC_INDENTSPIN                  1638
#define IDC_HIDECONTAINERS              1639
#define IDC_TYPINGSWITCH                1640
#define IDC_LOADCOUNTTEXT2              1641
#define IDC_CHAT_NICKROWTEXT2           1642
#define IDC_CHAT_LIMITTEXT2             1643
#define IDC_AVATAR                      1645
#define IDC_XSTATUSICON                 1646
#define IDC_INPUTLINES                  1647
#define IDC_INPUTLINESSPIN              1648
#define IDC_CHAT_LOG                    5005
#define IDC_CHAT_SPLITTERX              5006
#define IDC_CHAT_SMILEY                 5007
#define IDC_CHAT_SPLITTERY              5008
#define IDC_CHAT_MESSAGE                5009
#define IDC_CHAT_BOLD                   5010
#define IDC_CHAT_ITALICS                5011
#define IDC_CHAT_UNDERLINE              5012
#define IDC_CHAT_FILTER                 5013
#define IDC_CHAT_CHANMGR                5014
#define IDC_CHAT_SHOWNICKLIST           5016
#define IDC_CHAT_COLOR                  5017
#define IDC_CHAT_BKGCOLOR               5019
#define IDC_CHAT_CHECKBOXES             5021
#define IDC_CHAT_HISTORY                5022
#define IDC_CHAT_NICKROW                5024
#define IDC_CHAT_LOGLIMIT               5024
#define IDC_CHAT_SPIN1                  5028
#define IDC_CHAT_SPIN2                  5029
#define IDC_CHAT_SPIN3                  5030
#define IDC_CHAT_HIGHLIGHTWORDS         5040
#define IDC_CHAT_INSTAMP                5041
#define IDC_CHAT_OUTSTAMP               5043
#define IDC_CHAT_TIMESTAMP              5046
#define IDC_CHAT_LOGDIRCHOOSE           5047
#define IDC_CHAT_LOGDIRECTORY           5048
#define IDC_CHAT_LIMIT                  5050
#define IDC_CHAT_LOGTIMESTAMP           5051
#define IDC_CHAT_GROUP                  5057
#define IDC_CHAT_RADIO1                 5061
#define IDC_CHAT_RADIO2                 5062
#define IDC_CHAT_RADIO3                 5063
#define IDC_CHAT_TEXT                   5064
#define IDC_CHAT_BKG                    5065
#define IDC_CHAT_TIMEOUT                5067
#define IDC_CHAT_HIGHLIGHT              5068
#define IDC_CHAT_TEXTO                  5069
#define IDC_CHAT_LOGGING                5069
#define IDC_CHAT_COLORTEXT              5070
#define IDC_CHAT_LIST                   5072
#define IDC_CHAT_1                      5075
#define IDC_CHAT_2                      5076
#define IDC_CHAT_3                      5077
#define IDC_CHAT_4                      5078
#define IDC_CHAT_5                      5079
#define IDC_CHAT_6                      5080
#define IDC_CHAT_7                      5081
#define IDC_CHAT_8                      5082
#define IDC_CHAT_9                      5083
#define IDC_CHAT_10                     5084
#define IDC_CHAT_11                     5085
#define IDM_CUT                         40000
#define IDM_COPY                        40001
#define IDM_PASTE                       40002
#define IDM_UNDO                        40003
#define IDM_DELETE                      40004
#define IDM_REDO                        40005
#define IDM_PASTESEND                   40006
#define IDM_COPYALL                     40011
#define IDM_SELECTALL                   40012
#define IDM_CLEAR                       40013
#define IDM_OPENLINK                    40014
#define IDM_COPYLINK                    40016
#define IDM_CLOSETAB                    40020
#define IDM_CLOSEOTHERTABS              40021
#define IDM_SEARCH_GOOGLE               40080
#define IDM_SEARCH_BING                 40081
#define IDM_SEARCH_YANDEX               40082
#define IDM_SEARCH_WIKIPEDIA            40083
#define IDM_SEARCH_GOOGLE_MAPS          40084
#define IDM_SEARCH_GOOGLE_TRANSLATE     40085
#define IDM_SEARCH_YAHOO                40086
#define IDM_SEARCH_FOODNETWORK          40087
#define ID_MESS                         50001
#define ID_COPYALL                      50006
#define ID_Menu                         50026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
