//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by C:\Users\xx\Documents\Visual Studio 2010\Projects\miranda-ng\plugins\NewXstatusNotify\res\resource.rc
//
#define IDD_OPT_XPOPUP                  101
#define IDD_INFO_SOUNDS                 102
#define IDD_OPT_GENERAL                 103
#define IDI_RESET                       109
#define IDI_VARIABLES                   110
#define IDI_LOGGING_XSTATUS             112
#define IDD_AUTODISABLE                 113
#define IDI_LOGGING_SMSG                113
#define IDD_OPT_FILTERS                 114
#define IDD_OPT_POPUP                   115
#define IDD_OPT_XLOG                    116
#define IDI_POPUP                       117
#define IDD_OPT_SMPOPUP                 117
#define IDI_SOUND                       118
#define IDD_OPT_LOG                     118
#define IDI_XSTATUS                     120
#define IDI_DISABLEALL                  121
#define IDI_ENABLEALL                   122
#define IDI_NOTIFICATION_OFF            123
#define IDI_NOTIFICATION_ON             124
#define IDI_STATUS_MESSAGE              125
#define IDC_STATUS_STATIC_INFINITE      1002
#define IDC_STATUS_STATIC_DEFAULT       1003
#define IDC_TIMEOUT_VALUE_SPIN          1004
#define IDC_STATUS_STATIC_SEC           1005
#define IDC_STATUS_LC                   1006
#define IDC_USEWINCOLORS                1007
#define IDC_STATUS_RC                   1008
#define IDC_CONNECTIONTIMEOUT_VALUE_SPIN 1009
#define IDC_STATUS_STATIC_SEC2          1010
#define IDC_READAWAYMSG                 1011
#define IDC_CHK_DISABLEMUSIC            1011
#define IDC_SHOWPREVIOUSSTATUS          1012
#define IDC_CHK_CUTMSG                  1012
#define IDC_USEPOPUPCOLORS              1013
#define IDC_ED_MSGLEN                   1013
#define IDC_ED_TOPENING                 1018
#define IDC_ED_TXSTATUSOPENING          1018
#define IDC_ED_TCHANGE                  1024
#define IDC_ED_TCHANGEMSG               1025
#define IDC_ED_TREMOVEMSG               1026
#define IDC_BT_VARIABLES                1028
#define IDC_BT_RESET                    1029
#define IDC_PREVIEW                     1030
#define IDC_CHANGE                      1031
#define IDC_CHK_MSGCHANGE               1031
#define IDC_DELETE                      1032
#define IDC_CHK_XSTATUSCHANGE           1032
#define IDC_CHK_OPENING                 1033
#define IDC_CHK_MSGREMOVE               1033
#define IDC_CHK_XSTATUSOPENING          1033
#define IDC_UD_MSGLEN                   1034
#define IDC_CHK_PGLOBAL                 1035
#define IDC_CHK_SGLOBAL                 1036
#define IDC_CHK_ONLYGLOBAL              1037
#define IDC_HYPERLINK                   1038
#define IDC_CHK_REMOVE                  1039
#define IDC_ED_TREMOVE                  1040
#define IDC_ED_TDELIMITER               1042
#define IDC_INDSNDLIST                  1044
#define IDC_LOGTODB                     1044
#define IDC_CHECKMESSAGEWINDOW          1045
#define IDC_SMSGLOGTODB                 1045
#define IDC_ED_SMSGLEN                  1046
#define IDC_LOGTODB_WINOPEN             1046
#define IDC_UD_SMSGLEN                  1047
#define IDC_LOGTODB_REMOVE              1047
#define IDC_XONCONNECT                  1048
#define IDC_SMSGLOGTODB_WINOPEN         1048
#define IDC_LOGTOFILE                   1049
#define IDC_LOGPREVIOUS                 1050
#define IDC_SMSGLOGTOFILE               1051
#define IDC_HIDDENCONTACTSTOO           1052
#define IDC_SMSGLOGTODB_REMOVE          1052
#define IDC_USEINDIVSOUNDS              1053
#define IDC_LOG_SMSGCHANGED             1053
#define IDC_LOG_SMSGREMOVED             1054
#define IDC_OK                          1055
#define IDC_LOG_TSMSGCHANGED            1055
#define IDC_CANCEL                      1056
#define IDC_LOG_TSMSGREMOVED            1056
#define IDC_CONFIGUREAUTODISABLE        1057
#define IDC_LOG_SMSG_OPENING            1057
#define IDC_LOG_SMSGOPENING             1057
#define IDC_XLOGTODB_REMOVE             1057
#define IDC_LOG_TSMSGOPENING            1058
#define IDC_CHK_XSTATUSCHANGED          1058
#define IDC_CHK_MSGCHANGED              1059
#define IDC_AUTODISABLE                 1060
#define IDC_CHK_XSTATUSREMOVED          1060
#define IDC_LOG                         1061
#define IDC_ED_TXSTATUSCHANGED          1061
#define IDC_ED_TXSTATUSREMOVED          1062
#define IDC_ED_TMSGCHANGED              1063
#define IDC_CHK_MSGREMOVED              1064
#define IDC_CHECK1                      1064
#define IDC_ONEFORALL                   1064
#define IDC_ED_TMSGCHANGED2             1065
#define IDC_ED_TMSGREMOVED              1065
#define IDC_TIMEOUT_VALUE               1066
#define IDC_BLINKICON                   1067
#define IDC_CONNECTIONTIMEOUT_VALUE     1067
#define IDC_BLINKICON_STATUS            1068
#define IDC_SOUNDICON                   1069
#define IDC_BLINKICON_FORMSGS           1069
#define IDC_POPUPICON                   1070
#define IDC_CHECK_NOTIFYSOUNDS          1071
#define IDC_CHECK_NOTIFYPOPUPS          1073
#define IDC_TEXT_ENABLE_IS              1074
#define IDC_USEOWNCOLORS                1076
#define IDC_SHOWALTDESCS                1077
#define IDC_LOGGINGICON                 1078
#define IDC_SHOWSTATUS                  1078
#define IDC_XLOGGINGICON                1078
#define IDC_XSTATUSICON                 1079
#define IDC_DISABLEALLICON              1080
#define IDC_ENABLEALLICON               1081
#define IDC_SHOWGROUP                   1082
#define IDC_STATUSMESSAGEICON           1082
#define IDC_SMSGICON                    1082
#define IDC_XLOGGINGICON2               1083
#define IDC_SMSGLOGGINGICON             1083
#define IDC_ONCONNECT                   1101
#define IDC_PUIGNOREREMOVE              1102
#define IDC_CHK_NEWSMSG                 1102
#define IDC_CHK_SMSGREMOVE              1103
#define IDC_CUTSMSG                     1104
#define IDC_CHK_CUTSMSG                 1104
#define IDC_POPUPTEXT                   1115
#define IDC_ED_TNEWSMSG                 1115
#define IDC_ED_TSMSGREMOVE              1116
#define IDC_PROTOCOLLIST                1207
#define IDC_LOGFILE                     2029
#define IDC_BT_CHOOSELOGFILE            2030
#define IDC_BT_VIEWLOG                  2031
#define IDC_CHK_LOGGING                 2034
#define IDC_XLOGTOFILE                  2034
#define IDC_CHK_SAVETOHISTORY           2039
#define IDC_XLOGTODB_WINOPEN            2039
#define IDC_CHK_PREVENTIDENTICAL        2040
#define IDC_XLOGTODB                    2040
#define IDC_CHK_OFFLINE                 40071
#define IDC_CHK_ONLINE                  40072
#define IDC_CHK_AWAY                    40073
#define IDC_CHK_DND                     40074
#define IDC_CHK_NA                      40075
#define IDC_CHK_OCCUPIED                40076
#define IDC_CHK_FREECHAT                40077
#define IDC_CHK_INVISIBLE               40078
#define IDC_CHK_ONTHEPHONE              40079
#define IDC_CHK_OUTTOLUNCH              40080
#define IDC_CHK_XSTATUS                 40081
#define IDC_CHK_STATUS_MESSAGE          40082
#define IDC_CHK_FROMOFFLINE             40083
#define IDC_OFFLINE_TX                  41071
#define IDC_ONLINE_TX                   41072
#define IDC_AWAY_TX                     41073
#define IDC_DND_TX                      41074
#define IDC_NA_TX                       41075
#define IDC_OCCUPIED_TX                 41076
#define IDC_FREEFORCHAT_TX              41077
#define IDC_INVISIBLE_TX                41078
#define IDC_ONTHEPHONE_TX               41079
#define IDC_OUTTOLUNCH_TX               41080
#define IDC_XSTATUS_TX                  41081
#define IDC_STATUSMSG_TX                41082
#define IDC_OFFLINE_BG                  42071
#define IDC_ONLINE_BG                   42072
#define IDC_CHK_ONLINE2                 42072
#define IDC_AWAY_BG                     42073
#define IDC_CHK_AWAY2                   42073
#define IDC_DND_BG                      42074
#define IDC_CHK_DND2                    42074
#define IDC_NA_BG                       42075
#define IDC_CHK_NA2                     42075
#define IDC_OCCUPIED_BG                 42076
#define IDC_CHK_OCCUPIED2               42076
#define IDC_FREEFORCHAT_BG              42077
#define IDC_CHK_FREECHAT2               42077
#define IDC_INVISIBLE_BG                42078
#define IDC_CHK_INVISIBLE2              42078
#define IDC_ONTHEPHONE_BG               42079
#define IDC_CHK_ONTHEPHONE2             42079
#define IDC_OUTTOLUNCH_BG               42080
#define IDC_CHK_OUTTOLUNCH2             42080
#define IDC_XSTATUS_BG                  42081
#define IDC_STATUSMSG_BG                42082

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
