//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resources.rc
//
#define IDI_ICQ                         101
#define IDS_IDENTIFY                    102
#define IDD_ICQACCOUNT                  103
#define IDD_ASKAUTH                     104
#define IDD_LOGINPW                     105
#define IDD_OPT_ICQ                     108
#define IDD_OPT_ICQCONTACTS             109
#define IDD_OPT_ICQFEATURES             110
#define IDD_OPT_ICQPRIVACY              111
#define IDI_AUTH_ASK                    150
#define IDI_AUTH_GRANT                  151
#define IDI_AUTH_REVOKE                 152
#define IDI_SERVLIST_ADD                160
#define IDI_XSTATUS1                    201
#define IDI_XSTATUS2                    202
#define IDI_XSTATUS3                    203
#define IDI_XSTATUS4                    204
#define IDI_XSTATUS5                    205
#define IDI_XSTATUS6                    206
#define IDI_XSTATUS7                    207
#define IDI_XSTATUS8                    208
#define IDI_XSTATUS9                    209
#define IDI_XSTATUS10                   210
#define IDI_XSTATUS11                   211
#define IDI_XSTATUS12                   212
#define IDI_XSTATUS13                   213
#define IDI_XSTATUS14                   214
#define IDI_XSTATUS15                   215
#define IDI_XSTATUS16                   216
#define IDI_XSTATUS17                   217
#define IDI_XSTATUS18                   218
#define IDI_XSTATUS19                   219
#define IDI_XSTATUS20                   220
#define IDI_XSTATUS21                   221
#define IDI_XSTATUS22                   222
#define IDI_XSTATUS23                   223
#define IDI_XSTATUS24                   224
#define IDI_XSTATUS25                   225
#define IDI_XSTATUS26                   226
#define IDI_XSTATUS27                   227
#define IDI_XSTATUS28                   228
#define IDI_XSTATUS29                   229
#define IDI_XSTATUS30                   230
#define IDI_XSTATUS31                   231
#define IDI_XSTATUS32                   232
#define IDI_XSTATUS33                   233
#define IDI_XSTATUS34                   234
#define IDI_XSTATUS35                   235
#define IDI_XSTATUS36                   236
#define IDI_XSTATUS37                   237
#define IDI_XSTATUS38                   238
#define IDI_XSTATUS39                   239
#define IDI_XSTATUS40                   240
#define IDI_XSTATUS41                   241
#define IDI_XSTATUS42                   242
#define IDI_XSTATUS43                   243
#define IDI_XSTATUS44                   244
#define IDI_XSTATUS45                   245
#define IDI_XSTATUS46                   246
#define IDI_XSTATUS47                   247
#define IDI_XSTATUS48                   248
#define IDI_XSTATUS49                   249
#define IDI_XSTATUS50                   250
#define IDI_XSTATUS51                   251
#define IDI_XSTATUS52                   252
#define IDI_XSTATUS53                   253
#define IDI_XSTATUS54                   254
#define IDI_XSTATUS55                   255
#define IDI_XSTATUS56                   256
#define IDI_XSTATUS57                   257
#define IDI_XSTATUS58                   258
#define IDI_XSTATUS59                   259
#define IDI_XSTATUS60                   260
#define IDI_XSTATUS61                   261
#define IDI_XSTATUS62                   262
#define IDI_XSTATUS63                   263
#define IDI_XSTATUS64                   264
#define IDI_XSTATUS65                   265
#define IDI_XSTATUS66                   266
#define IDI_XSTATUS67                   267
#define IDI_XSTATUS68                   268
#define IDI_XSTATUS69                   269
#define IDI_XSTATUS70                   270
#define IDI_XSTATUS71                   271
#define IDI_XSTATUS72                   272
#define IDI_XSTATUS73                   273
#define IDI_XSTATUS74                   274
#define IDI_XSTATUS75                   275
#define IDI_XSTATUS76                   276
#define IDI_XSTATUS77                   277
#define IDI_XSTATUS78                   278
#define IDI_XSTATUS79                   279
#define IDI_XSTATUS80                   280
#define IDI_XSTATUS81                   281
#define IDI_XSTATUS82                   282
#define IDI_XSTATUS83                   283
#define IDI_XSTATUS84                   284
#define IDI_XSTATUS85                   285
#define IDI_XSTATUS86                   286
#define IDD_INFO_ICQ                    240
#define IDD_ICQADVANCEDSEARCH           242
#define IDD_ICQUPLOADLIST               253
#define IDD_SETXSTATUS                  256
#define IDD_PWCONFIRM                   300
#define IDD_INFO_CHANGEINFO             301
#define IDD_OPT_POPUPS                  400
#define IDC_POPUPS_ENABLED              410
#define IDC_POPUPS_LOG_ENABLED          411
#define IDC_POPUPS_SPAM_ENABLED         412
#define IDC_POPUP_LOG0_TEXTCOLOR        420
#define IDC_POPUP_LOG1_TEXTCOLOR        421
#define IDC_POPUP_LOG2_TEXTCOLOR        422
#define IDC_POPUP_LOG3_TEXTCOLOR        423
#define IDC_POPUP_SPAM_TEXTCOLOR        425
#define IDC_POPUP_LOG0_BACKCOLOR        430
#define IDC_POPUP_LOG1_BACKCOLOR        431
#define IDC_POPUP_LOG2_BACKCOLOR        432
#define IDC_POPUP_LOG3_BACKCOLOR        433
#define IDC_POPUP_SPAM_BACKCOLOR        435
#define IDC_POPUP_LOG0_TIMEOUT          440
#define IDC_POPUP_LOG1_TIMEOUT          441
#define IDC_POPUP_LOG2_TIMEOUT          442
#define IDC_POPUP_LOG3_TIMEOUT          443
#define IDC_POPUP_SPAM_TIMEOUT          444
#define IDC_USEWINCOLORS                450
#define IDC_USESYSICONS                 451
#define IDC_PREVIEW                     455
#define IDC_LOG                         1001
#define IDI_EXPANDSTRINGEDIT            1001
#define IDC_SAVEPASS                    1004
#define IDC_RETRXSTATUS                 1005
#define IDC_XTITLE_STATIC               1006
#define IDC_XMSG_STATIC                 1007
#define IDC_SSL                         1008
#define IDC_MD5LOGIN                    1009
#define IDC_UTFENABLE                   1010
#define IDC_XTITLE                      1010
#define IDC_KEEPALIVE                   1011
#define IDC_XMSG                        1011
#define IDC_UTFALL                      1012
#define IDC_UTFSTATIC                   1013
#define IDC_UTFCODEPAGE                 1014
#define IDC_PW                          1015
#define IDC_TEMPVISIBLE                 1015
#define IDC_REGISTER                    1016
#define IDC_EDITAUTH                    1017
#define IDC_LOGINPW                     1018
#define IDC_INSTRUCTION                 1019
#define IDC_PASSWORD                    1020
#define IDC_SUPTIME                     1020
#define IDC_DCENABLE                    1020
#define IDC_DCPASSIVE                   1021
#define IDC_OLDPASS                     1021
#define IDC_ICQNUM                      1022
#define IDC_AIMENABLE                   1030
#define IDC_CLIST                       1035
#define IDC_XSTATUSENABLE               1040
#define IDC_XSTATUSAUTO                 1041
#define IDC_XSTATUSRESET                1042
#define IDC_MOODSENABLE                 1043
#define IDC_KILLSPAMBOTS                1045
#define IDC_EMAIL                       1048
#define IDC_NICK                        1053
#define IDC_GENDER                      1060
#define IDC_CITY                        1061
#define IDC_STATE                       1062
#define IDC_COUNTRY                     1063
#define IDC_COMPANY                     1066
#define IDC_DEPARTMENT                  1067
#define IDC_POSITION                    1069
#define IDC_IP                          1094
#define IDC_UINSTATIC                   1122
#define IDC_UIN                         1123
#define IDC_STATIC11                    1154
#define IDC_STATIC12                    1155
#define IDC_ICQSERVER                   1171
#define IDC_ICQPORT                     1172
#define IDC_VERSION                     1179
#define IDC_FIRSTNAME                   1224
#define IDC_LASTNAME                    1225
#define IDC_REALIP                      1230
#define IDC_RECONNECTREQD               1239
#define IDC_OFFLINETOENABLE             1240
#define IDC_PORT                        1249
#define IDC_MIRVER                      1251
#define IDC_ONLINESINCE                 1252
#define IDC_SYSTEMUPTIME                1253
#define IDC_IDLETIME                    1254
#define IDC_STATUS                      1255
#define IDC_SLOWSEND                    1301
#define IDC_ONLYSERVERACKS              1302
#define IDC_LOGLEVEL                    1331
#define IDC_LEVELDESCR                  1332
#define IDC_NOERRMULTI                  1333
#define IDC_STICQGROUP                  1374
#define IDC_AGERANGE                    1410
#define IDC_MARITALSTATUS               1411
#define IDC_KEYWORDS                    1412
#define IDC_LANGUAGE                    1414
#define IDC_WORKFIELD                   1421
#define IDC_PASTCAT                     1422
#define IDC_PASTKEY                     1423
#define IDC_INTERESTSCAT                1424
#define IDC_INTERESTSKEY                1425
#define IDC_ORGANISATION                1426
#define IDC_ORGKEYWORDS                 1427
#define IDC_OTHERGROUP                  1429
#define IDC_ONLINEONLY                  1430
#define IDC_HOMEPAGECAT                 1431
#define IDC_HOMEPAGEKEY                 1432
#define IDC_SUMMARYGROUP                1434
#define IDC_WORKGROUP                   1435
#define IDC_LOCATIONGROUP               1436
#define IDC_BACKGROUNDGROUP             1437
#define IDC_NEWUINLINK                  1438
#define IDC_LOOKUPLINK                  1439
#define IDC_RESETSERVER                 1472
#define IDC_UPLOADNOW                   1521
#define IDC_GROUPS                      1522
#define IDC_ALLGROUPS                   1526
#define IDC_VISIBILITY                  1527
#define IDC_IGNORE                      1528
#define IDC_ENABLE                      1529
#define IDC_LOADFROMSERVER              1530
#define IDC_ADDSERVER                   1532
#define IDC_SAVETOSERVER                1533
#define IDC_ENABLEAVATARS               1536
#define IDC_AUTOLOADAVATARS             1537
#define IDC_STRICTAVATARCHECK           1539
#define IDC_WEBAWARE                    1546
#define IDC_DCALLOW_ANY                 1547
#define IDC_DCALLOW_CLIST               1548
#define IDC_DCALLOW_AUTH                1549
#define IDC_PUBLISHPRIMARY              1550
#define IDC_ADD_ANY                     1551
#define IDC_ADD_AUTH                    1552
#define IDC_STATUSMSG_CLIST             1553
#define IDC_STATUSMSG_VISIBLE           1554
#define IDC_STATIC_NOTONLINE            1555
#define IDC_STATIC_DC2                  1556
#define IDC_STATIC_DC1                  1557
#define IDC_STATIC_CLIST                1558
#define IDC_SAVE                        1600
#define IDC_LIST                        1601
#define IDC_UPLOADING                   1602

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
