const
  IDD_SEARCH       = 101;
  IDD_SETTING      = 102;
  IDD_SETTING_TECH = 103;
  IDD_FRAME        = 104;

  IDC_GENRE   = 1025;
  IDC_BITRATE = 1026;
  IDC_STATION = 1027;
  IDC_LT      = 1029;
  IDC_EQ      = 1030;
  IDC_GT      = 1031;

  IDC_LOOP       = 1032;
  IDC_SHUFFLE    = 1033;
  IDC_CONTREC    = 1034;
  IDC_PLAYFIRST  = 1035;
  IDC_EQOFF      = 1036;
  IDC_BN_INIPATH = 1037;
  IDC_BN_URLPATH = 1038;
  IDC_CUSTOMINI  = 1039;

  IDC_VOLUME     = 1040;
  IDC_STATIONURL = 1041;
  IDC_ADD_LIST   = 1042;
  IDC_ADD_INI    = 1043;
  IDC_BN_RECPATH = 1044;
  IDC_ED_RECPATH = 1045;
  IDC_BN_RECORD  = 1046;
  IDC_EAXTYPE    = 1047;
  IDC_USEEAX     = 1048;
  IDC_BUFFER     = 1049;
  IDC_PREBUF     = 1050;
  IDC_TIMEOUT    = 1051;
  IDC_PRESET     = 1052;
  IDC_TRIES      = 1053;
  IDC_MONO       = 1054;
  IDC_DEVICE     = 1055;

  IDC_BASSPATH   = 1100;
  IDC_BASSPTHBTN = 1101;

  IDC_ZERO       = 1060;
  IDC_EQ00       = 1061;
  IDC_EQ01       = 1062;
  IDC_EQ02       = 1063;
  IDC_EQ03       = 1064;
  IDC_EQ04       = 1065;
  IDC_EQ05       = 1066;
  IDC_EQ06       = 1067;
  IDC_EQ07       = 1068;
  IDC_EQ08       = 1069;
  IDC_EQ09       = 1070;
  IDC_0          = 1161;
  IDC_1          = 1162;
  IDC_2          = 1163;
  IDC_3          = 1164;
  IDC_4          = 1165;
  IDC_5          = 1166;
  IDC_6          = 1167;
  IDC_7          = 1168;
  IDC_8          = 1169;
  IDC_9          = 1170;

  IDC_CONNECT    = 1072;
  IDC_OFFLINE    = 1073;
  IDC_AUTOMUTE   = 1074;

  IDC_STATUS     = 1075;
  IDC_HLP_VARS   = 1076;

  IDC_IMPORT     = 1077;
  IDC_EXPORT     = 1078;

  IDC_EQ_ADD     = 1079;
  IDC_EQ_DEL     = 1080;

  IDC_RADIO_MUTE = 1025;
  IDC_RADIO_VOL  = 1026;
  IDC_RADIO_OPEN = 1027;

  BTN_RECUP = 202;
  BTN_RECDN = 203;

  IDI_MAIN  = 302;
  IDI_ON    = 303;
  IDI_OFF   = 304;
  IDI_ADD   = 305;
  IDI_DEL   = 306;
  IDI_OPEN  = 307;
