#define IDD_SHLOPTS                     101
#define IDC_USEGROUPS                   1014
#define IDC_CLISTGROUPS                 1015
#define IDC_SHOWFULL                    1016
#define IDC_NOPROF                      1020
#define IDC_SHOWINVISIBLES              1021
#define IDC_HIDEOFFLINE                 1022
#define IDC_STATUS                      1023
#define IDC_CAPMENUS                    1025
#define IDC_CAPSTATUS                   1026
#define IDC_CAPSHLSTATUS                1027
#define IDC_REMOVE                      1028
#define IDC_USEOWNERDRAW                1029
