#define __FILEVERSION_STRING  __MAJOR_VERSION,__MINOR_VERSION,__RELEASE_NUM,__BUILD_NUM
#define __FILEVERSION_DOTS    __MAJOR_VERSION.__MINOR_VERSION.__RELEASE_NUM.__BUILD_NUM

#define __STRINGIFY_IMPL(x)      #x
#define __STRINGIFY(x)           __STRINGIFY_IMPL(x)

#define __VERSION_DWORD          PLUGIN_MAKE_VERSION(__MAJOR_VERSION,__MINOR_VERSION,__RELEASE_NUM,__BUILD_NUM)
#define __VERSION_STRING         __STRINGIFY(__FILEVERSION_STRING)
#define __VERSION_STRING_DOTS    __STRINGIFY(__FILEVERSION_DOTS)
