//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_OPT_CLIST                   126
#define IDR_CONTEXT                     180
#define IDC_DROP                        183
#define IDD_OPT_HOTKEY                  184
#define IDR_CLISTMENU                   199
#define IDC_HYPERLINKHAND               214
#define IDC_DROPUSER                    215
#define IDD_OPT_CLUI                    218
#define IDD_OPT_CLC                     228
#define IDD_OPT_CLCBKG                  230
#define IDD_OPT_SBAR                    234
#define IDD_OPT_CLCTEXTSIMPLE           239
#define IDD_DELETECONTACT               254
#define IDD_MODERNOPT_CLIST             288
#define IDD_MODERNOPT_CLUI              289
#define IDD_MODERNOPT_SBAR              290
#define IDD_MODERNOPT_CLCBKG            291
#define IDC_MIN2TRAY                    1073
#define IDC_ONTOP                       1074
#define IDC_SHOWMAINMENU                1075
#define IDC_CLIENTDRAG                  1076
#define IDC_TOOLWND                     1097
#define IDC_ONECLK                      1098
#define IDC_SHOWCAPTION                 1098
#define IDC_HIDEOFFLINE                 1099
#define IDC_SHOWHIDE                    1100
#define IDC_HIDEEMPTYGROUPS             1100
#define IDC_SORTBYSTATUS                1101
#define IDC_FADEINOUT                   1101
#define IDC_READMSG                     1102
#define IDC_AUTOSIZE                    1102
#define IDC_DISABLEGROUPS               1102
#define IDC_AUTOSIZEUPWARD              1103
#define IDC_ALWAYSSTATUS                1103
#define IDC_NETSEARCH                   1104
#define IDC_CONFIRMDELETE               1104
#define IDC_SORTBYPROTO                 1105
#define IDC_SHOWOPTIONS                 1105
#define IDC_SEARCHURL                   1106
#define IDC_TRANSPARENT                 1124
#define IDC_TRANSINACTIVE               1126
#define IDC_TRANSACTIVE                 1128
#define IDC_STATIC11                    1154
#define IDC_STATIC12                    1155
#define IDC_STATIC21                    1156
#define IDC_STATIC22                    1157
#define IDC_HKSHOWHIDE                  1162
#define IDC_HKREADMSG                   1163
#define IDC_HKSEARCH                    1164
#define IDC_HKSHOWOPTIONS               1165
#define IDC_BROWSE                      1184
#define IDC_INACTIVEPERC                1187
#define IDC_ACTIVEPERC                  1188
#define IDC_SEARCHNEWWND                1188
#define IDC_TITLETEXT                   1196
#define IDC_AUTOHIDE                    1235
#define IDC_HIDETIME                    1236
#define IDC_MAXSIZEHEIGHT               1254
#define IDC_MAXSIZESPIN                 1255
#define IDC_BKGCOLOUR                   1269
#define IDC_FILENAME                    1271
#define IDC_SCROLL                      1277
#define IDC_PROPORTIONAL                1278
#define IDC_SELCOLOUR                   1281
#define IDC_SMOOTHTIME                  1283
#define IDC_SMOOTHTIMESPIN              1284
#define IDC_GREYOUT                     1285
#define IDC_ROWHEIGHT                   1286
#define IDC_ROWHEIGHTSPIN               1287
#define IDC_GREYOUTOPTS                 1288
#define IDC_GROUPINDENT                 1289
#define IDC_GROUPINDENTSPIN             1290
#define IDC_LEFTMARGIN                  1291
#define IDC_SAMPLE                      1292
#define IDC_LEFTMARGINSPIN              1292
#define IDC_FONTSIZE                    1293
#define IDC_STRETCHH                    1298
#define IDC_STRETCHV                    1299
#define IDC_TILEH                       1300
#define IDC_SCRIPT                      1300
#define IDC_TILEV                       1301
#define IDC_GAMMACORRECT                1302
#define IDC_HIDEOFFLINEOPTS             1308
#define IDC_DONTCYCLE                   1315
#define IDC_PRIMARYSTATUS               1316
#define IDC_CYCLE                       1317
#define IDC_CYCLETIME                   1318
#define IDC_CYCLETIMESPIN               1319
#define IDC_HIDETIMESPIN                1320
#define IDC_MULTITRAY                   1321
#define IDC_ALWAYSMULTI                 1322
#define IDC_SHOWICON                    1323
#define IDC_SHOWPROTO                   1324
#define IDC_SHOWSTATUS                  1325
#define IDC_EQUALSECTIONS               1326
#define IDC_SHOWSBAR                    1329
#define IDC_RIGHTMIRANDA                1330
#define IDC_RIGHTSTATUS                 1331
#define IDC_SORTBYNAME                  1347
#define IDC_STAUTOHIDESECS              1349
#define IDC_STCLISTGROUP                1350
#define IDC_DISABLEDRAGDROP             1351
#define IDC_NOTEDITLABELS               1352
#define IDC_SHOWSELALWAYS               1353
#define IDC_TRACKSELECT                 1354
#define IDC_SHOWGROUPCOUNTS             1355
#define IDC_HIDECOUNTSWHENEMPTY         1356
#define IDC_DIVIDERONOFF                1357
#define IDC_NOTNOTRANSLUCENTSEL         1358
#define IDC_LINEWITHGROUPS              1359
#define IDC_QUICKSEARCHVISONLY          1360
#define IDC_SORTGROUPSALPHA             1361
#define IDC_NOTNOSMOOTHSCROLLING        1362
#define IDC_BITMAP                      1363
#define IDC_STWINDOWGROUP               1364
#define IDC_STATIC01                    1365
#define IDC_HIDE                        1534
#define IDC_TOPLINE                     1535
#define IDC_HOTKEYURLSTR                1567
#define IDC_BRINGTOFRONT                1579
#define IDC_BLINKTIME                   1607
#define IDC_BLINKSPIN                   1608
#define IDC_DISABLEBLINK                1609
#define IDC_IDLE                        1610
#define IDC_SBPANELBEVEL                1611
#define IDC_DROPSHADOW                  1612
#define IDC_SHOWGRIP                    1612
#define IDC_NOSCROLLBAR                 1613
#define IDC_TXT_TITLE1                  1617
#define IDC_TXT_TITLE2                  1618
#define IDC_ONDESKTOP                   1657
#define IDC_DISABLEDOCKING              1658
#define IDC_WINCOLOUR                   1659
#define IDC_ICONBLINK                   1660
#define IDC_STMSDELAY                   1661
#define ID_ICQ_EXIT                     40001
#define POPUP_HIDEEMPTYGROUPS           40003
#define POPUP_NEWSUBGROUP               40004
#define POPUP_HIDEOFFLINE               40005
#define POPUP_GROUPHIDEOFFLINE          40006
#define POPUP_HIDEOFFLINEROOT           40007
#define POPUP_DISABLEGROUPS             40008
#define POPUP_HIDEMIRANDA               40017
#define ID_TRAY_HIDE                    40038
#define ID_TRAY_EXIT                    40040
#define POPUP_NEWGROUP                  40050
#define POPUP_RENAMEGROUP               40052
#define POPUP_DELETEGROUP               40053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        292
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1662
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
