{resource constants}
const
  // dialogs
//  IDD_STRUCTURE     = 1027;
//  IDD_HELP          = 1028;

  // icons
//  IDI_NEW           = 1125;
//  IDI_UP            = 1126;
//  IDI_DOWN          = 1127;
//  IDI_DELETE        = 1128;

  // Structure editor
  IDC_DATA_FULL     = 2001;
  IDC_DATA_TYPE     = 2002;
  IDC_DATA_SIZE     = 2004;
  IDC_DATA_EDIT     = 2005;
  IDC_DATA_LEN      = 2006;
  IDC_DATA_HELP     = 2007;

  IDC_DATA_NEW      = 2008;
  IDC_DATA_DELETE   = 2009;
  IDC_DATA_UP       = 2010;
  IDC_DATA_DOWN     = 2011;
  IDC_DATA_CHANGE   = 2012;
  IDC_DATA_VARS     = 2013;
  IDC_DATA_ALIGN    = 2014;
  IDC_DATA_MMI      = 2015;

  IDC_DATA_SALGN    = 2016;
  IDC_DATA_SEP      = 2017;
  IDC_DATA_EDTN     = 2018;

  IDC_DATA_TMPL     = 2019;
  IDC_DATA_INFO     = 2020;
  IDC_DATA_PASTE    = 2021;

  IDC_DATA_SLEN     = 2022;
  IDC_VAR_HELP      = 2023;

  // Structure helper
  IDC_HLP_NAME      = 2030;
  IDC_HLP_PLUGIN    = 2031;
  IDC_HLP_DESCR     = 2032;
  IDC_HLP_STRUCT    = 2033;
