const
  IDD_DIALOG1            = 101;
  IDD_MAIN               = 102;
  IDD_SCRIPT             = 103;
  IDD_FRAME              = 104;

  IDI_QS                 = 107;

  IDI_NEW                = 110;
  IDI_ITEM               = 111;
  IDI_UP                 = 112;
  IDI_DOWN               = 113;
  IDI_DELETE             = 114;
  IDI_DEFAULT            = 115;
  IDI_RELOAD             = 116;

  IDI_MALE               = 120;
  IDI_FEMALE             = 121;

  IDC_FRAME_EDIT         = 1025;
  IDC_FRAME_PREV         = 1026;
  IDC_FRAME_NEXT         = 1027;
  IDC_FRAME_OPEN         = 1028;
  
  IDC_NEW                = 1001;
  IDC_DELETE             = 1002;
  IDC_UP                 = 1003;
  IDC_DN                 = 1004;
  IDC_DEFAULT            = 1005;
  IDC_SETITEM            = 1006;
  IDC_RELOAD             = 1007;

  IDC_E_TITLE            = 1010;
  IDC_E_MODULE           = 1011;
  IDC_E_VAR              = 1012;
  IDC_E_LPAR             = 1013;
  IDC_HOTKEYGLOB         = 1014;
  IDC_HOTKEYLOC          = 1015;
  IDC_HKGROUP            = 1016;
  IDC_STAT_GLOBAL        = 1017;
  IDC_STAT_LOCAL         = 1018;
  IDC_LIST               = 1020;
  IDC_C_VARTYPE          = 1021;
  IDC_C_CNFTYPE          = 1022;
  IDC_CB_MAIN            = 1023;
  IDC_C_WPAR             = 1024;
  IDC_C_LPAR             = 1025;
  IDC_C_RESULT           = 1026;
  IDC_CH_SORTSTATUS      = 1030;
  IDC_CH_SHOWINMENU      = 1031;
  IDC_CH_SHOWONLYUSERS   = 1032;
  IDC_CH_ADDTOTOPTOOLBAR = 1033;
  IDC_CH_AUTOCLOSE       = 1034;
  IDC_CH_USETOOLSTYLE    = 1035;
  IDC_CH_HOOKCHANGES     = 1036;
  IDC_CH_DRAWGRID        = 1037;
  IDC_CH_SHOWCLIENTICONS = 1038;
  IDC_STAT_SERVICE       = 1040;
  IDC_STAT_MODULE        = 1041;
  IDC_STAT_WPAR          = 1042;
  IDC_STAT_SETTING       = 1043;
  IDC_CH_SINGLECSV       = 1044;
  IDC_CH_EXPORTHEADERS   = 1045;
  IDC_CH_SKIPMINIMIZED   = 1046;
  IDC_CH_SAVEPATTERN     = 1047;
  IDC_STAT_VARTYPE       = 1048;
  IDC_SCRIPT             = 1049;

  IDC_E_SEARCHTEXT       = 1001;
  IDC_CH_SHOWOFFLINE     = 1031;
  IDC_CH_COLORIZE        = 1032;
  IDC_REFRESH            = 1033;
  IDC_STATUSBAR          = 1034;
  IDC_CB_PROTOCOLS       = 1035;

  IDC_EDIT_SCRIPT        = 1025;
