const
  IDD_DIALOG1            = 101;
  IDD_MAIN               = 102;
  IDD_SCRIPT             = 103;
  IDD_FRAME              = 104;

  IDI_QS                 = 107;

  IDI_NEW                = 110;
  IDI_UP                 = 111;
  IDI_DOWN               = 112;
  IDI_DELETE             = 113;
  IDI_DEFAULT            = 114;
  IDI_RELOAD             = 115;

  IDI_MALE               = 120;
  IDI_FEMALE             = 121;

  IDC_NEW                = 1001;
  IDC_DELETE             = 1002;
  IDC_UP                 = 1003;
  IDC_DN                 = 1004;
  IDC_DEFAULT            = 1005;
  IDC_SETITEM            = 1006;
  IDC_RELOAD             = 1007;

  IDC_LIST               = 1010;
  IDC_B_RESIZE           = 1011;

  IDC_CH_SORTSTATUS      = 1030;
  IDC_CH_AUTOCLOSE       = 1031;
  IDC_CH_USETOOLSTYLE    = 1032;
  IDC_CH_DRAWGRID        = 1033;
  IDC_CH_CLIENTICONS     = 1034;
  IDC_CH_SAVEPATTERN     = 1035;
  IDC_CH_GROUP           = 1040;

  IDC_S_COLSETTING       = 1020;
  IDC_S_LINE             = 1021;

  IDC_E_TITLE            = 1022;
  IDC_S_TITLE            = 1023;
  IDC_C_VARTYPE          = 1024;
  IDC_S_VARTYPE          = 1025;

  IDC_E_SCRIPT           = 2001;
  
  IDC_S_DATATYPE         = 2010;
  IDC_C_DATATYPE         = 2011;
  IDC_S_MODULE           = 2012;
  IDC_E_MODULE           = 2013;
  IDC_S_SETTING          = 2014;
  IDC_E_SETTING          = 2015;

  IDC_S_CNFTYPE          = 2020;
  IDC_C_CNFTYPE          = 2021;

  IDC_C_OTHER            = 2030;


  IDC_E_SEARCHTEXT       = 1001;
  IDC_CH_SHOWOFFLINE     = 1031;
  IDC_CH_COLORIZE        = 1032;
  IDC_REFRESH            = 1033;
  IDC_STATUSBAR          = 1034;
  IDC_CB_PROTOCOLS       = 1035;

  IDC_FRAME_OPEN         = 1050;
  IDC_FRAME_EDIT         = 1051;
