//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется d:\svn\protocols\VKontakte\res\resource.rc
//
#define IDD_ACCMGRUI                    101
#define IDD_CAPTCHAFORM                 102
#define IDD_OPT_MAIN                    103
#define IDD_INVITE                      104
#define IDD_GC_CREATE                   105
#define IDD_OPT_ADV                     106
#define IDD_OPT_FEEDS                   107
#define IDI_NOTIFICATION                109
#define IDI_FRIENDADD                   110
#define IDI_BAN                         111
#define IDI_FRIENDDEL                   112
#define IDI_READMSG                     113
#define IDI_ABUSE                       114
#define IDI_VISITPROFILE                115
#define IDI_HISTORY                     116
#define IDI_BROADCAST                   117
#define IDD_OPT_VIEW                    118
#define IDI_STATUS                      119
#define IDD_WALLPOST                    120
#define IDI_WALL                        121
#define IDI_KEYS                        203
#define IDC_LOGIN                       1001
#define IDC_PASSWORD                    1002
#define IDC_URL                         1003
#define IDC_VALUE                       1004
#define IDC_WHITERECT                   1005
#define IDC_TITLE                       1006
#define IDC_INSTRUCTION                 1007
#define IDC_FRAME1                      1008
#define IDC_FRAME2                      1009
#define IDC_SUBMIT                      1010
#define IDC_DELIVERY                    1011
#define IDC_GROUPNAME                   1012
#define IDC_CLIST                       1013
#define IDC_HIDECHATS                   1014
#define IDC_CONTACT                     1015
#define IDC_AUTOCLEAN                   1020
#define IDC_MESASUREAD                  1025
#define IDC_USE_LOCAL_TIME              1029
#define IDC_REPORT_ABUSE                1030
#define IDC_CLEAR_SERVER_HISTORY        1031
#define IDC_REMOVE_FROM_FRENDLIST       1032
#define IDC_REMOVE_FROM_CLIST           1033
#define IDC_FORCE_ONLINE_ON_ACT         1035
#define IDC_STICKERS_AS_SMYLES          1036
#define IDC_ONREAD                      1039
#define IDC_ONRECEIVE                   1040
#define IDC_ONREPLY                     1041
#define IDC_ONTYPING                    1042
#define IDC_STATIC_MARK_AS_READ         1043
#define IDC_STATIC_SEND_MUSIC_METOD     1044
#define IDC_SEND_MUSIC_NONE             1045
#define IDC_SEND_MUSIC_STATUS           1046
#define IDC_SEND_MUSIC_BROADCAST        1047
#define IDC_SEND_MUSIC_BROADCAST_AND_STATUS 1048
#define IDC_STATIC_SYNC_HISTORY         1049
#define IDC_SYNC_OFF                    1050
#define IDC_SYNC_AUTO                   1051
#define IDC_SYNC_LAST1DAY               1052
#define IDC_SYNC_LAST3DAY               1053
#define IDC_NEWS_ENBL                   1054
#define IDC_NOTIF_ENBL                  1055
#define IDC_NEWSAUTOCLEAR               1056
#define IDC_ED_INT_NEWS                 1057
#define IDC_SPIN_INT_NEWS               1058
#define IDC_ED_INT_NOTIF                1059
#define IDC_SPIN_INT_NOTIF              1060
#define IDC_SPEC_CONT_ENBL              1061
#define IDC_IMG_OFF                     1062
#define IDC_IMG_FULLSIZE                1063
#define IDC_IMG_130                     1064
#define IDC_IMG_604                     1065
#define IDC_NEWSBBC_OFF                 1066
#define IDC_NEWSBBC_BASIC               1067
#define IDC_NEWSBBC_ADV                 1068
#define IDC_IEVIEW                      1069
#define IDC_F_POSTS                     1070
#define IDC_F_PHOTOS                    1071
#define IDC_F_TAGS                      1072
#define IDC_F_WALLPHOTOS                1073
#define IDC_S_FRIENDS                   1074
#define IDC_S_GROUPS                    1075
#define IDC_S_PAGES                     1076
#define IDC_S_FOLLOWING                 1077
#define IDC_S_BANNED                    1078
#define IDC_S_NOREPOSTES                1079
#define IDC_N_COMMENTS                  1080
#define IDC_N_LIKES                     1081
#define IDC_N_REPOSTS                   1082
#define IDC_N_MENTIONS                  1083
#define IDC_ATTBBC_OFF                  1084
#define IDC_ATTBBC_BASIC                1085
#define IDC_ATTBBC_ADV                  1086
#define IDC_BBC_ATT_NEWS                1087
#define IDC_USENOSTDURLENCODE           1088
#define IDC_ED_INT_INVIS                1089
#define IDC_SPIN_INT_INVIS              1090
#define IDC_ED_MSG                      1091
#define IDC_ED_URL                      1092
#define IDC_ONLY_FRIENDS                1093
#define IDC_ST_WARNING                  1095
#define IDC_NOTIF_MARK_VIEWED           1096
#define IDC_N_INVITES                   1097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
