#define BUILD_NUM 11
#define BUILD_NUM_STR  "11"

#define COREVERSION_NUM 0, 9, 0, 
#define COREVERSION_NUM_STR  "0, 9, 0 "

#define MINIMAL_COREVERSION_NUM PLUGIN_MAKE_VERSION(0, 9, 0, 0)
#define MINIMAL_COREVERSION 0, 9, 0, 0
#define MINIMAL_COREVERSION_STR "0, 9, 0, 0 "

#define FILE_VERSION	COREVERSION_NUM BUILD_NUM
#define FILE_VERSION_STR COREVERSION_NUM_STR " build " BUILD_NUM_STR	" " 

#define PRODUCT_VERSION	FILE_VERSION
#define PRODUCT_VERSION_STR	FILE_VERSION_STR
