//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDI_MRA                         101
#define IDD_OPT                         102
#define IDD_OPT_CONNECTIONS             102
#define IDI_INBOX                       103
#define IDD_DIALOG_SELECT_EMAIL         103
#define IDI_PROFILE                     104
#define IDI_AUTHRUGUEST                 106
#define IDI_AUTHGRANT                   107
#define IDD_MRAADVANCEDSEARCH           108
#define IDD_OPTAVATRS                   109
#define IDD_OPT_AVATRS                  109
#define IDI_MAIL_NOTIFY                 111
#define IDI_MRA_WEB_SEARCH              112
#define IDI_MRA_POSTCARD                114
#define IDI_MRA_PHOTO                   117
#define IDI_DELETED                     118
#define IDI_MRA_CHAT                    120
#define IDI_MRA_PHONE                   122
#define IDD_OPT_FILES                   126
#define IDD_OPT_ACCOUNT                 127
#define IDD_OPT_POPUPS                  128
#define IDD_MRAACCOUNT                  129
#define IDI_ICON1                       130
#define IDI_MRA_ALARM                   130
#define IDI_MRA_VIDEO                   132
#define IDI_MRA_ANSWERS                 133
#define IDI_MRA_WORLD                   134
#define IDD_MINIBLOG                    135
#define IDI_BLOGSTATUS                  137
#define IDD_SETXSTATUS                  256
#define IDC_GROUPCONFIG                 1000
#define IDC_GROUPCONFIG2                1001
#define IDC_GROUPMAIN                   1002
#define IDC_REGISTER                    1002
#define IDC_SLOWSEND                    1003
#define IDC_RETURN_ABC_PATH             1004
#define IDC_FILE_SEND_HIDE_MY_ADDRESSES 1004
#define IDC_RTF_SEND_ENABLE             1005
#define IDC_RTF_BGCOLOUR                1006
#define IDC_CVT_SMILES_ON_SEND_TEXT     1007
#define IDC_CVT_SMILES_TO_TAGS          1007
#define IDC_DELETE_AVT_ON_CONTACT_DELETE 1008
#define IDC_FILE_SEND_ADD_EXTRA_ADDRESS 1008
#define IDC_INCREMENTAL_NEW_MAIL_NOTIFY 1008
#define IDC_ENABLE                      1009
#define IDC_AUTO_ADD_CONTACTS_TO_SERVER 1009
#define IDC_FILE_SEND_NOOUTCONNECTIONONSEND 1010
#define IDC_AUTO_AUTH_REQ_ON_LOGON      1010
#define IDC_KEEPALIVE                   1011
#define IDC_FILE_SEND_NOOUTCONNECTIONONRECEIVE 1011
#define IDC_LIST_EMAILS                 1011
#define IDC_TRAYICON_NEW_MAIL_NOTIFY    1011
#define IDC_FILE_SEND_IGNORYADDITIONALPORTS 1012
#define IDC_RTF_RECEIVE_ENABLE          1012
#define IDC_DELETE_SPAMBOT_CONTACT      1013
#define IDC_RTF_SEND_SMART              1013
#define IDC_COMBO_PHONE                 1014
#define IDC_TRAYICON_NEW_MAIL_NOTIFY_CLICK_TO_INBOX 1014
#define IDC_FILE_SEND_ENABLE_DIRECT_CONN 1014
#define IDC_EDIT_TEXT                   1015
#define IDC_FILE_SEND_ENABLE_MRIMPROXY_CONS 1015
#define IDC_AUTO_AUTH_GRAND_IN_CLIST    1015
#define IDC_AUTO_AUTH_GRAND_NEW_USERS   1016
#define IDC_AUTO_AUTH_ON_WEB_SVCS	1017
#define IDC_OPTIONSTAB                  1017
#define IDC_NEW_ACCOUNT_LINK            1018
#define IDC_LOOKUPLINK                  1019
#define IDC_PASSWORD                    1020
#define IDC_BUTTON_DEFAULT              1020
#define IDC_LOGIN                       1022
#define IDC_FILE_SEND_BLOCK_SIZE        1022
#define IDC_COMBO_POPUP_TYPE            1023
#define IDC_CHK_ENABLE                  1024
#define IDC_CHK_USE_WIN_COLORS          1025
#define IDC_POPUP_BACKCOLOR             1026
#define IDC_POPUP_TEXTCOLOR             1027
#define IDC_POPUP_TIMEOUT               1028
#define IDC_PREVIEW                     1029
#define IDC_USE_KEEPALIVE_CONN          1030
#define IDC_BUTTON_FONT                 1031
#define IDC_EMAIL_USER                  1048
#define IDC_EMAIL_DOMAIN                1049
#define IDC_NICK                        1053
#define IDC_GENDER                      1060
#define IDC_STATE                       1061
#define IDC_ZODIAK                      1062
#define IDC_COUNTRY                     1063
#define IDC_CITY2                       1064
#define IDC_CITY                        1064
#define IDC_XTITLE                      1065
#define IDC_XMSG                        1066
#define IDC_USER_BLOG_STATUS_MSG        1072
#define IDC_MSG_TO_SEND                 1073
#define IDC_CHK_NOTIFY                  1074
#define IDC_STATIC_WRITED_TIME          1075
#define IDC_STATIC_CHARS_COUNTER        1076
#define IDC_CHECK1                      1077
#define IDC_CHK_REMEMBER                1077
#define IDC_SERVER                      1171
#define IDC_SERVERPORT                  1174
#define IDC_UPD_CHECK_INTERVAL          1175
#define IDC_FILE_SEND_EXTRA_ADDRESS     1175
#define IDC_FIRSTNAME                   1224
#define IDC_LASTNAME                    1225
#define IDC_AGERANGE_FROM               1410
#define IDC_AGERANGE_TO                 1411
#define IDC_BIRTHDAY_DAY                1412
#define IDC_BIRTHDAY_MONTH              1413
#define IDC_BIRTHDAY_YEAR               1414
#define IDC_ONLINEONLY                  1430
#define IDC_SUMMARYGROUP                1434
#define IDC_LOCATIONGROUP               1436
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
