//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\Miranda NG Git_orig_commit\miranda-ng\plugins\NewStory\res\resource.rc
//
#define IDD_HISTORY                     101
#define IDI_NEWSTORY                    102
#define IDD_SEARCH                      105
#define IDD_OPTIONS                     107
#define IDR_CONTEXT                     109
#define IDR_EXPORT                      110
#define IDR_FILTER                      111
#define IDD_MESSAGE                     112
#define IDR_POPUPS                      113
#define IDR_ACCEL                       114
#define IDD_PASSWORD                    116
#define IDD_CALENDARTOOL                118
#define IDD_CHANGEPASSWORD              119
#define IDD_OPT_TEMPLATES               121
#define IDD_FILTERMODE                  123
#define IDD_OPT_GENERAL                 124
#define IDI_FOLDER                      125
#define IDD_OPT_PASSWORDS               126
#define ICO_NEWSTORY                    127
#define ICO_USERINFO                    128
#define ICO_USERMENU                    129
#define ICO_SEARCH                      130
#define ICO_OPTIONS                     131
#define ICO_FILTER                      132
#define ICO_EXPORT                      133
#define ICO_COPY                        134
#define ICO_SENDMSG                     135
#define ICO_CLOSE                       136
#define ICO_MSGIN                       137
#define ICO_MSGOUT                      138
#define ICO_SIGNIN                      139
#define ICO_FILE                        140
#define ICO_URL                         141
#define ICO_UNKNOWN                     142
#define ICO_FINDPREV                    143
#define ICO_FINDNEXT                    144
#define ICO_NOPASSWORD                  145
#define ICO_PASSWORD                    146
#define ICO_CALENDAR                    147
#define ICO_TPLGROUP                    148
#define ICO_RESET                       149
#define ICO_PREVIEW                     150
#define ICO_VARHELP                     151
#define ICO_SAVEPASS                    152
#define IDC_CUSTOM1                     1000
#define IDC_GPREVIEW                    1000
#define IDC_LIST                        1000
#define IDC_ITEMS2                      1000
#define IDC_PROGRESS                    1002
#define IDC_EDIT1                       1003
#define IDC_SEARCHTEXT                  1003
#define IDC_CUSTOM3                     1009
#define IDC_CLOSE                       1009
#define IDC_MESSAGE                     1010
#define IDC_USERINFO                    1011
#define IDC_USERMENU                    1012
#define IDC_TEXT                        1012
#define IDC_SEARCH                      1013
#define IDC_USER                        1013
#define IDC_USERNICK                    1013
#define IDC_EXPORT                      1014
#define IDC_COPY                        1015
#define IDC_FILTER                      1016
#define IDC_FINDNEXT                    1017
#define IDC_LOGOPTIONS                  1018
#define IDC_FINDPREV                    1019
#define IDC_SEARCHICON                  1020
#define IDC_SECURITY                    1021
#define IDC_MSGICON                     1022
#define IDC_DATEPOPUP                   1022
#define IDC_ICO_MESSAGES_IN             1023
#define IDC_ICO_MESSAGES_OUT            1024
#define IDC_ICO_FILES_IN                1025
#define IDC_ICO_FILES_OUT               1026
#define IDC_ICO_TOTAL_IN                1027
#define IDC_EDIT2                       1028
#define IDC_PASSWORD                    1028
#define IDC_TPL_LOGTEXT                 1028
#define IDC_PREVIEW                     1028
#define IDC_CHANGEPASS2                 1028
#define IDC_ICO_TOTAL_OUT               1028
#define IDC_PASSWORD2                   1029
#define IDC_ICO_URLS_IN                 1029
#define IDC_PASSWORD3                   1030
#define IDC_ICO_URLS_OUT                1030
#define IDC_TABS                        1032
#define IDC_TAB                         1032
#define IDC_TIMETREE                    1035
#define IDC_LOADING                     1036
#define IDC_PROGRESS1                   1037
#define IDC_COMBO1                      1038
#define IDC_CHECK2                      1040
#define IDC_CHECK3                      1041
#define IDC_MONTHCALENDAR1              1044
#define IDC_USERLIST                    1049
#define IDC_TPL_WINDOW                  1050
#define IDC_UNLOCK                      1055
#define IDC_TEMPLATES                   1057
#define IDC_VARHELP                     1058
#define IDC_CHK_IN                      1059
#define IDC_VARHELP2                    1059
#define IDC_SAVEPASSWORD                1059
#define IDC_DISCARD                     1060
#define IDC_CHK_FILE                    1060
#define IDC_CHK_URL                     1061
#define IDC_SAVE                        1061
#define IDC_UPDATEPREVIEW               1061
#define IDC_CHK_STATUS                  1062
#define IDC_CHK_OTHER                   1063
#define IDC_CHK_AUTOFILTER              1064
#define IDC_DATETIMEPICKER1             1065
#define IDC_DATETIMEPICKER2             1066
#define IDC_CHK_OUT                     1067
#define IDC_CHK_MESSAGES                1068
#define IDC_EDITTEMPLATE                1069
#define IDC_EDIT3                       1071
#define IDC_CHANGEPASS3                 1071
#define IDC_ICO_NOPASSWORD              1072
#define IDC_ICO_PASSWORD                1073
#define IDC_CHANGEPASS                  1074
#define IDC_BUTTON1                     1076
#define IDC_ICO_MESSAGES                1078
#define IDC_ICO_FILES                   1079
#define IDC_ICO_URLS                    1080
#define IDC_ICO_TOTAL                   1081
#define IDC_TXT_MESSAGES                1090
#define IDC_TXT_FILES                   1091
#define IDC_TXT_TOTAL                   1092
#define IDC_IB_SEPARATOR                1093
#define IDC_TXT_URLS                    1094
#define IDC_TXT_MESSAGES_IN             1095
#define IDC_TXT_FILES_IN                1096
#define IDC_TXT_TOTAL_IN                1097
#define IDC_TXT_MESSAGES_OUT            1098
#define IDC_TXT_FILES_OUT               1099
#define IDC_TXT_TOTAL_OUT               1100
#define IDC_TXT_URLS_IN                 1101
#define IDC_TXT_URLS_OUT                1102
#define IDC_DATE_FROM                   1103
#define IDC_DATE_TO                     1104
#define IDC_CHK_DATE_FROM               1105
#define IDC_CHK_DATE_TO                 1106
#define ID_EXPOTASHTML                  40001
#define ID_EXPORTASXML                  40002
#define ID_INCOMINGONLY                 40003
#define IDD_FILTER_INCOMING             40003
#define ID_FILTER_INCOMING              40003
#define ID_OUTGOINGONLY                 40004
#define IDD_FILTER_OUTGOING             40004
#define ID_FILTER_OUTGOING              40004
#define ID_SHOWMESSAGES                 40006
#define IDD_FILTER_MESSAGES             40006
#define ID_FILTER_MESSAGES              40006
#define ID_SHOWFILES                    40008
#define IDD_FILTER_FILES                40008
#define ID_FILTER_FILES                 40008
#define ID_SHOWURLS                     40009
#define IDD_FILTER_URLS                 40009
#define ID_FILTER_URLS                  40009
#define ID_SHOWSIGININOUTMESSAGES       40010
#define IDD_FILTER_STATUS               40010
#define ID_FILTER_STATUS                40010
#define ID_SHOWOTHEREVENTS              40011
#define IDD_FILTER_OTHER                40011
#define ID_FILTER_OTHER                 40011
#define ID_CONTEXT_COPY                 40012
#define ID_EXPORT_EXPORTASTEXT          40013
#define ID_EXPORT_EXPORTASHTML          40014
#define ID_EXPORT_EXPORTASXML           40015
#define ID_EXPORT_EXPORTALLASTEXT       40017
#define ID_EXPORT_EXPORTALLASHTML       40018
#define ID_EXPORT_EXPORTALLASXML        40019
#define IDA_COPY                        40020
#define IDA_SEARCH                      40021
#define IDD_FILTER_AUTO                 40022
#define ID_FILTER_AUTO                  40022
#define ID_LOGOPTIONS_TEMPLATES         40023
#define ID_LOGOPTIONS_NEWSTORYOPTIONS   40024
#define ID_LOGOPTIONS_OPTIONS           40024
#define ID_CONTEXT_DELETE               40026
#define ID_CONTEXT_SELECTALL            40027
#define ID_CONTEXT_CANCEL               40028
#define ID_EXPORT_SAVEAS                40029
#define ID_EXPORT_SAVESELECTEDAS        40031
#define ID_LOGOPTIONS_SHOWTIMETREE      40032
#define ID_SECURITY_LOCK                40033
#define ID_SECURITY_CHANGEPASSWORD      40034
#define ID_FILTER_SHOWALLEVENTS         40036
#define ID_FILTER_SHOWINCOMINGEVENTSONLY 40037
#define ID_FILTER_SHOWOUTGOINGEVENTSONLY 40038
#define ID_FILTER_USECUSTOMFILTER       40039
#define ID_LOGOPTIONS_PASSWORDS         40040
#define IDC_CONTEXT_EXPORT              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40041
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
