{$IFNDEF INPACKAGE}
type
  TKOLProject = Pointer;
  TKOLApplet = Pointer;
  TKOLForm = Pointer;
  TKOLDataModule = Pointer;
  TKOLFrame = Pointer;
  TKOLMDIClient = PControl;
  TKOLMDIChild = Pointer;
  TKOLService = Pointer;

  TKOLButton = PControl;
  TKOLLabel = PControl;
  TKOLLabelEffect = PControl;
  TKOLPanel = PControl;
  TKOLSplitter = PControl;
  TKOLGradientPanel = PControl;
  TKOLBitBtn = PControl;
  TKOLGroupBox = PControl;
  TKOLCheckBox = PControl;
  TKOLRadioBox = PControl;
  TKOLEditBox = PControl;
  TKOLMemo = PControl;
  TKOLListBox = PControl;
  TKOLComboBox = PControl;
  TKOLPaintBox = PControl;
  TKOLImageShow = PControl;

  TKOLRichEdit = PControl;
  TKOLProgressBar = PControl;
  TKOLListView = PControl;
  TKOLTreeView = PControl;
  TKOLToolbar = PControl;
  TKOLTabControl = PControl;
  TTabPage = PControl;
  TKOLScrollBox = PControl;
  TKOLDateTimePicker = PControl;

  TKOLTimer = PTimer;
  TKOLThread = PThread;
  TKOLImageList = PImageList;
  TKOLMainMenu = PMenu;
  TKOLPopupMenu = PMenu;
  TKOLOpenSaveDialog = POpenSaveDialog;
  //TKOLOpenDirDialog = POpenDirDialog;
  TKOLTrayIcon = PTrayIcon;
  TKOLColorDialog = PColorDialog;
  //TKOLActionList = PActionList;
  //TKOLAction = PAction;
  TKOLScrollBar = PControl;
{$ENDIF}