{resource constants}
const
  IDD_UA = 1031;

  IDC_UA_ACTIONLIST  = 1025;
  IDC_UA_PLACELIST   = 1026;

  // menu settings
  IDC_UA_POPUPT      = 1030;
  IDC_UA_POPUPV      = 1031;

  IDC_UA_VARNAMEST   = 1032;
  IDC_UA_VARNAMESV   = 1033;

  IDC_UA_SHOWVART    = 1034;
  IDC_UA_SHOWVARV    = 1035;

  IDC_UA_BLOCK       = 1040;
  IDC_UA_SEPARATE    = 1041;
  IDC_UA_NOTRANSLATE = 1042;
  IDC_UA_MENU        = 1043;

  // toolbar settings
  IDC_UA_TTNORMALT   = 2028;
  IDC_UA_TTNORMALV   = 2029;
  IDC_UA_TTPRESSEDT  = 2030;
  IDC_UA_TTPRESSEDV  = 2031;
  
  // common
  IDC_UA_COMMON      = 2000;
  IDC_UA_TWOSTATE    = 2001;
  IDC_UA_SAVSTATE    = 2002;

  IDC_UA_GLOBAL      = 2003;

  IDI_ACTION = 101;
