//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ..\..\res\resource.rc
//
#define IDD_TEMPLATEEDIT                1
#define IDD_USERPREFS                   2
#define IDOK2                           2
#define IDD_USERPREFS1                  3
#define IDD_TABCONFIG                   4
#define IDD_ABOUT                       7
#define IDD_INFOPANEL                   8
#define IDC_TESTVALUE                   10
#define IDB_BITMAP1                     10
#define IDB_LOGO                        10
#define IDD_USERPREFS_FRAME             11
#define IDR_SKIN1                       13
#define IDR_SKIN_AERO                   14
#define IDR_SKIN_AERO_GLOW              15
#define IDD_SENDLATER_QMGR              15
#define IDR_SKIN_AERO_SWITCHBAR         16
#define IDD_WARNING                     16
#define IDR_SKIN_LOGO                   20
#define IDI_IMGOPEN                     102
#define IDI_IMGCLOSE                    103
#define IDI_FEATURE_DISABLED            104
#define IDI_FEATURE_ENABLED             105
#define IDR_CONTEXT                     180
#define IDM_PASTEFORMATTED              181
#define IDM_CUT                         182
#define IDM_PASTE                       183
#define IDD_MSGSPLITNEW                 184
#define IDM_QUOTE                       185
#define IDM_COPY                        186
#define IDM_COPYALL                     187
#define IDM_SELECTALL                   188
#define IDM_CLEAR                       189
#define IDM_OPENNEW                     190
#define IDM_OPENEXISTING                191
#define IDM_COPYLINK                    192
#define IDM_STICKY                      193
#define IDM_REPORTALWAY                 194
#define IDM_REPORTNEVER                 195
#define IDM_DONTREPORTMINIMIZED         196
#define IDD_OPT_MSGDLG                  243
#define IDD_OPT_MSGLOG                  245
#define IDD_OPT_MSGTYPE                 275
#define IDD_MSGCONTAINER                276
#define IDD_OPT_TABBEDMSG               277
#define IDD_POPUP_OPT                   278
#define IDR_ACCEL                       283
#define IDR_TABCONTEXT                  286
#define IDD_MODERNOPTS                  288
#define IDD_SELECTCONTAINER             299
#define IDD_CONTAINEROPTIONS            300
#define IDD_OPT_CONTAINERS              301
#define IDD_OPT_TOOLBAR                 304
#define IDR_MENUBAR                     308
#define IDD_CHOOSESTATUSMODES           310
#define IDD_SKINTABDIALOG               312
#define IDD_OPT_SKIN                    313
#define IDD_OPTIONS_PLUS                333
#define IDC_QMGR_REMOVE                 1000
#define IDC_EXCEPTION_DETAILS           1000
#define IDC_UNLOAD                      1000
#define IDC_READNEXT                    1000
#define IDC_MINIMIZE                    1000
#define IDC_COPY_EXCEPTION              1001
#define IDC_RELOADSKIN                  1001
#define IDC_APPLY                       1001
#define IDC_MAXIMIZE                    1001
#define IDC_SKINFILE                    1002
#define IDC_MESSAGE                     1002
#define IDC_THEMEEXPORT                 1002
#define IDC_HYPERLINKHAND               1003
#define IDC_THEMEEXPORT2                1003
#define IDC_THEMEIMPORT                 1003
#define IDC_EXPORT                      1005
#define IDC_IMPORT                      1006
#define IDC_PREVIEW                     1006
#define IDC_LOG                         1006
#define IDC_CHKNOTIFY_MESSAGE           1007
#define IDC_FASTGRADIENT                1008
#define IDC_CHKNOTIFY_URL               1009
#define IDC_USESKIN                     1011
#define IDC_AUTOCLOSE                   1012
#define IDC_CHKNOTIFY_OTHER             1013
#define IDC_AUTOMIN                     1014
#define IDC_CHKMENUITEM                 1015
#define IDC_TIME                        1016
#define IDC_CHKDISABLE                  1017
#define IDC_SENDMENU                    1018
#define IDC_CHKACTL_DISMISS             1019
#define IDC_QUOTE                       1020
#define IDC_CHKACTL_OPEN                1021
#define IDC_NAME                        1022
#define IDC_CHKACTL_REMOVE              1023
#define IDC_INFOPANELMENU               1023
#define IDC_CLOSE                       1024
#define IDC_SAVE                        1025
#define IDC_CHKACTR_DISMISS             1026
#define IDC_CHKACTR_OPEN                1028
#define IDC_CONTACTPIC                  1029
#define IDC_ST_ENTERMSG                 1031
#define IDC_PANELNICK                   1032
#define IDC_CHKWINDOWCHECK              1032
#define IDC_PANELUIN                    1033
#define IDC_CHKPREVIEW                  1034
#define IDC_CHKINFINITE                 1035
#define IDC_PANELSTATUS                 1036
#define IDC_SPLITTER                    1037
#define IDC_CHKDEFAULTCOL_MESSAGE       1038
#define IDC_CHKDEFAULTCOL_MUC           1039
#define IDC_CHKDEFAULTCOL_ERR           1040
#define IDC_COLBACK_MESSAGE             1041
#define IDC_COLTEXT_MESSAGE             1042
#define IDC_COLTEXT_MUC                 1043
#define IDC_COLBACK_MUC                 1044
#define IDC_COLTEXT_ERR                 1045
#define IDC_COLBACK_ERR                 1046
#define IDC_SHOWNAMES                   1047
#define IDC_CHKDEFAULTCOL_OTHERS        1050
#define IDC_COLBACK_OTHERS              1051
#define IDC_CLOSEONREPLY                1052
#define IDC_COLTEXT_OTHERS              1053
#define IDC_SHOWFILES                   1054
#define IDC_MERGEPOPUP                  1056
#define IDC_CHKINFINITE_MESSAGE         1057
#define IDC_CHKMERGEPOPUP               1058
#define IDC_IMGTAG                      1058
#define IDC_SHOWURLS                    1059
#define IDC_ANIAVATAR                   1059
#define IDC_DELAY_MESSAGE               1060
#define IDC_SCROLLFIX                   1060
#define IDC_CLIENTINSTATBAR             1061
#define IDC_TYPINGSOUNDS                1062
#define IDC_OFFLINEMULTI                1063
#define IDC_CLIENTINSTATBAR2            1063
#define IDC_ICONWARNINGS                1063
#define IDC_AUTOCLOSEV2                 1064
#define IDC_RESTART                     1065
#define IDC_DELAY_OTHERS                1066
#define IDC_CLIST                       1067
#define IDC_DELAY_MUC                   1067
#define IDC_NUMBERMSG                   1068
#define IDC_MULTISPLITTER               1069
#define IDC_CHKSHOWDATE                 1070
#define IDC_SAVEPERCONTACT              1071
#define IDC_CHKSHOWTIME                 1072
#define IDC_CHKSHOWHEADERS              1073
#define IDC_LOADCOUNTN                  1074
#define IDC_RDNEW                       1075
#define IDC_LOADCOUNTSPIN               1076
#define IDC_RDOLD                       1077
#define IDC_SHOWINFOLINE                1078
#define IDC_LBNUMBERMSG                 1079
#define IDC_SHOWBUTTONLINE              1080
#define IDC_CHKINFINITE_URL             1081
#define IDC_LOADUNREAD                  1082
#define IDC_SENDONENTER                 1083
#define IDC_CHKINFINITE_FILE            1084
#define IDC_LOADCOUNT                   1085
#define IDC_SENDONDBLENTER              1086
#define IDC_CHKINFINITE_OTHERS          1087
#define IDC_LOADTIMEN                   1088
#define IDC_LOADTIMESPIN                1089
#define IDC_LOADTIME                    1090
#define IDC_CMDEDITHEADERS              1091
#define IDC_TRIM                        1091
#define IDC_FONTLIST                    1092
#define IDC_TRIMSPIN                    1092
#define IDC_USEOSD                      1093
#define IDC_CHOOSEFONT                  1094
#define IDC_CHKACTTE_DISMISS            1095
#define IDC_CHKACTTE_OPEN               1096
#define IDC_STMINSOLD                   1097
#define IDC_CHKACTTE_REMOVE             1098
#define IDC_NORSS                       1099
#define IDC_DETAILS                     1100
#define IDC_ADD                         1101
#define IDC_DELAY_ERR                   1102
#define IDC_RTL                         1103
#define IDC_PIC                         1104
#define IDC_SMILEYBTN                   1105
#define IDC_FONTBOLD                    1106
#define IDC_FONTITALIC                  1107
#define IDC_FONTUNDERLINE               1108
#define IDC_FONTFACE                    1110
#define IDC_HISTORY                     1111
#define IDC_CANCELADD                   1112
#define IDC_FONTSTRIKEOUT               1113
#define IDC_MATH_BKGCOLOUR              1124
#define IDC_FONTCOLOR                   1127
#define IDC_LOGFROZENTEXT               1128
#define IDC_FONTCOLOUR                  1128
#define IDC_STSIZETEXT                  1135
#define IDC_STCOLOURTEXT                1136
#define IDC_PRESETSPLIT                 1137
#define IDC_PRESETSINGLE                1138
#define IDC_STMSGLOGGROUP               1139
#define IDC_PROTOCOL                    1140
#define IDC_STMSGLOGGROUP2              1140
#define IDC_STMSGLOGGROUP3              1141
#define IDC_PROTOMENU                   1141
#define IDC_TYPING                      1143
#define IDC_TOGGLETOOLBAR               1144
#define IDC_ERRORTEXT                   1145
#define IDC_SHOWNOTIFY                  1146
#define IDC_STATUSWIN                   1147
#define IDC_TYPEFLASHWIN                1148
#define IDC_CHARCOUNT                   1149
#define IDC_TYPENOWIN                   1150
#define IDC_TYPEWIN                     1151
#define IDC_CASCADE                     1151
#define IDC_SECONDS                     1152
#define IDC_NOTIFYTRAY                  1153
#define IDC_NOTIFYBALLOON               1154
#define IDC_NOTIFYBALLOON2              1155
#define IDC_NOTIFYPOPUP                 1155
#define IDC_MathSubst                   1156
#define IDC_INDENT                      1157
#define IDC_INDENTAMOUNT                1158
#define IDC_MSGTABS                     1159
#define IDC_SIDEBARUP                   1160
#define IDC_SIDEBARDOWN                 1161
#define IDC_WARNONCLOSE                 1162
#define IDC_CUT_TABTITLE                1163
#define IDC_CUT_TITLEMAX                1164
#define IDC_SHOWTABTIP                  1165
#define IDC_SHOWSTATUSONTAB             1166
#define IDC_SWAPTIMESTAMP               1167
#define IDC_AUTOCREATETABS              1168
#define IDC_LOCALTIME                   1169
#define IDC_O_HIDETITLE                 1170
#define IDC_STICKY                      1171
#define IDC_LOGSTATUS                   1172
#define IDC_DEBUGPOPUPS                 1173
#define IDC_CONTAINERGROUPMODE          1174
#define IDC_SELFTYPING                  1175
#define IDC_LOGHOTKEYS                  1176
#define IDC_NOTITLE                     1177
#define IDC_TABPADDING                  1178
#define IDC_PADSPIN                     1179
#define IDC_HTABPADDING                 1179
#define IDC_BOTTOMTABADJUST             1180
#define IDC_POPUPCONTAINER              1181
#define IDC_TABWIDTH                    1181
#define IDC_PRIVATESPLITTER             1182
#define IDC_CNTPRIVATE                  1182
#define IDC_NEWSPLITLAYOUT              1183
#define IDC_O_NOTABS                    1184
#define IDC_DONTREPORTUNFOCUSED         1185
#define IDC_ESC_MINIMIZE                1186
#define IDC_USEDIVIDERS                 1187
#define IDC_DRAWGRID                    1188
#define IDC_LIMITTABS                   1189
#define IDC_WANTVERTICALGRID            1190
#define IDC_LIMITPREVIEW                1191
#define IDC_AUTOLOCALE                  1192
#define IDC_MUC_LOGCOLORS               1192
#define IDC_DONTREPORTUNFOCUSED2        1193
#define IDC_GCHECK                      1194
#define IDC_HIDETAB                     1195
#define IDC_O_DONTREPORT                1196
#define IDC_USEDEFERRED                 1197
#define IDC_AUTOSWITCHTABS              1198
#define IDC_USEINDIVIDUALBKG            1199
#define IDC_SINGLEWINDOWMODE            1200
#define IDC_FLATBUTTONS                 1201
#define IDC_O_STICKY                    1202
#define IDC_DIVIDERSUSEPOPUPCONFIG      1203
#define IDC_FLASHFOREVER                1205
#define IDC_DONTFLASH                   1206
#define IDC_O_FLASHDEFAULT              1208
#define IDC_FLASHDEFAULT                1209
#define IDC_DEFAULTCONTAINERMODE        1210
#define IDC_ALWAYS                      1211
#define IDC_DONTREPORTFOCUSED2          1212
#define IDC_TRANSPARENCY                1215
#define IDC_PANELSPLITTER               1216
#define IDC_AUTOCREATECONTAINER         1216
#define IDC_LIMITAVATARS                1217
#define IDC_DONTREPORT                  1219
#define IDC_SPIN1                       1220
#define IDC_CNTLIST                     1221
#define IDC_SPIN3                       1221
#define IDC_NEWCONTAINER                1222
#define IDC_TABWIDTHSPIN                1222
#define IDC_UPDATEPREVIEW               1223
#define IDC_MODIFY                      1223
#define IDC_SAVESIZEASGLOBAL            1223
#define IDC_REVERTGLOBAL                1223
#define IDC_CREATENEW                   1224
#define IDC_RTLMODIFY                   1224
#define IDC_RESETALLTEMPLATES           1224
#define IDC_SENDLATER                   1226
#define IDC_RETRY                       1227
#define IDC_SETUPAUTOCREATEMODES        1228
#define IDC_POPUPSTATUSMODES            1229
#define IDC_DELETECONTAINER             1230
#define IDC_CANCELSEND                  1231
#define IDC_O_FLASHALWAYS               1232
#define IDC_RENAMECONTAINER             1233
#define IDC_RETRY2                      1234
#define IDC_MSGSENDLATER                1235
#define IDC_O_FLASHNEVER                1236
#define IDC_NEWCONTAINERNAME            1237
#define IDC_O_TITLENEVER                1238
#define IDC_O_TITLEFRONT                1239
#define IDC_O_TITLESUFFIX               1240
#define IDC_TRANSPARENCY_ACTIVE         1241
#define IDC_TRANSPARENCY_INACTIVE       1242
#define IDC_INDENTSPIN                  1250
#define IDC_TABBORDER                   1251
#define IDC_SPIN2                       1252
#define IDC_TABBORDERSPIN               1253
#define IDC_FLASHINTERVALSPIN           1254
#define IDC_HIDESBAR                    1255
#define IDC_TABBORDEROUTER              1256
#define IDC_TABBORDEROUTERRIGHT         1257
#define IDC_TABBORDERSPINOUTER          1258
#define IDC_ALWAYSPOPUPSINACTIVE        1259
#define IDC_TABBORDERSPINOUTER2         1259
#define IDC_BOTTOMTABADJUSTSPIN         1259
#define IDC_HISTORYSIZE                 1260
#define IDC_TABBORDERSPINOUTERRIGHT     1260
#define IDC_HISTORYSIZESPIN             1261
#define IDC_TABBORDEROUTERTOP           1261
#define IDC_HOTKEYSAREGLOBAL            1262
#define IDC_TABBORDERSPINOUTERTOP       1262
#define IDC_SINGLEROWTAB                1263
#define IDC_STREAMTHREADING             1264
#define IDC_TABBORDEROUTERBOTTOM        1264
#define IDC_IEVIEWMODE                  1265
#define IDC_TABBORDERSPINOUTERBOTTOM    1265
#define IDC_TEXTFORMATTING              1266
#define IDC_AVATARMODE                  1267
#define IDC_OWNAVATARMODE               1268
#define IDC_EMPTYLINEFIX                1272
#define IDC_SPLITTERSTATICEDGES         1273
#define IDC_MAXAVATARHEIGHT             1275
#define IDC_TABLIMIT                    1276
#define IDC_RIGHTINDENT                 1277
#define IDC_AVATARSPIN                  1278
#define IDC_TABLIMITSPIN                1279
#define IDC_SHOWFORMATTING              1280
#define IDC_AGGRESSIVEUPDATE            1283
#define IDC_THINSEPARATORS              1284
#define IDC_RINDENTSPIN                 1285
#define IDC_STATICERRORICON             1286
#define IDC_STATICTEXT                  1287
#define IDC_GROUPMODE                   1288
#define IDC_ANIMATED                    1289
#define IDC_ISFAVORITE                  1289
#define IDC_ALWAYSTRIM                  1289
#define IDC_SKIN_LOADFONTS              1289
#define IDC_PRESERVEAVATARSIZE          1289
#define IDC_UPREFS_SHOWICONS            1289
#define IDC_ALWAYSTRIM2                 1290
#define IDC_SKIN_LOADTEMPLATES          1290
#define IDC_UPREFS_SHOWSYMBOLS          1290
#define IDC_SKIN_LOADTEMPLATES2         1291
#define IDC_UPREFS_INOUTICONS           1291
#define IDC_AVADYNAMIC                  1292
#define IDC_UPREFS_SHOWTIMESTAMP        1292
#define IDC_USESNAPPING                 1293
#define IDC_UPREFS_SHOWSECONDS          1293
#define IDC_UPREFS_SHOWICONS3           1294
#define IDC_UPREFS_SHOWDATES            1294
#define IDC_SENDFORMAT                  1295
#define IDC_UPREFS_LOCALTIME            1295
#define IDC_FLATMSGLOG                  1296
#define IDC_UPREFS_INDENT               1296
#define IDC_UPREFS_GRID                 1297
#define IDC_UPREFS_GROUPING             1298
#define IDC_TOGGLESIDEBAR               1299
#define IDC_CNTNOSTATUSBAR              1299
#define IDC_UPREFS_BBCODE               1299
#define IDC_SECTIONTREE                 1300
#define IDC_UPREFS_RTL                  1301
#define IDC_CHECKICONDLL                1302
#define IDC_UPREFS_LOGSTATUS            1302
#define IDC_ENABLETRAYSUPPORT           1303
#define IDC_UPREFS_LOGSTATUS2           1303
#define IDC_UPREFS_NORMALTEMPLATES      1303
#define IDC_HEADERSHADING               1304
#define IDC_HIDEMENUBAR                 1305
#define IDC_STATICCONTROL               1307
#define IDC_AUTOCLOSETABTIME            1308
#define IDC_AUTOCLOSETABSPIN            1309
#define IDC_SENDONSHIFTENTER            1310
#define IDC_USEGLOBALSIZE               1311
#define IDC_LOADONLYACTUAL              1311
#define IDC_MICROLF                     1312
#define IDC_EVENTAPI                    1313
#define IDC_MINIMIZETOTRAY              1316
#define IDC_DELETETEMP                  1318
#define IDC_FORMATTING                  1319
#define IDC_AUTOSELECTCOPY              1319
#define IDC_HIDETOOLBAR                 1320
#define IDC_FLASHCLIST                  1322
#define IDC_MSGLOGPLUGIN                1323
#define IDC_UIDSTATUSBAR                1324
#define IDC_NRFLASH                     1325
#define IDC_NRFLASHSPIN                 1326
#define IDC_FLASHINTERVAL               1327
#define IDC_USEKBDHOOK                  1328
#define IDC_STATIC111                   1329
#define IDC_TAB1                        1330
#define IDC_ALWAYSFULLWIDTHTOOLBAR      1335
#define IDC_FORMATWHOLEWORDSONLY        1337
#define IDC_STATUSGROUP                 1338
#define IDC_ALLOWSENDBUTTONHIDE         1340
#define IDC_VERTICALMAX                 1341
#define IDC_AUTOSPLITTER                1342
#define IDC_ICONDLLNAME                 1343
#define IDC_SAVETEMPLATE                1344
#define IDC_SELECTICONDLL               1345
#define IDC_RTLDEFAULT                  1346
#define IDC_MATHMODSUPPORT              1348
#define IDC_MESSAGEPREVIEWLIMIT         1349
#define IDC_MESSAGEPREVIEWLIMITSPIN     1350
#define IDC_DELAY_MESSAGE_SPIN          1351
#define IDC_DELAY_MESSAGE_MUC_SPIN      1352
#define IDC_DELAY_ERR_SPIN              1353
#define IDC_MESSAGEPREVIEWLIMITSPIN2    1354
#define IDC_DELAY_OTHERS_SPIN           1354
#define IDC_TEMPLATELIST                1361
#define IDC_EDITTEMPLATE                1362
#define IDC_REVERT                      1363
#define IDC_FORGET                      1364
#define IDC_COLOR1                      1366
#define IDC_COLOR2                      1367
#define IDC_COLOR3                      1368
#define IDC_COLOR4                      1369
#define IDC_COLOR5                      1370
#define IDC_TEMPLOVERRIDE               1372
#define IDC_IGNORETIMEOUTS              1372
#define IDC_RTLTEMPLOVERRIDE            1373
#define IDC_SELECTTHEME                 1376
#define IDC_RELOAD                      1376
#define IDC_LOGOPTIONS                  1377
#define IDC_WINDOWOPTIONS               1378
#define IDC_TRAYCONTAINER               1379
#define IDC_EVENTOPTIONS                1380
#define IDC_VARIABLESHELP               1381
#define IDC_TABMSGOPTIONS               1384
#define IDC_HELPTEXT                    1392
#define IDC_TITLEFORMAT                 1393
#define IDC_THEME                       1394
#define IDC_INFOPANEL                   1395
#define IDC_SUPPORT                     1396
#define IDC_SHOWAVATAR                  1396
#define IDC_NOPOPUPAVAIL                1398
#define IDC_QHTM                        1399
#define IDC_TSLABEL_ACTIVE              1400
#define IDC_TSLABEL_INACTIVE            1401
#define IDC_TITLEBOX                    1402
#define IDC_DESC                        1404
#define IDC_LABEL_PRIVATETHEME          1405
#define IDC_MSGLOGDIDSPLAY              1407
#define IDC_IMCHECK                     1410
#define IDC_CHATCHECK                   1411
#define IDC_CANBEHIDDEN                 1412
#define IDC_BBRESET                     1413
#define IDC_BOTTOMTOOLBAR               1414
#define IDC_BUTTON1                     1415
#define IDC_SEPARATOR                   1415
#define IDC_PLUS_REVERT                 1415
#define IDC_SIZECOMPACT                 1415
#define IDC_RESCANSKIN                  1415
#define IDC_RESETWARNINGS               1415
#define IDC_TIMEOUTSPIN                 1416
#define IDC_SIZENORMAL                  1416
#define IDC_SIZELARGE                   1417
#define IDC_MTN_POPUPMODE               1418
#define IDC_MTN_HELP                    1419
#define IDC_CUT_TITLEMAXSPIN            1420
#define IDC_HELP_CONTAINERS             1421
#define IDC_HELP_GENERAL                1422
#define IDC_CLOSEONESC                  1423
#define IDC_ALWAYSPOPUP                 1424
#define IDC_AEROEFFECT                  1424
#define IDC_CREATEMIN                   1425
#define IDC_ESCMODE                     1425
#define IDC_CHECK5                      1426
#define IDC_TABMODE                     1426
#define IDC_SENDSHIFTENTER              1427
#define IDC_O_TABMODE                   1427
#define IDC_SENDENTER                   1428
#define IDC_O_SBARLAYOUT                1428
#define IDC_PANELVISIBILITY             1428
#define IDC_SENDDBLENTER                1429
#define IDC_SBARLAYOUT                  1429
#define IDC_PANELSIZE                   1429
#define IDC_MINSEND                     1430
#define IDC_IPCONFIG_TITLE              1430
#define IDC_SENDCTRLENTER               1431
#define IDC_NOSYNC                      1431
#define IDC_USETABS                     1432
#define IDC_IPCONFIG_FOOTER             1432
#define IDC_NOOPENPOPUP                 1433
#define IDC_NOOPENNOTIFY                1433
#define IDC_GROUP_SCOPE                 1433
#define IDC_CREATENOACTIVATE            1434
#define IDC_GROUP_SIZE                  1434
#define IDC_NOTIFYMSG                   1435
#define IDC_GROUP_OTHER                 1435
#define IDC_POPUPONCREATE               1436
#define IDC_SIZE_TIP                    1436
#define IDC_IPCONFIG_PRIVATECONTAINER   1437
#define IDC_EXPLAINMSGLOGSETTINGS       1437
#define IDC_NOTIFYFILE                  1438
#define IDC_PANELPICTUREVIS             1438
#define IDC_SKINNAME                    1438
#define IDC_NOTIFYURL                   1439
#define IDC_SKINROOTFOLDER              1439
#define IDC_NOTIFYOTHER                 1440
#define IDC_SKIN_WARN                   1440
#define IDC_QMGR_LIST                   1441
#define IDC_QMGR_FILTER                 1442
#define IDC_TOOLBARTREE                 1444
#define IDC_QMGR_HELP                   1444
#define IDC_QMGR_ERRORPOPUPS            1445
#define IDC_QMGR_ERRORPOPUPS2           1446
#define IDC_QMGR_SUCCESSPOPUPS          1446
#define IDC_BUTTON2                     1446
#define IDC_SKIN_CLOSENOW               1446
#define IDC_CHECK1                      1447
#define IDC_DONTSHOWAGAIN               1447
#define IDC_CAPTION                     1448
#define IDC_WARNTEXT                    1449
#define IDC_WARNICON                    1450
#define IDC_WARNGROUP                   1451
#define IDC_EX_REASON                   1452
#define IDC_FLASHICON                   1489
#define IDC_FLASHLABEL                  1490
#define IDC_STATIC_VISIBILTY            1491
#define IDC_BUTTONTABS                  1492
#define IDC_CLOSEBUTTONONTABS           1493
#define IDC_O_STATIC_AVATAR             1501
#define IDC_O_STATIC_OWNAVATAR          1502
#define IDC_USEAERO                     1531
#define IDC_USEAEROPEEK                 1532
#define IDC_TXT_TITLE1                  1617
#define IDC_TXT_TITLE2                  1618
#define IDC_TXT_TITLE4                  1620
#define IDC_TXT_TITLE5                  1622
#define IDC_TXT_TITLE3                  1623
#define IDC_O_EXPLAINGLOBALNOTIFY       1624
#define IDC_O_AUTOHIDE                  1625
#define IDC_O_AUTOHIDESECONDS           1626
#define IDC_O_ENABLESOUNDS              1701
#define IDC_O_SOUNDSMINIMIZED           1702
#define IDC_O_SOUNDSUNFOCUSED           1703
#define IDC_O_SOUNDSINACTIVE            1704
#define IDC_O_SOUNDSFOCUSED             1705
#define IDC_O_TITLEBARFORMAT            1706
#define IDC_EDIT1                       1720
#define IDC_O_CNTPRIVATE                1901
#define IDC_PLUS_CHECKTREE              2000
#define IDC_COPYRIGHT                   2002
#define IDC_PLUS_HELP                   2004
#define IDC_O_HELP_TITLEFORMAT          2064
#define IDC_OPTIONSTAB                  2111
#define IDC_HEADERBAR                   2397
#define IDC_AVATARSONTASKBAR            2735
#define IDC_TSLABEL_EXPLAINTHEME        3123
#define IDC_TSLABEL_REOPENWARN          3124
#define IDD_OPT_TYPINGNOTIFYPOPUP       30159
#define IDI_START1                      30160
#define IDI_STOP1                       30161
#define IDI_START2                      30162
#define IDI_STOP2                       30163
#define IDI_ENABLED                     30164
#define IDI_DISABLED                    30165
#define IDD_OPT                         30166
#define IDC_START                       30167
#define IDC_STOP                        30168
#define IDI_START3                      30169
#define IDI_STOP3                       30170
#define IDI_START4                      30171
#define IDI_STOP4                       30172
#define IDI_START5                      30173
#define IDI_STOP5                       30174
#define IDI_START6                      30175
#define IDI_STOP6                       30176
#define IDI_START7                      30177
#define IDI_STOP7                       30178
#define IDI_START8                      30179
#define IDI_STOP8                       30180
#define IDI_START9                      30181
#define IDI_STOP9                       30182
#define IDC_ICON1                       31600
#define IDC_ICON2                       31601
#define IDC_TIMEOUT_POPUP2              31602
#define IDC_TIMEOUT_CUSTOM2             31603
#define IDC_TIMEOUT_POPUP               31604
#define IDC_TIMEOUT_PROTO               31605
#define IDC_TIMEOUT_CUSTOM              31606
#define IDC_TIMEOUT_VALUE               31607
#define IDC_TIMEOUT_POPUP3              31608
#define IDC_TIMEOUT_PERMANENT2          31608
#define IDC_USEWINCOLORS                31609
#define IDC_USEPOPUPCOLORS              31610
#define IDC_TYPEON_BG                   31611
#define IDC_TYPEON_TX                   31612
#define IDC_TYPEOFF_BG                  31613
#define IDC_TYPEOFF_TX                  31614
#define IDC_INFO                        31615
#define IDC_INFO2                       31616
#define IDC_WO                          31617
#define IDC_TIMEOUT_PERMANENT1          31618
#define IDC_TIMEOUT_PERMANENT           31618
#define IDC_SHOWMENU                    31619
#define IDC_DISABLED                    31620
#define IDC_ONEPOPUP                    31621
#define IDC_WOCL                        31622
#define IDC_ICONS                       31623
#define IDC_TIMEOUT_VALUE2              31624
#define IDC_PREVIEW_ALL                 31625
#define ID_CLOSETAB_DETACHTAB           40025
#define ID_TABCONTEXT_NEXTTAB           40026
#define ID_TABCONTEXT_ATTACH            40027
#define ID_TABCONTEXT_CLOSECONTAINER    40028
#define ID_TABCONTEXT_PREVTAB           40029
#define ID_CLOSETAB                     40030
#define ID_TABMENU_CLOSETAB             40031
#define ID_TABMENU_CLOSEOTHERTABS       40032
#define ID_TABMENU_SAVELOCALESETTINGFORTHISCONTACT 40034
#define ID_TABMENU_OPENWINDOWSERVICE    40035
#define ID_TABMENU_ATTACHTOCONTAINER    40036
#define ID_Menu                         40037
#define ID_PICMENU_TOGGLEAVATARDISPLAY  40041
#define ID_PICMENU_SETTINGS             40042
#define ID_LOG_CONTAINEROPTIONS         40045
#define ID_TABMENU_CONTAINEROPTIONS     40046
#define ID_LOGMENU_SHOWMESSAGEICONS     40056
#define ID_LOGMENU_LOADDEFAULTS         40057
#define ID_LOGMENU_ALWAYSUSEGLOBALSPLITTERPOSITION 40060
#define ID_LOGMENU_TIMESTAMPSETTINGS    40061
#define ID_LOGMENU_MESSAGELOGFORMATTING 40062
#define ID_TABMENU_CLOSECONTAINER       40063
#define ID_STATUSBARSETTINGS_USEGLOBALDEFAULT 40065
#define ID_STATUSBARSETTINGS_SHOWTHESTATUSBAR 40066
#define ID_STATUSBARSETTINGS_HIDETHESTATUSBAR 40067
#define ID_VIEW_SHOWMENUBAR             40076
#define ID_VIEW_SHOWSTATUSBAR           40077
#define ID_VIEW_SHOWTOOLBAR             40078
#define ID_TOOLBAR_SENDBUTTON           40079
#define ID_TOOLBAR_USERINFORMATION      40080
#define ID_TOOLBAR_EXTRABUTTONS         40081
#define ID_VIEW_SHOWAVATAR              40082
#define ID_VIEW_SHOWTITLEBAR            40083
#define ID_FILE                         40084
#define ID_FILE_CLOSE                   40085
#define ID_FILE_CLOSEMESSAGESESSION     40086
#define ID_VIEW_SHOWMULTISENDCONTACTLIST 40087
#define ID_VIEW_TITLEBAR                40088
#define ID_FILE_CLOSEOTHERMSGSESSIONS   40090
#define ID_VIEW_TABSATBOTTOM            40093
#define ID_VIEW_STAYONTOP               40095
#define ID_HELP                         40096
#define ID_OPTIONS_EVENTPOPUPS          40097
#define ID_EVENTPOPUPS_DISABLEALLEVENTPOPUPS 40098
#define ID_OPTIONS_SOUNDS               40101
#define ID_SOUNDS_DISABLEALLMESSAGESOUNDS 40102
#define ID_SOUNDS_SYNCSOUNDSWITHEVENTPOPUPS 40103
#define ID_SOUNDS_ENABLEALLMESSAGESOUNDS 40104
#define ID_VIEW_FLASHING                40105
#define ID_WINDOWFLASHING_USEDEFAULTVALUES 40106
#define ID_WINDOWFLASHING_FLASHUNTILFOCUSED 40107
#define ID_WINDOWFLASHING_DISABLEFLASHING 40108
#define ID_FILE_SAVEMESSAGELOGAS        40109
#define ID_EVENTPOPUPS_SHOWPOPUPSIFWINDOWISMINIMIZED 40110
#define ID_EVENTPOPUPS_SHOWPOPUPSIFWINDOWISUNFOCUSED 40111
#define ID_EVENTPOPUPS_SHOWPOPUPSFORALLINACTIVESESSIONS 40112
#define ID_OPTIONS_SAVECURRENTWINDOWPOSITIONASDEFAULT 40113
#define ID_CONTAINER_CONTAINEROPTIONS   40114
#define ID_MESSAGELOG                   40115
#define ID_MESSAGELOG_LOGITEMSTOSHOW    40116
#define ID_LOGITEMSTOSHOW_USETHINGRIDLINES 40117
#define ID_MESSAGELOG_TIMESTAMPSETTINGS 40118
#define ID_MESSAGELOG_MESSAGELOGFORMATTING 40119
#define ID_EVENTPOPUPS_SHOWPOPUPSIFWINDOWISFOCUSED 40120
#define ID_LOGMENU_MESSAGELOGSETTINGSAREGLOBAL 40124
#define ID_USER                         40125
#define ID_TITLEBAR_USESTATICCONTAINERICON 40126
#define ID_PICMENU_ALWAYSKEEPTHEBUTTONBARATFULLWIDTH 40134
#define ID_SENDMENU_SENDDEFAULT         40135
#define ID_SENDMENU_SENDTOMULTIPLEUSERS 40136
#define ID_SENDMENU_SENDTOCONTAINER     40137
#define ID_VIEW_VERTICALMAXIMIZE        40143
#define ID_SENDMENU_SENDLATER           40144
#define ID_PROTOMENU_SPLITTER           40145
#define ID_MODE_GLOBAL                  40148
#define ID_MODE_PRIVATE                 40150
#define ID_UNREADMENU_TEST              40151
#define ID_UNREADMENU_FOOBAR            40152
#define ID_UNREADMENU_                  40153
#define ID_TRAYCONTEXT_RECENTSESSIONS   40154
#define ID_RECENTSESSIONS_1             40155
#define ID_TRAYCONTEXT_FAVORITES        40156
#define ID_FAVORITES_1                  40157
#define ID_TRAYCONTEXT_DISABLEALLPOPUPS 40158
#define ID_TRAYCONTEXT_DON              40159
#define ID_TRAYCONTEXT_HIDEALLMESSAGECONTAINERS 40160
#define ID_TRAYCONTEXT_RESTOREALLMESSAGECONTAINERS 40161
#define ID_TRAYCONTEXT_DON40223         40164
#define ID_TRAYCONTEXT_BE               40165
#define ID_RECENTSESSIONS_2             40166
#define ID_PROTOMENU_SENDTEXTFORMATTING 40167
#define ID_SENDTEXTFORMATTING_GLOBAL    40169
#define ID_Menu40228                    40170
#define ID_VIEW_BOTTOMTOOLBAR           40171
#define ID_GLOBAL_OFF                   40172
#define ID_SENDTEXTFORMATTING_THISCONTACT 40173
#define ID_THISCONTACT_GLOBALSETTING    40174
#define ID_THISCONTACT_BBCODE           40175
#define ID_THISCONTACT_OFF              40177
#define ID_GLOBAL_BBCODE                40178
#define ID_PROTOMENU_FAVORITES          40179
#define ID_FAVORITES_ADDCONTACTTOFAVORITES 40180
#define ID_FAVORITES_REMOVECONTACTFROMFAVORITES 40181
#define ID_FILE_HTTP                    40182
#define ID_LOG_FREEZELOG                40183
#define ID_FONT_SIZE                    40186
#define ID_SIZE_LARGE                   40187
#define ID_SIZE_BIGGER                  40188
#define ID_SIZE_NORMAL                  40189
#define ID_SIZE_SMALLER                 40190
#define ID_SIZE_TINY                    40191
#define ID_FONT_RED                     40192
#define ID_FONT_GREEN                   40193
#define ID_FONT_BLUE                    40194
#define ID_FONT_MAGENTA                 40195
#define ID_FONT_YELLOW                  40196
#define ID_FONT_BLACK                   40197
#define ID_FONT_WHITE                   40198
#define ID_FONT_CLEARALLFORMATTING      40199
#define ID_FONT_DEFAULTCOLOR            40200
#define ID_FONT_CYAN                    40201
#define ID_DUMMY_NOMESSAGESESSIONSOPENED 40202
#define ID_SENDMENU_SENDWITHOUTTIMEOUTS 40203
#define ID_TRAYCONTEXT_SHOWTHETRAYICON  40204
#define ID_INFOPANEL_QUICKTOGGLE        40206
#define ID_INFOPANEL_GLOBAL             40207
#define ID_VIEW_INFOPANEL               40208
#define ID_GLOBAL_ENABLED               40208
#define ID_GLOBAL_DISABLED              40209
#define ID_INFOPANEL_THISCONTACT        40210
#define ID_THISCONTACT_USEGLOBALSETTING 40211
#define ID_THISCONTACT_ALWAYSON         40212
#define ID_THISCONTACT_ALWAYSOFF        40213
#define ID_PANELPICMENU_RESETTHEAVATAR  40218
#define ID_EDITOR_PASTEANDSENDIMMEDIATELY 40221
#define ID_HELP_ABOUTTABSRMM            40223
#define ID_SENDMENU_SENDNUDGE           40228
#define ID_SPLITTERCONTEXT_SAVEGLOBALFORALLSESSIONS 40229
#define ID_SPLITTERCONTEXT_SAVEFORTHISCONTACTONLY 40230
#define ID_SPLITTERCONTEXT_FORGETTHECHANGES 40231
#define ID_SPLITTERCONTEXT_SETPOSITIONFORTHISSESSION 40232
#define ID_FONT_CYAN40233               40233
#define ID_TABMENU_LEAVECHATROOM        40234
#define ID_PANELPICMENU_SAVETHISPICTUREAS 40235
#define ID_PICMENU_SAVETHISPICTUREAS    40236
#define ID_TABMENU_SAVETABPOSITION      40239
#define ID_TABMENU_CLEARSAVEDTABPOSITION 40240
#define ID_VISIBILITY_DEFAULT           40241
#define ID_VISIBILITY_HIDDENFORTHISCONTACT 40242
#define ID_VISIBILITY_VISIBLEFORTHISCONTACT 40243
#define ID_LOGMENU_USEADVANCEDTEMPLATE  40244
#define ID_MESSAGELOG_USESIMPLETEMPLATES 40246
#define ID_EDITOR_SHOWMESSAGELENGTHINDICATOR 40248
#define ID_LOGMENU_MESSAGELOGSETTINGS   40250
#define ID_MESSAGELOGSETTINGS_GLOBAL    40251
#define ID_MESSAGELOGSETTINGS_FORTHISCONTACT 40252
#define ID_MESSAGELOG_MESSAGELOGSETTINGS 40253
#define ID_QUEUEMANAGER_MARKSELECTEDFORREMOVAL 40256
#define ID_QUEUEMANAGER_RESETSELECTED   40257
#define ID_QUEUEMANAGER_HOLDSELECTED    40258
#define ID_QUEUEMANAGER_RESUMESELECTED  40259
#define ID_QUEUEMANAGER_CANCELALLMULTISENDJOBS 40260
#define ID_QUEUEMANAGER_COPYMESSAGETOCLIPBOARD 40261

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        17
#define _APS_NEXT_COMMAND_VALUE         40263
#define _APS_NEXT_CONTROL_VALUE         1453
#define _APS_NEXT_SYMED_VALUE           40283
#endif
#endif
