tstring DBGetContactSettingStringPAN(MCONTACT hContact, char const * szModule, char const * szSetting, tstring errorValue);
std::string DBGetContactSettingStringPAN_A(MCONTACT hContact, char const * szModule, char const * szSetting, std::string errorValue);
tstring &GetDlgItemString(HWND hwnd, int id);
std::string &GetProtoList();
bool ProtoInList(std::string proto);
void RemoveExcludedUsers();
tstring variables_parse(tstring const &tstrFormat, MCONTACT hContact);
const int Stricmp(const TCHAR *str, const TCHAR *substr);
//const int Stristr(const TCHAR *str, const TCHAR *substr);
TCHAR* ReqGetText(DBEVENTINFO* dbei);
BOOL IsUrlContains(TCHAR * Str);
void DeleteCListGroupsByName(TCHAR* szGroupName);
tstring GetContactUid(MCONTACT hContact, std::string Protocol);
void LogSpamToFile(MCONTACT hContact, tstring message);
std::string toUTF8(std::wstring str);
std::string toUTF8(std::string str);
std::wstring toUTF16(std::string str);
void HistoryLogFunc(MCONTACT hContact, std::string message);
std::string get_random_num(int length);