//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ..\res\resource.rc
//
#define IDD_OPT_VIEWMODES               1
#define IDD_OPT_SKIN                    4
#define IDD_QUICKIGNORE                 5
#define IDD_OPT                         6
#define IDD_EXCEPTION                   20
#define IDD_OPTIONSDIALOG               101
#define IDD_CLNABOUT                    102
#define IDD_OPT_CLIST                   126
#define IDI_ADDGROUP                    143
#define IDI_CLIST                       146
#define IDI_OPTIONS                     163
#define IDI_DELETE                      175
#define IDI_CLVM_OPTIONS                176
#define IDI_CLVM_SELECT                 177
#define IDR_CONTEXT                     180
#define IDC_DROP                        183
#define IDR_CLISTMENU                   199
#define IDI_BLANK                       200
#define IDI_ADDCONTACT                  210
#define IDC_HYPERLINKHAND               214
#define IDC_DROPUSER                    215
#define IDD_OPT_CLUI                    218
#define IDD_OPT_ICONS                   220
#define IDD_OPT_CLC                     228
#define IDD_OPT_CLCBKG                  230
#define IDD_OPT_SBAR                    234
#define IDD_DELETECONTACT               254
#define IDD_OPT_DSPADVANCED             301
#define IDD_OPT_DSPITEMS                302
#define IDD_OPT_DSPGROUPS               303
#define IDC_ACTIVEPERC                  1000
#define IDC_OPTIONSTAB                  1000
#define IDC_ALWAYSSTATUS                1009
#define IDC_APPLY                       1011
#define IDC_AUTOSIZE                    1013
#define IDC_AUTOSIZEUPWARD              1014
#define IDC_AVATARSIZESPIN              1015
#define IDC_SKINMODE                    1020
#define IDC_FULLTRANSPARENT             1020
#define IDC_STATUSICONSCENTERED         1020
#define IDC_NOTRAYINFOTIPS              1020
#define IDC_SHOWXSTATUS                 1020
#define IDC_AUTOCLEAR                   1020
#define IDC_FLT_SIMPLELAYOUT            1020
#define IDC_USESKIN                     1020
#define IDC_IGN_MSGEVENTS               1020
#define IDC_AUTOCLEARVAL                1021
#define IDC_MARKLOCKED                  1021
#define IDC_IGN_FILEEVENTS              1021
#define IDC_AUTOCLEARSPIN               1022
#define IDC_IGN_URLEVENTS               1022
#define IDC_LASTMSG                     1023
#define IDC_IGN_AUTH                    1023
#define IDC_IGN_ADD                     1024
#define IDC_CONFIRMDELETE               1025
#define IDC_IGN_ONLINE                  1025
#define IDC_IGN_ALWAYSONLINE            1026
#define IDC_IGN_ALWAYSOFFLINE           1027
#define IDC_IGN_PRIORITY                1028
#define IDC_DISABLEGROUPS               1030
#define IDC_DROPSHADOW                  1035
#define IDC_EQUALSELECTION              1040
#define IDC_USEPERPROTO                 1041
#define IDC_OVERRIDEPERSTATUSCOLOR      1042
#define IDC_EVENTAREASUNKEN             1043
#define IDC_SETALLBUTTONSKINNED         1043
#define IDC_EVENTSONTOP                 1044
#define IDC_FASTGRADIENT                1044
#define IDC_DONTSEPARATE                1045
#define IDC_FADEINOUT                   1056
#define IDC_FRAMEGAP                    1064
#define IDC_FRAMEGAPSPIN                1065
#define IDC_CLIPBORDER                  1066
#define IDC_FULLROWSELECT               1067
#define IDC_CLIPBORDERSPIN              1067
#define IDC_LOCALTIME                   1068
#define IDC_CLEFT                       1070
#define IDC_CLEFTSPIN                   1071
#define IDC_GREYOUT                     1072
#define IDC_CTOP                        1072
#define IDC_ONTOP                       1074
#define IDC_SHOWMAINMENU                1075
#define IDC_CLIENTDRAG                  1076
#define IDC_HIDEEMPTYGROUPS             1077
#define IDC_CTOPSPIN                    1077
#define IDC_CBOTTOM                     1078
#define IDC_CBOTTOMSPIN                 1079
#define IDC_CRIGHT                      1080
#define IDC_HIDEOFFLINE                 1081
#define IDC_CRIGHTSPIN                  1081
#define IDC_HIDEOFFLINEOPTS             1082
#define IDC_LEFTMARGINSPIN              1092
#define IDC_NOGROUPICON                 1102
#define IDC_ONECLK                      1105
#define IDC_RIGHTMARGIN                 1121
#define IDC_ROWGAP                      1122
#define IDC_TRANSPARENT                 1124
#define IDC_ROWHEIGHT                   1125
#define IDC_TRANSINACTIVE               1126
#define IDC_GROUPROWHEIGHT              1126
#define IDC_TRANSACTIVE                 1128
#define IDC_PROFILELIST                 1134
#define IDC_CLASSLIST                   1135
#define IDC_SELBLEND                    1140
#define IDC_SHOWBOTTOMBUTTONS           1148
#define IDC_STATIC11                    1154
#define IDC_STATIC12                    1155
#define IDC_STATIC21                    1156
#define IDC_STATIC13                    1156
#define IDC_STATIC22                    1157
#define IDC_STATIC14                    1157
#define IDC_STATIC15                    1158
#define IDC_SHOWGRIP                    1169
#define IDC_SKINBACKGROUND              1170
#define IDC_FILLWALLPAPER               1171
#define IDC_SHOWMETA                    1172
#define IDC_CENTERGROUPNAMES            1173
#define IDC_APPLYINDENTBG               1174
#define IDC_COPYRIGHT                   1178
#define IDC_VERSION                     1179
#define IDC_SHOWSTATUSICONS             1180
#define IDC_BROWSE                      1184
#define IDC_INACTIVEPERC                1187
#define IDC_SHOWSTATUSMSG               1188
#define IDC_SHOWLOCALTIME               1189
#define IDC_SHOWLOCALTIMEONLYWHENDIFFERENT 1191
#define IDC_TITLETEXT                   1196
#define IDC_EXCEPTION_DETAILS           1200
#define IDC_COPY_EXCEPTION              1201
#define IDC_EX_REASON                   1202
#define IDC_TILEH                       1208
#define IDC_WHITERECT                   1225
#define IDC_AUTOHIDE                    1235
#define IDC_HIDETIME                    1236
#define IDC_ALWAYSHIDEONTASKBAR         1237
#define IDC_IMPORT                      1241
#define IDC_MAXSIZEHEIGHT               1254
#define IDC_MAXSIZESPIN                 1255
#define IDC_BKGCOLOUR                   1269
#define IDC_FILENAME                    1271
#define IDC_SCROLL                      1277
#define IDC_PROPORTIONAL                1278
#define IDC_SMOOTHTIME                  1283
#define IDC_SMOOTHTIMESPIN              1284
#define IDC_ROWHEIGHTSPIN               1286
#define IDC_GROUPROWHEIGHTSPIN          1287
#define IDC_GREYOUTOPTS                 1288
#define IDC_GROUPINDENT                 1289
#define IDC_GROUPINDENTSPIN             1290
#define IDC_LEFTMARGIN                  1291
#define IDC_RIGHTMARGINSPIN             1294
#define IDC_ROWGAPSPIN                  1295
#define IDC_STRETCHH                    1298
#define IDC_STRETCHV                    1299
#define IDC_TILEV                       1301
#define IDC_DONTCYCLE                   1315
#define IDC_PRIMARYSTATUS               1316
#define IDC_CYCLE                       1317
#define IDC_CYCLETIME                   1318
#define IDC_CYCLETIMESPIN               1319
#define IDC_HIDETIMESPIN                1320
#define IDC_MULTITRAY                   1321
#define IDC_ALWAYSMULTI                 1322
#define IDC_SHOWICON                    1323
#define IDC_SORTTHEN                    1323
#define IDC_SHOWPROTO                   1324
#define IDC_SORTFINALLY                 1324
#define IDC_SHOWSTATUS                  1325
#define IDC_EQUALSECTIONS               1326
#define IDC_SHOWSBAR                    1329
#define IDC_RIGHTMIRANDA                1330
#define IDC_RIGHTSTATUS                 1331
#define IDC_STCLISTGROUP                1350
#define IDC_DISABLEDRAGDROP             1351
#define IDC_NOTEDITLABELS               1352
#define IDC_SHOWSELALWAYS               1353
#define IDC_TRACKSELECT                 1354
#define IDC_SHOWGROUPCOUNTS             1355
#define IDC_HIDECOUNTSWHENEMPTY         1356
#define IDC_DIVIDERONOFF                1357
#define IDC_NOTNOTRANSLUCENTSEL         1358
#define IDC_LINEWITHGROUPS              1359
#define IDC_QUICKSEARCHVISONLY          1360
#define IDC_SORTGROUPSALPHA             1361
#define IDC_NOTNOSMOOTHSCROLLING        1362
#define IDC_BITMAP                      1363
#define IDC_STWINDOWGROUP               1364
#define IDC_STATIC01                    1365
#define IDC_SORTPRIMARY                 1420
#define IDC_HIDE                        1534
#define IDC_TOPLINE                     1535
#define IDC_BRINGTOFRONT                1579
#define IDC_LOGO                        1591
#define IDC_BLINKTIME                   1607
#define IDC_BLINKSPIN                   1608
#define IDC_DISABLEBLINK                1609
#define IDC_IDLE                        1610
#define IDC_SBPANELBEVEL                1611
#define IDC_DBLCLKAVATARS               1611
#define IDC_XSTATUSASSTATUS             1611
#define IDC_NOSCROLLBAR                 1613
#define IDC_ADDVIEWMODE                 1633
#define IDC_SKINFILESELECT              1633
#define IDC_IGN_ALL                     1633
#define IDC_EXPORT                      1634
#define IDC_DELETEVIEWMODE              1634
#define IDC_IGN_NONE                    1634
#define IDC_RELOAD                      1635
#define IDC_IGN_ADDPERMANENTLY          1635
#define IDC_DSP_LOADDEFAULT             1636
#define IDC_ONDESKTOP                   1657
#define IDC_WINCOLOUR                   1659
#define IDC_ICONBLINK                   1660
#define IDC_APPLYLASTVIEWMODE           1661
#define IDC_IGNORESELFORGROUPS          1722
#define IDC_CLISTAVATARS                1729
#define IDC_ALIGNMENT                   1730
#define IDC_AVATARSBORDER               1732
#define IDC_AVATARBORDERCLR             1733
#define IDC_AVATARSROUNDED              1734
#define IDC_DUALROWMODE                 1735
#define IDC_CLISTALIGN                  1737
#define IDC_CLISTSUNKEN                 1738
#define IDC_EVENTAREAAUTOHIDE           1740
#define IDC_RADIUS                      1742
#define IDC_RADIUSSPIN                  1743
#define IDC_ALWAYSALIGNNICK             1744
#define IDC_SELECTIVEICONS              1746
#define IDC_OVERLAYICONS                1747
#define IDC_AVATARHEIGHT                1748
#define IDC_NOAVATARSOFFLINE            1749
#define IDC_CORNERRAD                   1751
#define IDC_CORNERSPIN                  1752
#define IDC_AVATARPADDING               1753
#define IDC_GRPTOPPADDING               1753
#define IDC_AVATARPADDINGSPIN           1754
#define IDC_GRPPADDINGSPIN              1754
#define IDC_LASTITEMPADDING             1755
#define IDC_LASTITEMPADDINGSPIN         1756
#define IDC_TBHIDEOFFLINE               1800
#define IDC_TBHIDEGROUPS                1801
#define IDC_TBSOUND                     1802
#define IDC_TBFINDANDADD                1803
#define IDC_TBOPTIONS                   1804
#define IDC_TBMINIMIZE                  1805
#define IDC_TBMENU                      1806
#define IDC_TBGLOBALSTATUS              1807
#define IDC_TABSRMMSLIST                1808
#define IDC_TABSRMMMENU                 1809
#define IDC_TBSELECTVIEWMODE            1810
#define IDC_ROUNDEDBORDER               1810
#define IDC_TBCLEARVIEWMODE             1811
#define IDC_TBCONFIGUREVIEWMODE         1812
#define IDC_TBTOPMENU                   1813
#define IDC_TBTOPSTATUS                 1814
#define IDC_TBFOLDER                    1815
#define IDC_TBPOPUP                     1816
#define IDC_TBACCOUNTS                  1817
#define IDC_TBFIRSTUID                  1820
#define IDC_NOTIFYBUTTON                1900
#define IDC_CLNICER                     2002
#define IDC_SUPPORT                     2003
#define IDI_OVL_OFFLINE                 2050
#define IDI_OVL_ONLINE                  2051
#define IDI_OVL_AWAY                    2052
#define IDI_OVL_DND                     2053
#define IDI_OVL_NA                      2054
#define IDI_OVL_OCCUPIED                2055
#define IDI_OVL_INVISIBLE               2057
#define IDI_OVL_ONTHEPHONE              2058
#define IDI_OVL_OUTTOLUNCH              2059
#define IDI_HIDEOFFLINE                 2100
#define IDI_HIDEGROUPS                  2101
#define IDI_SOUNDSON                    2102
#define IDI_FINDANDADD                  2103
#define IDI_TBOPTIONS                   2104
#define IDI_MINIMIZE                    2105
#define IDI_SOUNDSOFF                   2106
#define IDI_TABSRMMSESSIONLIST          2107
#define IDI_TABSRMMMENU                 2108
#define IDI_PROTOCONNECTING             2111
#define IDI_TBTOPMENU                   2112
#define IDI_TBACCOUNTS                  2113
#define IDC_FLT_DEFHOVERTIME            2200
#define IDC_CLUIFRAMESBDR               25492
#define IDC_FLT_PADLEFTSPIN             25494
#define IDC_FLT_PADLEFT                 25495
#define IDC_GROUPALIGN                  25499
#define IDC_BORDERSTYLE                 25501
#define IDC_CURVIEWMODE2                25503
#define ID_ICQ_EXIT                     40001
#define IDC_STATIC7                     40002
#define POPUP_HIDEEMPTYGROUPS           40003
#define POPUP_NEWSUBGROUP               40004
#define POPUP_HIDEOFFLINE               40005
#define POPUP_GROUPHIDEOFFLINE          40006
#define POPUP_HIDEOFFLINEROOT           40007
#define POPUP_DISABLEGROUPS             40008
#define IDC_VIEWMODES                   40010
#define IDC_PROTOCOLS                   40011
#define IDC_GROUPS                      40012
#define IDC_STATUSMODES                 40013
#define IDC_NEWVIEMODE                  40014
#define POPUP_HIDEMIRANDA               40017
#define IDC_TAB                         40017
#define IDC_STATIC1                     40018
#define IDC_STATIC2                     40019
#define IDC_STATIC3                     40020
#define IDC_STATIC16                    40021
#define IDC_STATIC4                     40022
#define IDC_STATIC5                     40023
#define IDC_CLIST                       40025
#define IDC_STATIC8                     40026
#define IDC_STATIC9                     40027
#define POPUP_BUTTONS                   40028
#define IDC_CLEARALL                    40028
#define POPUP_FRAME                     40029
#define IDC_STATIC10                    40029
#define IDC_PROTOGROUPOP                40030
#define POPUP_MOVEMARKEDHERE            40031
#define IDC_GROUPSTATUSOP               40031
#define IDC_LASTMESSAGEOP               40032
#define ID_BUTTONS_ONLINE               40033
#define IDC_SKINFILE                    40034
#define IDC_LASTMESSAGEUNIT             40034
#define IDC_FLT_AVATARS                 40036
#define IDC_HIDECONTACT                 40036
#define IDC_FLT_DUALROWS                40037
#define IDC_FLT_EXTRAICONS              40038
#define ID_TRAY_HIDE                    40038
#define ID_TRAY_EXIT                    40039
#define IDC_FLT_SYNCED                  40039
#define POPUP_SHOWMETAICONS             40040
#define IDC_FLT_AUTOHIDE                40040
#define IDC_FLT_FILLSTD                 40041
#define IDC_FLT_PADRIGHT                40043
#define IDC_LASTMSGVALUE                40043
#define IDC_FLT_PADRIGHTSPIN            40044
#define IDC_FLT_PADTOP                  40045
#define IDC_SKINFILENAME                40045
#define IDC_FLT_PADTOPSPIN              40046
#define IDC_SELECTSKINFILE              40046
#define IDC_FLT_PADBOTTOM               40047
#define IDC_RELOADSKIN                  40047
#define IDC_FLT_PADBOTTOMSPIN           40048
#define IDC_UNLOAD                      40048
#define POPUP_NEWGROUP                  40050
#define IDC_SECONDLINEMODE              40050
#define POPUP_SHOWSTATUSICONS           40051
#define IDC_OVERLAYICON                 40051
#define IDC_SHOWLOCALTIME1              40052
#define POPUP_RENAMEGROUP               40052
#define POPUP_DELETEGROUP               40053
#define IDC_DSP_ADD                     -25483
#define IDC_DSP_DELETE                  40054
#define IDC_FLT_ENABLED                 40054
#define IDC_DSP_RENAME                  40055
#define IDC_FLT_OPACITY                 40055
#define IDC_DSP_APPLY                   40056
#define IDC_FLT_ACTIVEOPACITY           40056
#define IDC_FLT_WIDTH                   40058
#define IDC_AVATARDISPMODE              40059
#define IDC_FLT_WIDTHSPIN               40059
#define IDC_FLT_SNAP                    40060
#define IDC_FLT_ACTIVEOPACITYVALUE      40061
#define IDC_FLT_BORDER                  40062
#define IDC_FLT_ROUNDED                 40063
#define IDC_FLT_RADIUS                  40065
#define IDC_FLT_RADIUSSPIN              40066
#define IDC_FLT_HOVERTIME               40067
#define IDC_RESETXICONS                 40067
#define IDC_FLT_SHOWTOOLTIPS            40068
#define IDC_FLT_HOVERTIMESPIN           40069
#define IDC_FLT_OPACITYVALUE            40070
#define IDC_FLT_BORDERCOLOUR            40072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10
#define _APS_NEXT_COMMAND_VALUE         40061
#define _APS_NEXT_CONTROL_VALUE         40066
#define _APS_NEXT_SYMED_VALUE           40154
#endif
#endif
