//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by chat.rc
//
#define IDD_CHANNEL                     101
#define IDD_OPTIONS1                    102
#define IDD_OPTIONS2                    103
#define IDD_FILTER                      105
#define IDD_OPTIONSPOPUP                106
#define IDI_BUNDERLINE                  120
#define IDI_BBOLD                       121
#define IDI_BITALICS                    122
#define IDI_BSMILEY                     123
#define IDI_TOPICBUT                    124
#define IDI_BKGCOLOR                    125
#define IDI_CHANMGR                     126
#define IDI_COLOR                       127
#define IDI_FILTER                      128
#define IDI_HISTORY                     129
#define IDI_NICKLIST                    130
#define IDI_JOIN                        131
#define IDI_PART                        132
#define IDI_QUIT                        133
#define IDI_KICK                        134
#define IDI_NICK                        135
#define IDI_NOTICE                      136
#define IDI_MESSAGE                     137
#define IDI_MESSAGEOUT                  138
#define IDI_TOPIC                       139
#define IDI_INFO                        140
#define IDI_ADDSTATUS                   141
#define IDI_REMSTATUS                   142
#define IDI_ACTION                      143
#define IDI_HIGHLIGHT                   144
#define IDI_BLANK                       146
#define IDI_TAG1                        149
#define IDI_TAG2                        150
#define IDR_MENU                        151
#define IDD_COLORCHOOSER                152
#define IDI_STATUS3                     153
#define IDI_STATUS2                     154
#define IDI_STATUS4                     155
#define IDI_STATUS1                     156
#define IDI_STATUS0                     157
#define IDI_STATUS5                     158
#define IDI_CLOSE                       159
#define IDI_OVERLAY                     160
#define IDI_NICKLIST2                   161
#define IDI_FILTER2                     162
#define IDC_LOG                         1005
#define IDC_SPLITTERX                   1006
#define IDC_SMILEY                      1007
#define IDC_SPLITTERY                   1008
#define IDC_MESSAGE                     1009
#define IDC_BOLD                        1010
#define IDC_ITALICS                     1011
#define IDC_UNDERLINE                   1012
#define IDC_FILTER                      1013
#define IDC_CHANMGR                     1014
#define IDC_SHOWNICKLIST                1016
#define IDC_COLOR                       1017
#define IDC_BKGCOLOR                    1019
#define IDC_CHECKBOXES                  1021
#define IDC_NICKLISTBKG                 1021
#define IDC_HISTORY                     1022
#define IDC_CLOSE                       1023
#define IDC_NICKROW                     1024
#define IDC_LOGLIMIT                    1024
#define IDC_NICKROW2                    1025
#define IDC_SPIN1                       1028
#define IDC_SPIN2                       1029
#define IDC_SPIN3                       1030
#define IDC_SPIN4                       1031
#define IDC_FONTLIST                    1032
#define IDC_CHOOSEFONT                  1034
#define IDC_FONTCOLOR                   1035
#define IDC_MESSAGEBKG                  1036
#define IDC_LOGBKG                      1037
#define IDC_HIGHLIGHTWORDS              1040
#define IDC_INSTAMP                     1041
#define IDC_OUTSTAMP                    1043
#define IDC_TIMESTAMP                   1046
#define IDC_FONTCHOOSE                  1047
#define IDC_LOGDIRECTORY                1048
#define IDC_LIMIT                       1050
#define IDC_LOGTIMESTAMP                1051
#define IDC_GROUP                       1057
#define IDC_RADIO1                      1061
#define IDC_RADIO2                      1062
#define IDC_RADIO3                      1063
#define IDC_TEXT                        1064
#define IDC_BKG                         1065
#define IDC_TIMEOUT                     1067
#define IDC_HIGHLIGHT                   1068
#define IDC_TEXTO                       1069
#define IDC_LOGGING                     1069
#define IDC_COLORTEXT                   1070
#define IDC_LIST                        1072
#define IDC_TAB                         1074
#define IDC_1                           1075
#define IDC_2                           1076
#define IDC_3                           1077
#define IDC_4                           1078
#define IDC_5                           1079
#define IDC_6                           1080
#define IDC_7                           1081
#define IDC_8                           1082
#define IDC_9                           1083
#define IDC_10                          1084
#define IDC_11                          1085
#define ID_MESS                         40001
#define ID_NEW                          40002
#define ID_CURR                         40003
#define ID_COPY                         40004
#define ID_COPYALL                      40006
#define ID_CLEARLOG                     40009
#define ID_MESSAGE_UNDO                 40013
#define ID_MESSAGE_COPY                 40014
#define ID_MESSAGE_CUT                  40015
#define ID_MESSAGE_CLEAR                40017
#define ID_MESSAGE_SELECTALL            40018
#define ID_MESSAGE_REDO                 40019
#define ID_MESSAGE_PASTE                40020
#define ID_CLOSE                        40022
#define ID_CLOSEOTHER                   40023
#define ID_LOCKPOSITION                 40024
#define ID_Menu                         40026
#define ID_SEARCH_GOOGLE                40027
#define ID_SEARCH_WIKIPEDIA             40028
#define ID_WIKIPEDIA_                   40029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
