#ifndef calendars_h
#define calendars_h

/**
 * @brief Czech names database
 *
 */
static char *czech_names[] = {
	"CZE", 
	"Novy rok", "Karina", "Radmila", "Diana", "Dalimil", "Tri kralove", "Vilma",
	"Cestmir", "Vladan", "Bretislav", "Bohdana", "Pravoslav", "Edita", "Radovan",
	"Alice", "Ctirad", "Drahoslav", "Vladislav", "Doubravka", "Ilona", "Bila",
	"Slavomir", "Zdenek", "Milena", "Milos", "Zora", "Ingrid", "Otylie", "Zdislava",
	"Robin", "Marika",
	
	"Hynek", "Nela", "Blazej", "Jarmila", "Dobromila", "Vanda", "Veronika", "Milada",
	"Apolena", "Mojmir", "Bozena", "Slavina", "Vinceslav", "Valentyn", "Jirina",
	"Ljuba", "Miloslava", "Gizela", "Patrik", "Oldrich", "Lenka", "Petr", "Svatopluk",
	"Matej", "Liliana", "Dorota", "Alexandr", "Lumir", "Horymir",
	
	"Bedrich", "Anezka", "Kamil", "Stela", "Kazimir", "Miroslav", "Tomas", "Gabriela",
	"Frantiska", "Viktorie", "Andela", "Rehor", "Ruzena", "Rut a Matylda", "Ida",
	"Elena a Herbert", "Vlastimil", "Eduard", "Josef", "Svetlana", "Radek", "Leona",
	"Ivona", "Gabriel", "Marian", "Emanuel", "Dita", "Sona", "Tatana", "Arnost",
	 "Kvido",
	
	"Hugo", "Erika", "Richard", "Ivana", "Miroslava", "Vendula", "Herman a Hermina",
	"Ema", "Dusan", "Darja", "Izabela", "Julius", "Ales", "Vincenc", "Anastazie", "Irena",
	"Rudolf", "Valerie", "Rostislav a Rosta", "Marcela", "Alexandra a Sasa", "Evzenie", "Vojtech a Vojta",
	"Jiri a Jirka", "Marek", "Oto", "Jaroslav a Jarda", "Vlastislav", "Robert", "Blahoslav",
	
	".....", "Zikmund", "Alexej", "Kvetoslav", "Klaudie", "Radoslav", "Stanislav a Standa",
	".....", "Ctibor", "Blazena", "Svatava", "Pankrac", "Servac", "Bonifac", "Zofie",
	"Premysl", "Aneta", "Natasa", "Ivo", "Zbysek", "Monika", "Emil", "Vladimir a Vlada",
	"Jana", "Viola", "Filip", "Valdemar", "Vilem", "Maxmilian", "Ferdinand", "Kamila",
	
	"Laura", "Jarmil", "Tamara", "Dalibor", "Dobroslav", "Norbert", "Iveta a Slavoj",
	"Medard", "Stanislava", "Gita", "Bruno", "Antonie", "Antonin", "Roland", "Vit",
	"Zbynek", "Adolf", "Milan", "Leos", "Kveta", "Alois", "Pavla", "Zdenka", "Jan a Honza",
	"Ivan", "Adriana", "Ladislav", "Lubomir a Lubos", "Petr a Pavel", "Sarka",
	
	"Jaroslava", "Patricie", "Radomir", "Prokop", ".....", ".....", "Bohuslava",
	"Nora", "Drahoslava", "Libuse a Amalie", "Olga", "Borek", "Marketa", "Karolina",
	"Jindrich", "Lubos", "Martina", "Drahomira", "Cenek", "Ilja", "Vitezslav", "Magdalena",
	"Libor", "Kristyna", "Jakub", "Anna", "Veroslav", "Viktor", "Marta", "Borivoj", "Ignac",
	
	"Oskar", "Gustav", "Miluse", "Dominik", "Kristian", "Oldriska", "Lada", "Sobeslav",
	"Roman", "Vavrinec", "Zuzana", "Klara", "Alena", "Alan", "Hana", "Jachym", "Petra",
	"Helena", "Ludvik", "Bernard", "Johana", "Bohuslav", "Sandra", "Bartolomej", "Radim",
	"Ludek", "Otakar", "Augustyn", "Evelina", "Vladena", "Pavlína",
	
	"Linda a Samuel", "Adela", "Bronislav", "Jindriska", "Boris", "Boleslav", "Regina",
	"Mariana", "Daniela", "Irma", "Denisa", "Marie", "Lubor", "Radka", "Jolana", "Ludmila",
	"Nadezda", "Krystof", "Zita", "Oleg", "Matous", "Darina", "Berta", "Jaromir", "Zlata",
	"Andrea", "Jonas", "Vaclav a Vasek", "Michal", "Jeronym",
	
	"Igor", "Olivie a Oliver", "Bohumil", "Frantisek", "Eliska", "Hanus", "Justyna",
	"Vera", "Stefan a Sara", "Marina", "Andrej", "Marcel", "Renata", "Agata", "Tereza",
	"Havel", "Hedvika", "Lukas", "Michaela", "Vendelin", "Brigita", "Sabina", "Teodor",
	"Nina", "Beata", "Erik", "Sarlota a Zoe", ".....", "Silvie", "Tadeas", "Stepanka",
	
	"Felix", ".....", "Hubert", "Karel", "Miriam", "Libina", "Saskie", "Bohumir",
	"Bohdan", "Evzen", "Martin", "Benedikt", "Tibor", "Sava", "Leopold", "Otmar",
	"Mahulena", "Romana", "Alzbeta", "Nikola", "Albert", "Cecilie", "Klement",
	"Emilie", "Katerina", "Artur", "Xenie", "Rene", "Zina", "Ondrej a Ondra",
	
	"Iva", "Blanka", "Svatoslav", "Barbora", "Jitka", "Mikulas", "Ambroz a Benjamin",
	"Kvetoslava", "Vratislav", "Julie", "Dana", "Simona", "Lucie", "Lydie", "Radana a Radan",
	"Albina", "Daniel", "Miloslav",  "Ester", "Dagmar", "Natalie", "Simon", "Vlasta",
	"Adam a Eva", "...", "Stepan", "Zaneta", "Bohumila", "Judita", "David",
	"Silvestr" };

/**
 * @brief Slovak names database
 *
 */
static char *slovak_names[] = {
	"SVK", 
	"Novy rok", "Alexandra a Sasa", "Daniela", "Drahoslav", "Andrea a Ajka", "Antonia", "Bohuslava", 
	"Severin", "Alexej", "Dasa", "Malvina", "Ernest", "Rastislav", "Radovan", "Dobroslav", "Kristina", 
	"Natasa", "Bohdana", "Drahomira", "Dalibor", "Vincent", "Zora", "Milos", "Timotej", "Gejza", "Tamara", 
	"Bohus", "Alfonz", "Gaspar", "Ema", "Emil",

	"Tatiana", "Erik a Erika", "Blazej", "Veronika", "Agata", "Dorota", "Vanda", "Zoja", "Zdenko", 
	"Gabriela", "Dezider", "Perla", "Arpad", "Valentin", "Pravoslav", "Ida a Liana", "Miloslava", "Jaromir", 
	"Vlasta", "Livia", "Eleonora", "Etela", "Roman a Romana", "Matej", "Frederik", "Viktor", "Alexander", 
	"Zlatica", "....",

	"Albin", "Anezka", "Bohumil a Bohumila", "Kazimir", "Fridrich", "Radoslav", "Tomas", "Alan", "Frantiska", 
	"Branislav", "Angela", "Gregor", "Vlastimil", "Matilda", "Svetlana", "Boleslav", "Lubica", "Eduard", 
	"Jozef", "Vítazoslav", "Blahoslav", "Benadik", "Adrian", "Gabriel", "Marian", "Emanuel", "Alena", "Sona", 
	"Miroslav", "Vieroslava", "Benjamin",

	"Hugo", "Zita", "Richard", "Izidor", "Miroslava", "Irena", "Zoltan", "Albert", "Milena", "Igor", 
	"Julius", "Estera", "Ales", "Justina", "Fedor", "Dana a Danica", "Rudolf", "Valer", "Jela", "Marcel", 
	"Ervin", "Slavomir", "Vojtech", "Juraj", "Marek", "Jaroslava", "Jaroslav", "Jarmila", "Lea", "Anastazia",

	"Sviatok prace", "Zigmund", "Galina", "Florian", "Lesana", "Hermina", "Monika", "Ingrida", "Roland", 
	"Viktoria", "Blazena", "Pankrac", "Servác", "Bonifac", "Zofia", "Svetozar", "Gizela", "Viola", 
	"Gertruda", "Bernard", "Zina", "Julia a Juliana", "Zelmira", "Ela", "Urban", "Dusan", "Iveta", "Viliam", 
	"Vilma", "Ferdinand", "Petronela",
	
	"Zaneta", "Xenia", "Karolina", "Lenka", "Laura", "Norbert", "Robert", "Medard", "Stanislava", 
	"Margareta", "Dobroslava", "Zlatko", "Anton", "Vasil", "Vit", "Blanka", "Adolf", "Vratislav", "Alfred", 
	"Valeria", "Alojz", "Paulina", "Sidonia", "Jan", "Tadeas", "Adriana", "Ladislav", "Beata", 
	"Peter a Pavol a Petra", "Melania",

	"Diana", "Berta", "Miloslav", "Prokop", "Cyril a Metod", "Patrik a Patricia", "Oliver", "Ivan", "Lujza", 
	"Amalia", "Milota", "Nina", "Margita", "Kamil", "Henrich", "Drahomir", "Bohuslav", "Kamila", "Dusana", 
	"Ilja", "Daniel", "Magdalena", "Olga", "Vladimir", "Jakub", "Anna", "Bozena", "Kristof", "Marta", 
	"Libusa", "Ignac",

	"Bozidara", "Gustav", "Jergus", "Dominik", "Hortenzia", "Jozefina", "Stefania", "Oskar", "Lubomira", 
	"Vavrinec", "Zuzana", "Darina", "Lubomir", "Mojmir", "Marcela", "Leonard", "Milica", "Elena", "Lydia", 
	"Anabela", "Jana", "Tichomir", "Filip", "Bartolomej", "Ludovit", "Samuel", "Silvia", "Augustin", 
	"Nikola", "Ruzena", "Nora",

	"Drahoslava", "Linda", "Belo", "Rozalia", "Regina", "Alica", "Marianna", "Miriama", "Martina", "Oleg", 
	"Bystrik", "Maria", "Ctibor", "Ludomil", "Jolana", "Ludomila a Ludmila", "Olympia", "Eugenia", 
	"Konstantin", "Luboslava", "Matus", "Moric", "Zdenka", "Lubos", "Vladislav", "Edita", "Cyprian", 
	"Vaclav", "Michal", "Jarolim", 

	"Arnold", "Levoslav", "Stela", "Frantisek", "Viera", "Natalia", "Eliska", "Brigita", "Dionyz", 
	"Slavomira", "Valentina", "Maximilian", "Koloman", "Boris", "Terezia", "Vladimira", "Hedviga", "Lukas", 
	"Kristian", "Vendelin", "Ursula", "Sergej", "Alojza", "Kvetoslava", "Aurel", "Demeter", "Sabina", 
	"Dobromila", "Klara", "Simona", "Aurelia",

	"Denisa", "Pamiatka zosnulych", "Hubert", "Karol", "Imrich", "Renata", "Rene", "Bohumir", "Teodor", 
	"Tibor", "Martin", "Svatopluk", "Stanislav", "Irma", "Leopold", "Agnesa", "Klaudia", "Eugen", "Alzbeta", 
	"Felix", "Elvira", "Cecilia", "Klement", "Emilia", "Katarina", "Kornel", "Milan", "Henrieta", "Vratko", 
	"Ondrej a Andrej",

	"Edmund", "Bibiana", "Oldrich", "Barbora", "Oto", "Mikulas", "Ambroz", "Marina", "Izabela", "Raduz", 
	"Hilda", "Otilia", "Lucia", "Branislava", "Ivica", "Albina", "Kornelia", "Slava", "Judita", "Dagmara", 
	"Bohdan", "Adela", "Nadezda", "Adam a Eva", "sviatok vianocny", "Stefan", "Filomena", "Ivana", "Milada", 
	"David", "Silvester" };

/**
 * @brief French names database
 *
 */
static char *french_names[] = {
"FRA",
"Jour de l'An or Fulgence",
"Basile or Clair or Vassili",
"Genest or Geneviève or Ginette",
"Odilon",
"Edouard or Édouardine or Émilienne or Teddy",
"Guérin or Melaine or Tiphaine",
"Cédric or Ramon or Ramuntcho or Raymond or Raymonde or Virginie",
"Gudule or Lucien or Lucienne or Peggy",
"Alexia or Alix or Alix",
"Billy or Guillaume or  or Guillaumette or Guillem or Guillemette or William or Willy",
"Paulin",
"Césarine or Tania or Tatiana or Tatienne",
"Hilaire or Hilarion or Yvette",
"Nina",
"Amaury or Macaire or Maur or Rémi or Rachel",
"Honorat or Marceau or Marcel or Priscilla",
"Anthony or Antoine or Roseline",
"Prisca",
"Marius",

"Bastien or Bastienne or Fabien or Fabienne or Sébastien or Sébastienne",
"Agnès",
"Anastase or Vincent",
"Barnard",
"Babylas or François or Paquito",
"Apollos or Paul",
"Paola or Paula or Paule or Paulette or Pauline or Mélanie",
"Angèle or Angélina or Angéline or Angélique or Dévote",
"Thomas",
"Gildas",
"Bathilde or Bathylle or Jacinthe or Martina or Martine",
"Marcelle or Marcellia or Nikita",

"Ella or Ellénita or Viridiana",
"Théophane",
"Anatole or Anatolie or Blaise or Oscar",
"Bérénice or Gilbert or Vanessa or Véronique",
"Agathe or Avit",
"Armand or Doris or Dorothée or Gaston",
"Eugénie",
"Apolline",
"Jackie or Jacqueline or Jacquette or Jacquine or Jacquotte",
"Arnaud",
"Théodora",
"Félix",
"Béatrice or Béatrix or Jordane",
"Tino or Valentin or Saint Valentin",
"Claude or Claudius or Faust or Fausta or Faustin or Faustine or Georgetta or Georgette or Georgia or Georgina or Georgine",
"Julienne or Lucile or Onésime or Paméla or Pamphile",
"Alexis or Cendres",
"Bernadette or Flavien or Flavienne or Nadette or Nadine or Siméon",
"Gabin",
"Aimée or Aymée",
"Carême",
"Isabeau or Isabelle",
"Lazare",
"Modeste",
"Roméo",
"Nestor",
"Galmier or Honorin or Honorine",
"Antoinette or Léandre or Romain or Toinon",
"Augusta or Auguste",

"Albin or Albine or Auban or Aubane or Aubin or Aubry",
"Charles or Chad or Jaouen",
"Cunégonde or Guénolé or Gwénola",
"Casimir",
"Olive or Olivette or Olivia or Olivier",
"Coletta or Colette or Nicole or Nicoletta",
"Félicie or Félicité or Perpétue",
"Jean or Philémon",
"Fanchon or France or Franceline or Francette or Francine or Françoise or Paquita",
"Anastasie or Vivian or Viviane or Vivien",
"Mi-Carême or Rosine",
"Elphège or Justine or Justinien or Maxime or Maximilien or Maximilienne or Pol",
"Rodrigue",
"Mathilde or Maud",
"Longin or Louise or Louisette or Lucrèce",
"Bénédict or Bénédicte or Eusébie",
"Patrice or Patricia or Patrick",
"Cyrille or Salvador or Salvatore",
"José or Joseph or Josèphe or Joséphin or Joséphine or Josette or Josiane",
"Herbert or Svetlana",
"Axel or Axelle or Béryl or Clémence",
"Léa or Léïla or Lia or Liane or Lila",
"Rébecca or Victorien",
"Hildelitte",
"Annonciade or Humbert or Violaine",
"Lara or Larissa",
"Habib",
"Gontran",
"Gladys or Gwladys or Jonas",
"Amédée",
"Amos or Balbine or Benjamin or Benjamine",

"Hugues or Huguette or Hugo or Ugo or Valéry",
"Sandie or Sandra or Sandrine or Sandy",
"Richard",
"Alèthe or Alette or Aliette or Isidore",
"Irène",
"Marcelin or Marcellin",
"Jean-Baptiste or Hégésippe",
"Constance or Julia or Julie",
"Gautier or Walter",
"Fulbert",
"Stanislas",
"Jules",
"Ida",
"Max or Maxence",
"Paterne",
"Benoît or José or Druon",
"Anicet or Etienne",
"Parfait",
"Emma or Werner",
"Giraud or Odette",
"Anselme or Selma",
"Alex or Alexandra or Alexandre or Alexandrine",
"Adalbert or Fortunat or Georges or Georgette or Youri",
"Fidèle or Fortunat",
"Souv. or Déportés or Marc",
"Alida or Alda or Clet or ",	
"Zita",
"Valérie",
"Tropez",
"Robert or Roberte or Robertine or Robin or Roparz or Rosemonde",

"Fête du Travail or Andéol or Brieux or Florine or Jérémie or Muguet or Muguette or Tamara", 
"Athanase or Boris or Zoé",
"Juvéna or Philippe or Philippine",
"Florian or Sylvain or Sylvaine",
"Ange or Judith",
"Marien or Prudence",
"Domitille or Flavie or Flavia or Gisèle",
"Victoire 1945 or Désiré or Désirée",
"Fête Jeanne d'Arc or Isaïe or Pâcome or Tudi",
"Solange",
"Estelle or Epiphane or Etoile or Mayeul or Stella",
"Achille or Nérée",
"Rolande",
"Mathias or Matthias",
"Denise or Primaël or Victorin or Victorine",
"Honoré",
"Pascal or Pascale or Pascaline",
"Coralie or Corinne or Cora or Coraline or Eric or Erich or Erick or Ericka",
"Célestin or Célestine or Erwan or Yves or Yvon or Yvonne",
"Bernardin or Bernardine",
"Constantin",
"Caste or Émile or Miloud or Quiterie or Rita",
"Didier",
"Amaël or Donatien or Donatienne or Maël or Maëlle or Rogatien",
"Sophie",
"Bérenger or Bérengère",
"Auguste or Augustin or Hildebert",
"Germain",
"Aymar or Maximin",
"Trinité or Ferdinand or Ivanne or Jane or Jeanne or Jeannette or Jenny or Jeanine or Jehanne or Juanita or Lorraine or Vanina",
"Pernelle or Péroline or Perrette or Perrin or Perrine or Pétronille or Pierrette",

"Justin or Ronan or Renan or Paméla",
"Blandine or Elme or Erasme or Vital",
"Kévin",
"Clotilde",
"Boniface or Igor",
"Claude or  or Claudia or Claudette or Claudie or Claudine or Dieu or Norbert",
"Gilbert or Maité or Mériadec",
"Armande or Armance or Médard",
"Diane or Ephrem or Félicien or Félicienne",
"Landry",
"Aleyde or Barnabé or Yolande",
"Guy or Guyonne",
"Saint Antoine de Padoue or Antoine",
"Elisée or Elysée or Rufin or Valère",
"Germaine",
"Aurélien or Ferréol or Régis",
"Hervé or Rainier",
"Ophélie or Léonce",
"Déodat or Gervais or Gervaise or Micheline or Romuald",
"Silvère or Sylvère",
"Aloïs or Aloysius or Gina or Gino or Gonzague or Loïs or Ralph or Rodolphe or Rudolf or Rudy",
"Alban or Alba or Albane or Albe",
"Audrey",
"Baptista or Baptiste or Baptistin or Baptistine or Jean-Baptiste",
"Eléonore or Lore or Nora or Prosper or Salomon",
"Anthelme or Maixent",
"Fernand or Fernande",
"Irénée",
"Paul or Pablo or Peter or Pierre or Pierrick",
"Adnette or Adolphe or Adolphine or Martial",

"Aaron or Diétrich or Dirk or Esther or Goulven or Servan or Servane or Thierry",
"Martinien",
"Thomas",
"Bertha or Berthe or Elia or Eliane or Florent or Lilian or Liliana or Liliane",
"Hélie",
"Marietta or Mariette or Nolwenn",
"Aubierge or Raoul",
"Edgar or Thibaud or Thibaut or Thiébaud",
"Amanda or Amandine or Hermine or Herminie or Irma or Marianne",
"Canut or Ulrich",
"Benoît or Benoîte or Olga",
"Olivier",
"Clélia or Enrique or Eugène or Harry or Henri or Henriette or Joël or Joëlle or Mildred or Milfred",
"Camille or Camille or Fête Nationale",
"Bonaventure or Donald or Vladimir or Wladimir",
"Carmen or Carmine or Elvire",
"Arlette or Carol or Carole or Caroline or Charlotte or Chloé or Marceline or Marcelline",
"Arnould or Freddy or Frédéric or Frédérique or Frédérique or Frida",
"Arsène",
"Elie or Eliette or Elyette or Gaud or Gaudeline or Hélyette or Marguerite or Marina or Marine or Marinette or Marjorie or May",
"Domnin or Victor",
"Maddy or Madeleine or Marie-Madeleine",
"Brigitte",
"Christel or Christelle or Christiane or Christilla or Christina or Christine or Ségolène",
"Jacky or Jacme or Jacques or James or Jim or Valentine",
"Anabelle or Anais or Anita or Anna or Annabella or Annabelle or Anne or AnneAnnette or Annick or Annie or Anouchka or Anouck or Joachim or Joris or Nancy or Océane",
"Aurèle or Nathalie",
"Celse or Innocent or Samson",
"Loup or Marthe or Olaf or Olav",
"Juliette",
"Ignace",

"Arcadius or Arcady or Alphonse or Alphonsin or Alphonsine or Eléazar",
"Julien or Julian or Eusèbe",
"Lydie or Lydiane",
"Jean-Marie or Vianney",
"Abel or Abella or Oswald",
"Octavien",
"Gaétan or Gaétane",
"Cyrus or Cyr or Cyriaque or Dominique or Dominique",
"Amour",
"Dieudonné or Laurent or Laura or Laure or Laurie or Laurette or Laurentine or Laurence",
"Claire or Clara or Clairette or Suzy or Suzon or Suzette or Suzel or Suzanne or Suzanna or Gilberte or Géry",
"Clarisse or Clarence",
"Hippolyte or Philomène",
"Evrard or Arnold",
"Assomption or Alfred or Alfréda or Napoléon or Manon or Maryvonne or Maria or Marie or Marielle or Mariannick or Mariam or Marlène or Marion or Maryline or Maryse or Mylène or Marielle or Marjolaine or Milène or Mireille or Murielle or Muriel or Mylène or Myriam",
"Armel or Armelle or Arméla or Roch",
"Hyacinthe",
"Hélèna or Hélène or Laetitia or Liesse or Léna or Lénaïc or Nelly or Nella or Héliéna or Emmeline or Elina or Eline",
"Jean or Eudes or Guerric",
"Ahmed or Bernard or Samuel or Samy or Philibert or Philiberte",
"Christophe or Ombeline",
"Fabrice or Siegfried or Symphorien",
"Eglantine or Rose or Rosy or Rosa or Rosette or Rosita or Rozenn",
"Barthélémy or Bartholomé or Nathan or Nathanaëlle or Nathanaël",
"Clovis or Louis or Loïc or Martian or Ludowig or Ludwig or Louison",
"Natacha or Césaire or César",
"Amédée or Monique",
"Augustin or Augustine or Hermance or Hermès",
"Sabine or Sabina or Sabrina",
"Fiacre or Sacha",
"Aristide",

"Gilles or Gillette or Josué",
"Ingrid",
"Grégoire or Grégory",
"Iris or Marin or Moïse or Rosalie",
"Raïssa",
"Bertin or Bertrand or Bertrande or Donat or Eva or Eve or Evelyne",
"Reine or Régine or Réjane",
"Hadrien or Nativité or Adrien or Adrienne or Adrian",
"Alain or Omer",
"Aubert or Inès",
"Adelphe or Vinciane",
"Apollinaire",
"Amé or Aimé or Aymé or Dante",
"Sainte Croix",
"Dolorès or Lola or Lolita or Roland",
"Corneille or Cornille or Cyprien or Edith or Ludmilla",
"Hildegarde or Lambert or Réginald or Renald or Renaud or Ronald",
"Ariane or Nadège or Nadia or Sonia or Véra",
"Emilie or Janvier or Amélie",
"Davy or Eustache",
"Deborah or Mathieu or Matthieu",
"Maurice or Mauricette or Morvan",
"Constant",
"Andoche or Thècle",
"Hermann",
"Côme / Dam or Côme or Cosme or Damien",
"St Vincent de Paul or Vincent",
"Venceslas or Wenceslas",
"Gabriel or Gabrielle or Gaby or Michaël or Michel or Michelle or Michèle or Miguel or Raphaël or Raphaëlle",
"Gérôme or Géromina or Jérôme",

"Ariel or Arielle or Thérèse or Uriel or Urielle",
"Léger",
"Blanche or Blanchette or Candida or Candide or Candide or Gérard or Gérardin or Gérardine",
"Aure or Francelin or Francis or Francisque or Franck or François or Frankie or Franklin or Frantz or Orianne or Paco or Soizic",
"Bluette or Fleur or Capucine or Dahlia or Fleur or Foy or Hortense or Jasmine or Myrtille or Pâquerette or Pervenche or Placide or Violette",
"Bruno",
"Gustave or Serge or Sergine",
"Pélagie",
"Denis or Sara or Sibille or Sybil",
"Ghislain or Ghislaine or Virgile",
"Firmin or Soledad",
"Séraphin or Séraphine or Wilfried",
"Géraud",
"Calliste or Céleste or Céleste or Gwendoline or Juste",
"Aurélie or Aurélia or Térésa or Thérèse",
"Bertin or Edwige or Gall or Hedwige or Perlette",
"Baudouin or Solenne or Soline or Zélie",
"Aimable or Amable or Gwenn or Luc or Lucas",
"René or Renée or Rénata",
"Adelin or Adeline or Alin or Aline or Lina or Linda or Line",
"Céline or Ursula or Ursule or Gélase",
"Elodie or Salomé",
"Jean or Régina or Régine or Réjane",
"Florentin or Florentine or Magloire",
"Crépin or Daria or Darius or Doria or Dorian or Enguerran",
"Dimitri or Évariste",
"Emeline",
"Jude or Simon or Simone or Thaddée",
"Narcisse",
"Bienvenue or Bienvenue",
"Quentin or Wolfgang",

"Toussaint or Toussainte or Adam or Aglaée or Anaël or Annibal or Arabelle or Archambaud or Archibald or Balthazar or Clodomir or Colas or Daphné or Diomède or Harold or Hector or Hectorine or Hégisippe or Héloïse or Hercule or Homère or Horace or Kléber or Mathurin or Mathurine or Mercédès or Pénélope or Quasimodo",
"Défunts",
"Gwennaël or Gwennaëlle or Hubert or Huberte or Malachie",
"Amance or Aymeric or Carl or Carlos or Charlemagne or Charles or Charley or Charly or Emeric or Imré or Jessica or Jessy",
"Sylvette or Sylviane or Sylvia or Sylvie or Zacharie",
"Berthilde or Bertille or Léo or Léonard",
"Carine or Ernest or Ernestine or Karell or Karen or Karina or Karine",
"Dora or Dorine or Geoffrey or Geoffroy or Godefroy",
"Maturin or Théodora or Théodore",
"Léon or Léone or Léonie or Léonilde or Léontine or Lionel or Noé or Pulchérie",
"Armistice 1918 or Martin or Vérane",
"Christian or Emilien or Tristan",
"Brice or Diégo",
"Sidoine or Sidonie",
"Albéric or Albert or Alberta or Alberte or Albertina or Albertine or Arthur or Léopold or Léopoldine or Malo or Ninon or Victoire or Victoria",
"Daisy or Gertrude or Magali or Maggy or Marguerite",
"Aude",
"Tanguy",
"Edma or Edme or Edmée or Edmond or Edmonde or Octave or Octavie",
"Christ-Roi",
"Cécile or Célia or Sheila",
"Clément or Clémentine or Colomban or Rachilde",
"Flora or Flore",
"Cathel or Catherine or Katel or Katia or Katy or Katty or Ketty",
"Conrad or Delphine or Kurt",
"Astrid or Séverin or Séverine",
"Avent",
"Saturnin",
"André or Andréa or Andrée",
"Éloi or Florence or Tudal",

"Florence",
"Bibiane or Vivette or Viviane",
"Xavier",
"Ada or Adnette or Barbara or Barbe or Barberine",
"Gérald or Géraldine",
"Colin or Coline or Colinette or Nicolas or Colin",
"Ambroise",
"Immaculée Conception or Elfi or Elfried",
"Fourier or Léocadie or Pierre",
"Romaric",
"Damase or Daniel or Danièle or Danielle or Danitza or Danny",
"Chantal or Corentin or Corentine",
"Aurore or Jocelyne or Josse or Josselin or Josseline or Luce or Lucette or Lucia or Lucie",
"Odile",
"Ninon",
"Adelaïde or Alice or Chrétien or Chrétienne",
"Gaël or Gaëla or Gaëlle or Judicaël or Tessa",
"Briac or Gatien",
"Urbain",
"Achille or Isaac or Jacob or Théophile or Zéphyrin or Zéphyrine",
"Pierre",
"Xavière",
"Armand",
"Adèle or Delphin",
"Noël or Noëlie or Noëlla or Noëlle or Emmanuel or Emmanuelle or Manoël or Manuel or Manuelle or Nello",
"Sainte or Famille or Esteban or Etienne or Etiennette or Fanny or Stéphane or Stéphane or Stéphanette or Stéphanie or Stéphen or Steve",
"Evelyne or Fabiola or Hans or Ivan or Jack or Jean or Jehan or John or Johnny or Yann or Yannick or Yoann or Yvain or Yvan",
"Gaspard or Innocent",
"David",
"Roger",
"Colomba or Colombe or Silvestre or Sylvestre" };

#endif