//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется d:\MNG_orig\plugins\Clist_mw\res\resource.rc
//
#define IDC_AUTHICON                    1
#define IDC_NOTOALL                     3
#define IDC_APPLY                       3
#define MIM_V1                          10
#define IDI_GLOBUS                      11
#define MIM_V2                          20
#define MIM_V3                          30
#define MIM_V4                          30
#define IDD_ABOUT                       103
#define IDI_SMS                         103
#define IDI_ONLINE                      104
#define IDI_OFFLINE                     105
#define IDD_GNUPL                       110
#define IDD_ADDED                       115
#define IDD_URLSEND                     119
#define IDD_URLRECV                     120
#define IDD_AUTHREQ                     121
#define IDD_DETAILS                     125
#define IDD_OPT_CLIST                   126
#define IDD_HISTORY                     127
#define IDI_AWAY                        128
#define IDI_FREE4CHAT                   129
#define IDI_INVISIBLE                   130
#define IDI_NA                          131
#define IDD_OPT_SOUND                   134
#define IDD_OPT_HOTKEYS                 134
#define IDI_SENDURL                     135
#define IDI_RECVMSG                     136
#define IDI_SENDMSG                     137
#define IDI_URL                         138
#define IDI_DND                         158
#define IDI_OCCUPIED                    159
#define IDI_USERDETAILS                 160
#define IDI_FINDUSER                    161
#define IDI_HELP                        162
#define IDI_OPTIONS                     163
#define IDI_MIRANDAWEBSITE              172
#define IDI_RENAME                      173
#define IDI_HISTORY                     174
#define IDI_DELETE                      175
#define IDR_CONTEXT                     180
#define IDC_DROP                        183
#define IDD_OPT_HOTKEY                  184
#define IDD_HISTORY_FIND                192
#define IDI_SENDEMAIL                   193
#define IDD_FILERECV                    194
#define IDD_PROFILEMANAGER              197
#define IDD_NEWPROFILE                  198
#define IDR_CLISTMENU                   199
#define IDI_BLANK                       200
#define IDD_FINDADD                     201
#define IDI_USERONLINE                  201
#define IDD_OPT_AUTOAWAY                202
#define IDI_GROUPSHUT                   202
#define IDD_OPTIONS                     203
#define IDI_GROUPOPEN                   203
#define IDD_PLUGINCONFLICT              204
#define IDD_FILESEND                    205
#define IDI_NOTICK                      205
#define IDD_OPT_PLUGINS                 206
#define IDI_TICK                        206
#define IDD_OPT_ICONS                   207
#define IDI_FILE                        207
#define IDI_TIMESTAMP                   208
#define IDI_CHANGEFONT                  209
#define IDI_ADDCONTACT                  210
#define IDI_SMALLDOT                    211
#define IDI_FILLEDBLOB                  212
#define IDD_READAWAYMSG                 213
#define IDI_EMPTYBLOB                   213
#define IDD_OPT_IGNORE                  214
#define IDC_HYPERLINKHAND               214
#define IDD_OPT_VISIBILITY              215
#define IDC_DROPUSER                    215
#define IDD_SETAWAYMSG                  216
#define IDI_DETAILSLOGO                 216
#define IDD_OPT_AWAYMSG                 217
#define IDD_OPT_CLUI                    218
#define IDD_INFO_SUMMARY                220
#define IDD_INFO_CONTACT                221
#define IDD_INFO_BACKGROUND             222
#define IDD_INFO_NOTES                  223
#define IDD_ADDEMAIL                    226
#define IDD_ICONINDEX                   227
#define IDD_OPT_CLC                     228
#define IDD_OPT_CLCBKG                  230
#define IDD_INFO_LOCATION               231
#define IDD_INFO_WORK                   232
#define IDD_ADDPHONE                    233
#define IDD_OPT_SBAR                    234
#define IDD_INSTALLINI                  235
#define IDD_WARNINICHANGE               236
#define IDD_INIIMPORTDONE               237
#define IDB_SORTCOLUP                   239
#define IDB_SORTCOLDOWN                 240
#define IDD_OPT_NETLIB                  246
#define IDD_NETLIBLOGOPTS               247
#define IDD_FILETRANSFERINFO            249
#define IDD_OPT_FILETRANSFER            250
#define IDD_FILEEXISTS                  251
#define IDD_DELETECONTACT               254
#define IDD_DENYREASON                  256
#define IDD_ADDCONTACT                  257
#define IDD_OPT_CONTACT                 261
#define IDD_OPT_PROTOCOLORDER           262
#define IDI_MULTISEND                   263
#define IDI_DOWNARROW                   264
#define IDD_CREDITS                     265
#define IDD_OPT_IDLE                    268
#define IDI_ICQC1                       269
#define IDI_ICQC2                       270
#define IDI_ICQC3                       271
#define IDI_ICQC4                       272
#define IDI_ICQC5                       273
#define IDI_ICQC6                       274
#define IDI_ICQC7                       275
#define IDI_ICQC8                       276
#define IDI_EMAIL                       277
#define IDD_OPT_META_CLC                279
#define IDI_NEWGROUP                    282
#define IDI_NEWGROUP2                   282
#define IDI_CLIENTTRILLIAN              298
#define IDI_CLIENTMIRANDA               299
#define IDI_CLIENTRQ                    300
#define IDI_CLIENTGAIM                  301
#define IDI_CLIENTIM2                   302
#define IDI_CLIENTKOPETE                303
#define IDI_CLIENTLICQ                  304
#define IDI_CLIENTQIP                   305
#define IDI_CLIENTSIM                   306
#define IDI_MIRANDA2                    307
#define IDD_OPT_CLCBKG2                 308
#define IDI_CLIENTICQL5                 315
#define IDI_CLIENTAGILE                 318
#define IDI_CLIENTGNOMEICU              319
#define IDI_ICON1                       320
#define IDI_CLIENTMOBICQ                320
#define IDI_CLIENTSPAMBOT               321
#define IDI_CLIENTICQMAC                322
#define IDI_CLIENTIMPLUS                323
#define IDI_CLIENTYSM                   324
#define IDI_CLIENTYAMIGO                325
#define IDI_CLIENTWEBICQ                326
#define IDI_CLIENTVICQ                  327
#define IDI_CLIENTSTRICQ                328
#define IDI_CLIENTSTICQ                 329
#define IDI_CLIENTNICQ2                 330
#define IDI_CLIENTPSI                   331
#define IDI_CLIENTMOB2ICQ               333
#define IDI_CLIENTMICQ                  334
#define IDI_CLIENTLIBICQ2000            335
#define IDI_CLIENTCENTERICQ             336
#define IDI_CLIENTALICQ                 337
#define IDI_CLIENTICQ2000               339
#define IDI_CLIENTICQ2001               340
#define IDI_CLIENTICQ2003               341
#define IDI_CLIENTICQLITE               342
#define IDI_CLIENTICQLITE4              343
#define IDI_CLIENTICQLITE5              344
#define IDI_CLIENTICQGOF                345
#define IDI_CLIENTICQGOJ                346
#define IDC_RESETPROTOCOLDATA           1000
#define IDC_SAVE                        1001
#define IDC_DEFBKCOLOR                  1001
#define IDI_ONTHEPHONE                  1002
#define IDC_MESSAGE                     1002
#define IDI_OUTTOLUNCH                  1003
#define IDC_AUTOCLOSE                   1004
#define IDC_FROM                        1005
#define IDC_AUTOMIN                     1005
#define IDC_DATE                        1006
#define IDC_DUMPRECV                    1006
#define IDC_MSG                         1008
#define IDC_PROXYDNS                    1008
#define IDC_NAME                        1009
#define IDC_PROXYTYPE                   1009
#define IDC_STATIC23                    1010
#define IDC_NAMEVAL                     1010
#define IDC_SPECIFYPORTS                1013
#define IDC_ST_ENTERMSG                 1013
#define IDC_ST_ENTERURL                 1014
#define IDC_SPECIFYPORTSO               1014
#define IDC_TEXT                        1019
#define IDC_SHOWNAMES                   1024
#define IDC_ABOUT                       1032
#define IDC_MYNOTES                     1033
#define IDC_URLS                        1037
#define IDC_REPLY                       1039
#define IDC_URL                         1041
#define IDC_REASON                      1046
#define IDC_EMAIL                       1048
#define IDC_NAMENICK                    1049
#define IDC_NAMEFIRST                   1050
#define IDC_NAMELAST                    1051
#define IDC_NICK                        1053
#define IDC_GENDER                      1060
#define IDC_CITY                        1061
#define IDC_STATE                       1062
#define IDC_COUNTRY                     1063
#define IDC_AGE                         1064
#define IDC_ZIP                         1064
#define IDC_PHONE                       1065
#define IDC_STREET                      1065
#define IDC_COMPANY                     1066
#define IDC_LANGUAGE1                   1066
#define IDC_TIMEZONE                    1067
#define IDC_DEPARTMENT                  1067
#define IDC_LOCALTIME                   1068
#define IDC_DETAILS                     1069
#define IDC_POSITION                    1069
#define IDC_LANGUAGE2                   1069
#define IDC_ADD                         1070
#define IDC_LANGUAGE3                   1070
#define IDC_MOREOPTIONS                 1071
#define IDC_USERMENU                    1071
#define IDC_MIN2TRAY                    1073
#define IDC_ONTOP                       1074
#define IDC_SHOWMAINMENU                1075
#define IDC_CLIENTDRAG                  1076
#define IDC_EDIT                        1078
#define IDC_LIST                        1079
#define IDC_HISTORY                     1080
#define IDC_USESOUND                    1085
#define IDC_TOOLWND                     1097
#define IDC_ONECLK                      1098
#define IDC_SHOWCAPTION                 1098
#define IDC_HIDEOFFLINE                 1099
#define IDC_SHOWHIDE                    1100
#define IDC_HIDEEMPTYGROUPS             1100
#define IDC_SORTBYSTATUS                1101
#define IDC_FADEINOUT                   1101
#define IDC_READMSG                     1102
#define IDC_AUTOSIZE                    1102
#define IDC_DISABLEGROUPS               1102
#define IDC_AUTOSIZEUPWARD              1103
#define IDC_ALWAYSSTATUS                1103
#define IDC_NETSEARCH                   1104
#define IDC_CONFIRMDELETE               1104
#define IDC_SORTBYPROTO                 1105
#define IDC_SHOWOPTIONS                 1105
#define IDC_SEARCHURL                   1106
#define IDC_BUILDTIME                   1108
#define IDC_NUMBER                      1113
#define IDC_UIN                         1123
#define IDC_TRANSPARENT                 1124
#define IDC_TRANSINACTIVE               1126
#define IDC_TRANSACTIVE                 1128
#define IDC_FINDWHAT                    1131
#define IDC_FIND                        1132
#define IDC_FILE                        1133
#define IDC_PROFILELIST                 1134
#define IDC_NEWPROFILE                  1135
#define IDC_NEWPROFILENAME              1136
#define IDC_TABS                        1141
#define IDC_RESULTS                     1142
#define IDC_STATUS                      1144
#define IDC_SCREENSAVE                  1145
#define IDC_TIMED                       1146
#define IDC_AWAYTIME                    1147
#define IDC_USEPROXY                    1148
#define IDC_SETNA                       1148
#define IDC_PROXYAUTH                   1149
#define IDC_NATIME                      1149
#define IDC_PROXYHOST                   1150
#define IDC_PROXYPORT                   1151
#define IDC_PROXYUSER                   1152
#define IDC_PROXYPASS                   1153
#define IDC_STATIC11                    1154
#define IDC_STATIC12                    1155
#define IDC_STATIC21                    1156
#define IDC_STATIC22                    1157
#define IDC_STATIC31                    1158
#define IDC_STATIC32                    1159
#define IDC_PROXYAUTHNTLM               1160
#define IDC_HKSHOWHIDE                  1162
#define IDC_HKREADMSG                   1163
#define IDC_SOUNDLIST                   1163
#define IDC_HKSEARCH                    1164
#define IDC_CHANGE                      1164
#define IDC_PREVIEW                     1165
#define IDC_HKSHOWOPTIONS               1165
#define IDC_PLUGINLIST                  1167
#define IDC_FEATURENAME                 1168
#define IDC_CHOOSE                      1169
#define IDC_TO                          1170
#define IDC_ABOUTGROUP                  1175
#define IDC_DESCRIPTION                 1176
#define IDC_AUTHOR                      1177
#define IDC_COPYRIGHT                   1178
#define IDC_VERSION                     1179
#define IDC_HOMEPAGE                    1181
#define IDC_RESTARTREQD                 1182
#define IDC_ICONSET                     1183
#define IDC_BROWSE                      1184
#define IDC_RUNATSTARTBROWSE            1185
#define IDC_PAGETREE                    1186
#define IDC_RUNNOW                      1186
#define IDC_INACTIVEPERC                1187
#define IDC_ACTIVEPERC                  1188
#define IDC_SEARCHNEWWND                1188
#define IDC_RETRIEVING                  1193
#define IDC_TITLETEXT                   1196
#define IDC_GETMORE                     1200
#define IDC_VISIBLEICON                 1204
#define IDC_INVISIBLEICON               1205
#define IDC_FILEICON                    1206
#define IDC_ONLINEICON                  1207
#define IDC_FILENAMES                   1208
#define IDC_ALLICON                     1208
#define IDC_DONTREPLY                   1209
#define IDC_NONEICON                    1209
#define IDC_USEPREVIOUS                 1210
#define IDC_NODIALOG                    1211
#define IDC_USESPECIFIC                 1212
#define IDC_FILEDIR                     1213
#define IDC_ALLFILESPROGRESS            1217
#define IDC_CURRENTSPEED                1219
#define IDC_STAWAYTYPE                  1220
#define IDC_WHITERECT                   1221
#define IDC_ALLSPEED                    1221
#define IDC_CURRENTFILEPROGRESS         1222
#define IDC_CURRENTFILEGROUP            1223
#define IDC_FIRSTNAME                   1224
#define IDC_LASTNAME                    1225
#define IDC_CURRENTTRANSFERRED          1225
#define IDC_DOBDAY                      1226
#define IDC_DOBMONTH                    1227
#define IDC_WEBPAGE                     1228
#define IDC_DOBYEAR                     1228
#define IDC_UPDATING                    1231
#define IDC_NAMEORDER                   1234
#define IDC_AUTOHIDE                    1235
#define IDC_HIDETIME                    1236
#define IDC_RECONNECTREQD               1239
#define IDC_IMPORT                      1241
#define IDC_TOMAIN                      1243
#define IDC_TOPROTO                     1244
#define IDC_PROTOLIST                   1245
#define IDC_TODEFICON                   1246
#define IDC_IMPORTMULTI                 1247
#define IDC_MAXSIZEHEIGHT               1254
#define IDC_MAXSIZESPIN                 1255
#define IDC_FONTID                      1256
#define IDC_SAMETYPE                    1257
#define IDC_SAMESTYLE                   1258
#define IDC_SAMECOLOUR                  1259
#define IDC_SAMEAS                      1260
#define IDC_TYPEFACE                    1261
#define IDC_BOLD                        1262
#define IDC_ITALIC                      1263
#define IDC_COLOUR                      1264
#define IDC_UNDERLINE                   1265
#define IDC_HOTCOLOUR                   1267
#define IDC_SAMESIZE                    1268
#define IDC_BKGCOLOUR                   1269
#define IDC_FILENAME                    1271
#define IDC_SCROLL                      1277
#define IDC_PROPORTIONAL                1278
#define IDC_SELCOLOUR                   1281
#define IDC_QUICKCOLOUR                 1282
#define IDC_SMOOTHTIME                  1283
#define IDC_SMOOTHTIMESPIN              1284
#define IDC_GREYOUT                     1285
#define IDC_ROWHEIGHT                   1285
#define IDC_ROWHEIGHTSPIN               1286
#define IDC_GREYOUTOPTS                 1288
#define IDC_GROUPINDENT                 1289
#define IDC_GROUPINDENTSPIN             1290
#define IDC_LEFTMARGIN                  1291
#define IDC_SAMPLE                      1292
#define IDC_LEFTMARGINSPIN              1292
#define IDC_FONTSIZE                    1293
#define IDC_STRETCHH                    1298
#define IDC_STRETCHV                    1299
#define IDC_TILEH                       1300
#define IDC_SCRIPT                      1300
#define IDC_TILEV                       1301
#define IDC_GAMMACORRECT                1302
#define IDC_TILEVROWH                   1302
#define IDC_INTERESTS                   1305
#define IDC_EMAILS                      1306
#define IDC_PAST                        1307
#define IDC_HIDEOFFLINEOPTS             1308
#define IDC_PHONES                      1308
#define IDC_SMS                         1310
#define IDC_AREA                        1312
#define IDC_UPDATE                      1313
#define IDC_DONTCYCLE                   1315
#define IDC_PRIMARYSTATUS               1316
#define IDC_CYCLE                       1317
#define IDC_CYCLETIME                   1318
#define IDC_CYCLETIMESPIN               1319
#define IDC_HIDETIMESPIN                1320
#define IDC_MULTITRAY                   1321
#define IDC_ALWAYSMULTI                 1322
#define IDC_SHOWICON                    1323
#define IDC_SHOWPROTO                   1324
#define IDC_SHOWSTATUS                  1325
#define IDC_EQUALSECTIONS               1326
#define IDC_SHOWSIZEGRIP                1327
#define IDC_USEOWNERDRAW                1328
#define IDC_SHOWSBAR                    1329
#define IDC_RIGHTMIRANDA                1330
#define IDC_RIGHTSTATUS                 1331
#define IDC_ININAME                     1333
#define IDC_VIEWINI                     1334
#define IDC_SECURITYINFO                1335
#define IDC_SETTINGNAME                 1336
#define IDC_NEWVALUE                    1337
#define IDC_WARNNOMORE                  1338
#define IDC_DELETE                      1339
#define IDC_RECYCLE                     1340
#define IDC_NEWNAME                     1341
#define IDC_MOVE                        1342
#define IDC_LEAVE                       1343
#define IDC_EXPERT                      1346
#define IDC_SORTBYNAME                  1347
#define IDC_STAUTOHIDESECS              1349
#define IDC_STCLISTGROUP                1350
#define IDC_DISABLEDRAGDROP             1351
#define IDC_NOTEDITLABELS               1352
#define IDC_SHOWSELALWAYS               1353
#define IDC_TRACKSELECT                 1354
#define IDC_SHOWGROUPCOUNTS             1355
#define IDC_HIDECOUNTSWHENEMPTY         1356
#define IDC_DIVIDERONOFF                1357
#define IDC_NOTNOTRANSLUCENTSEL         1358
#define IDC_LINEWITHGROUPS              1359
#define IDC_QUICKSEARCHVISONLY          1360
#define IDC_SORTGROUPSALPHA             1361
#define IDC_NOTNOSMOOTHSCROLLING        1362
#define IDC_BITMAP                      1363
#define IDC_STWINDOWGROUP               1364
#define IDC_STATIC01                    1365
#define IDC_CATEGORYLIST                1366
#define IDC_LOADICONS                   1369
#define IDC_STICONSGROUP                1371
#define IDC_MSGICON                     1375
#define IDC_URLICON                     1376
#define IDC_STNOPAGE                    1377
#define IDC_STCHECKMARKS                1380
#define IDC_STSAMETEXT                  1382
#define IDC_STASTEXT                    1383
#define IDC_STSIZETEXT                  1384
#define IDC_STCOLOURTEXT                1385
#define IDC_STHORZBAR                   1386
#define IDC_MIRANDA                     1388
#define IDC_STATUSBAR                   1389
#define IDC_PROTOIDGROUP                1392
#define IDC_BYPROTOID                   1393
#define IDC_PROTOID                     1394
#define IDC_EMAILGROUP                  1395
#define IDC_BYEMAIL                     1396
#define IDC_STNAMENICK                  1397
#define IDC_NAMEGROUP                   1398
#define IDC_BYNAME                      1399
#define IDC_STNAMEFIRST                 1400
#define IDC_STNAMELAST                  1401
#define IDC_ADVANCEDGROUP               1402
#define IDC_BYADVANCED                  1403
#define IDC_ADVANCED                    1404
#define IDC_STSIMPLERIGHT               1440
#define IDC_NETLIBUSERS                 1443
#define IDC_STOFTENPORT                 1445
#define IDC_STATIC51                    1446
#define IDC_STATIC52                    1447
#define IDC_STATIC43                    1448
#define IDC_LOGOPTIONS                  1449
#define IDC_PORTSRANGE                  1450
#define IDC_TOCONSOLE                   1451
#define IDC_STATIC53                    1451
#define IDC_SHOWCONSOLEATSTART          1452
#define IDC_PORTSRANGEO                 1452
#define IDC_STATIC54                    1453
#define IDC_SHOWCONSOLE                 1454
#define IDC_TOOUTPUTDEBUGSTRING         1455
#define IDC_TOFILE                      1456
#define IDC_CLEARCONSOLE                1457
#define IDC_RUNATSTART                  1458
#define IDC_DUMPSENT                    1464
#define IDC_DUMPPROXY                   1466
#define IDC_TEXTDUMPS                   1467
#define IDC_AUTODETECTTEXT              1468
#define IDC_TIMEFORMAT                  1469
#define IDC_FILENAMEBROWSE              1470
#define IDC_SHOWTHISDLGATSTART          1471
#define IDC_FILEDIRBROWSE               1475
#define IDC_ALLFILESGROUP               1476
#define IDC_SCANCMDLINEBROWSE           1476
#define IDC_ALLTRANSFERRED              1477
#define IDC_OPENFOLDER                  1478
#define IDC_OPENFILE                    1479
#define IDC_TOTALSIZE                   1480
#define IDC_APPENDNICKTODIR             1483
#define IDC_AUTOACCEPT                  1484
#define IDC_SCANCMDLINE                 1485
#define IDC_WARNBEFOREOPENING           1488
#define IDC_SCANDURINGDL                1489
#define IDC_SCANAFTERDL                 1490
#define IDC_NOSCANNER                   1491
#define IDC_ST_CMDLINE                  1492
#define IDC_ST_CMDLINEHELP              1493
#define IDC_PROPERTIES                  1496
#define IDC_RESUME                      1497
#define IDC_EXISTINGICON                1499
#define IDC_RESUMEALL                   1500
#define IDC_OVERWRITE                   1501
#define IDC_OVERWRITEALL                1502
#define IDC_SKIP                        1503
#define IDC_EXISTINGSIZE                1506
#define IDC_EXISTINGDATE                1507
#define IDC_EXISTINGTYPE                1508
#define IDC_NEWICON                     1509
#define IDC_NEWSIZE                     1510
#define IDC_NEWDATE                     1511
#define IDC_NEWTYPE                     1512
#define IDC_SAVEAS                      1513
#define IDC_ASK                         1516
#define IDC_RENAME                      1519
#define IDC_VIRUSSCANNERGROUP           1520
#define IDC_HIDE                        1534
#define IDC_TOPLINE                     1535
#define IDC_GPLBTN                      1536
#define IDC_MAIL                        1536
#define IDC_MYHANDLE                    1540
#define IDC_GROUP                       1541
#define IDC_ADDED                       1542
#define IDC_AUTH                        1543
#define IDC_PLUGINSTATIC1               1559
#define IDC_DELETEHISTORY               1560
#define IDC_HOTKEYURLSTR                1567
#define IDC_SETNASTR                    1568
#define IDC_AAUTHOR                     1569
#define IDC_AHOMEPAGE                   1570
#define IDC_AVERSION                    1571
#define IDC_ACOPYRIGHT                  1572
#define IDC_ADESCRIPTION                1573
#define IDC_PLUGINENABLE                1574
#define IDC_AUTHREQ                     1577
#define IDC_AUTHGB                      1578
#define IDC_BRINGTOFRONT                1579
#define IDC_PROTOCOL                    1580
#define IDC_CONTRIBLINK                 1586
#define IDC_HOMELINK                    1587
#define IDC_SUPPORTLINK                 1588
#define IDC_DEVS                        1589
#define IDC_GPL                         1590
#define IDC_LOGO                        1591
#define IDC_PROTOCOLORDER               1591
#define IDC_PROTOCOLORDERWARNING        1592
#define IDC_CREDITSTEXT                 1595
#define IDC_WSLOCK                      1599
#define IDC_BLINKTIME                   1607
#define IDC_BLINKSPIN                   1608
#define IDC_DISABLEBLINK                1609
#define IDC_IDLE                        1610
#define IDC_SBPANELBEVEL                1611
#define IDC_META                        1611
#define IDC_DROPSHADOW                  1612
#define IDC_METADBLCLK                  1612
#define IDC_NOSCROLLBAR                 1613
#define IDC_METASUBEXTRA                1614
#define IDC_METASUBEXTRA_IGN            1615
#define IDC_METASUB_HIDEOFFLINE         1616
#define IDC_BUTTON1                     1633
#define IDC_IDLECHECK                   1636
#define IDC_IDLEONWINDOWS               1637
#define IDC_IDLEONMIRANDA               1638
#define IDC_IDLEUSEGLI                  1639
#define IDC_SCREENSAVER                 1642
#define IDC_LOCKED                      1643
#define IDC_IDLESHORT                   1644
#define IDC_IDLELONG                    1645
#define IDC_IDLE1STTIME                 1646
#define IDC_IDLE2NDTIME                 1647
#define IDC_IDLEPRIVATE                 1649
#define IDC_AASTATUS                    1650
#define IDC_AASHORTIDLE                 1651
#define IDC_AALONGSTATUS                1652
#define IDC_AALONGIDLE                  1656
#define IDC_NOOFFLINEMOVE               1657
#define IDC_HOTKEYTREE                  1657
#define IDC_LOCATION                    1659
#define IDC_SGROUP                      1660
#define IDC_SLOC                        1661
#define IDC_ONDESKTOP                   1662
#define IDC_SETHOTKEY                   1759
#define IDC_HKTITLE                     1760
#define IDC_CHECK1                      1761
#define IDC_USECONNECTINGICON           1761
#define IDC_BKGRLIST                    1762
#define IDC_BC_STATIC                   1763
#define IDC_SC_STATIC                   1764
#define IDD_OPT_GENMENU                 11267
#define IDC_MENUITEMS                   11710
#define IDC_MENUOBJECTS                 11711
#define IDC_NOTSUPPORTWARNING           11712
#define IDC_INSERTSEPARATOR             11715
#define IDC_GENMENU_SERVICE             11716
#define IDC_GENMENU_CUSTOMNAME          11717
#define IDC_GENMENU_SET                 11718
#define IDC_GENMENU_SET2                11719
#define IDC_GENMENU_DEFAULT             11719
#define IDC_ICONBLINK                   11720
#define IDI_SEARCHALL                   32548
#define ID_ICQ_EXIT                     40001
#define IDM_COPY                        40001
#define ID_RESET                        40002
#define POPUP_HIDEEMPTYGROUPS           40003
#define POPUP_NEWSUBGROUP               40004
#define POPUP_HIDEOFFLINE               40005
#define POPUP_GROUPHIDEOFFLINE          40006
#define POPUP_HIDEOFFLINEROOT           40007
#define POPUP_DISABLEGROUPS             40008
#define IDC_SENDMESSAGE                 40009
#define IDM_COPYALL                     40011
#define IDM_SELECTALL                   40012
#define IDM_CLEAR                       40013
#define IDM_OPENNEW                     40014
#define IDM_OPENEXISTING                40015
#define IDM_COPYLINK                    40016
#define POPUP_HIDEMIRANDA               40017
#define ID_TRAY_HIDE                    40038
#define ID_TRAY_EXIT                    40040
#define POPUP_NEWGROUP                  40050
#define POPUP_RENAMEGROUP               40052
#define POPUP_DELETEGROUP               40053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        347
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1763
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
