//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDC_ALWAYS_VISIBLEICON          0
#define IDC_APPLY                       3
#define IDI_MIRANDA                     102
#define IDD_OPT_ITEM_CONTACT_TIME       102
#define IDI_SMS                         103
#define IDD_OPT_ROWTMPL                 103
#define IDD_OPT_CLIST                   126
#define IDD_OPT_SOUND                   134
#define IDD_OPT_HOTKEYS                 134
#define IDD_OPT_CLIST_LISTBKG           135
#define IDI_URL                         138
#define IDI_FINDUSER                    161
#define IDI_OPTIONS                     163
#define IDI_RENAME                      173
#define IDI_DELETE                      175
#define IDR_CONTEXT                     180
#define IDC_DROP                        183
#define IDI_SENDEMAIL                   193
#define IDR_CLISTMENU                   199
#define IDI_BLANK                       200
#define IDI_NOTICK                      205
#define IDI_TICK                        206
#define IDD_OPT_ICONS                   207
#define IDI_FILE                        207
#define IDI_TIMESTAMP                   208
#define IDI_CHANGEFONT                  209
#define IDI_ADDCONTACT                  210
#define IDI_SMALLDOT                    211
#define IDI_FILLEDBLOB                  212
#define IDD_READAWAYMSG                 213
#define IDI_EMPTYBLOB                   213
#define IDD_OPT_IGNORE                  214
#define IDC_DROPUSER                    215
#define IDD_OPT_VISIBILITY              215
#define IDD_SETAWAYMSG                  216
#define IDI_DETAILSLOGO                 216
#define IDI_HIDE_AVATAR                 217
#define IDD_OPT_AWAYMSG                 217
#define IDI_SHOW_AVATAR                 218
#define IDD_OPT_CLUI                    218
#define IDD_INFO_SUMMARY                220
#define IDD_INFO_CONTACT                221
#define IDD_INFO_BACKGROUND             222
#define IDD_INFO_NOTES                  223
#define IDD_ADDEMAIL                    226
#define IDD_ICONINDEX                   227
#define IDD_OPT_CLC                     228
#define IDD_OPT_CLCTEXT                 229
#define IDD_OPT_TRAY                    229
#define IDD_INFO_LOCATION               231
#define IDD_INFO_WORK                   232
#define IDD_ADDPHONE                    233
#define IDD_OPT_SBAR                    234
#define IDD_INSTALLINI                  235
#define IDD_WARNINICHANGE               236
#define IDD_INIIMPORTDONE               237
#define IDB_SORTCOLUP                   239
#define IDB_SORTCOLDOWN                 240
#define IDD_OPT_NETLIB                  246
#define IDD_NETLIBLOGOPTS               247
#define IDD_FILETRANSFERINFO            249
#define IDD_OPT_FILETRANSFER            250
#define IDD_FILEEXISTS                  251
#define IDD_OPT_SKIN                    251
#define IDD_DELETECONTACT               254
#define IDD_DENYREASON                  256
#define IDD_ADDCONTACT                  257
#define IDD_OPT_CONTACT                 261
#define IDD_OPT_PROTOCOLORDER           262
#define IDI_MULTISEND                   263
#define IDI_DOWNARROW                   264
#define IDD_CREDITS                     265
#define IDD_OPT_IDLE                    268
#define IDD_OPT_META_CLC                279
#define IDI_ACCMGR                      281
#define IDI_NEWGROUP                    282
#define IDI_NEWGROUP2                   283
#define IDD_MODERNOPTS                  288
#define IDI_ICON1                       290
#define IDC_DEFAULTSUB                  293
#define IDC_DROPMETA                    295
#define IDC_CURSOR1                     296
#define IDC_REGROUP                     296
#define IDI_MIRANDA2                    307
#define IDI_CLIENTICQL5                 315
#define IDI_AVATAR_OVERLAY_NA           357
#define IDI_AVATAR_OVERLAY_OCCUPIED     358
#define IDI_AVATAR_OVERLAY_OFFLINE      359
#define IDI_AVATAR_OVERLAY_ONLINE       360
#define IDI_AVATAR_OVERLAY_PHONE        361
#define IDI_ICON9                       362
#define IDI_AVATAR_OVERLAY_AWAY         362
#define IDI_AVATAR_OVERLAY_DND          363
#define IDI_AVATAR_OVERLAY_INVISIBLE    364
#define IDI_AVATAR_OVERLAY_LUNCH        365
#define IDI_ICON4                       366
#define IDI_AVATAR_OVERLAY_CHAT         366
#define IDI_ICQC1                       367
#define IDI_ICQC2                       368
#define IDI_ICQC3                       369
#define IDI_ICQC4                       370
#define IDI_ICQC5                       371
#define IDI_ICQC6                       372
#define IDI_ICQC7                       373
#define IDI_ICQC8                       374
#define IDD_OPT_ITEMS                   385
#define IDD_OPT_ITEM_ROW                386
#define IDD_OPT_ITEM_AVATAR             387
#define IDD_OPT_ITEM_ICON               388
#define IDD_OPT_ITEM_TEXT               389
#define IDD_OPT_ITEM_SECOND_LINE        390
#define IDD_OPT_ITEM_THIRD_LINE         391
#define IDI_ICON2                       396
#define IDI_ICON3                       397
#define IDD_OPT_SKINEDITOR              398
#define IDI_STATUS_OVERLAY_NA           400
#define IDI_STATUS_OVERLAY_OCCUPIED     401
#define IDI_STATUS_OVERLAY_OFFLINE      402
#define IDI_STATUS_OVERLAY_ONLINE       403
#define IDI_STATUS_OVERLAY_PHONE        404
#define IDI_STATUS_OVERLAY_AWAY         405
#define IDI_STATUS_OVERLAY_DND          406
#define IDI_STATUS_OVERLAY_INVISIBLE    407
#define IDI_STATUS_OVERLAY_LUNCH        408
#define IDI_STATUS_OVERLAY_CHAT         409
#define IDR_TGA_DEFAULT_SKIN            413
#define IDR_MSF_DEFAULT_SKIN            413
#define IDD_SKIN_TAB                    415
#define IDI_ROWCONT1                    416
#define IDI_ROWCONT2                    417
#define IDI_ROWCONT3                    418
#define IDD_TAB                         450
#define IDD_OPT_CLUI_2                  451
#define IDI_ALWAYSVIS                   453
#define IDI_ICON6                       454
#define IDI_NEVERVIS                    454
#define IDI_ICON5                       455
#define IDI_CHAT                        455
#define IDI_LISTENING_TO                456
#define IDD_OPT_ITEM_EXTRAICONS         461
#define IDD_OPT_CLCBKG                  462
#define IDI_FAVORITE_0                  500
#define IDI_FAVORITE_1                  501
#define IDI_FAVORITE_2                  502
#define IDI_FAVORITE_3                  503
#define IDI_SETVIEW                     504
#define IDI_RESETVIEW                   505
#define IDD_OPT_TOOLBAR                 507
#define IDC_RESETPROTOCOLDATA           1000
#define IDC_SAVE                        1001
#define IDC_DEFBKCOLOR                  1001
#define IDI_ONTHEPHONE                  1002
#define IDC_MESSAGE                     1002
#define IDI_OUTTOLUNCH                  1003
#define IDC_AUTOCLOSE                   1004
#define IDC_FROM                        1005
#define IDC_AUTOMIN                     1005
#define IDC_DATE                        1006
#define IDC_DUMPRECV                    1006
#define IDC_MSG                         1008
#define IDC_PROXYDNS                    1008
#define IDC_NAME                        1009
#define IDC_PROXYTYPE                   1009
#define IDC_STATIC23                    1010
#define IDC_NAMEVAL                     1010
#define IDC_SPECIFYPORTS                1013
#define IDC_ST_ENTERMSG                 1013
#define IDC_ST_ENTERURL                 1014
#define IDC_SPECIFYPORTSO               1014
#define IDC_TEXT                        1019
#define IDC_SHOWNAMES                   1024
#define IDC_ABOUT                       1032
#define IDC_MYNOTES                     1033
#define IDC_URLS                        1037
#define IDC_REPLY                       1039
#define IDC_URL                         1041
#define IDC_REASON                      1046
#define IDC_EMAIL                       1048
#define IDC_NAMENICK                    1049
#define IDC_NAMEFIRST                   1050
#define IDC_NAMELAST                    1051
#define IDC_NICK                        1053
#define IDC_GENDER                      1060
#define IDC_CITY                        1061
#define IDC_STATE                       1062
#define IDC_COUNTRY                     1063
#define IDC_AGE                         1064
#define IDC_ZIP                         1064
#define IDC_PHONE                       1065
#define IDC_STREET                      1065
#define IDC_COMPANY                     1066
#define IDC_LANGUAGE1                   1066
#define IDC_TIMEZONE                    1067
#define IDC_DEPARTMENT                  1067
#define IDC_LOCALTIME                   1068
#define IDC_DETAILS                     1069
#define IDC_POSITION                    1069
#define IDC_LANGUAGE2                   1069
#define IDC_ADD                         1070
#define IDC_LANGUAGE3                   1070
#define IDC_MOREOPTIONS                 1071
#define IDC_USERMENU                    1071
#define IDC_DN                          1072
#define IDC_MIN2TRAY                    1073
#define IDC_ONTOP                       1074
#define IDC_SHOWMAINMENU                1075
#define IDC_CLIENTDRAG                  1076
#define IDC_EVENTAREA                   1077
#define IDC_EDIT                        1078
#define IDC_LIST                        1079
#define IDC_HISTORY                     1080
#define IDC_USESOUND                    1085
#define IDC_TOOLWND                     1097
#define IDC_ONECLK                      1098
#define IDC_SHOWCAPTION                 1098
#define IDC_HIDEOFFLINE                 1099
#define IDC_SHOWHIDE                    1100
#define IDC_HIDEEMPTYGROUPS             1100
#define IDC_SORTBYSTATUS                1101
#define IDC_FADEINOUT                   1101
#define IDC_READMSG                     1102
#define IDC_AUTOSIZE                    1102
#define IDC_DISABLEGROUPS               1102
#define IDC_AUTOSIZEUPWARD              1103
#define IDC_ALWAYSSTATUS                1103
#define IDC_NETSEARCH                   1104
#define IDC_CONFIRMDELETE               1104
#define IDC_EXTRA_PROTO                 1104
#define IDC_SORTBYPROTO                 1105
#define IDC_SHOWOPTIONS                 1105
#define IDC_EXTRA_EMAIL                 1105
#define IDC_SEARCHURL                   1106
#define IDC_EXTRA_CELLULAR              1106
#define IDC_EXTRA_ADV2                  1107
#define IDC_BUILDTIME                   1108
#define IDC_EXTRA_ADV1                  1108
#define IDC_EXTRA_WEB                   1109
#define IDC_EXTRA_CLIENT                1110
#define IDC_LOCKSIZING                  1111
#define IDC_CHECKKEYCOLOR               1112
#define IDC_NUMBER                      1113
#define IDC_UIN                         1123
#define IDC_TRANSPARENT                 1124
#define IDC_TRANSINACTIVE               1126
#define IDC_TRANSACTIVE                 1128
#define IDC_FINDWHAT                    1131
#define IDC_FIND                        1132
#define IDC_FILE                        1133
#define IDC_PROFILELIST                 1134
#define IDC_NEWPROFILE                  1135
#define IDC_NEWPROFILENAME              1136
#define IDC_TABS                        1141
#define IDC_RESULTS                     1142
#define IDC_STATUS                      1144
#define IDC_SCREENSAVE                  1145
#define IDC_TIMED                       1146
#define IDC_AWAYTIME                    1147
#define IDC_USEPROXY                    1148
#define IDC_SETNA                       1148
#define IDC_PROXYAUTH                   1149
#define IDC_NATIME                      1149
#define IDC_PROXYHOST                   1150
#define IDC_PROXYPORT                   1151
#define IDC_PROXYUSER                   1152
#define IDC_PROXYPASS                   1153
#define IDC_STATIC11                    1154
#define IDC_STATIC12                    1155
#define IDC_STATIC21                    1156
#define IDC_STATIC22                    1157
#define IDC_STATIC31                    1158
#define IDC_STATIC24                    1158
#define IDC_STATIC32                    1159
#define IDC_PROXYAUTHNTLM               1160
#define IDC_HKSHOWHIDE                  1162
#define IDC_HKREADMSG                   1163
#define IDC_SOUNDLIST                   1163
#define IDC_HKSEARCH                    1164
#define IDC_CHANGE                      1164
#define IDC_PREVIEW                     1165
#define IDC_HKSHOWOPTIONS               1165
#define IDC_PLUGINLIST                  1167
#define IDC_FEATURENAME                 1168
#define IDC_CHOOSE                      1169
#define IDC_TO                          1170
#define IDC_ABOUTGROUP                  1175
#define IDC_DESCRIPTION                 1176
#define IDC_AUTHOR                      1177
#define IDC_COPYRIGHT                   1178
#define IDC_VERSION                     1179
#define IDC_HOMEPAGE                    1181
#define IDC_RESTARTREQD                 1182
#define IDC_ICONSET                     1183
#define IDC_BROWSE                      1184
#define IDC_RUNATSTARTBROWSE            1185
#define IDC_PAGETREE                    1186
#define IDC_RUNNOW                      1186
#define IDC_INACTIVEPERC                1187
#define IDC_ACTIVEPERC                  1188
#define IDC_SEARCHNEWWND                1188
#define IDC_RETRIEVING                  1193
#define IDC_TITLETEXT                   1196
#define IDC_GETMORE                     1200
#define IDC_VISIBLEICON                 1204
#define IDC_INVISIBLEICON               1205
#define IDC_FILEICON                    1206
#define IDC_ONLINEICON                  1207
#define IDC_FILENAMES                   1208
#define IDC_ALLICON                     1208
#define IDC_DONTREPLY                   1209
#define IDC_NONEICON                    1209
#define IDC_USEPREVIOUS                 1210
#define IDC_NODIALOG                    1211
#define IDC_BORDER                      1211
#define IDC_USESPECIFIC                 1212
#define IDC_NOBORDERWND                 1212
#define IDC_FILEDIR                     1213
#define IDC_BORDER2                     1213
#define IDC_ROUNDCORNERS                1213
#define IDC_ALLFILESPROGRESS            1217
#define IDC_CURRENTSPEED                1219
#define IDC_STAWAYTYPE                  1220
#define IDC_WHITERECT                   1221
#define IDC_ALLSPEED                    1221
#define IDC_CURRENTFILEPROGRESS         1222
#define IDC_CURRENTFILEGROUP            1223
#define IDC_FIRSTNAME                   1224
#define IDC_LASTNAME                    1225
#define IDC_CURRENTTRANSFERRED          1225
#define IDC_DOBDAY                      1226
#define IDC_DOBMONTH                    1227
#define IDC_WEBPAGE                     1228
#define IDC_DOBYEAR                     1228
#define IDC_UPDATING                    1231
#define IDC_NAMEORDER                   1234
#define IDC_AUTOHIDE                    1235
#define IDC_HIDETIME                    1236
#define IDC_FRAMESGAP                   1237
#define IDC_CAPTIONSGAP                 1238
#define IDC_RECONNECTREQD               1239
#define IDC_HIDETIME2                   1239
#define IDC_SHOWDELAY                   1239
#define IDC_HIDEDELAY                   1240
#define IDC_IMPORT                      1241
#define IDC_HIDEDELAY2                  1241
#define IDC_TOMAIN                      1243
#define IDC_TOPROTO                     1244
#define IDC_PROTOLIST                   1245
#define IDC_TODEFICON                   1246
#define IDC_IMPORTMULTI                 1247
#define IDC_MAXSIZEHEIGHT               1254
#define IDC_MAXSIZESPIN                 1255
#define IDC_FONTID                      1256
#define IDC_MINSIZEHEIGHT               1256
#define IDC_SAMETYPE                    1257
#define IDC_MAXSIZESPIN2                1257
#define IDC_MINSIZESPIN                 1257
#define IDC_SAMESTYLE                   1258
#define IDC_SAMECOLOUR                  1259
#define IDC_SAMEAS                      1260
#define IDC_TYPEFACE                    1261
#define IDC_BOLD                        1262
#define IDC_ITALIC                      1263
#define IDC_COLOUR                      1264
#define IDC_UNDERLINE                   1265
#define IDC_COLOUR_MENUNORMAL           1265
#define IDC_NOTCHECKFONTSIZE            1266
#define IDC_COLOUR_MENU_SELECTED        1266
#define IDC_COLOUR_MENUSELECTED         1266
#define IDC_EFFECT_COLOUR1              1266
#define IDC_HOTCOLOUR                   1267
#define IDC_COLOUR_FRAMES               1267
#define IDC_VARIABLE_ROW_HEIGHT         1267
#define IDC_SAMESIZE                    1268
#define IDC_COLOUR_STATUSBAR            1268
#define IDC_VARIABLE_ROW_HEIGHT2        1268
#define IDC_BKGCOLOUR                   1269
#define IDC_VARIABLE_ROW_HEIGHT3        1269
#define IDC_EFFECT_COLOUR2              1269
#define IDC_TXTCOLOUR                   1270
#define IDC_SAMECOLOUR2                 1270
#define IDC_SAMEEFFECT                  1270
#define IDC_FILENAME                    1271
#define IDC_SCROLL                      1277
#define IDC_PROPORTIONAL                1278
#define IDC_SELCOLOUR                   1281
#define IDC_QUICKCOLOUR                 1282
#define IDC_SELCOLOUR2                  1282
#define IDC_SELTXTCOLOUR                1282
#define IDC_SMOOTHTIME                  1283
#define IDC_SMOOTHTIMESPIN              1284
#define IDC_GREYOUT                     1285
#define IDC_ROWHEIGHT                   1285
#define IDC_ROWHEIGHTSPIN               1286
#define IDC_GREYOUTOPTS                 1288
#define IDC_GROUPINDENT                 1289
#define IDC_GROUPINDENTSPIN             1290
#define IDC_LEFTMARGIN                  1291
#define IDC_SAMPLE                      1292
#define IDC_LEFTMARGINSPIN              1292
#define IDC_FONTSIZE                    1293
#define IDC_LEFTMARGINSPIN2             1294
#define IDC_LEFTMARGIN3                 1295
#define IDC_LEFTMARGINSPIN3             1296
#define IDC_LEFTMARGIN4                 1297
#define IDC_STRETCHH                    1298
#define IDC_STRETCHV                    1299
#define IDC_TILEH                       1300
#define IDC_SCRIPT                      1300
#define IDC_TILEV                       1301
#define IDC_EFFECT_NAME                 1301
#define IDC_GAMMACORRECT                1302
#define IDC_TILEVROWH                   1302
#define IDC_INTERESTS                   1305
#define IDC_EMAILS                      1306
#define IDC_PAST                        1307
#define IDC_HIDEOFFLINEOPTS             1308
#define IDC_PHONES                      1308
#define IDC_SMS                         1310
#define IDC_AREA                        1312
#define IDC_UPDATE                      1313
#define IDC_DONTCYCLE                   1315
#define IDC_PRIMARYSTATUS               1316
#define IDC_CYCLE                       1317
#define IDC_CYCLETIME                   1318
#define IDC_CYCLETIMESPIN               1319
#define IDC_HIDETIMESPIN                1320
#define IDC_MULTITRAY                   1321
#define IDC_FRAMESSPIN                  1321
#define IDC_ALWAYSMULTI                 1322
#define IDC_CAPTIONSSPIN                1322
#define IDC_SHOWICON                    1323
#define IDC_HIDETIMESPIN2               1323
#define IDC_ALWAYSMULTI2                1323
#define IDC_ALWAYSPRIMARY               1323
#define IDC_SHOWPROTO                   1324
#define IDC_HIDETIMESPIN3               1324
#define IDC_SHOWSTATUS                  1325
#define IDC_HIDETIMESPIN4               1325
#define IDC_EQUALSECTIONS               1326
#define IDC_SHOWSIZEGRIP                1327
#define IDC_SHOWXSTATUS                 1327
#define IDC_USEOWNERDRAW                1328
#define IDC_SHOWNORMAL                  1328
#define IDC_SHOWSBAR                    1329
#define IDC_RIGHTMIRANDA                1330
#define IDC_RIGHTSTATUS                 1331
#define IDC_SHOWNORMAL2                 1332
#define IDC_SHOWBOTH                    1332
#define IDC_ININAME                     1333
#define IDC_VIEWINI                     1334
#define IDC_SECURITYINFO                1335
#define IDC_SHOWXSTATUSNAME             1335
#define IDC_SETTINGNAME                 1336
#define IDC_NEWVALUE                    1337
#define IDC_WARNNOMORE                  1338
#define IDC_DELETE                      1339
#define IDC_RECYCLE                     1340
#define IDC_NEWNAME                     1341
#define IDC_MOVE                        1342
#define IDC_LEAVE                       1343
#define IDC_DISABLEENGINE               1343
#define IDC_EXPERT                      1346
#define IDC_SORTBYNAME                  1347
#define IDC_STAUTOHIDESECS              1349
#define IDC_STCLISTGROUP                1350
#define IDC_DISABLEDRAGDROP             1351
#define IDC_NOTEDITLABELS               1352
#define IDC_SHOWSELALWAYS               1353
#define IDC_TRACKSELECT                 1354
#define IDC_SHOWGROUPCOUNTS             1355
#define IDC_HIDECOUNTSWHENEMPTY         1356
#define IDC_DIVIDERONOFF                1357
#define IDC_NOTNOTRANSLUCENTSEL         1358
#define IDC_LINEWITHGROUPS              1359
#define IDC_QUICKSEARCHVISONLY          1360
#define IDC_SORTGROUPSALPHA             1361
#define IDC_NOTNOSMOOTHSCROLLING        1362
#define IDC_BITMAP                      1363
#define IDC_STWINDOWGROUP               1364
#define IDC_STATIC01                    1365
#define IDC_STWINDOWGROUP3              1365
#define IDC_CATEGORYLIST                1366
#define IDC_STATIC2                     1366
#define IDC_STATIC3                     1367
#define IDC_STWINDOWGROUP2              1368
#define IDC_LOADICONS                   1369
#define IDC_STATIC4                     1369
#define IDC_STATIC5                     1370
#define IDC_STICONSGROUP                1371
#define IDC_STATIC6                     1371
#define IDC_STATIC7                     1372
#define IDC_STATIC8                     1373
#define IDC_STATIC9                     1374
#define IDC_MSGICON                     1375
#define IDC_STATIC10                    1375
#define IDC_URLICON                     1376
#define IDC_STATIC13                    1376
#define IDC_STNOPAGE                    1377
#define IDC_STCHECKMARKS                1380
#define IDC_STSAMETEXT                  1382
#define IDC_STASTEXT                    1383
#define IDC_STSIZETEXT                  1384
#define IDC_STSAMETEXT2                 1384
#define IDC_STCOLOURTEXT                1385
#define IDC_STSAMETEXT3                 1385
#define IDC_STHORZBAR                   1386
#define IDC_MIRANDA                     1388
#define IDC_STATUSBAR                   1389
#define IDC_PROTOIDGROUP                1392
#define IDC_BYPROTOID                   1393
#define IDC_PROTOID                     1394
#define IDC_EMAILGROUP                  1395
#define IDC_BYEMAIL                     1396
#define IDC_STNAMENICK                  1397
#define IDC_NAMEGROUP                   1398
#define IDC_BYNAME                      1399
#define IDC_STNAMEFIRST                 1400
#define IDC_STNAMELAST                  1401
#define IDC_ADVANCEDGROUP               1402
#define IDC_BYADVANCED                  1403
#define IDC_ADVANCED                    1404
#define IDC_CHECK13                     1434
#define IDC_STSIMPLERIGHT               1440
#define IDC_NETLIBUSERS                 1443
#define IDC_STOFTENPORT                 1445
#define IDC_STATIC51                    1446
#define IDC_STATIC52                    1447
#define IDC_STATIC43                    1448
#define IDC_LOGOPTIONS                  1449
#define IDC_PORTSRANGE                  1450
#define IDC_TOCONSOLE                   1451
#define IDC_STATIC53                    1451
#define IDC_SHOWCONSOLEATSTART          1452
#define IDC_PORTSRANGEO                 1452
#define IDC_STATIC54                    1453
#define IDC_SHOWCONSOLE                 1454
#define IDC_TOOUTPUTDEBUGSTRING         1455
#define IDC_TOFILE                      1456
#define IDC_CLEARCONSOLE                1457
#define IDC_RUNATSTART                  1458
#define IDC_DUMPSENT                    1464
#define IDC_DUMPPROXY                   1466
#define IDC_TEXTDUMPS                   1467
#define IDC_AUTODETECTTEXT              1468
#define IDC_TIMEFORMAT                  1469
#define IDC_FILENAMEBROWSE              1470
#define IDC_SHOWTHISDLGATSTART          1471
#define IDC_FILEDIRBROWSE               1475
#define IDC_ALLFILESGROUP               1476
#define IDC_SCANCMDLINEBROWSE           1476
#define IDC_ALLTRANSFERRED              1477
#define IDC_OPENFOLDER                  1478
#define IDC_OPENFILE                    1479
#define IDC_TOTALSIZE                   1480
#define IDC_APPENDNICKTODIR             1483
#define IDC_AUTOACCEPT                  1484
#define IDC_SCANCMDLINE                 1485
#define IDC_WARNBEFOREOPENING           1488
#define IDC_SCANDURINGDL                1489
#define IDC_SCANAFTERDL                 1490
#define IDC_NOSCANNER                   1491
#define IDC_ST_CMDLINE                  1492
#define IDC_ST_CMDLINEHELP              1493
#define IDC_PROPERTIES                  1496
#define IDC_RESUME                      1497
#define IDC_EXISTINGICON                1499
#define IDC_RESUMEALL                   1500
#define IDC_OVERWRITE                   1501
#define IDC_OVERWRITEALL                1502
#define IDC_AVATAR_OVERLAY_ICON_CONTACT 1502
#define IDC_SKIP                        1503
#define IDC_EXISTINGSIZE                1506
#define IDC_EXISTINGDATE                1507
#define IDC_EXISTINGTYPE                1508
#define IDC_NEWICON                     1509
#define IDC_NEWSIZE                     1510
#define IDC_NEWDATE                     1511
#define IDC_NEWTYPE                     1512
#define IDC_SAVEAS                      1513
#define IDC_ASK                         1516
#define IDC_RENAME                      1519
#define IDC_VIRUSSCANNERGROUP           1520
#define IDC_HIDE                        1534
#define IDC_TOPLINE                     1535
#define IDC_GPLBTN                      1536
#define IDC_MAIL                        1536
#define IDC_MYHANDLE                    1540
#define IDC_GROUP                       1541
#define IDC_ADDED                       1542
#define IDC_AUTH                        1543
#define IDC_PLUGINSTATIC1               1559
#define IDC_DELETEHISTORY               1560
#define IDC_HOTKEYURLSTR                1567
#define IDC_SETNASTR                    1568
#define IDC_AAUTHOR                     1569
#define IDC_AHOMEPAGE                   1570
#define IDC_AVERSION                    1571
#define IDC_ACOPYRIGHT                  1572
#define IDC_ADESCRIPTION                1573
#define IDC_PLUGINENABLE                1574
#define IDC_AUTHREQ                     1577
#define IDC_AUTHGB                      1578
#define IDC_BRINGTOFRONT                1579
#define IDC_PROTOCOL                    1580
#define IDC_CONTRIBLINK                 1586
#define IDC_HOMELINK                    1587
#define IDC_SUPPORTLINK                 1588
#define IDC_DEVS                        1589
#define IDC_GPL                         1590
#define IDC_LOGO                        1591
#define IDC_PROTOCOLORDER               1591
#define IDC_PROTOCOLORDERWARNING        1592
#define IDC_CREDITSTEXT                 1595
#define IDC_WSLOCK                      1599
#define IDC_BLINKTIME                   1607
#define IDC_BLINKSPIN                   1608
#define IDC_DISABLEBLINK                1609
#define IDC_IDLE                        1610
#define IDC_SBPANELBEVEL                1611
#define IDC_META                        1611
#define IDC_DROPSHADOW                  1612
#define IDC_METADBLCLK                  1612
#define IDC_NOSCROLLBAR                 1613
#define IDC_METAEXPAND                  1613
#define IDC_AEROGLASS                   1613
#define IDC_METASUBEXTRA                1614
#define IDC_METASUBEXTRA_IGN            1615
#define IDC_METASUB_HIDEOFFLINE         1616
#define IDC_MIN_ROW_HEIGHT              1616
#define IDC_MIN_ROW_HEIGHT_SPIN         1617
#define IDC_TXT_TITLE1                  1617
#define IDC_ROW_BORDER                  1618
#define IDC_TXT_TITLE2                  1618
#define IDC_ROW_BORDER_SPIN             1619
#define IDC_AVATAR_SIZE                 1620
#define IDC_TXT_TITLE4                  1620
#define IDC_AVATAR_SIZE_SPIN            1621
#define IDC_ROW_BORDER2                 1622
#define IDC_AVATAR_CUSTOM_CORNER_SIZE   1622
#define IDC_TXT_TITLE5                  1622
#define IDC_ROW_BORDER3                 1623
#define IDC_AVATAR_SIZE_SPIN2           1623
#define IDC_AVATAR_CUSTOM_CORNER_SIZE_SPIN 1623
#define IDC_TXT_TITLE3                  1623
#define IDC_ROW_BORDER_SPIN2            1624
#define IDC_AVATAR_WIDTH                1624
#define IDC_ROW_BORDER_SPIN3            1625
#define IDC_AVATAR_SIZE_SPIN3           1625
#define IDC_AVATAR_WIDTH_SPIN           1625
#define IDC_BUTTON1                     1633
#define IDC_BUTTON_BROWSE               1633
#define IDC_UP                          1633
#define IDC_BUTTON_UP                   1633
#define IDC_DOWN                        1634
#define IDC_C_SPLIT                     1634
#define IDC_PASTE                       1634
#define IDC_BUTTON4                     1634
#define IDC_BUTTON_DOWN                 1634
#define IDC_IDLECHECK                   1636
#define IDC_IDLEONWINDOWS               1637
#define IDC_IDLEONMIRANDA               1638
#define IDC_IDLEUSEGLI                  1639
#define IDC_SCREENSAVER                 1642
#define IDC_LOCKED                      1643
#define IDC_IDLESHORT                   1644
#define IDC_IDLELONG                    1645
#define IDC_IDLE1STTIME                 1646
#define IDC_IDLE2NDTIME                 1647
#define IDC_IDLEPRIVATE                 1649
#define IDC_AASTATUS                    1650
#define IDC_AASHORTIDLE                 1651
#define IDC_AALONGSTATUS                1652
#define IDC_AALONGIDLE                  1656
#define IDC_NOOFFLINEMOVE               1657
#define IDC_HOTKEYTREE                  1657
#define IDC_HILIGHTMODE                 1658
#define IDC_OFFLINETOROOT               1658
#define IDC_HILIGHTMODE2                1659
#define IDC_LOCATION                    1659
#define IDC_HILIGHTMODE1                1660
#define IDC_SGROUP                      1660
#define IDC_HILIGHTMODE3                1661
#define IDC_SLOC                        1661
#define IDC_ONDESKTOP                   1662
#define IDC_HILIGHTMODE4                1663
#define IDC_SETHOTKEY                   1759
#define IDC_HKTITLE                     1760
#define IDC_CHECK1                      1761
#define IDC_USECONNECTINGICON           1761
#define IDC_CHECK_METHOD                1761
#define IDC_AVATAR_CUSTOM_CORNER_SIZE_CHECK 1761
#define IDC_XSTATUS_HAS_PRIORITY        1761
#define IDC_CONTLAYER                   1761
#define IDC_FRAME_META_CAPT             1762
#define IDC_OFFSETICON                  1762
#define IDC_CHECK_COLOR                 1762
#define IDC_SHOW_STATUS_IF_NOAWAY       1762
#define IDC_CHECK6                      1762
#define IDC_CHECK_AUTOSIZE              1762
#define IDC_DISCOVER_AWAYMSG            1763
#define IDC_OFFSETSPIN                  1763
#define IDC_CHECK_IMAGE                 1763
#define IDC_XSTATUS_HAS_PRIORITY2       1763
#define IDC_USE_NAME_AND_MESSAGE        1763
#define IDC_STATUSTEXT                  1763
#define IDC_CHECK9                      1763
#define IDC_DRAGTOSCROLL                1764
#define IDC_OFFSETSUB                   1764
#define IDC_SUBINDENT                   1764
#define IDC_CHECK_ALPHA                 1764
#define IDC_AVATAR_DRAW_BORDER          1764
#define IDC_OFFSETICON2                 1764
#define IDC_SHOW_STATUS_IF_NOAWAY2      1764
#define IDC_SHOW_LISTENING_IF_NOAWAY    1764
#define IDC_CHECK10                     1764
#define IDC_COMBO1                      1765
#define IDC_SUBINDENTSPIN               1765
#define IDC_HIDEMETHOD                  1765
#define IDC_OFFSETSPIN2                 1765
#define IDC_ALIGNGROUPCOMBO             1765
#define IDC_CHECK11                     1765
#define IDC_BKGRLIST                    1766
#define IDC_SUBIDENTCAPT                1766
#define IDC_COMBO_FIT                   1766
#define IDC_OFFSETICON3                 1766
#define IDC_H_ALIGN                     1766
#define IDC_BC_STATIC                   1767
#define IDC_OBJECTSTREE                 1767
#define IDC_OFFSETSPIN3                 1767
#define IDC_REMOVE_OFFLINE_AWAYMSG      1767
#define IDC_V_ALIGN                     1767
#define IDC_SC_STATIC                   1768
#define IDC_COMBO_SAME                  1768
#define IDC_TRANSPARENTOVERLAY          1768
#define IDC_SHOWUNREADEMAIL             1769
#define IDC_IDC_MULTI_COUNT             1771
#define IDC_MULTI_COUNT                 1771
#define IDC_MULTI_SPIN                  1772
#define IDC_EDIT_FILENAME               1773
#define IDC_EDIT_FILENAME2              1774
#define IDC_EDIT_SKIN_FILENAME          1774
#define IDC_OFFSETICON4                 1774
#define IDC_EDIT_LEFT                   1775
#define IDC_EDIT_RIGHT                  1776
#define IDC_EDIT_TOP                    1777
#define IDC_EDIT_BOTTOM                 1778
#define IDC_SPIN_LEFT                   1779
#define IDC_EDIT_ALPHA                  1780
#define IDC_SPIN_RIGHT                  1781
#define IDC_SPIN_TOP                    1782
#define IDC_SPIN_BOTTOM                 1783
#define IDC_SPIN_ALPHA                  1784
#define IDC_BUTTON_LOAD                 1785
#define IDC_BUTTON_SAVE                 1786
#define IDC_FRAME_GLYPH                 1787
#define IDC_BUTTON_LOAD2                1787
#define IDC_BUTTON_APPLY_SKIN           1787
#define IDC_STATIC_SAME                 1788
#define IDC_STATIC_MARGINS              1788
#define IDC_FRAME_BACKGROUND            1789
#define IDC_BUTTON_LOAD3                1789
#define IDC_BUTTON_INFO                 1789
#define IDC_STATIC_STYLE                1790
#define IDC_COMBO_STYLE                 1791
#define IDC_STATIC_COLOR                1792
#define IDC_STATIC_ALPHA                1793
#define IDC_FRAME_IMAGE                 1794
#define IDC_STATIC_LEFT                 1795
#define IDC_STATIC_RIGHT                1796
#define IDC_STATIC_TOP                  1797
#define IDC_STATIC_BOTTOM               1798
#define IDC_STATIC_FIT                  1799
#define IDC_STATIC_COLOR2               1800
#define IDC_AVATAR_ROUND_CORNERS        1800
#define IDC_STATIC_COLOR3               1801
#define IDC_AVATAR_ALIGN_LEFT           1801
#define IDC_DRAW_ON_AVATAR_SPACE        1801
#define IDC_STATIC_COLOR4               1802
#define IDC_AVATAR_OVERLAY_ICONS        1802
#define IDC_STATIC_COLOR5               1803
#define IDC_AVATAR_SIZE_L               1803
#define IDC_AVATAR_SIZE_PIXELS          1804
#define IDC_COLOUR_KEYCOLOR             1805
#define IDC_COLOUR_KEY                  1805
#define IDC_IGNORE_SIZE                 1805
#define IDC_AVATAR_SIZE_PIXELS2         1805
#define IDC_LIST1                       1806
#define IDC_OBJECTSLIST                 1806
#define IDC_IGNORE_SIZE2                1806
#define IDC_ALIGN_RIGHT                 1806
#define IDC_AVATAR_SIZE_PIXELS3         1806
#define IDC_CHECK2                      1807
#define IDC_OBJECTSLIST2                1807
#define IDC_SKINS_LIST                  1807
#define IDC_LAYERENGINE                 1807
#define IDC_CHECK3                      1808
#define IDC_SNAPTOEDGES                 1808
#define IDC_LAYERENGINE2                1808
#define IDC_CHECK4                      1809
#define IDC_SNAPTOEDGES2                1809
#define IDC_DOCKTOSIDES                 1809
#define IDC_CHECK5                      1810
#define IDC_RADIO1                      1811
#define IDC_AVATAR_OVERLAY_ICON_NORMAL  1811
#define IDC_EVENTAREA_NONE              1811
#define IDC_RADIO2                      1812
#define IDC_AVATAR_OVERLAY_ICON_PROTOCOL 1812
#define IDC_RADIO3                      1813
#define IDC_OVERLAY_ICON3               1813
#define IDC_EVENTAREA_ALWAYS            1813
#define IDC_RADIO4                      1814
#define IDC_RADIO5                      1815
#define IDC_CHECK7                      1816
#define IDC_TAB1                        1816
#define IDC_TAB                         1816
#define IDC_RADIO6                      1817
#define IDC_RADIO7                      1818
#define IDC_ALIGN_TO_LEFT               1818
#define IDC_RADIO8                      1819
#define IDC_ALIGN_TO_RIGHT              1819
#define IDC_CHECK8                      1820
#define IDC_LIST_ORDER                  1820
#define IDC_RADIO9                      1820
#define IDC_AVATAR_IGNORE_SIZE          1821
#define IDC_RADIO10                     1821
#define IDC_NOTCHECKICONSIZE            1822
#define IDC_RADIO11                     1822
#define IDC_RTL                         1823
#define IDC_RADIO12                     1823
#define IDC_REPLACE_SMILEYS             1824
#define IDC_RADIO13                     1824
#define IDC_USE_PROTOCOL_SMILEYS        1825
#define IDC_DRAW_SMILEYS_ON_FIRST_LINE  1826
#define IDC_TOP_SPACE                   1827
#define IDC_RESIZE_SMILEYS              1827
#define IDC_TOP_SPACE_SPIN              1828
#define IDC_DRAW_SMILEYS_ON_FIRST_LINE2 1828
#define IDC_APPEND_NICK                 1828
#define IDC_DRAW_SMILEYS                1829
#define IDC_TRIM_TEXT                   1829
#define IDC_EMPTY                       1830
#define IDC_NICKNAME                    1831
#define IDC_STATUS_MESSAGE              1832
#define IDC_VARIABLE_TEXT               1833
#define IDC_DRAW_SMILEYS2               1834
#define IDC_SHOW                        1834
#define IDC_CONTACT_TIME                1835
#define IDC_LISTENING_TO                1836
#define IDC_STATIC_PIXELS               1837
#define IDC_STATIC_TEXT                 1838
#define IDC_AVATAR_BORDER_COLOR_L       1839
#define IDC_AVATAR_BORDER_COLOR         1840
#define IDC_VARIABLES_L                 1841
#define IDC_SHOW_ONLY_IF_DIFFERENT      1842
#define IDC_COMBO2                      1842
#define IDC_EDIT1                       1843
#define IDC_CONTWIDTH                   1843
#define IDC_HIDE_GROUPSICON             1844
#define IDC_STATIC_INFO                 1845
#define IDC_USEXSTATUS                  1845
#define IDC_HIDE_GROUPSICON3            1846
#define IDC_DRAWSTATUSOVERLAY           1846
#define IDC_DESIGNTREE                  1848
#define IDC_TYPE                        1849
#define IDC_R_SPLIT                     1850
#define IDC_PREVIEW_IMAGE               1851
#define IDC_TITLEBAR_STATIC             1852
#define IDC_EFFECT_COLOUR_TEXT1         1853
#define IDC_EFFECT_COLOUR_SPIN1         1854
#define IDC_OBJECT_TREE                 1856
#define IDC_FIT                         1858
#define IDC_E_X                         1862
#define IDC_E_Y                         1863
#define IDC_E_W                         1864
#define IDC_E_H                         1865
#define IDC_E_LEFT                      1866
#define IDC_E_TOP                       1867
#define IDC_E_RIGHT                     1868
#define IDC_E_BOTTOM                    1869
#define IDC_TREE1                       1871
#define IDC_SPIN_POSLEFT                1875
#define IDC_SPIN_POSTOP                 1876
#define IDC_SPIN_WIDTH                  1877
#define IDC_SPIN_HEIGHT                 1878
#define IDC_GROUP_0                     1879
#define IDC_GROUP_1                     1880
#define IDC_GROUP_2                     1881
#define IDC_GROUP_3                     1883
#define IDC_COLOR                       1884
#define IDC_COPY                        1885
#define IDC_ST_COLOUR                   1886
#define IDC_ST_ALPHA                    1887
#define IDC_S_SIZE                      1888
#define IDC_EXTRAORDER                  1889
#define IDC_SKIN_TAB                    1890
#define IDC_ROWTREE                     1955
#define IDC_ADDCONTAINER                1956
#define IDC_BUTTON2                     1957
#define IDC_DELCONTAINER                1957
#define IDC_VALIGN                      1958
#define IDC_HALIGN                      1959
#define IDC_CONTTYPE                    1960
#define IDC_SPINCONTWIDTH               1966
#define IDC_CONTHEIGHT                  1967
#define IDC_SPINCONTHEIGHT              1968
#define IDC_CONTUP                      1969
#define IDC_BUTTON3                     1970
#define IDC_CONTDOWN                    1970
#define IDC_MULTI                       2000
#define IDC_MULTI_2                     2001
#define IDC_FRAMESORDER                 2002
#define IDC_USEWINCOL                   2004
#define IDC_MINIMODE                    2005
#define IDC_BTNORDER                    2006
#define IDC_TBSHOW                      2007
#define IDC_STATIC_W                    2008
#define IDC_STATIC_H                    2009
#define IDC_STATIC_S                    2010
#define IDC_TEXT_W                      2011
#define IDC_TEXT_H                      2012
#define IDC_TEXT_S                      2013
#define IDC_SPIN_W                      2014
#define IDC_SPIN_H                      2015
#define IDC_SPIN_S                      2016
#define IDC_CHECK_MULTILINE             2017
#define IDC_CHECK_ATOSIZE               2018
#define IDC_SBAR_HORIZ_ALIGN            2019
#define IDC_SBAR_TOP_BORDER             2020
#define IDC_SBAR_BOTTOM_BORDER          2021
#define IDC_STATUSBAR_PER_PROTO         2022
#define IDC_OFFSETICON_RIGHT            2023
#define IDC_OFFSETSPIN_RIGHT            2024
#define IDC_OFFSETICON_LEFT             2025
#define IDC_OFFSETSPIN_LEFT             2026
#define IDC_STATUSBAR_PROTO_LIST        2027
#define IDC_SBAR_USE_ACCOUNT_SETTINGS   2028
#define IDC_SBAR_HIDE_ACCOUNT_COMPLETELY 2029
#define IDC_SBAR_BORDER_TOP             2030
#define IDC_SBAR_BORDER_TOP_SPIN        2031
#define IDC_SBAR_BORDER_BOTTOM          2032
#define IDC_SBAR_BORDER_BOTTOM_SPIN     2033
#define IDC_SBAR_VERT_ALIGN             2034
#define IDC_CLSORT1                     6666
#define IDC_CLSORT2                     6667
#define IDC_CLSORT3                     6668
#define IDC_WINCOLOUR                   6669
#define IDD_OPT_CLCBKG3                 11268
#define IDD_OPT_EXTFRAMES               11269
#define IDC_MENUITEMS                   11710
#define IDC_MENUOBJECTS                 11711
#define IDC_NOTSUPPORTWARNING           11712
#define IDC_INSERTSEPARATOR             11715
#define IDC_GENMENU_SERVICE             11716
#define IDC_GENMENU_CUSTOMNAME          11717
#define IDC_GENMENU_SET                 11718
#define IDC_GENMENU_SET2                11719
#define IDC_GENMENU_DEFAULT             11719
#define IDC_ICONBLINK                   11720
#define IDC_ICONBLINK2                  11721
#define IDC_SHOW_AVATARS                11721
#define IDC_SHOW_AVATARS2               11722
#define IDC_SHOW_ANIAVATARS             11722
#define IDC_SHOW_STATUSMSG              11723
#define IDC_HIDE_ICON_ON_AVATAR         11723
#define IDC_SHOW_ANIAVATARS2            11723
#define IDC_AVATAR_FASTDRAW             11723
#define IDC_SHOW_STATUSMSG2             11724
#define IDC_SHOW_STATUS_MSG             11724
#define IDC_SUBIDENTCAPT2               11767
#define IDC_SUBIDENTCAPT3               11768
#define IDC_SUBIDENTCAPT4               11769
#define IDC_RIGHTMARGIN                 11800
#define IDC_TOPMARGIN                   11801
#define IDC_BOTTOMMARGIN                11802
#define IDC_RIGHTMARGINSPIN             11803
#define IDC_EFFECT_COLOUR_TEXT2         11803
#define IDC_TOPMARGINSPIN               11804
#define IDC_BOTTOMMARGINSPIN            11805
#define IDC_EFFECT_COLOUR_SPIN2         11806
#define IDC_LEFTMARGIN2                 12931
#define IDC_LEFTMARGINSPIN4             12981
#define IDD_OPT_VIEWMODES               19100
#define IDC_VIEWMODES                   19102
#define IDC_PROTOCOLS                   19103
#define IDC_ADDVIEWMODE                 19104
#define IDC_DELETEVIEWMODE              19105
#define IDC_NEWVIEMODE                  19106
#define IDC_GROUPS                      19107
#define IDC_STATUSMODES                 19108
#define IDC_CLIST                       19109
#define IDC_CLEARALL                    19110
#define IDC_PROTOGROUPOP                19111
#define IDC_GROUPSTATUSOP               19112
#define IDC_STATIC14                    19113
#define IDC_AUTOCLEAR                   19114
#define IDC_AUTOCLEARVAL                19115
#define IDC_AUTOCLEARSPIN               19116
#define IDC_STATIC15                    19117
#define IDC_STATIC16                    19118
#define IDC_CURVIEWMODE2                19119
#define IDC_LASTMSG                     19120
#define IDC_LASTMESSAGEOP               19121
#define IDC_LASTMSGVALUE                19122
#define IDC_LASTMESSAGEUNIT             19123
#define IDC_STATIC1                     19124
#define IDC_RESETMODES                  19125
#define IDC_LASTMSG2                    19125
#define IDC_SELECTMODE                  19126
#define IDC_CONFIGUREMODES              19127
#define IDC_USEGROUPS                   19128
#define IDI_SEARCHALL                   32548
#define ID_ICQ_EXIT                     40001
#define IDM_COPY                        40001
#define ID_RESET                        40002
#define POPUP_HIDEEMPTYGROUPS           40003
#define POPUP_NEWSUBGROUP               40004
#define POPUP_HIDEOFFLINE               40005
#define POPUP_GROUPHIDEOFFLINE          40006
#define POPUP_HIDEOFFLINEROOT           40007
#define POPUP_DISABLEGROUPS             40008
#define IDC_SENDMESSAGE                 40009
#define IDM_COPYALL                     40011
#define IDM_SELECTALL                   40012
#define IDM_CLEAR                       40013
#define IDM_OPENNEW                     40014
#define IDM_OPENEXISTING                40015
#define IDM_COPYLINK                    40016
#define POPUP_HIDEMIRANDA               40017
#define POPUP_GROUPSHOWOFFLINE          40019
#define ID_MINIMIZE                     40021
#define ID_TRAY_HIDE                    40038
#define ID_TRAY_EXIT                    40040
#define POPUP_NEWGROUP                  40050
#define POPUP_RENAMEGROUP               40052
#define POPUP_DELETEGROUP               40053
#define IDC_FRAME_META                  40054
#define IDC_FRAME_META2                 40055
#define IDC_STATIC						-1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        509
#define _APS_NEXT_COMMAND_VALUE         40022
#define _APS_NEXT_CONTROL_VALUE         2024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
