const
  IDI_PREV_NORMAL    = 1;
  IDI_PREV_HOVERED   = 2;
  IDI_PREV_PRESSED   = 3;
                    
  IDI_PLAY_NORMAL    = 4;
  IDI_PLAY_HOVERED   = 5;
  IDI_PLAY_PRESSED   = 6;
                    
  IDI_PAUSE_NORMAL   = 7;
  IDI_PAUSE_HOVERED  = 8;
  IDI_PAUSE_PRESSED  = 9;
                    
  IDI_STOP_NORMAL    = 10;
  IDI_STOP_HOVERED   = 11;
  IDI_STOP_PRESSED   = 12;
                    
  IDI_NEXT_NORMAL    = 13;
  IDI_NEXT_HOVERED   = 14;
  IDI_NEXT_PRESSED   = 15;
                    
  IDI_VOLDN_NORMAL   = 16;
  IDI_VOLDN_HOVERED  = 17;
  IDI_VOLDN_PRESSED  = 18;
                    
  IDI_VOLUP_NORMAL   = 19;
  IDI_VOLUP_HOVERED  = 20;
  IDI_VOLUP_PRESSED  = 21;
                    
  IDI_SLIDER_NORMAL  = 22;
  IDI_SLIDER_HOVERED = 23;
  IDI_SLIDER_PRESSED = 24;

  IDI_PLUGIN_ENABLE  = 100;
  IDI_PLUGIN_DISABLE = 101;
