#!/bin/sh
# Copyright (C) 1999, 2002, 2003 Free Software Foundation, Inc.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This file is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
isubdirafter=""

output=""
mt=no

usage()
{
    cat <<EOF
Usage: gpg-error-config [OPTIONS]
Options:
        [--mt]       (must be the first option)
	[--prefix]
	[--exec-prefix]
	[--version]
	[--libs]
	[--cflags]
EOF
    exit $1
}

if test $# -eq 0; then
    usage 1 1>&2
fi

while test $# -gt 0; do
    case "$1" in
	-*=*)
	    optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	    ;;
	*)
	    optarg=
	    ;;
    esac

    case $1 in
        --mt)
            mt=yes
            ;;
        --prefix)
	    output="$output $prefix"
	    ;;
        --exec-prefix)
	    output="$output $exec_prefix"
	    ;;
        --version)
            echo "1.18"
	    exit 0
	    ;;
        --cflags)
	    if test "x$includedir" != "x/usr/include" -a "x$includedir" != "x/include"; then
		output="$output -I$includedir"
	    fi
            # Note: -idirafter is a gcc extension.  It is only used on
            #       systems where gcc is the only compiler we support.
            for i in $isubdirafter; do
                output="$output -idirafter ${includedir}/${i}"
            done
	    output="$output "
            if test $mt = yes ; then
                output="$output "
            fi
	    ;;
	--libs)
	    case "$libdir" in
		/usr/lib|/usr/lib64|/lib|/lib64) ;;
		*)
		    output="$output -L$libdir"
		    ;;
	    esac
	    output="$output -lgpg-error"
            if test $mt = yes ; then
                output="$output "
            fi
	    ;;
        --host)
            echo "x86_64-pc-mingw32"
            exit 0
            ;;
	*)
            usage 1 1>&2
	    ;;
    esac
    shift
done

echo $output
