#ifdef _MSC_VER
#include "..\auto.h"
#else
#include "auto.h"
#endif
#include <assert.h>
struct paramed_type *tglf_extf_store (struct tgl_state *TLS, const char *data, int data_len);
int tglf_store_type (struct tgl_state *TLS, const char *work, int work_len, struct paramed_type *P);
int store_constructor_account_days_t_t_l (struct paramed_type *T);
int store_constructor_audio_empty (struct paramed_type *T);
int store_constructor_audio (struct paramed_type *T);
int store_constructor_authorization (struct paramed_type *T);
int store_constructor_bool_false (struct paramed_type *T);
int store_constructor_bool_true (struct paramed_type *T);
int store_constructor_bot_command (struct paramed_type *T);
int store_constructor_bot_command_old (struct paramed_type *T);
int store_constructor_bot_info_empty (struct paramed_type *T);
int store_constructor_bot_info (struct paramed_type *T);
int store_constructor_bytes (struct paramed_type *T);
int store_constructor_chat_empty (struct paramed_type *T);
int store_constructor_chat (struct paramed_type *T);
int store_constructor_chat_forbidden (struct paramed_type *T);
int store_constructor_geo_chat (struct paramed_type *T);
int store_constructor_chat_full (struct paramed_type *T);
int store_constructor_chat_invite_already (struct paramed_type *T);
int store_constructor_chat_invite (struct paramed_type *T);
int store_constructor_chat_located (struct paramed_type *T);
int store_constructor_chat_participant (struct paramed_type *T);
int store_constructor_chat_participants_forbidden (struct paramed_type *T);
int store_constructor_chat_participants (struct paramed_type *T);
int store_constructor_chat_photo_empty (struct paramed_type *T);
int store_constructor_chat_photo (struct paramed_type *T);
int store_constructor_client_d_h_inner_data (struct paramed_type *T);
int store_constructor_config (struct paramed_type *T);
int store_constructor_contact (struct paramed_type *T);
int store_constructor_contact_blocked (struct paramed_type *T);
int store_constructor_contact_found (struct paramed_type *T);
int store_constructor_contact_link_unknown (struct paramed_type *T);
int store_constructor_contact_link_none (struct paramed_type *T);
int store_constructor_contact_link_has_phone (struct paramed_type *T);
int store_constructor_contact_link_contact (struct paramed_type *T);
int store_constructor_contact_status (struct paramed_type *T);
int store_constructor_contact_suggested (struct paramed_type *T);
int store_constructor_dc_option_l28 (struct paramed_type *T);
int store_constructor_dc_option (struct paramed_type *T);
int store_constructor_decrypted_message (struct paramed_type *T);
int store_constructor_decrypted_message_service (struct paramed_type *T);
int store_constructor_decrypted_message_action_set_message_t_t_l (struct paramed_type *T);
int store_constructor_decrypted_message_action_read_messages (struct paramed_type *T);
int store_constructor_decrypted_message_action_delete_messages (struct paramed_type *T);
int store_constructor_decrypted_message_action_screenshot_messages (struct paramed_type *T);
int store_constructor_decrypted_message_action_flush_history (struct paramed_type *T);
int store_constructor_decrypted_message_action_resend (struct paramed_type *T);
int store_constructor_decrypted_message_action_notify_layer (struct paramed_type *T);
int store_constructor_decrypted_message_action_typing (struct paramed_type *T);
int store_constructor_decrypted_message_action_request_key (struct paramed_type *T);
int store_constructor_decrypted_message_action_accept_key (struct paramed_type *T);
int store_constructor_decrypted_message_action_abort_key (struct paramed_type *T);
int store_constructor_decrypted_message_action_commit_key (struct paramed_type *T);
int store_constructor_decrypted_message_action_noop (struct paramed_type *T);
int store_constructor_decrypted_message_layer (struct paramed_type *T);
int store_constructor_decrypted_message_media_empty (struct paramed_type *T);
int store_constructor_decrypted_message_media_photo (struct paramed_type *T);
int store_constructor_decrypted_message_media_geo_point (struct paramed_type *T);
int store_constructor_decrypted_message_media_contact (struct paramed_type *T);
int store_constructor_decrypted_message_media_document (struct paramed_type *T);
int store_constructor_decrypted_message_media_video (struct paramed_type *T);
int store_constructor_decrypted_message_media_audio (struct paramed_type *T);
int store_constructor_decrypted_message_media_external_document (struct paramed_type *T);
int store_constructor_decrypted_message_media_video_l12 (struct paramed_type *T);
int store_constructor_decrypted_message_media_audio_l12 (struct paramed_type *T);
int store_constructor_dialog (struct paramed_type *T);
int store_constructor_disabled_feature (struct paramed_type *T);
int store_constructor_document_empty (struct paramed_type *T);
int store_constructor_document (struct paramed_type *T);
int store_constructor_document_l19 (struct paramed_type *T);
int store_constructor_document_attribute_image_size (struct paramed_type *T);
int store_constructor_document_attribute_animated (struct paramed_type *T);
int store_constructor_document_attribute_sticker_l28 (struct paramed_type *T);
int store_constructor_document_attribute_sticker (struct paramed_type *T);
int store_constructor_document_attribute_video (struct paramed_type *T);
int store_constructor_document_attribute_audio (struct paramed_type *T);
int store_constructor_document_attribute_filename (struct paramed_type *T);
int store_constructor_double (struct paramed_type *T);
int store_constructor_encrypted_chat_empty (struct paramed_type *T);
int store_constructor_encrypted_chat_waiting (struct paramed_type *T);
int store_constructor_encrypted_chat_requested (struct paramed_type *T);
int store_constructor_encrypted_chat (struct paramed_type *T);
int store_constructor_encrypted_chat_discarded (struct paramed_type *T);
int store_constructor_encrypted_file_empty (struct paramed_type *T);
int store_constructor_encrypted_file (struct paramed_type *T);
int store_constructor_encrypted_message (struct paramed_type *T);
int store_constructor_encrypted_message_service (struct paramed_type *T);
int store_constructor_error (struct paramed_type *T);
int store_constructor_chat_invite_empty (struct paramed_type *T);
int store_constructor_chat_invite_exported (struct paramed_type *T);
int store_constructor_file_location_unavailable (struct paramed_type *T);
int store_constructor_file_location (struct paramed_type *T);
int store_constructor_geo_chat_message_empty (struct paramed_type *T);
int store_constructor_geo_chat_message (struct paramed_type *T);
int store_constructor_geo_chat_message_service (struct paramed_type *T);
int store_constructor_geo_point_empty (struct paramed_type *T);
int store_constructor_geo_point (struct paramed_type *T);
int store_constructor_imported_contact (struct paramed_type *T);
int store_constructor_input_app_event (struct paramed_type *T);
int store_constructor_input_audio_empty (struct paramed_type *T);
int store_constructor_input_audio (struct paramed_type *T);
int store_constructor_input_chat_photo_empty (struct paramed_type *T);
int store_constructor_input_chat_uploaded_photo (struct paramed_type *T);
int store_constructor_input_chat_photo (struct paramed_type *T);
int store_constructor_input_phone_contact (struct paramed_type *T);
int store_constructor_input_document_empty (struct paramed_type *T);
int store_constructor_input_document (struct paramed_type *T);
int store_constructor_input_encrypted_chat (struct paramed_type *T);
int store_constructor_input_encrypted_file_empty (struct paramed_type *T);
int store_constructor_input_encrypted_file_uploaded (struct paramed_type *T);
int store_constructor_input_encrypted_file (struct paramed_type *T);
int store_constructor_input_encrypted_file_big_uploaded (struct paramed_type *T);
int store_constructor_input_file (struct paramed_type *T);
int store_constructor_input_file_big (struct paramed_type *T);
int store_constructor_input_file_location (struct paramed_type *T);
int store_constructor_input_video_file_location (struct paramed_type *T);
int store_constructor_input_encrypted_file_location (struct paramed_type *T);
int store_constructor_input_audio_file_location (struct paramed_type *T);
int store_constructor_input_document_file_location (struct paramed_type *T);
int store_constructor_input_geo_chat (struct paramed_type *T);
int store_constructor_input_geo_point_empty (struct paramed_type *T);
int store_constructor_input_geo_point (struct paramed_type *T);
int store_constructor_input_media_empty (struct paramed_type *T);
int store_constructor_input_media_uploaded_photo (struct paramed_type *T);
int store_constructor_input_media_photo (struct paramed_type *T);
int store_constructor_input_media_geo_point (struct paramed_type *T);
int store_constructor_input_media_contact (struct paramed_type *T);
int store_constructor_input_media_uploaded_video (struct paramed_type *T);
int store_constructor_input_media_uploaded_thumb_video (struct paramed_type *T);
int store_constructor_input_media_video (struct paramed_type *T);
int store_constructor_input_media_uploaded_audio (struct paramed_type *T);
int store_constructor_input_media_audio (struct paramed_type *T);
int store_constructor_input_media_uploaded_document (struct paramed_type *T);
int store_constructor_input_media_uploaded_thumb_document (struct paramed_type *T);
int store_constructor_input_media_document (struct paramed_type *T);
int store_constructor_input_media_venue (struct paramed_type *T);
int store_constructor_input_notify_peer (struct paramed_type *T);
int store_constructor_input_notify_users (struct paramed_type *T);
int store_constructor_input_notify_chats (struct paramed_type *T);
int store_constructor_input_notify_all (struct paramed_type *T);
int store_constructor_input_notify_geo_chat_peer (struct paramed_type *T);
int store_constructor_input_peer_empty (struct paramed_type *T);
int store_constructor_input_peer_self (struct paramed_type *T);
int store_constructor_input_peer_contact (struct paramed_type *T);
int store_constructor_input_peer_foreign (struct paramed_type *T);
int store_constructor_input_peer_chat (struct paramed_type *T);
int store_constructor_input_peer_notify_events_empty (struct paramed_type *T);
int store_constructor_input_peer_notify_events_all (struct paramed_type *T);
int store_constructor_input_peer_notify_settings (struct paramed_type *T);
int store_constructor_input_photo_empty (struct paramed_type *T);
int store_constructor_input_photo (struct paramed_type *T);
int store_constructor_input_photo_crop_auto (struct paramed_type *T);
int store_constructor_input_photo_crop (struct paramed_type *T);
int store_constructor_input_privacy_key_status_timestamp (struct paramed_type *T);
int store_constructor_input_privacy_value_allow_contacts (struct paramed_type *T);
int store_constructor_input_privacy_value_allow_all (struct paramed_type *T);
int store_constructor_input_privacy_value_allow_users (struct paramed_type *T);
int store_constructor_input_privacy_value_disallow_contacts (struct paramed_type *T);
int store_constructor_input_privacy_value_disallow_all (struct paramed_type *T);
int store_constructor_input_privacy_value_disallow_users (struct paramed_type *T);
int store_constructor_input_sticker_set_empty (struct paramed_type *T);
int store_constructor_input_sticker_set_i_d (struct paramed_type *T);
int store_constructor_input_sticker_set_short_name (struct paramed_type *T);
int store_constructor_input_user_empty (struct paramed_type *T);
int store_constructor_input_user_self (struct paramed_type *T);
int store_constructor_input_user_contact (struct paramed_type *T);
int store_constructor_input_user_foreign (struct paramed_type *T);
int store_constructor_input_video_empty (struct paramed_type *T);
int store_constructor_input_video (struct paramed_type *T);
int store_constructor_int (struct paramed_type *T);
int store_constructor_int128 (struct paramed_type *T);
int store_constructor_int256 (struct paramed_type *T);
int store_constructor_keyboard_button (struct paramed_type *T);
int store_constructor_keyboard_button_row (struct paramed_type *T);
int store_constructor_long (struct paramed_type *T);
int store_constructor_message_empty (struct paramed_type *T);
int store_constructor_message (struct paramed_type *T);
int store_constructor_message_service (struct paramed_type *T);
int store_constructor_message_action_empty (struct paramed_type *T);
int store_constructor_message_action_chat_create (struct paramed_type *T);
int store_constructor_message_action_chat_edit_title (struct paramed_type *T);
int store_constructor_message_action_chat_edit_photo (struct paramed_type *T);
int store_constructor_message_action_chat_delete_photo (struct paramed_type *T);
int store_constructor_message_action_chat_add_user (struct paramed_type *T);
int store_constructor_message_action_chat_delete_user (struct paramed_type *T);
int store_constructor_message_action_geo_chat_create (struct paramed_type *T);
int store_constructor_message_action_geo_chat_checkin (struct paramed_type *T);
int store_constructor_message_action_chat_joined_by_link (struct paramed_type *T);
int store_constructor_message_media_empty (struct paramed_type *T);
int store_constructor_message_media_photo (struct paramed_type *T);
int store_constructor_message_media_video (struct paramed_type *T);
int store_constructor_message_media_geo (struct paramed_type *T);
int store_constructor_message_media_contact (struct paramed_type *T);
int store_constructor_message_media_unsupported (struct paramed_type *T);
int store_constructor_message_media_document (struct paramed_type *T);
int store_constructor_message_media_audio (struct paramed_type *T);
int store_constructor_message_media_web_page (struct paramed_type *T);
int store_constructor_message_media_venue (struct paramed_type *T);
int store_constructor_message_media_photo_l27 (struct paramed_type *T);
int store_constructor_message_media_video_l27 (struct paramed_type *T);
int store_constructor_input_messages_filter_empty (struct paramed_type *T);
int store_constructor_input_messages_filter_photos (struct paramed_type *T);
int store_constructor_input_messages_filter_video (struct paramed_type *T);
int store_constructor_input_messages_filter_photo_video (struct paramed_type *T);
int store_constructor_input_messages_filter_photo_video_documents (struct paramed_type *T);
int store_constructor_input_messages_filter_document (struct paramed_type *T);
int store_constructor_input_messages_filter_audio (struct paramed_type *T);
int store_constructor_nearest_dc (struct paramed_type *T);
int store_constructor_notify_peer (struct paramed_type *T);
int store_constructor_notify_users (struct paramed_type *T);
int store_constructor_notify_chats (struct paramed_type *T);
int store_constructor_notify_all (struct paramed_type *T);
int store_constructor_null (struct paramed_type *T);
int store_constructor_p_q_inner_data (struct paramed_type *T);
int store_constructor_p_q_inner_data_temp (struct paramed_type *T);
int store_constructor_peer_user (struct paramed_type *T);
int store_constructor_peer_chat (struct paramed_type *T);
int store_constructor_peer_notify_events_empty (struct paramed_type *T);
int store_constructor_peer_notify_events_all (struct paramed_type *T);
int store_constructor_peer_notify_settings_empty (struct paramed_type *T);
int store_constructor_peer_notify_settings (struct paramed_type *T);
int store_constructor_photo_empty (struct paramed_type *T);
int store_constructor_photo (struct paramed_type *T);
int store_constructor_photo_l27 (struct paramed_type *T);
int store_constructor_photo_size_empty (struct paramed_type *T);
int store_constructor_photo_size (struct paramed_type *T);
int store_constructor_photo_cached_size (struct paramed_type *T);
int store_constructor_privacy_key_status_timestamp (struct paramed_type *T);
int store_constructor_privacy_value_allow_contacts (struct paramed_type *T);
int store_constructor_privacy_value_allow_all (struct paramed_type *T);
int store_constructor_privacy_value_allow_users (struct paramed_type *T);
int store_constructor_privacy_value_disallow_contacts (struct paramed_type *T);
int store_constructor_privacy_value_disallow_all (struct paramed_type *T);
int store_constructor_privacy_value_disallow_users (struct paramed_type *T);
int store_constructor_received_notify_message (struct paramed_type *T);
int store_constructor_reply_keyboard_hide (struct paramed_type *T);
int store_constructor_reply_keyboard_force_reply (struct paramed_type *T);
int store_constructor_reply_keyboard_markup (struct paramed_type *T);
int store_constructor_res_p_q (struct paramed_type *T);
int store_constructor_send_message_typing_action (struct paramed_type *T);
int store_constructor_send_message_cancel_action (struct paramed_type *T);
int store_constructor_send_message_record_video_action (struct paramed_type *T);
int store_constructor_send_message_upload_video_action_l27 (struct paramed_type *T);
int store_constructor_send_message_upload_video_action (struct paramed_type *T);
int store_constructor_send_message_record_audio_action (struct paramed_type *T);
int store_constructor_send_message_upload_audio_action_l27 (struct paramed_type *T);
int store_constructor_send_message_upload_audio_action (struct paramed_type *T);
int store_constructor_send_message_upload_photo_action (struct paramed_type *T);
int store_constructor_send_message_upload_document_action_l27 (struct paramed_type *T);
int store_constructor_send_message_upload_document_action (struct paramed_type *T);
int store_constructor_send_message_geo_location_action (struct paramed_type *T);
int store_constructor_send_message_choose_contact_action (struct paramed_type *T);
int store_constructor_server_d_h_params_fail (struct paramed_type *T);
int store_constructor_server_d_h_params_ok (struct paramed_type *T);
int store_constructor_server_d_h_inner_data (struct paramed_type *T);
int store_constructor_dh_gen_ok (struct paramed_type *T);
int store_constructor_dh_gen_retry (struct paramed_type *T);
int store_constructor_dh_gen_fail (struct paramed_type *T);
int store_constructor_sticker_pack (struct paramed_type *T);
int store_constructor_sticker_set (struct paramed_type *T);
int store_constructor_string (struct paramed_type *T);
int store_constructor_update_new_message (struct paramed_type *T);
int store_constructor_update_message_i_d (struct paramed_type *T);
int store_constructor_update_delete_messages (struct paramed_type *T);
int store_constructor_update_user_typing (struct paramed_type *T);
int store_constructor_update_chat_user_typing (struct paramed_type *T);
int store_constructor_update_chat_participants (struct paramed_type *T);
int store_constructor_update_user_status (struct paramed_type *T);
int store_constructor_update_user_name (struct paramed_type *T);
int store_constructor_update_user_photo (struct paramed_type *T);
int store_constructor_update_contact_registered (struct paramed_type *T);
int store_constructor_update_contact_link (struct paramed_type *T);
int store_constructor_update_new_authorization (struct paramed_type *T);
int store_constructor_update_new_geo_chat_message (struct paramed_type *T);
int store_constructor_update_new_encrypted_message (struct paramed_type *T);
int store_constructor_update_encrypted_chat_typing (struct paramed_type *T);
int store_constructor_update_encryption (struct paramed_type *T);
int store_constructor_update_encrypted_messages_read (struct paramed_type *T);
int store_constructor_update_chat_participant_add (struct paramed_type *T);
int store_constructor_update_chat_participant_delete (struct paramed_type *T);
int store_constructor_update_dc_options (struct paramed_type *T);
int store_constructor_update_user_blocked (struct paramed_type *T);
int store_constructor_update_notify_settings (struct paramed_type *T);
int store_constructor_update_service_notification (struct paramed_type *T);
int store_constructor_update_privacy (struct paramed_type *T);
int store_constructor_update_user_phone (struct paramed_type *T);
int store_constructor_update_read_history_inbox (struct paramed_type *T);
int store_constructor_update_read_history_outbox (struct paramed_type *T);
int store_constructor_update_web_page (struct paramed_type *T);
int store_constructor_update_read_messages_contents (struct paramed_type *T);
int store_constructor_update_msg_update (struct paramed_type *T);
int store_constructor_updates_too_long (struct paramed_type *T);
int store_constructor_update_short_message (struct paramed_type *T);
int store_constructor_update_short_chat_message (struct paramed_type *T);
int store_constructor_update_short (struct paramed_type *T);
int store_constructor_updates_combined (struct paramed_type *T);
int store_constructor_updates (struct paramed_type *T);
int store_constructor_user_empty (struct paramed_type *T);
int store_constructor_user (struct paramed_type *T);
int store_constructor_user_full (struct paramed_type *T);
int store_constructor_user_profile_photo_empty (struct paramed_type *T);
int store_constructor_user_profile_photo (struct paramed_type *T);
int store_constructor_user_status_empty (struct paramed_type *T);
int store_constructor_user_status_online (struct paramed_type *T);
int store_constructor_user_status_offline (struct paramed_type *T);
int store_constructor_user_status_recently (struct paramed_type *T);
int store_constructor_user_status_last_week (struct paramed_type *T);
int store_constructor_user_status_last_month (struct paramed_type *T);
int store_constructor_vector (struct paramed_type *T);
int store_constructor_video_empty (struct paramed_type *T);
int store_constructor_video (struct paramed_type *T);
int store_constructor_video_l27 (struct paramed_type *T);
int store_constructor_wall_paper (struct paramed_type *T);
int store_constructor_wall_paper_solid (struct paramed_type *T);
int store_constructor_web_page_empty (struct paramed_type *T);
int store_constructor_web_page_pending (struct paramed_type *T);
int store_constructor_web_page (struct paramed_type *T);
int store_constructor_account_authorizations (struct paramed_type *T);
int store_constructor_account_no_password (struct paramed_type *T);
int store_constructor_account_password (struct paramed_type *T);
int store_constructor_account_password_input_settings (struct paramed_type *T);
int store_constructor_account_password_settings (struct paramed_type *T);
int store_constructor_account_privacy_rules (struct paramed_type *T);
int store_constructor_account_sent_change_phone_code (struct paramed_type *T);
int store_constructor_auth_authorization (struct paramed_type *T);
int store_constructor_auth_checked_phone (struct paramed_type *T);
int store_constructor_auth_exported_authorization (struct paramed_type *T);
int store_constructor_auth_password_recovery (struct paramed_type *T);
int store_constructor_auth_sent_code (struct paramed_type *T);
int store_constructor_auth_sent_app_code (struct paramed_type *T);
int store_constructor_binlog_encr_key (struct paramed_type *T);
int store_constructor_binlog_start (struct paramed_type *T);
int store_constructor_binlog_dc_option (struct paramed_type *T);
int store_constructor_binlog_dc_option_new (struct paramed_type *T);
int store_constructor_binlog_auth_key (struct paramed_type *T);
int store_constructor_binlog_default_dc (struct paramed_type *T);
int store_constructor_binlog_dc_signed (struct paramed_type *T);
int store_constructor_binlog_our_id (struct paramed_type *T);
int store_constructor_binlog_set_dh_params (struct paramed_type *T);
int store_constructor_binlog_set_pts (struct paramed_type *T);
int store_constructor_binlog_set_qts (struct paramed_type *T);
int store_constructor_binlog_set_date (struct paramed_type *T);
int store_constructor_binlog_set_seq (struct paramed_type *T);
int store_constructor_binlog_encr_chat_delete (struct paramed_type *T);
int store_constructor_binlog_encr_chat_new (struct paramed_type *T);
int store_constructor_binlog_encr_chat_exchange_new (struct paramed_type *T);
int store_constructor_binlog_user_delete (struct paramed_type *T);
int store_constructor_binlog_user_new (struct paramed_type *T);
int store_constructor_binlog_chat_new (struct paramed_type *T);
int store_constructor_binlog_chat_add_participant (struct paramed_type *T);
int store_constructor_binlog_chat_del_participant (struct paramed_type *T);
int store_constructor_binlog_set_msg_id (struct paramed_type *T);
int store_constructor_binlog_message_delete (struct paramed_type *T);
int store_constructor_binlog_message_new (struct paramed_type *T);
int store_constructor_binlog_message_encr_new (struct paramed_type *T);
int store_constructor_binlog_msg_update (struct paramed_type *T);
int store_constructor_binlog_reset_authorization (struct paramed_type *T);
int store_constructor_contacts_blocked (struct paramed_type *T);
int store_constructor_contacts_blocked_slice (struct paramed_type *T);
int store_constructor_contacts_contacts_not_modified (struct paramed_type *T);
int store_constructor_contacts_contacts (struct paramed_type *T);
int store_constructor_contacts_found (struct paramed_type *T);
int store_constructor_contacts_imported_contacts (struct paramed_type *T);
int store_constructor_contacts_link (struct paramed_type *T);
int store_constructor_contacts_suggested (struct paramed_type *T);
int store_constructor_geochats_located (struct paramed_type *T);
int store_constructor_geochats_messages (struct paramed_type *T);
int store_constructor_geochats_messages_slice (struct paramed_type *T);
int store_constructor_geochats_stated_message (struct paramed_type *T);
int store_constructor_help_app_update (struct paramed_type *T);
int store_constructor_help_no_app_update (struct paramed_type *T);
int store_constructor_help_invite_text (struct paramed_type *T);
int store_constructor_help_support (struct paramed_type *T);
int store_constructor_messages_affected_history (struct paramed_type *T);
int store_constructor_messages_affected_messages (struct paramed_type *T);
int store_constructor_messages_all_stickers_not_modified (struct paramed_type *T);
int store_constructor_messages_all_stickers (struct paramed_type *T);
int store_constructor_messages_chat_full (struct paramed_type *T);
int store_constructor_messages_chats (struct paramed_type *T);
int store_constructor_messages_dh_config_not_modified (struct paramed_type *T);
int store_constructor_messages_dh_config (struct paramed_type *T);
int store_constructor_messages_dialogs (struct paramed_type *T);
int store_constructor_messages_dialogs_slice (struct paramed_type *T);
int store_constructor_messages_message_empty (struct paramed_type *T);
int store_constructor_messages_messages (struct paramed_type *T);
int store_constructor_messages_messages_slice (struct paramed_type *T);
int store_constructor_messages_sent_encrypted_message (struct paramed_type *T);
int store_constructor_messages_sent_encrypted_file (struct paramed_type *T);
int store_constructor_messages_sent_message (struct paramed_type *T);
int store_constructor_messages_sent_message_link (struct paramed_type *T);
int store_constructor_messages_sticker_set (struct paramed_type *T);
int store_constructor_messages_stickers_not_modified (struct paramed_type *T);
int store_constructor_messages_stickers (struct paramed_type *T);
int store_constructor_photos_photo (struct paramed_type *T);
int store_constructor_photos_photos (struct paramed_type *T);
int store_constructor_photos_photos_slice (struct paramed_type *T);
int store_constructor_storage_file_unknown (struct paramed_type *T);
int store_constructor_storage_file_jpeg (struct paramed_type *T);
int store_constructor_storage_file_gif (struct paramed_type *T);
int store_constructor_storage_file_png (struct paramed_type *T);
int store_constructor_storage_file_pdf (struct paramed_type *T);
int store_constructor_storage_file_mp3 (struct paramed_type *T);
int store_constructor_storage_file_mov (struct paramed_type *T);
int store_constructor_storage_file_partial (struct paramed_type *T);
int store_constructor_storage_file_mp4 (struct paramed_type *T);
int store_constructor_storage_file_webp (struct paramed_type *T);
int store_constructor_updates_difference_empty (struct paramed_type *T);
int store_constructor_updates_difference (struct paramed_type *T);
int store_constructor_updates_difference_slice (struct paramed_type *T);
int store_constructor_updates_state (struct paramed_type *T);
int store_constructor_upload_file (struct paramed_type *T);
int store_type_account_days_t_t_l (struct paramed_type *T);
int store_type_bare_account_days_t_t_l (struct paramed_type *T);
int store_type_audio (struct paramed_type *T);
int store_type_bare_audio (struct paramed_type *T);
int store_type_authorization (struct paramed_type *T);
int store_type_bare_authorization (struct paramed_type *T);
int store_type_bool (struct paramed_type *T);
int store_type_bare_bool (struct paramed_type *T);
int store_type_bot_command (struct paramed_type *T);
int store_type_bare_bot_command (struct paramed_type *T);
int store_type_bot_info (struct paramed_type *T);
int store_type_bare_bot_info (struct paramed_type *T);
int store_type_bytes (struct paramed_type *T);
int store_type_bare_bytes (struct paramed_type *T);
int store_type_chat (struct paramed_type *T);
int store_type_bare_chat (struct paramed_type *T);
int store_type_chat_full (struct paramed_type *T);
int store_type_bare_chat_full (struct paramed_type *T);
int store_type_chat_invite (struct paramed_type *T);
int store_type_bare_chat_invite (struct paramed_type *T);
int store_type_chat_located (struct paramed_type *T);
int store_type_bare_chat_located (struct paramed_type *T);
int store_type_chat_participant (struct paramed_type *T);
int store_type_bare_chat_participant (struct paramed_type *T);
int store_type_chat_participants (struct paramed_type *T);
int store_type_bare_chat_participants (struct paramed_type *T);
int store_type_chat_photo (struct paramed_type *T);
int store_type_bare_chat_photo (struct paramed_type *T);
int store_type_client_d_h_inner_data (struct paramed_type *T);
int store_type_bare_client_d_h_inner_data (struct paramed_type *T);
int store_type_config (struct paramed_type *T);
int store_type_bare_config (struct paramed_type *T);
int store_type_contact (struct paramed_type *T);
int store_type_bare_contact (struct paramed_type *T);
int store_type_contact_blocked (struct paramed_type *T);
int store_type_bare_contact_blocked (struct paramed_type *T);
int store_type_contact_found (struct paramed_type *T);
int store_type_bare_contact_found (struct paramed_type *T);
int store_type_contact_link (struct paramed_type *T);
int store_type_bare_contact_link (struct paramed_type *T);
int store_type_contact_status (struct paramed_type *T);
int store_type_bare_contact_status (struct paramed_type *T);
int store_type_contact_suggested (struct paramed_type *T);
int store_type_bare_contact_suggested (struct paramed_type *T);
int store_type_dc_option (struct paramed_type *T);
int store_type_bare_dc_option (struct paramed_type *T);
int store_type_decrypted_message (struct paramed_type *T);
int store_type_bare_decrypted_message (struct paramed_type *T);
int store_type_decrypted_message_action (struct paramed_type *T);
int store_type_bare_decrypted_message_action (struct paramed_type *T);
int store_type_decrypted_message_layer (struct paramed_type *T);
int store_type_bare_decrypted_message_layer (struct paramed_type *T);
int store_type_decrypted_message_media (struct paramed_type *T);
int store_type_bare_decrypted_message_media (struct paramed_type *T);
int store_type_dialog (struct paramed_type *T);
int store_type_bare_dialog (struct paramed_type *T);
int store_type_disabled_feature (struct paramed_type *T);
int store_type_bare_disabled_feature (struct paramed_type *T);
int store_type_document (struct paramed_type *T);
int store_type_bare_document (struct paramed_type *T);
int store_type_document_attribute (struct paramed_type *T);
int store_type_bare_document_attribute (struct paramed_type *T);
int store_type_double (struct paramed_type *T);
int store_type_bare_double (struct paramed_type *T);
int store_type_encrypted_chat (struct paramed_type *T);
int store_type_bare_encrypted_chat (struct paramed_type *T);
int store_type_encrypted_file (struct paramed_type *T);
int store_type_bare_encrypted_file (struct paramed_type *T);
int store_type_encrypted_message (struct paramed_type *T);
int store_type_bare_encrypted_message (struct paramed_type *T);
int store_type_error (struct paramed_type *T);
int store_type_bare_error (struct paramed_type *T);
int store_type_exported_chat_invite (struct paramed_type *T);
int store_type_bare_exported_chat_invite (struct paramed_type *T);
int store_type_file_location (struct paramed_type *T);
int store_type_bare_file_location (struct paramed_type *T);
int store_type_geo_chat_message (struct paramed_type *T);
int store_type_bare_geo_chat_message (struct paramed_type *T);
int store_type_geo_point (struct paramed_type *T);
int store_type_bare_geo_point (struct paramed_type *T);
int store_type_imported_contact (struct paramed_type *T);
int store_type_bare_imported_contact (struct paramed_type *T);
int store_type_input_app_event (struct paramed_type *T);
int store_type_bare_input_app_event (struct paramed_type *T);
int store_type_input_audio (struct paramed_type *T);
int store_type_bare_input_audio (struct paramed_type *T);
int store_type_input_chat_photo (struct paramed_type *T);
int store_type_bare_input_chat_photo (struct paramed_type *T);
int store_type_input_contact (struct paramed_type *T);
int store_type_bare_input_contact (struct paramed_type *T);
int store_type_input_document (struct paramed_type *T);
int store_type_bare_input_document (struct paramed_type *T);
int store_type_input_encrypted_chat (struct paramed_type *T);
int store_type_bare_input_encrypted_chat (struct paramed_type *T);
int store_type_input_encrypted_file (struct paramed_type *T);
int store_type_bare_input_encrypted_file (struct paramed_type *T);
int store_type_input_file (struct paramed_type *T);
int store_type_bare_input_file (struct paramed_type *T);
int store_type_input_file_location (struct paramed_type *T);
int store_type_bare_input_file_location (struct paramed_type *T);
int store_type_input_geo_chat (struct paramed_type *T);
int store_type_bare_input_geo_chat (struct paramed_type *T);
int store_type_input_geo_point (struct paramed_type *T);
int store_type_bare_input_geo_point (struct paramed_type *T);
int store_type_input_media (struct paramed_type *T);
int store_type_bare_input_media (struct paramed_type *T);
int store_type_input_notify_peer (struct paramed_type *T);
int store_type_bare_input_notify_peer (struct paramed_type *T);
int store_type_input_peer (struct paramed_type *T);
int store_type_bare_input_peer (struct paramed_type *T);
int store_type_input_peer_notify_events (struct paramed_type *T);
int store_type_bare_input_peer_notify_events (struct paramed_type *T);
int store_type_input_peer_notify_settings (struct paramed_type *T);
int store_type_bare_input_peer_notify_settings (struct paramed_type *T);
int store_type_input_photo (struct paramed_type *T);
int store_type_bare_input_photo (struct paramed_type *T);
int store_type_input_photo_crop (struct paramed_type *T);
int store_type_bare_input_photo_crop (struct paramed_type *T);
int store_type_input_privacy_key (struct paramed_type *T);
int store_type_bare_input_privacy_key (struct paramed_type *T);
int store_type_input_privacy_rule (struct paramed_type *T);
int store_type_bare_input_privacy_rule (struct paramed_type *T);
int store_type_input_sticker_set (struct paramed_type *T);
int store_type_bare_input_sticker_set (struct paramed_type *T);
int store_type_input_user (struct paramed_type *T);
int store_type_bare_input_user (struct paramed_type *T);
int store_type_input_video (struct paramed_type *T);
int store_type_bare_input_video (struct paramed_type *T);
int store_type_int (struct paramed_type *T);
int store_type_bare_int (struct paramed_type *T);
int store_type_int128 (struct paramed_type *T);
int store_type_bare_int128 (struct paramed_type *T);
int store_type_int256 (struct paramed_type *T);
int store_type_bare_int256 (struct paramed_type *T);
int store_type_keyboard_button (struct paramed_type *T);
int store_type_bare_keyboard_button (struct paramed_type *T);
int store_type_keyboard_button_row (struct paramed_type *T);
int store_type_bare_keyboard_button_row (struct paramed_type *T);
int store_type_long (struct paramed_type *T);
int store_type_bare_long (struct paramed_type *T);
int store_type_message (struct paramed_type *T);
int store_type_bare_message (struct paramed_type *T);
int store_type_message_action (struct paramed_type *T);
int store_type_bare_message_action (struct paramed_type *T);
int store_type_message_media (struct paramed_type *T);
int store_type_bare_message_media (struct paramed_type *T);
int store_type_messages_filter (struct paramed_type *T);
int store_type_bare_messages_filter (struct paramed_type *T);
int store_type_nearest_dc (struct paramed_type *T);
int store_type_bare_nearest_dc (struct paramed_type *T);
int store_type_notify_peer (struct paramed_type *T);
int store_type_bare_notify_peer (struct paramed_type *T);
int store_type_null (struct paramed_type *T);
int store_type_bare_null (struct paramed_type *T);
int store_type_p_q_inner_data (struct paramed_type *T);
int store_type_bare_p_q_inner_data (struct paramed_type *T);
int store_type_peer (struct paramed_type *T);
int store_type_bare_peer (struct paramed_type *T);
int store_type_peer_notify_events (struct paramed_type *T);
int store_type_bare_peer_notify_events (struct paramed_type *T);
int store_type_peer_notify_settings (struct paramed_type *T);
int store_type_bare_peer_notify_settings (struct paramed_type *T);
int store_type_photo (struct paramed_type *T);
int store_type_bare_photo (struct paramed_type *T);
int store_type_photo_size (struct paramed_type *T);
int store_type_bare_photo_size (struct paramed_type *T);
int store_type_privacy_key (struct paramed_type *T);
int store_type_bare_privacy_key (struct paramed_type *T);
int store_type_privacy_rule (struct paramed_type *T);
int store_type_bare_privacy_rule (struct paramed_type *T);
int store_type_received_notify_message (struct paramed_type *T);
int store_type_bare_received_notify_message (struct paramed_type *T);
int store_type_reply_markup (struct paramed_type *T);
int store_type_bare_reply_markup (struct paramed_type *T);
int store_type_res_p_q (struct paramed_type *T);
int store_type_bare_res_p_q (struct paramed_type *T);
int store_type_send_message_action (struct paramed_type *T);
int store_type_bare_send_message_action (struct paramed_type *T);
int store_type_server_d_h_params (struct paramed_type *T);
int store_type_bare_server_d_h_params (struct paramed_type *T);
int store_type_server_d_h_inner_data (struct paramed_type *T);
int store_type_bare_server_d_h_inner_data (struct paramed_type *T);
int store_type_set_client_d_h_params_answer (struct paramed_type *T);
int store_type_bare_set_client_d_h_params_answer (struct paramed_type *T);
int store_type_sticker_pack (struct paramed_type *T);
int store_type_bare_sticker_pack (struct paramed_type *T);
int store_type_sticker_set (struct paramed_type *T);
int store_type_bare_sticker_set (struct paramed_type *T);
int store_type_string (struct paramed_type *T);
int store_type_bare_string (struct paramed_type *T);
int store_type_update (struct paramed_type *T);
int store_type_bare_update (struct paramed_type *T);
int store_type_updates (struct paramed_type *T);
int store_type_bare_updates (struct paramed_type *T);
int store_type_user (struct paramed_type *T);
int store_type_bare_user (struct paramed_type *T);
int store_type_user_full (struct paramed_type *T);
int store_type_bare_user_full (struct paramed_type *T);
int store_type_user_profile_photo (struct paramed_type *T);
int store_type_bare_user_profile_photo (struct paramed_type *T);
int store_type_user_status (struct paramed_type *T);
int store_type_bare_user_status (struct paramed_type *T);
int store_type_vector (struct paramed_type *T);
int store_type_bare_vector (struct paramed_type *T);
int store_type_video (struct paramed_type *T);
int store_type_bare_video (struct paramed_type *T);
int store_type_wall_paper (struct paramed_type *T);
int store_type_bare_wall_paper (struct paramed_type *T);
int store_type_web_page (struct paramed_type *T);
int store_type_bare_web_page (struct paramed_type *T);
int store_type_account_authorizations (struct paramed_type *T);
int store_type_bare_account_authorizations (struct paramed_type *T);
int store_type_account_password (struct paramed_type *T);
int store_type_bare_account_password (struct paramed_type *T);
int store_type_account_password_input_settings (struct paramed_type *T);
int store_type_bare_account_password_input_settings (struct paramed_type *T);
int store_type_account_password_settings (struct paramed_type *T);
int store_type_bare_account_password_settings (struct paramed_type *T);
int store_type_account_privacy_rules (struct paramed_type *T);
int store_type_bare_account_privacy_rules (struct paramed_type *T);
int store_type_account_sent_change_phone_code (struct paramed_type *T);
int store_type_bare_account_sent_change_phone_code (struct paramed_type *T);
int store_type_auth_authorization (struct paramed_type *T);
int store_type_bare_auth_authorization (struct paramed_type *T);
int store_type_auth_checked_phone (struct paramed_type *T);
int store_type_bare_auth_checked_phone (struct paramed_type *T);
int store_type_auth_exported_authorization (struct paramed_type *T);
int store_type_bare_auth_exported_authorization (struct paramed_type *T);
int store_type_auth_password_recovery (struct paramed_type *T);
int store_type_bare_auth_password_recovery (struct paramed_type *T);
int store_type_auth_sent_code (struct paramed_type *T);
int store_type_bare_auth_sent_code (struct paramed_type *T);
int store_type_binlog_encr_key (struct paramed_type *T);
int store_type_bare_binlog_encr_key (struct paramed_type *T);
int store_type_binlog_update (struct paramed_type *T);
int store_type_bare_binlog_update (struct paramed_type *T);
int store_type_contacts_blocked (struct paramed_type *T);
int store_type_bare_contacts_blocked (struct paramed_type *T);
int store_type_contacts_contacts (struct paramed_type *T);
int store_type_bare_contacts_contacts (struct paramed_type *T);
int store_type_contacts_found (struct paramed_type *T);
int store_type_bare_contacts_found (struct paramed_type *T);
int store_type_contacts_imported_contacts (struct paramed_type *T);
int store_type_bare_contacts_imported_contacts (struct paramed_type *T);
int store_type_contacts_link (struct paramed_type *T);
int store_type_bare_contacts_link (struct paramed_type *T);
int store_type_contacts_suggested (struct paramed_type *T);
int store_type_bare_contacts_suggested (struct paramed_type *T);
int store_type_geochats_located (struct paramed_type *T);
int store_type_bare_geochats_located (struct paramed_type *T);
int store_type_geochats_messages (struct paramed_type *T);
int store_type_bare_geochats_messages (struct paramed_type *T);
int store_type_geochats_stated_message (struct paramed_type *T);
int store_type_bare_geochats_stated_message (struct paramed_type *T);
int store_type_help_app_update (struct paramed_type *T);
int store_type_bare_help_app_update (struct paramed_type *T);
int store_type_help_invite_text (struct paramed_type *T);
int store_type_bare_help_invite_text (struct paramed_type *T);
int store_type_help_support (struct paramed_type *T);
int store_type_bare_help_support (struct paramed_type *T);
int store_type_messages_affected_history (struct paramed_type *T);
int store_type_bare_messages_affected_history (struct paramed_type *T);
int store_type_messages_affected_messages (struct paramed_type *T);
int store_type_bare_messages_affected_messages (struct paramed_type *T);
int store_type_messages_all_stickers (struct paramed_type *T);
int store_type_bare_messages_all_stickers (struct paramed_type *T);
int store_type_messages_chat_full (struct paramed_type *T);
int store_type_bare_messages_chat_full (struct paramed_type *T);
int store_type_messages_chats (struct paramed_type *T);
int store_type_bare_messages_chats (struct paramed_type *T);
int store_type_messages_dh_config (struct paramed_type *T);
int store_type_bare_messages_dh_config (struct paramed_type *T);
int store_type_messages_dialogs (struct paramed_type *T);
int store_type_bare_messages_dialogs (struct paramed_type *T);
int store_type_messages_message (struct paramed_type *T);
int store_type_bare_messages_message (struct paramed_type *T);
int store_type_messages_messages (struct paramed_type *T);
int store_type_bare_messages_messages (struct paramed_type *T);
int store_type_messages_sent_encrypted_message (struct paramed_type *T);
int store_type_bare_messages_sent_encrypted_message (struct paramed_type *T);
int store_type_messages_sent_message (struct paramed_type *T);
int store_type_bare_messages_sent_message (struct paramed_type *T);
int store_type_messages_sticker_set (struct paramed_type *T);
int store_type_bare_messages_sticker_set (struct paramed_type *T);
int store_type_messages_stickers (struct paramed_type *T);
int store_type_bare_messages_stickers (struct paramed_type *T);
int store_type_photos_photo (struct paramed_type *T);
int store_type_bare_photos_photo (struct paramed_type *T);
int store_type_photos_photos (struct paramed_type *T);
int store_type_bare_photos_photos (struct paramed_type *T);
int store_type_storage_file_type (struct paramed_type *T);
int store_type_bare_storage_file_type (struct paramed_type *T);
int store_type_updates_difference (struct paramed_type *T);
int store_type_bare_updates_difference (struct paramed_type *T);
int store_type_updates_state (struct paramed_type *T);
int store_type_bare_updates_state (struct paramed_type *T);
int store_type_upload_file (struct paramed_type *T);
int store_type_bare_upload_file (struct paramed_type *T);
struct paramed_type *store_function_account_change_phone (void);
struct paramed_type *store_function_account_check_username (void);
struct paramed_type *store_function_account_delete_account (void);
struct paramed_type *store_function_account_get_account_t_t_l (void);
struct paramed_type *store_function_account_get_authorizations (void);
struct paramed_type *store_function_account_get_notify_settings (void);
struct paramed_type *store_function_account_get_password (void);
struct paramed_type *store_function_account_get_password_settings (void);
struct paramed_type *store_function_account_get_privacy (void);
struct paramed_type *store_function_account_get_wall_papers (void);
struct paramed_type *store_function_account_register_device (void);
struct paramed_type *store_function_account_reset_authorization (void);
struct paramed_type *store_function_account_reset_notify_settings (void);
struct paramed_type *store_function_account_send_change_phone_code (void);
struct paramed_type *store_function_account_set_account_t_t_l (void);
struct paramed_type *store_function_account_set_privacy (void);
struct paramed_type *store_function_account_unregister_device (void);
struct paramed_type *store_function_account_update_device_locked (void);
struct paramed_type *store_function_account_update_notify_settings (void);
struct paramed_type *store_function_account_update_password_settings (void);
struct paramed_type *store_function_account_update_profile (void);
struct paramed_type *store_function_account_update_status (void);
struct paramed_type *store_function_account_update_username (void);
struct paramed_type *store_function_auth_bind_temp_auth_key (void);
struct paramed_type *store_function_auth_check_password (void);
struct paramed_type *store_function_auth_check_phone (void);
struct paramed_type *store_function_auth_export_authorization (void);
struct paramed_type *store_function_auth_import_authorization (void);
struct paramed_type *store_function_auth_import_bot_authorization (void);
struct paramed_type *store_function_auth_log_out (void);
struct paramed_type *store_function_auth_recover_password (void);
struct paramed_type *store_function_auth_request_password_recovery (void);
struct paramed_type *store_function_auth_reset_authorizations (void);
struct paramed_type *store_function_auth_send_call (void);
struct paramed_type *store_function_auth_send_code (void);
struct paramed_type *store_function_auth_send_invites (void);
struct paramed_type *store_function_auth_send_sms (void);
struct paramed_type *store_function_auth_sign_in (void);
struct paramed_type *store_function_auth_sign_up (void);
struct paramed_type *store_function_contacts_block (void);
struct paramed_type *store_function_contacts_delete_contact (void);
struct paramed_type *store_function_contacts_delete_contacts (void);
struct paramed_type *store_function_contacts_export_card (void);
struct paramed_type *store_function_contacts_get_blocked (void);
struct paramed_type *store_function_contacts_get_contacts (void);
struct paramed_type *store_function_contacts_get_statuses (void);
struct paramed_type *store_function_contacts_get_suggested (void);
struct paramed_type *store_function_contacts_import_card (void);
struct paramed_type *store_function_contacts_import_contacts (void);
struct paramed_type *store_function_contacts_resolve_username (void);
struct paramed_type *store_function_contacts_search (void);
struct paramed_type *store_function_contacts_unblock (void);
struct paramed_type *store_function_geochats_checkin (void);
struct paramed_type *store_function_geochats_create_geo_chat (void);
struct paramed_type *store_function_geochats_edit_chat_photo (void);
struct paramed_type *store_function_geochats_edit_chat_title (void);
struct paramed_type *store_function_geochats_get_full_chat (void);
struct paramed_type *store_function_geochats_get_history (void);
struct paramed_type *store_function_geochats_get_located (void);
struct paramed_type *store_function_geochats_get_recents (void);
struct paramed_type *store_function_geochats_search (void);
struct paramed_type *store_function_geochats_send_media (void);
struct paramed_type *store_function_geochats_send_message (void);
struct paramed_type *store_function_geochats_set_typing (void);
struct paramed_type *store_function_help_get_app_update (void);
struct paramed_type *store_function_help_get_config (void);
struct paramed_type *store_function_help_get_invite_text (void);
struct paramed_type *store_function_help_get_nearest_dc (void);
struct paramed_type *store_function_help_get_support (void);
struct paramed_type *store_function_help_save_app_log (void);
struct paramed_type *store_function_init_connection (void);
struct paramed_type *store_function_invoke_after_msg (void);
struct paramed_type *store_function_invoke_after_msgs (void);
struct paramed_type *store_function_invoke_with_layer (void);
struct paramed_type *store_function_invoke_without_updates (void);
struct paramed_type *store_function_messages_accept_encryption (void);
struct paramed_type *store_function_messages_add_chat_user (void);
struct paramed_type *store_function_messages_check_chat_invite (void);
struct paramed_type *store_function_messages_create_chat (void);
struct paramed_type *store_function_messages_delete_chat_user (void);
struct paramed_type *store_function_messages_delete_history (void);
struct paramed_type *store_function_messages_delete_messages (void);
struct paramed_type *store_function_messages_discard_encryption (void);
struct paramed_type *store_function_messages_edit_chat_photo (void);
struct paramed_type *store_function_messages_edit_chat_title (void);
struct paramed_type *store_function_messages_export_chat_invite (void);
struct paramed_type *store_function_messages_forward_message (void);
struct paramed_type *store_function_messages_forward_messages (void);
struct paramed_type *store_function_messages_get_all_stickers (void);
struct paramed_type *store_function_messages_get_chats (void);
struct paramed_type *store_function_messages_get_dh_config (void);
struct paramed_type *store_function_messages_get_dialogs (void);
struct paramed_type *store_function_messages_get_full_chat (void);
struct paramed_type *store_function_messages_get_history (void);
struct paramed_type *store_function_messages_get_messages (void);
struct paramed_type *store_function_messages_get_sticker_set (void);
struct paramed_type *store_function_messages_get_stickers (void);
struct paramed_type *store_function_messages_get_web_page_preview (void);
struct paramed_type *store_function_messages_import_chat_invite (void);
struct paramed_type *store_function_messages_install_sticker_set (void);
struct paramed_type *store_function_messages_read_encrypted_history (void);
struct paramed_type *store_function_messages_read_history (void);
struct paramed_type *store_function_messages_read_message_contents (void);
struct paramed_type *store_function_messages_received_messages (void);
struct paramed_type *store_function_messages_received_queue (void);
struct paramed_type *store_function_messages_request_encryption (void);
struct paramed_type *store_function_messages_search (void);
struct paramed_type *store_function_messages_send_broadcast (void);
struct paramed_type *store_function_messages_send_encrypted (void);
struct paramed_type *store_function_messages_send_encrypted_file (void);
struct paramed_type *store_function_messages_send_encrypted_service (void);
struct paramed_type *store_function_messages_send_media (void);
struct paramed_type *store_function_messages_send_message (void);
struct paramed_type *store_function_messages_set_encrypted_typing (void);
struct paramed_type *store_function_messages_set_typing (void);
struct paramed_type *store_function_messages_start_bot (void);
struct paramed_type *store_function_messages_uninstall_sticker_set (void);
struct paramed_type *store_function_photos_delete_photos (void);
struct paramed_type *store_function_photos_get_user_photos (void);
struct paramed_type *store_function_photos_update_profile_photo (void);
struct paramed_type *store_function_photos_upload_profile_photo (void);
struct paramed_type *store_function_req_d_h_params (void);
struct paramed_type *store_function_req_pq (void);
struct paramed_type *store_function_set_client_d_h_params (void);
struct paramed_type *store_function_updates_get_difference (void);
struct paramed_type *store_function_updates_get_state (void);
struct paramed_type *store_function_upload_get_file (void);
struct paramed_type *store_function_upload_save_big_file_part (void);
struct paramed_type *store_function_upload_save_file_part (void);
struct paramed_type *store_function_users_get_full_user (void);
struct paramed_type *store_function_users_get_users (void);
int store_type_any (struct paramed_type *T);
struct paramed_type *store_function_any (void);
