//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IRC.rc
//
#define ID_INFO_QUERY                   3
#define IDD_PREFS_MAIN                  101
#define IDC_OPTIONSTAB                  102
#define IDD_PREFS_CONNECT               103
#define IDD_INFO                        106
#define IDD_NICK                        107
#define IDD_PREFS_OTHER                 113
#define IDD_ADDSERVER                   120
#define IDD_LIST                        123
#define IDR_MENU                        129
#define IDD_QUICKCONN                   133
#define IDI_MAIN                        136
#define IDD_USERINFO                    154
#define IDD_CHANMANAGER                 155
#define IDD_QUESTION                    156
#define IDD_PREFS_CTCP                  158
#define IDD_MESSAGEBOX                  159
#define IDD_PREFS_IGNORE                160
#define IDD_ADDIGNORE                   161
#define IDD_ACCMGRUI                    162
#define IDI_ADD                         175
#define IDI_BLOCK                       176
#define IDI_DELETE                      177
#define IDI_WHOIS                       179
#define IDI_LIST                        181
#define IDI_MANAGER                     182
#define IDI_QUICK                       184
#define IDI_GO                          185
#define IDI_APPLY                       185
#define IDI_SHOW                        186
#define IDI_LOGO                        187
#define IDI_RENAME                      188
#define IDI_SERVER                      189
#define IDI_DCC                         196
#define IDR_SERVERS                     200
#define IDI_EDIT                        201
#define IDI_IRCQUESTION                 202
#define IDC_ENICK                       1000
#define IDC_USERID                      1001
#define IDC_INFO_NAME                   1001
#define IDC_NICK                        1002
#define IDC_LIST                        1002
#define IDC_INFO_AUTH                   1002
#define IDC_INFO_LISTVIEW               1002
#define IDC_PORT                        1003
#define IDC_INFO_CHANNELS               1003
#define IDC_INFO_LISTVIEW2              1003
#define IDC_NAME                        1004
#define IDC_INFO_ADDRESS                1004
#define IDC_PASS                        1005
#define IDC_INFO_SERVER                 1005
#define IDC_SERVER                      1006
#define IDC_INFO_ID                     1006
#define IDC_PERFORMEDIT                 1007
#define IDC_PORT2                       1008
#define IDC_INFO_AWAY2                  1008
#define IDC_NICK2                       1009
#define IDC_REPLY                       1009
#define IDC_SSL                         1010
#define IDC_PORT3                       1010
#define IDC_INFO_OTHER                  1011
#define IDC_EDIT                        1012
#define IDC_RETRYCOUNT                  1013
#define IDC_INFO_NICK                   1013
#define IDC_EDIT2                       1013
#define ID_INFO_GO                      1017
#define IDC_SERVERCOMBO                 1022
#define IDC_IDENT                       1023
#define IDC_IDENT_TIMED                 1024
#define IDC_RETRY                       1029
#define IDC_ADDSERVER                   1031
#define IDC_EDITSERVER                  1032
#define IDC_RETRYWAIT                   1035
#define IDC_IDENTSYSTEM                 1036
#define IDC_IDENTPORT                   1037
#define IDC_ONLINETIMER                 1038
#define IDC_FORCEVISIBLE                1039
#define IDC_REJOINCHANNELS              1041
#define IDC_REJOINONKICK                1042
#define IDC_PERFORM                     1043
#define IDC_PERFORMCOMBO                1044
#define IDC_DISABLEERROR                1044
#define IDC_KEEPALIVE                   1045
#define IDC_ENABLEIP                    1045
#define IDC_ONLINENOTIF                 1046
#define IDC_CHANNELAWAY                 1047
#define IDC_USESERVER                   1048
#define IDC_SHOWSERVER                  1049
#define IDC_ADDRESS                     1050
#define IDC_AUTOJOIN                    1051
#define IDC_OLDSTYLE                    1052
#define IDC_ADD                         1090
#define IDC_DELETE                      1091
#define IDC_ALIASEDIT                   1094
#define IDC_REMOVE                      1094
#define IDC_APPLYTOPIC                  1095
#define IDC_APPLYMODES                  1096
#define IDC_DELETESERVER                1097
#define IDC_ADD_COMBO                   1100
#define IDC_ADD_SERVER                  1101
#define IDC_ADD_ADDRESS                 1102
#define IDC_ADD_PORT                    1103
#define IDC_ADD_PORT2                   1104
#define IDC_CLOSE                       1108
#define IDC_JOIN                        1109
#define ID_INFO_OK                      1110
#define IDC_STARTUP                     1133
#define IDC_TEXT                        1134
#define IDC_DEFAULT                     1139
#define IDC_WILDCARD                    1140
#define IDC_USER                        1141
#define IDC_HOST                        1142
#define IDC_BUTTON                      1143
#define IDC_BUTTON2                     1144
#define IDC_CHECK1                      1147
#define IDC_CHECK2                      1148
#define IDC_CHECK3                      1149
#define IDC_CHECK4                      1150
#define IDC_CHECK5                      1151
#define IDC_CHECK6                      1152
#define IDC_CHECK7                      1153
#define IDC_CHECK8                      1154
#define IDC_KEY                         1159
#define IDC_LIMIT                       1160
#define IDC_TOPIC                       1161
#define IDC_RADIO1                      1170
#define IDC_RADIO2                      1171
#define IDC_RADIO3                      1172
#define IDC_HIDDENEDIT                  1175
#define IDC_NOTOP                       1176
#define IDC_WHITERECT                   1179
#define IDC_LOGO                        1180
#define IDC_CAPTION                     1181
#define IDC_OFF                         1184
#define IDC_AUTO                        1185
#define IDC_ON                          1186
#define IDC_QUITMESSAGE                 1187
#define IDC_USERINFO                    1189
#define IDC_PING                        1190
#define IDC_IP                          1190
#define IDC_VERSION                     1191
#define IDN_YES                         1191
#define IDC_PASSIVE                     1191
#define IDC_TIME                        1192
#define IDN_NO                          1192
#define IDC_PASSIVE2                    1192
#define IDC_SENDNOTICE                  1192
#define IDC_SLOW                        1193
#define IDC_FAST                        1194
#define IDC_COMBO                       1196
#define IDC_DISC                        1197
#define IDC_FROMSERVER                  1201
#define IDC_SCRIPT                      1202
#define IDC_MASK                        1204
#define IDC_Q                           1205
#define IDC_M                           1206
#define IDC_N                           1207
#define IDC_I                           1208
#define IDC_C                           1209
#define IDC_D                           1210
#define IDC_NETWORK                     1211
#define IDC_IGNORECHANNEL               1212
#define IDC_ENABLEIGNORE                1213
#define IDC_IGNOREFILE                  1214
#define IDC_IGNORECHAT                  1215
#define IDC_IGNOREUNKNOWN               1216
#define IDC_CUSTOM                      1218
#define IDC_SPIN1                       1219
#define IDC_SPIN2                       1220
#define IDC_CODEPAGE                    1222
#define IDC_COMBO1                      1223
#define IDC_CHECK9                      1224
#define IDC_UTF_AUTODETECT              1225
#define IDC_AWAYTIME                    1226
#define IDC_SSL_ON                      1227
#define IDC_SSL_AUTO                    1228
#define IDC_SSL_OFF                     1229
#define IDC_GRBOX_SSL                   1230
#define IDC_LIST1                       1231
#define IDC_EDIT1                       1232
#define IDC_STATICTEXT1                 1233
#define IDC_STATICTEXT2                 1234
#define IDC_FILTER_STRING               1235
#define IDC_BUTTON1                     1236
#define IDC_FILTER_BTN                  1237
#define ID_MENU1_OP                     40013
#define ID_MENU1_DEOP                   40014
#define ID_MENU1_VOICE                  40015
#define ID_MENU1_DEVOICE                40016
#define ID_MENU1_KICK                   40017
#define ID_MENU1_QUERY                  40018
#define ID_MENU1_WHOIS                  40019
#define IDM_COPYALL                     40020
#define IDM_SELECTALL                   40022
#define IDM_CLEAR                       40023
#define IDM_OPENNEW                     40024
#define IDM_OPENEXISTING                40025
#define IDM_COPYLINK                    40026
#define IDM_COPY                        40027
#define IDM_JOIN                        40028
#define IDM_CHANGENICK                  40029
#define IDM_SHOWSERVER                  40030
#define IDM_LEAVECHAN                   40031
#define ID_MENU1_ADDCONTACT             40032
#define IDM_CHANMANAGER                 40033
#define ID_MENU1_KICKREASON             40034
#define ID_MENU1_BAN                    40035
#define ID_MENU1_BANKICK                40036
#define ID_MENU1_BANKICKREASON          40037
#define ID_MENU1_IGNORE_ON              40038
#define ID_MENU1_IGNORE_OFF             40039
#define ID_MENU1_OWNER                  40040
#define ID_MENU1_DEOWNER                40041
#define ID_MENU1_ADMIN                  40042
#define ID_MENU1_DEADMIN                40043
#define ID_MENU1_SENDNOTICE             40044
#define ID_MENU1_INVITETOCHANNEL        40045
#define ID_MENU1_SLAP                   40046
#define ID_MENU1_NICKSERV               40047
#define ID_NICKSERV_REGISTERNICK        40048
#define ID_NICKSERV_AUTHNICK            40049
#define ID_NICKSERV_DELETENICK          40050
#define ID_NICKSERV_IDENTIFY            40051
#define ID_NICKSERV_SENDPASSWORD        40052
#define ID_NICKSERV_SETTINGS            40053
#define ID_SETTINGS_LANGUAGE            40054
#define ID_SETTINGS_E                   40055
#define ID_SETTINGS_INFO                40056
#define ID_SETTINGS_KILL                40057
#define ID_NICKSERV_KILL                40058
#define ID_KILL_OFF                     40059
#define ID_KILL_ON                      40060
#define ID_KILL_QUICK                   40061
#define ID_NICKSERV_PRIVATE             40062
#define ID_PRIVATE_ON                   40063
#define ID_PRIVATE_OFF                  40064
#define ID_NICKSERV_SETNEWPASSWORD      40065
#define ID_NICKSERV_                    40066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        203
#define _APS_NEXT_COMMAND_VALUE         40067
#define _APS_NEXT_CONTROL_VALUE         1238
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
